### ISSUE TITLE
PackerInstall fails

### ISSUE THREAD

**Issue by ranebrown** [wbthomason/packer.nvim#100]
After 06caefb116998aa60fab37e54137942da4de4755 / #91 `:PackerInstall` fails. This is on a network that requires a proxy and it looks like the existing environment variable `https_proxy` is no longer used. Adding that variable to the env config in `lua/packer/plugin_types/git.lua` fixes the issue. It seems like it would make sense to keep the old behavior of using variables that are already set rather than needing to add this additional configuration.

**Comment by wbthomason** [comment]
Thanks for the report! I agree, the fix is probably to duplicate the environment.

**Comment by wbthomason** [comment]
@ranebrown: Could you please check if https://github.com/wbthomason/packer.nvim/pull/101 fixes this problem for you?

**Comment by nanotee** [comment]
My bad, I should've been more careful when I sent the patch

This seems to works as a temporary fix:

```lua
    local cur_env = vim.fn.environ()
    local job_env = {}
    for key, value in pairs(cur_env) do
        table.insert(job_env, key .. '=' .. value)
    end
    table.insert(job_env, 'GIT_TERMINAL_PROMPT=0')

    local installer_opts = {
      capture_output = callbacks,
      timeout = config.clone_timeout,
      options = {
          env = job_env,
      },
    }
```

**Comment by ranebrown** [comment]
Yep, that one works

**Comment by wbthomason** [comment]
Hmm, I am curious why the version in #101 doesn't work, though. @ranebrown, would you be able to rebuild Neovim from current `master`? My best guess is that the bundled `luv` version in your Neovim is out of date, since I cannot reproduce the failure on my end.

If you still see the failure, I'll adapt @nanotee's workaround to generate the environment table a single time, then update the PR with that. I prefer the `luv` approach for cleanliness and (very slight) performance, but if it's going to cause a compatibility nightmare then it's not worth it.

**Comment by ranebrown** [comment]
I tried using the HEAD install with brew and a direct install from a fresh clone/build and got the same error. Maybe related to being on a Mac?

**Comment by wbthomason** [comment]
Strange. Regardless, it seems like we cannot depend on `os_environ` being present, so I'll rework #101 based on @nanotee's workaround. Thanks!

**Comment by wbthomason** [comment]
@nanotee did you find that you had to copy the result of `environ()` into a list of strings of the form `{KEY}={VAL}` for your workaround to work? I would expect that just passing a dictionary should work, based on the Luv docs.

**Comment by wbthomason** [comment]
I've pushed an update to #101 that just passes a table; if that doesn't work, I'll build a table of strings like the above workaround (if it does work, then I'll merge #101).

**Comment by nanotee** [comment]
@wbthomason I just tried the latest commit from #101 and it really does seem like `options.env` has to be a list of strings, otherwise I can reproduce #26

**Comment by wbthomason** [comment]
Huh, that's surprising and disappointing. Thanks for giving it a go! I'll switch to a list of strings and merge now, then.
