### ISSUE TITLE
[Q&A] Copy ~/.config/nvim and ~/.local/share/nvim to another computer with the same OS does not work 

### ISSUE THREAD

**Issue by the-die** [wbthomason/packer.nvim#1025]
I want to use nvim on another computer without network (same OS) as well, so I copied ~/.config/nvim and ~/.local/share/nvim from my own computer to that computer. Then I run 'PackerCompile', but some plugins report errors. My config file is https://github.com/the-die/dotfiles/tree/main/nvim. How can I fix it please?

**Comment by EdenEast** [comment]
What are the issues that you are having? Need more information on what is not working in order to help. Also there is no real bug here with packer. I see you have opened a discussion issue. That is a better place for this question.

**Comment by GgoCoder** [comment]
yes，i have the same error. Ubuntu22.04 with network and centos7 without network,  i copied `/root/~.config/*` and `/root/.lcoal/*` from Ubuntu22.04 to centos7` /home/user/.local `and `/home/user/.config`. Then, something errors. Open nvim in bash with `pakcer.nvim:Error running config for lsp_signature.nvim: attempt to call a nil value`, all plugins have same error. And` :PackerStatus` show the path of every plugin is` /root/.local/share/...` , not `/home/user/.lcoal/share` or` ~/.local/share`
