### ISSUE TITLE
Packer does not work after the commit c11416c009afab56af1ba0b7930c2a80321591aa

### ISSUE THREAD

**Issue by lu5je0** [wbthomason/packer.nvim#1045]
![image](https://user-images.githubusercontent.com/17700877/188297885-30b919bc-0f2e-4abc-8d76-e26d4b0f1f6b.png)

**Comment by wbthomason** [comment]
Seems like a probable duplicate of #1043?

**Comment by lu5je0** [comment]
@wbthomason Sorry, i didn't see it

**Comment by wbthomason** [comment]
No worries!
