### ISSUE TITLE
`config` doesn't work with `after` at the same time

### ISSUE THREAD

**Issue by datwaft** [wbthomason/packer.nvim#105]
Hello, I am having a problem where the `config` key doesn't work when the plugin also has the `after` key.

## What I am trying to do

I am trying to:

1. Load `lightline` and create a global vim variable with the configuration.
2. Load the _colorscheme_.
3. Add to that global vim variable a new key with the theme for lightline.

## How to recreate the bug

This is the minimal configuration to test this:

```lua
vim.cmd [[ packadd packer.nvim ]]

return require'packer'.startup(function()
   use { 'wbthomason/packer.nvim', opt = true }
   use {
      'itchyny/lightline.vim',
      config = function() vim.cmd [[ echom 'lightline.vim' ]] end,
   }
   use {
      'bluz71/vim-nightfly-guicolors',
      after = 'lightline.vim',
      config = function() vim.cmd [[ echom 'colorscheme.vim' ]] end,
   }
end)
```

## Expected behaviour

When you type `:messages` the output is:

```
lightline.vim
colorscheme.vim
```

## Actual behaviour

When you type `:messages` the output is:

```
lightline.vim
```

`colorscheme.vim` doesn't appear at all.

**Note:** the `setup` key works but the `config` key doesn't.

---

Also, it would be useful to document how to use the `after` key; I coudn't find anything.

**Comment by wbthomason** [comment]
Thanks for the report! This is indeed a bug in lazy-loader compilation. I'm working on a fix now.

Also, the current only documentation of the `after` key is the line in the big code block in https://github.com/wbthomason/packer.nvim#specifying-plugins (and the corresponding block in the `docs/`). What information do you think it would help to add?

Also, the semantics of `after` will be changing soon :tm:, per #87 and friends.

**Comment by datwaft** [comment]
> What information do you think it would help to add?

I think it would be helpful to add how to specify the plugin.

Like, for example, if you specify `lightline` as `itchyny/lightline.vim` or as `lightline.vim`. And if the `as` key works as an alias with `after`.

**Comment by wbthomason** [comment]
Ah, excellent points. I'll add some quick notes.

Also, please let me know if you continue to experience the original bug.

**Comment by datwaft** [comment]
It works perfectly without the `as` to create an alias, but with `as` it gives me this error:

```
Error detected while processing /home/datwaft/.config/nvim/plugin/packer_compiled.vim:
line  179:
E5107: Error loading lua [string ":lua"]:165: unexpected symbol near 'char(27)'
E5108: Error executing lua .../site/pack/packer/opt/packer.nvim/lua/packer/compile.lua:360: attempt to index a nil value
```

Here is an extract of my configuration:

```lua
   use {
      'sainnhe/edge',
      config = require'plugins.colorscheme',
      as = 'colorscheme',
   }
   use {
      'itchyny/lightline.vim',
      config = require'plugins.lightline',
      after = 'colorscheme',
   }
```

**Comment by wbthomason** [comment]
Ah, my bad - should be fixed in 242773d. Thanks for your patience!

**Comment by datwaft** [comment]
The index value error seems to be fixed, but the other one continues:

```
Error detected while processing /home/datwaft/.config/nvim/plugin/packer_compiled.vim:
line  179:
E5107: Error loading lua [string ":lua"]:165: unexpected symbol near 'char(27)'
```

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/37723586/100927584-b4f56d80-34aa-11eb-8a1a-13bbf0688c19.png)

</details>

**Comment by wbthomason** [comment]
Hmm, that one I cannot reproduce. I suspect this may be an error with your `plugins.colorscheme` or `plugins.lightline` modules, since that's the one part of your config that I didn't directly replicate. Do either of those functions contain upvalues? Due to the limitations of Lua's `string.dump`, functions passed to `config` and `setup` cannot use upvalues (this is hopefully getting worked around soonish).

**Comment by datwaft** [comment]
Strangely, I commented the lines for `plugins.colorscheme` and `plugins.lightline` and the uncommented them and it works.

And when copying the configuration to Debian from Ubuntu it doesn't work. It seems to be an error from my side.

Thanks!

**Comment by datwaft** [comment]
I think it was the old `packer_compiled.vim` that was giving me problems. After deleting it and compiling it again it works!

**Comment by wbthomason** [comment]
Ah, got it. Glad to hear it's working now!

**Comment by h4helium** [comment]
I've been breaking my head on the config part not getting applied for nvim-tree plugin. Finally - looking at this thread here, I decided to do a PackerSync to regenerate the plugin/packer_compiled.lua and the configs took. Thanks awefully for this thread.

Request we put in BOLD letters 🤣  that if we make a change in nvim/lua/plugins.lua, and packer_compiled.lua is already generated, either delete and reinstall or re-sync. Thanks!

**Comment by wbthomason** [comment]
@h4helium" Almost always, restarting Neovim (in case your `plugins.lua` was already loaded, to avoid the Lua module caching behavior that causes subtle problems) and then running compile/sync will properly regenerate the compiled file. Did this not work in your case?

**Comment by h4helium** [comment]
I guess I did not understand the compile process - that I have to do a recompile/resync everytime I change plugins.lua.
I basically stumbled onto it.

**Comment by wbthomason** [comment]
Gotcha, yes - this is a stumbling block for many people. Hopefully #402 (as soon as I get the time to work on it) should make use easier.
