### ISSUE TITLE
use `homebrew` to install `packer.nvim`

### ISSUE THREAD

**Issue by CollieIsCute** [wbthomason/packer.nvim#1052]
### Describe the feature
use `homebrew` to install `packer.nvim`, and I can use homebrew to update packer and other tools I installed at once.

**Comment by wbthomason** [comment]
You're welcome to create a Homebrew recipe to install `packer` - if you do, we can link it in the README. However, creating and maintaining such a recipe officially is out of scope for the project for now, so I'm going to go ahead and close this issue.
