### ISSUE TITLE
Exclude plugins from loading in specified file types

### ISSUE THREAD

**Issue by bojanmilevski** [wbthomason/packer.nvim#1074]
It would be nice to exclude certain plugins from being loaded in certain files and/or filetypes. This would greatly increase performance and usability in lower-spec machines (like the Raspberry Pi for example), where resources are limited.

In my everyday-to-day use, I find myself constantly editing `*.txt` files - such as `todo.txt`, `shopping-cart.txt` or `albums.txt`, where most of my plugins are just not necessary. I certainly do not need `lsp-config` loading in these files.

To further explain my request, here is a very dumb, yet practical example of what I mean:

```lua
require('packer').startup(function(use)

    use {
        'neovim/nvim-lspconfig',
        exclude_file = '*.txt' -- accepts regex
    }

    use {
        'L3MON4D3/LuaSnip',
        exclude_file = 'main.rs'
    }

    use 'nvim-telescope/telescope.nvim'

end)
```
This would mean that any file ending in `.txt` (regex'd) would not load `nvim-lspconfig` and any file named `main.rs` (no hate to rustaceans), would not load `LuaSnip`, but both would load `telescope.nvim`.

Looking forward on collaborating and contributing!

**Comment by XVilka** [comment]
It also makes sense for using NeoVim as a pager:
- https://github.com/rkitover/vimpager
- https://github.com/lucc/nvimpager

For example, when opening `man` or `info` pages, or when used as `git diff`/`git rebase`, etc editor, you got the idea.

**Comment by nat-418** [comment]
See this issue for a discussion on how to use the `opt` to lazy load plugins per filetype: https://github.com/wbthomason/packer.nvim/discussions/946

In a sense this is the opposite of what you are asking for, but it might get you the behavior you want in the end.

**Comment by bojanmilevski** [comment]
Closing this issue because I don't use packer anymore.
