### ISSUE TITLE
config and after slows down neovim

### ISSUE THREAD

**Issue by notwidow** [wbthomason/packer.nvim#1075]
Hi, first of all i really like packer. It's a great plugin for neovim. How ever i have issues with it when configuring neovim on newly installed OS. 
**ISSUE**
i clone my repo or copy nvim folder from backup drive to .config on new os. and when i open neovim it first of all shows nothing other than just a blank screen. but thats fine because packer is downloading and setting itself and this blank screen goes away after a second or 2 and the packer's float window appears and it tries to download plugins.
but when downloading it gives out errros
1. nvim-ts-auto tag not found treesitter.configs not found ( this is because treesitter is still downlaoding and ts-auto-tag uses treesitter )
2. colorscheme does not apply until i restart neovim.
**Tried**
1. to get rid of ts-auto-tag error about treesitter i added an option of **after** with ts-auto-tag in packer startup function and the error was gone. but it slowed down neovim
2. to get rid of colorscheme anot applied i added config option to colorscheme in packer startup function and it was then applied without restarting neovim but it also slows down neovim.
**HELP WANTED**
tell me a way to avoid getting these issues without compromising on neovim's performance.

**INFO**
1. I don't know lua except the very basics just for neovim.
2. i am not using packer's custom initialization..
NEOVIM: 0.7.2
OS: Arch Linux

**Comment by nat-418** [comment]
You should follow these steps:

1. Do a fresh install of Packer per the README.
2. Write a minimal `~/.config/nvim/init.lua` and load your plugins in there with no added configuration.
3. Test that you can get everything installed correctly.
4. Once you know Packer is installing your plugins correctly, then you can start incrementally adding back in your configuration to `init.lua` etc.
