### ISSUE TITLE
Restore cursor position in floating mode

### ISSUE THREAD

**Issue by numToStr** [wbthomason/packer.nvim#111]
Packer is awesome and thanks for making it. :heart: 

So, I enabled the floating mode, and now whenever I run `PackerInstall` or `PackerUpdate` the cursor always moves to the first buffer in the splits which is NERDTree.

What I want is `packer` to restore the cursor position to the last buffer/cursor position after the floating window is closed.

**Comment by wbthomason** [comment]
Ah, nice catch (I don't use the floating window implementation myself, so I'm less likely to find bugs with that). I'll look into fixing this, but if you're willing to add a patch to the floating window implementation, that would be great! You'll probably want to use `line()` to find the position in the buffer before opening a new window/buffer, and `nvim_get_current_buf`/`nvim_get_current_win` to find the correct window and buffer to return to.

**Comment by numToStr** [comment]
@wbthomason Thanks and but I am not sure how and when to return to the last buffer. I tried with `wincmd` in `BufWipeout` autocmd but It didn't work.

**Comment by numToStr** [comment]
Ahh, I fixed it by using `winnr` and `wincmd`. :smile:
