### ISSUE TITLE
Source plugins from other files in startup()

### ISSUE THREAD

**Issue by markfaine** [wbthomason/packer.nvim#1136]
I'm trying to keep each plugin (installation and configuration) together in separate files.  I get overwhelmed easily and my packer.lua is getting unwieldy.   

My thinking was just to keep each plugin in a separate file and load them in startup(), like this:

```lua
return require("packer").startup(function(use)
  require("plugins.nvim-webdev-icons")
  require(...)  - other plugin
  require(...)  - other plugin
  ...
end)
```

Then in `plugins/nvim-webdev-icons.lua`

```lua
use("nvim-tree/nvim-web-devicons")
```

Granted, in this example it's hardly necessary but in some cases there is extensive configuration and while I can put the configuration elsewhere I can't seem to put both the installation (use) and the setup() in another file.

Long-term, I'd like to include this list of plugins dynamically but for now, the first step is just figuring out how to get each `use(...)`  in a separate file.

Every time I've tried this I get an error:

```
attempt to call global 'use' (a nil value) 
```

I have seen some mention of getting around this in the readme, but I'm a very new newbie with lua and neovim and I'm not sure it applies in this situation.

Thanks for packer, I'm enjoying learning how to use it.

**Comment by EdenEast** [comment]
I will link to my own configuration where I do have all my plugins located in separate files. All of my plugins are defined in a folder called [modules](https://github.com/EdenEast/nyx/tree/671c4a6/config/.config/nvim/lua/eden/modules). An example of these file module file is [nav](https://github.com/EdenEast/nyx/blob/671c4a6/config/.config/nvim/lua/eden/modules/nav.lua). Any plugin that contains more complex configuration has is own file that can be required in the `config` section. 

I have created my own custom handles called [conf](https://github.com/EdenEast/nyx/blob/671c4a6/config/.config/nvim/lua/eden/core/pack.lua#L75) as a shorthand for `config = function() require() end`. 

I then go though all the files in that [modules folder](https://github.com/EdenEast/nyx/blob/671c4a6/config/.config/nvim/lua/eden/core/pack.lua#L100-L134) and collect all the plugin tables and pass that to packer. This full setup is in my [pack](https://github.com/EdenEast/nyx/blob/671c4a6/config/.config/nvim/lua/eden/core/pack.lua) file.

Hope this example help with creating your own setup.

**Comment by markfaine** [comment]
@EdenEast  Thank you, that is very helpful.  You have done a great job with your configuration and I will be going through it using it as an educational material ;)

Of course, I see the value in learning how to configure this.  I'm learning it now, however, I don't know why a configuration such as yours couldn't be provided as defaults to neovim.  I know everyone loves to customize but  I am starting to wonder why neovim doesn't provide something like this out-of-the-box.

They could just use a giant lookup table and let the configuration look up the values from the table, that would be a relatively easy way to make it customizable and provide sane defaults.  Those who want to customize still could do so but those who don't or can't could just set options in a config file and accept the defaults for the rest.

Sorry for the speculation, I just can't get over how much work goes into reinventing the wheel every time someone creates another neovim config.
