### ISSUE TITLE
PackerCompile encounters "concat" error

### ISSUE THREAD

**Issue by sidmadala** [wbthomason/packer.nvim#114]
- `nvim --version`: NVIM v0.5.0-dev+4383c0f
- packer.nvim version(commit hash): 18244f03b76094dd0a62f6a210ff9f4303b18e51
- `:checkhealth` result: All green
- Operating system/version: MacOS Catalina 10.15.4
- Terminal name/version: Alacritty 0.6.0
- `$TERM`: xterm-256color

### How to reproduce the problem from neovim startup

Use the configuration I have pasted below.

<details>
<summary>plugins.lua</summary>

```lua
--[[
Packer plugin configuration
--]]

-- Only required if you have packer in your `opt` pack
vim.cmd [[packadd packer.nvim]]

vim.cmd [[ autocmd BufWritePost plugins.lua PackerCompile ]]

require("packer").startup(function()

	-- Essential
	use {"wbthomason/packer.nvim", opt = true}		-- Packer can manage itself as an optional plugin
	use {"svermeulen/vimpeccable"}

	-- Aesthetic
	use {"jnurmine/zenburn", config = require("plugins.colorscheme")}
	use {"itchyny/lightline.vim", config = require("plugins.lightline")}
	use {"Yggdroot/indentLine", config = require("plugins.indentline")}
	use {"junegunn/goyo.vim", config = require("plugins.goyo")}
	use {"kyazdani42/nvim-tree.lua", requires = "kyazdani42/nvim-web-devicons", config = require("plugins.tree")}

	-- LSP
	use {"neovim/nvim-lspconfig", requires = "nvim-lua/completion-nvim", config = require("plugins.lsp_config")}
	use {"nvim-treesitter/nvim-treesitter", config = require("plugins.treesitter")}
	use {"liuchengxu/vista.vim", config = require("plugins.vista")}
	use {"rust-lang/rust.vim"}

	-- Utilities
	use {"tpope/vim-commentary"}
	use {"jiangmiao/auto-pairs"}
	use {"junegunn/fzf.vim", requires = "junegunn/fzf", config = require("plugins.fzf")}
	use {"junegunn/vim-easy-align"}
	use {"lervag/vimtex", config = require("plugins.vimtex")}
	use {"tpope/vim-fugitive", config = require("plugins.fugitive")}
	use {"christoomey/vim-tmux-navigator"}
end)
```
</details>

### Actual behaviour

When using `:PackerCompile` or any commands that rely on it, I get the following error.

`
E5108: Error executing lua share/nvim/site/pack/packer/opt/packer.nvim/lua/packer.lua:363: invalid value (boolean) at index 11 in table for 'concat' 
`

### Expected behaviour

I would expect that Packer.nvim would be able to compile plugins for lazy loading. However, even after reading the documentation, I am slightly confused as to how `PackerCompile` actually works in detail. If this error is the result of no plugins being able to be compiled lazily, I would expect an explicit error letting me know that none of my current options allow for lazy loading. 

Other than this error, Packer.nvim has been great in my transition to a pure Lua config. Thanks for the effort.

**Comment by wbthomason** [comment]
Interesting, thanks for the report. Your config looks reasonable, but I suspect there's an issue in one of the config modules you're requiring. Could you share a link to these modules?

`PackerCompile` should work with any plugins - what it does is to build code to automatically trigger loads of plugins based on certain conditions, and bundle in any user-provided configuration.

Adding explicit errors would be a good thing; it's been on my to-do list to add.

**Comment by sidmadala** [comment]
This is a [link](https://github.com/sidmadala/.dotfiles/tree/master/.config/nvim) to my Neovim dotfiles. Excuse me if I didn't understand what link you wanted correctly.

**Comment by nanotee** [comment]
Does replacing `require("module")` with `'require("module")'` (a string) fix the issue? It looks like you want to require the modules at startup rather than feed the results of `require()` to the `config` key

**Comment by wbthomason** [comment]
Whoops, sorry - I thought I'd replied to this last week.

@sidmadala: I believe @nanotee is right. From the link you sent, your config files are not modules and do not return a function, so you want the form @nanotee suggests. The alternative is to wrap the settings in each file in a function returned at the end of the file, and keep your plugin specification as it currently is.

The value for the `config` or `setup` key can either be a string (which will be directly included in the compiled output) or a function with no upvalues (which will be byte-compiled and called in the compiled output).

**Comment by sidmadala** [comment]
Doing either fix seems to brick the configuration and prevents the plugin's config file from loading.

**Comment by wbthomason** [comment]
Did you run `PackerCompile` or `PackerSync` after making the changes? If so, can you explain more what you mean by "brick the configuration"? Do you get errors, etc.?

**Comment by sidmadala** [comment]
I don't really know what happened between me replying, fiddling with my config a bit more, and Neovim sorting itself out. But following @nanotee advice solved the issue.

**Comment by wbthomason** [comment]
It is not the case that either all or none of the config key values need to be strings (wrapped in quotes) or not. All of the config values must be _valid_, meaning either a string, a table of strings, or a function value, but you can mix these types freely (for an example, you can see `plugins.lua` in my own dotfiles).
