### ISSUE TITLE
Weird jump on operator lazy-loading

### ISSUE THREAD

**Issue by kuator** [wbthomason/packer.nvim#115]
Hi, first, thanks for the amazing plugin! Second, I noticed that if I try to lazy-load any operator plugin, like vim-surround, vim-commentary, replacewithregister, the moment packer loads it, cursor jumps to the beginning of the line.
![Peek 2020-12-08 21-04](https://user-images.githubusercontent.com/25168308/101500731-12048e00-3999-11eb-83bd-5509012a64c5.gif)

**Comment by wbthomason** [comment]
Thanks for the report! Could you please post a snippet of your config showing an example of how you lazy-load one of these plugins? I suspect this is a bug in the main lazy-load function, probably to do with how we use `feedkeys` to run keymaps after loading a plugin.

Also, do you happen to know if this also happens with other plugin managers (e.g. `vim-plug`)?

**Comment by kuator** [comment]
Something like this:
```
packadd packer.nvim

lua << EOF
local packer = require('packer')
local use = packer.use

packer.init()
    use {
      'tpope/vim-surround';
      opt = true;
      keys = {{'n'; 'yss'}; {'x'; 'S'}; {'o'; 'ys'};{'n'; 'ys'}};
    };

packer.compile('~/.config/nvim/plugin/packer_load.vim')
EOF
```
Sorry, but I don't know about how vim-plug handles this, I used to use minpac and it didn't provide lazy-loading capabilities,
