### ISSUE TITLE
how to load packer's plugin on `nvim --noplugin`

### ISSUE THREAD

**Issue by NEX-S** [wbthomason/packer.nvim#1151]
if we startup nvim with `--noplugin` the packer's plugin seems won't load :O 

I wish to use packer in `--noplugin` (just because I don't want to use newtrw and other stuff etc.), I guess I need to add packer RTP manually ?

**Comment by EdenEast** [comment]
If you dont want to load netrw then you can just set the following to 1 in your init file:

```lua
  vim.g.loaded_netrw = 1
  vim.g.loaded_netrwPlugin = 1
  vim.g.loaded_netrwSettings = 1
  vim.g.loaded_netrwFileHandlers = 1
```

Here is a full [example] of disabling default features in neovim.

[example]: https://github.com/EdenEast/nyx/blob/671c4a6eb0ef6ecbda2531756bfc6cacd37f46d1/config/.config/nvim/lua/eden/bootstrap.lua#L45-L68

**Comment by wbthomason** [comment]
`--noplugin` skips loading plugins. This means *all* plugins, which includes packages. See `:h load-plugins`. That means that the only way you can use `packer` with `--noplugin` is via manual sourcing (I do not recommend for simple use) or *maybe* some sort of modified `packpath` + making every plugin `opt` and lazy-loading/calling `packadd` manually as required (also strongly not recommended).

As @EdenEast notes, you probably do not need `--noplugin` for most use. You can see https://github.com/wbthomason/dotfiles/blob/main/dot_config/nvim/lua/config/disable_builtins.lua for an example of blocking the built-in plugins from loading.
