### ISSUE TITLE
Recent update (on command-lazyloading) screws up vim-floaterm

### ISSUE THREAD

**Issue by Bekaboo** [wbthomason/packer.nvim#1166]
- `nvim --version`: 0.8.1
- `git --version`: 2.38.1
- Operating system/version: Linux, kernel 6.0.11-arch1-1
- Terminal name/version: kitty 0.26.5

### Steps to reproduce

1. Use packer to install vim-floaterm with lazyloading:

```
use {
  'voldikss/vim-floaterm',
  cmd = {
    'FloatermNew',
    'FloatermToggle'
  },
}
```

2. Enter nvim
3. Type in commandline: `FloatermNew`
4. Hit space
5. Floaterm opens a new terminal with error right after we hit space

### Actual behaviour

See above.

### Expected behaviour

Floaterm should not open a new terminal before we hit <Enter>. The problem is command-lazyloading: if I do not lazy load Floaterm, or use key-lazyloading, the problem will not appear.

**Comment by wbthomason** [comment]
I can't reproduce this. Is it still an issue? What `packer` commit are you on?

**Comment by Bekaboo** [comment]
> I can't reproduce this. Is it still an issue? What `packer` commit are you on?

Hi! Thank you for your reply, I also find that with minimal config i.e. single `init.lua` that only calls `packer.startup` and registers `packer` and `vim-floaterm` does not have this issue. I'm trying to figuring out the real reason. I'll close this if the issue is related to packer. Sorry for the inconvenience.

**Comment by Bekaboo** [comment]
It turns out `nvim-cmp` is the cause of the problem (don't know why). Close this issue.

**Comment by Bekaboo** [comment]
Reopen this issue because I find starting from commit `ed2d5c9c17f4df2eeaca4878145fecc9669e0138` the problem arises. Before this commit packer use `file` for `complete` option; after this commit packer use a custom function to get the completion list. This brings a better completion experience but also introduces the bug.
@wbthomason

**Comment by Bekaboo** [comment]
A short video demonstrating the bug:

https://user-images.githubusercontent.com/76579810/207523205-bd5db373-0769-4d8a-a33c-4f5016822f58.mp4
