### ISSUE TITLE
Conditional plugin installation

### ISSUE THREAD

**Issue by ChocolateOverflow** [wbthomason/packer.nvim#1169]
### Describe the feature

I want some packages to be installed only if some conditions are met. In my case, it's checking the system OS.

I currently have some plugins with dependencies that are very easy to install on Linux but a pain on Windows (which I only use because I need to for work), and I haven't got the time to debug all of those. I'm currently just commenting out those plugins on windows, but of course I'd like to keep my configs the same between all my daily-drive machines.

I know there's currently `cond` in `use` but that's just for lazy-loading, while the plugins in question fail during installation, so `packer` will keep trying to install them and fail when I update.

**Comment by lewis6991** [comment]
This is exactly what `use` is for. Surround the call to `use` with the check.

**Comment by ChocolateOverflow** [comment]
Oh right, `startup()` is given a function, not a table, as its 1st argument.

```lua
local is_linux = vim.loop.os_uname().sysname == 'Linux'
```

That was easy.
