### ISSUE TITLE
documentation about "package_path" is wrong

### ISSUE THREAD

**Issue by bfredl** [wbthomason/packer.nvim#117]
The docs mention:

    package_root   = util.is_windows and '~\\AppData\\Local\\nvim-data\\site\\pack' or '~/.local/share/nvim/site/pack',
    compile_path = vim.fn.stdpath('config') .. '/plugin/packer_compiled.vim',sync()

but this is not correct, `package_root` is defined as

    package_root = util.join_paths(vim.fn.stdpath('data'), 'site', 'pack'),

**Comment by wbthomason** [comment]
Thanks @bfredl! The docs got stale.

**Comment by wbthomason** [comment]
Fixed in 41a73a0 which didn't get linked because I forgot a #
