### ISSUE TITLE
requiring rocks in plugins in a recent version of osx breaks, since hererocks requires python, which was removed from the system

### ISSUE THREAD

**Issue by orhid** [wbthomason/packer.nvim#1196]
- `nvim --version`:
NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.8.2/share/nvim"

Run :checkhealth for more info
- `git --version`:
git version 2.37.1 (Apple Git-137.1)
- Operating system/version:
OSX 13.2 (b) Beta (22D7750270e)
- Terminal name/version:
alacritty 0.10.1 (2844606)

### Steps to reproduce
sin a recent update to OSX, apple decided to remove the installation of python (https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes#Python), which is required by the hererocks software that you use to install luarocks with packer, to reproduce require a not installed rock in some plugin, then attempt to :PackerUpdate
### Actual behaviour
here rocks complains about not being able to access python and throws this error

[packer.nvim] [ERROR 13:00:20] jobs.lua:83: Failed spawning command: python because ENOENT: no such file or directory
[packer.nvim] [ERROR 13:00:20] luarocks.lua:103: Failed to install hererocks: {
  exit_code = -1,
  signal = "ENOENT: no such file or directory"
### Expected behaviour
the plugins would install the required rocks correctly
### packer files

<details>
<summary>Plugin specification file(s)</summary>

Post or link your plugin specification files here, if you aren't able to provide a minimal
reproducer

</details>

<details>
<summary>packer log file</summary>

[ERROR Wed Jan 18 12:29:36 2023 7.0881782881919e+14] ...m/site/pack/packer/start/packer.nvim/lua/packer/jobs.lua:83: Failed spawning command: python because ENOENT: no such file or directory
[ERROR Wed Jan 18 12:29:36 2023 7.0881782957707e+14] ...te/pack/packer/start/packer.nvim/lua/packer/luarocks.lua:103: Failed to install hererocks: {
  exit_code = -1,
  signal = "ENOENT: no such file or directory"
}
</details>

<details>
<summary>packer compiled file</summary>

Post the contents of `packer_compiled.vim` here

</details>

**Comment by orhid** [comment]
my bad, i can see now that the python binary to be used can be specified in the config

**Comment by LostSoul-019364** [comment]
Excuse me, How exactly did you fix the issue?

**Comment by orhid** [comment]
in your packer config you can set the python command to be used in place of the default one, in my config it looks something like the code below, but somewhere in the packer docs there are more exact guidelines on how to do this

```lua
  config = {
    luarocks = {
      python_cmd = '/usr/bin/python3', -- set the python command to use for running hererocks
    }
  }
```
