### ISSUE TITLE
Command to list installed plugins

### ISSUE THREAD

**Issue by clason** [wbthomason/packer.nvim#12]
It would be useful (sometimes) to have a function that lists the plugins managed by packer together with some rudimentary information -- mainly whether it's a `start` or an `opt` plugin, and maybe the source (commit hash, branch, local dir...). As a bonus, it could show the full config dictionary when selected (just like the `update` command shows the git log after updating).

I saw there's already a `packer/display` function, but that is not exposed?

**Comment by wbthomason** [comment]
Thanks, this is a good suggestion. I had thought about adding this earlier, but opted against for the first version.

I'll try to get to this soon, but PRs are always welcome! Implementing this will entail:
1. For each managed plugin, get installation status (installed or not, `start` or `opt`)
2. For each installed plugin, get VCS information (if available)
3. Open a display window
4. Render the information for each plugin
5. Register a keybinding to display the config dictionary (which will need to elide e.g. functions that can't be easily represented as human-readable strings) when a plugin is selected.

(1) can use existing code mostly from `plugin_utils`; (2) can (after a bit of refactoring) use existing code from the module for `git`-managed plugins. (3) is trivial (using the `display` module). (4) is the main work item, but shouldn't be too involved.

As another note, `packer/display` is the module handling all display windows - not a function that shows plugin status.

**Comment by clason** [comment]
> I'll try to get to this soon, but PRs are always welcome! 

That's a fair point ;) I'll see if I can beat you, but I'll have to understand the code base better. 5. is probably best left for later.

> As another note, packer/display is the module handling all display windows - not a function that shows plugin status.

Makes sense, thanks!

**Comment by wbthomason** [comment]
This is now arguably accomplished by #171, which makes `packer_plugins` a global table. I'll leave it as open for the moment, because (1) I don't know if that table contains all the information you'd want to see and (2) there's no logic to display this information; you'd need to write it yourself.

**Comment by akinsho** [comment]
FWIW I think a further wrapper around listing the contents of that table in a nice format would be nice +/- the ability to manually load things similar to `vim-plug`'s `PlugStatus` command would be occasionally useful, also having this could also be a useful jumping of point for triggering manual actions for installed plugins such as deletions, reverting changes etc.

**Comment by akinsho** [comment]
@wbthomason I've been really yearning for this recently and would be happy to implement it myself. I just had a few questions around the display module. Could it be extended as is to allow for a `PackerStatus` command or would I need to implement something separate but re-using some elements. From a brief look it appeared to be maybe quite specific to it's current usecase

**Comment by wbthomason** [comment]
Ah, sorry - I didn't realize this was something that should be higher priority.

The display module is somewhat specialized to its current use, but I think extending it wouldn't be too involved. In particular, I think you could look at the `final_results` method to implement something like `PackerStatus` pretty easily - basically, you'd re-use the display initialization stuff (which sets buffer type and buffer local settings) and the logic for the headline message and setting the buffer lines (`set_lines`). The rest would just be what you'd need to write anyway - formatting the table of plugins. The main upside other than the reused setup logic is that this should automatically integrate with a user's configured `display_fn`, i.e. if this has been customized to display in a floating window/similar.

**Comment by akinsho** [comment]
> Ah, sorry - I didn't realize this was something that should be higher priority.
Woops didn't mean to imply I'd been waiting on you or other people were clamouring for this, it's just something that I've been thinking would be quite nice, to have a quick look at the current internal state of packer like what's loaded, what isn't what's optional what isn't etc.

Anyway thanks for the pointer will have a look in the next couple of days 👍🏿
