### ISSUE TITLE
Weird behavior for config key when running PackerCompile a second time

### ISSUE THREAD

**Issue by xonuto** [wbthomason/packer.nvim#128]
I ran into a problem when compiling plugins with condition and config flag multiple times.

Here is a minimal init.lua for reproducing.
```lua
vim.cmd('packadd packer.nvim')
local packer = require('packer')
local use = packer.use
packer.startup(function()
    use {'wbthomason/packer.nvim', opt = true}
    use {
      'neovim/nvim-lspconfig',
      config = function() require('lspconfig') end,
      cond = 'true'
    }
end)
```
The first run of :PackerCompile results in the string at line 155 of the packer_compiled.vim file:
```lua
	loadstring("\27LJ\1\2)\0\0\2\0\2\0\0044\0\0\0%\1\1\0>\0\2\1G\0\1\0\14lspconfig\frequire\0")()
```
Running it a second time produces clutter like this, which results in errors when trying to load the file:
```lua
	LJ)
```

I took a look at packer.compile and commenting out the ```plugin.config[i] = ...``` line in the following code seems to fix it:
```lua
      if plugin.config then
        plugin.executable_config = {}
        if type(plugin.config) ~= 'table' then plugin.config = {plugin.config} end
        for i, config_item in ipairs(plugin.config) do
          local executable_string = config_item
          if type(config_item) == 'function' then
            local stringified = string.dump(config_item, true)
            executable_string = 'loadstring(' .. vim.inspect(stringified) .. ')()'
            if not plugin.opt then stringified = executable_string end
            -- plugin.config[i] = stringified
          end

          table.insert(plugin.executable_config, executable_string)
        end
      end
```

**Comment by wbthomason** [comment]
Hmm. `PackerCompile` is stateless, so this really shouldn't be possible. Could you please share your/a representative `lspconfig.lua` file so that I can try to reproduce the error? Thanks!

**Comment by xonuto** [comment]
The ```require'lspconfig'``` loads a file provided by the plugin. You could even omit the function body and just set config to ```lua function() end``` and still have the same issue.
Regarding the state: the line commented out actually changes state and overwrites the config field of the plugin, because the table for ```plugin``` is not copied, if I remember that about lua correctly. So I don't think ```PackerComile``` is currently completly stateless.

I hope that helps!

**Comment by wbthomason** [comment]
Ah, my bad - when I was calling `PackerCompile` stateless, I was incorrectly assuming you were running it twice across two different executions of Neovim.

This is a bug, though commenting out that line isn't the fix - it causes issues with other types of lazy-loads. I'm working on a fix now.

**Comment by wbthomason** [comment]
This should now be fixed; please let me know if you continue to encounter the original error. Thanks!

**Comment by xonuto** [comment]
It works as intended now. Thanks for the quick fix!
