### ISSUE TITLE
Why I'm getting the error that plugin is used twice?

### ISSUE THREAD

**Issue by weilbith** [wbthomason/packer.nvim#129]
Hey :wave: 
I'm just in the middle of trying and figuring out a new setup structure for my NeoVim dotfiles using packages quite heavily. The basic idea is that I create for each plugin I use a `start` package that "installs" it by setting up Packer and eventually have other plugin scripts like key mappings (used to lazy load plugin) or filetype plugins etc. Then I have an `opt` package that contains the configuration for that plugin. This call for example the setup function of the plugin, sets highlights, etc pp. This optional plugin is added by the `config` property of the plugin. I tried this approach with a couple of plugins and it works pretty good. You could argue that this comes with a big overhead of directory structure. But I like it atm.
Unfortunately I'm always getting the error that I use a plugin twice. And I must admit that I don't understand why. Here is a minimal example just using the basic treesitter plugin.

Structure:
```
├── init.lua
├── pack
│  └── treesitter
│     ├── start
│     │  └── treesitter
│     │     └── plugin
│     │        └── install.vim
│     └── opt
│        └── treesitter
│           └── plugin
│              └── setup.vim
└── plugin
   └── packer_compiled.vim
```

And here the relevant files:
`init.lua`:
```lua
local test_site  = '/home/thore/.cache/nvim_test_site_pr'
local packer_install_path = test_site .. '/pack/packer/start/packer.nvim'
local packer_source_url = 'https://github.com/wbthomason/packer.nvim'

vim.o.packpath = vim.o.packpath .. ',' .. test_site

if vim.fn.empty(vim.fn.glob(packer_install_path)) > 0 then
  vim.api.nvim_command(string.format('!git clone %s %s', packer_source_url, packer_install_path))
end

packer = require('packer')
packer.init({
  package_root = test_site .. '/pack',
})

packer.use('wbthomason/packer.nvim') -- Else Packer wants to remove itself.
```

`pack/treesitter/start/treesitter/plugin/install.vim`:
```vim
lua packer.use({
    \   'nvim-treesitter/nvim-treesitter',
    \   run = 'vim.cmd("TSUpdate")',
    \   config = 'vim.cmd("packadd treesitter")',
    \ })
```

`pack/treesitter/opt/treesitter/plugin/setup.vim`:
```vim
echom 'do setup here...'
```

This is the error message I get: `[packer] Plugin "nvim-treesitter" is used twice!`

Thanks for any help.

**Comment by wbthomason** [comment]
Interesting use case. `packer` detects double-use on the basis of names (i.e. it doesn't look at the path), but I'm not seeing where you do use `nvim-treesitter` more than once. My best guess is that `packadd` is sourcing both `treesitter` plugins (though the docs indicate that this should not happen).

Could you please try renaming one of the two plugins and seeing if you still see the same error? If you do, then I believe this is probably an upstream bug with `packadd`.

**Comment by weilbith** [comment]
Alright yes. If I rename the `opt/treesitter` to `opt/test` and adopt the `config` property this works fine. But why does the error message tell me I load the `nvim-treesitter` twice. Shouldn't it then tell me I load twice `treesitter`? Without that I would not know how to go upstream.

**Comment by wbthomason** [comment]
So, what seems to be happening here is that the `start/treesitter/plugin/install.vim` file gets sourced twice, which means the call to `packer.use` that adds `nvim-treesitter` happens twice - and hence we get the error from `packer`.

**Comment by weilbith** [comment]
Ah I understand.Thanks for the explanation.
So this is also a big performance downside since everything for each `start` package gets executed twice. :thinking: 
But you are right. According to the docs this should actually not happen. So apparently I need to name the packages differently for the moment.

**Comment by weilbith** [comment]
If someone is interested into the upstream issue: [neovim/neovim#13568](https://github.com/neovim/neovim/issues/13568)
