### ISSUE TITLE
Allow multiple plugin specs in a single call to use

### ISSUE THREAD

**Issue by wbthomason** [wbthomason/packer.nvim#13]
e.g. permit both of these styles:

```lua
use 'foo/bar'
use {'baz/bax', {'bbb/aaa', opt = true}}
```

(from @clason's suggestion on Gitter)

**Comment by clason** [comment]
Ah, then you can have a startup check its first argument for a dict (which gets fed to `packer.use` key by key) or a user-provided function that is then called? First is for beginners/simple setups, second for intermediate/advanced use?

**Comment by wbthomason** [comment]
Yeah - this actually enables a lot of different uses:
- You can do either function/table for `startup`
- You can have a single call to `use` with a table containing plugins you *always* want, then still use conditional logic calling `use` with individual plugins for those you only sometimes want
- You can mix and match the `startup` and traditional styles

etc.

**Comment by wbthomason** [comment]
Added in 16c75ea (seems to work for me, at least)
