### ISSUE TITLE
Help wanted - Solution approach for lazy load via function call

### ISSUE THREAD

**Issue by weilbith** [wbthomason/packer.nvim#131]
Hey :wave: 
I currently have the need to load a package lazy when a function or `<Plug>` gets called. This should work similar to the lazy loading via commands. So I started to experiment and try if my solution approach works. So I tried it for a specific example but kept it generic enough to later make it a new feature for this plugin here. Since I have no clue how `<Plug>` does work in Vim, I'm focusing on the function call. 

So here I add a plugin to packer and make it just optional:

```lua
require('packer').use({ 'preservim/nerdcommenter', opt = true })
```

And then I have a `plugin/comment_mappings.vim` file with the following content:

```vim
function s:load(package, function, arguments) abort
  execute 'delfunction ' . a:function
  packadd a:package
  call call(function(a:function), a:arguments)
endfunction

function g:NERDComment(...) abort
  call s:load('vim-nerdcommenter', 'NERDComment', a:000)
endfunction

nnoremap <silent> <leader>cl <cmd>call NERDComment('n', 'Comment')<CR>
```

Note that I used `s:load` as this is the naming in this plugin. The `g:NERDComment` function would be what the compiler module needs to generate later. The `package` and `function` arguments will change as you maintain such information in a global dict, if I'm not mistaken.

Well, after all this approach doesn't work. When I `call s:load` from `g:NERDComment`, the latter function is still "active". This means the `delfunction` command fails with the error: `E131: Cannot delete function NERDComment: It is in use`.
Makes sense...

So I'm asking you and everyone who is watching the repository: do you have any other ideas how to implement such a feature? The idea is to later have a packer plugin attribute called `functions`, which works the same as the already existing `cmd` attribute.

For my currently "productive" NeoVim setup I still use `dein.nvim` which has this feature of lazy loading via functions. I should eventually take a look there how Shougo is doing it.

PS: I know that functions can also make use of ranges as commands do with the `range` keyword. I haven't used this feature yet and also haven't thought about how to support it here. To be 100% save we should think about that issue as well. Just for notice.

**Comment by weilbith** [comment]
Would an approach using Lua jobs work? So that we start a job from the "fake function" with a delay, which makes this function be finished when the job function deletes it?

**Comment by weilbith** [comment]
I tried to use Vim timer, but it throws the same error:

```vim
function g:NERDComment(...) abort
  let load_call = call(function('s:load'), ['vim-nerdcommenter', 'NERDComment', a:000])
  call timer_start(500, 'load_call')
endfunction
```

**Comment by wbthomason** [comment]
I think you probably want to look at the `FuncUndefined` autocommand for this; it will tell you the name of the function that was called.

**Comment by wbthomason** [comment]
Yep, looks like that's how `dein` does this: https://github.com/Shougo/dein.vim/blob/79dd0274e4303b40ad08807715f669e1925e5768/autoload/dein.vim#L33

**Comment by wbthomason** [comment]
Also, the `<plug>` mappings should be supported under the existing `keys` key - `<plug>` is just a special "fake" key iirc.

**Comment by weilbith** [comment]
> Yep, looks like that's how `dein` does this: https://github.com/Shougo/dein.vim/blob/79dd0274e4303b40ad08807715f669e1925e5768/autoload/dein.vim#L33

Ah nice. Let's experiment with that.



> Also, the `<plug>` mappings should be supported under the existing `keys` key - `<plug>` is just a special "fake" key iirc.

Sorry, but could you provide a small example please?

**Comment by wbthomason** [comment]
re: `<plug>`: Take a look at `:help <Plug>` and/or `:help using-<Plug>`

**Comment by delphinus** [comment]
FYI: thanks for signposts here and I also achieved the feature like dein's `on_func`.

```lua
use{
  'foo/bar.vim',
  setup = function()
    vim.cmd[[autocmd FuncUndefined bar#some#func packadd bar.vim]]
  end,
}
```

**Comment by wbthomason** [comment]
@delphinus: Does that work as expected? I would expect that you would need to not only `packadd bar.vim` but also call `bar#some#func` again, forwarding arguments.

**Comment by wbthomason** [comment]
This should be fairly easy to add to the lazy-load compiler, though I don't have time to get to it right now.

**Comment by weilbith** [comment]
I tried to add it to the compiler. But I failed because for some reason I can't access the `plugins` dictionary inside the callback function of the auto-command.

**Comment by weilbith** [comment]
> @delphinus: Does that work as expected? I would expect that you would need to not only `packadd bar.vim` but also call `bar#some#func` again, forwarding arguments.

No you don't. The auto-command is pretty smart and is not like a thrown exception, but especially made to create/load functions lazy by listening to this event. This makes it pretty easy.

**Comment by wbthomason** [comment]
> No you don't. The auto-command is pretty smart and is not like a thrown exception, but especially made to create/load functions lazy by listening to this event. This makes it pretty easy.

Ah, cool. I didn't know that.

> But I failed because for some reason I can't access the plugins dictionary inside the callback function of the auto-command.

Can you make a PR with what you had, and I can clean it up? Thanks!

**Comment by weilbith** [comment]
My first approach was quite stupid as I tried to use `*` for a single autocmd. I now just followed the same approach for all the other lazy loading features, especially how events work. So i just replicated the code structure from there. I hope that is fine.

**Comment by wbthomason** [comment]
Thanks for the draft PR! I'll take a look.
