### ISSUE TITLE
Fix startup() to not require use()

### ISSUE THREAD

**Issue by wbthomason** [wbthomason/packer.nvim#14]
i.e. default to `packer.use` if the argument is `nil`

**Comment by clason** [comment]
Yep, that would help minimize confusion for novice users!

**Comment by tjdevries** [comment]
I don't understand this issue.

**Comment by tjdevries** [comment]
```diff
 return require('packer').startup(function(use)
-  local use = packer.use
-  -- Clear state from previous operations
-  packer.reset()
-
```

This is what the readme should look like -- you don't need to "pass use" anywhere.

**Comment by clason** [comment]
I think the point is the first line (`function(use)`); it'd be nice if the call could be `function() ...`

**Comment by tjdevries** [comment]
You could use `_ENV`  to do this I think.

**Comment by tjdevries** [comment]
Like this might work:

```diff
diff --git a/lua/packer.lua b/lua/packer.lua
index 51b92bc..e8976df 100644
--- a/lua/packer.lua
+++ b/lua/packer.lua
@@ -284,6 +284,9 @@ packer.startup = function(user_func, user_config)
   packer.init(user_config)
   packer.reset()
 
+  local _ENV = {}
+  _ENV.use = packer.use
+
   user_func(packer.use)
 
   if not config.disable_commands then
```

**Comment by wbthomason** [comment]
@tjdevries https://github.com/wbthomason/packer.nvim/pull/16 is what I was intending to do; does that seem reasonable? I'm also not sure I understand the `_ENV` approach - doesn't that always use `packer.use`?

**Comment by wbthomason** [comment]
Ah, wait, nvm - ignore my PR for the moment; I made a dumb mistake in misinterpreting the purpose of `user_func`.
