### ISSUE TITLE
lazy-loading with <C-j> causes an error

### ISSUE THREAD

**Issue by delphinus** [wbthomason/packer.nvim#147]
* `init.lua`

    ```lua
    vim.cmd[[packadd packer.nvim]]
    require'packer'.startup(function()
      use{'wbthomason/packer.nvim', opt = true}
      use{'spolu/dwm.vim', keys = '<C-j>'}
    end)
    ```

And run nvim, type `<C-j>`, then an error occurs.

```
E114: Missing quote: "
E116: Invalid arguments for function <SNR>7_load
```

Just after nvim launched, `<C-j>` = `<NL>` map has this below. Perhaps Neovim evaluates this with a new line after `{ "keys": "`.

```vim
:map <C-j>
   <NL>        * <Cmd>call <SNR>7_load(['dwm.vim'], { "keys": "<NL>", "prefix": "" })<CR>
```

**Comment by wbthomason** [comment]
Thanks for the report! It seems like maybe we need to escape the `keys` string? I wonder if there's a better way to do this than hard-coding some special cases...

**Comment by nanotee** [comment]
I think the `<lt>` keycode exists to disambiguate cases like these. I see `packer` already handles the `<CR>` key in `compile.lua`:
https://github.com/wbthomason/packer.nvim/blob/f62f2fc1fb1802a217afdbac6a487e541019f658/lua/packer/compile.lua#L346

Maybe it could be made more general by replacing every `<` with `<lt>`. I'm not 100% confident it wouldn't break any setups though...

**Comment by wbthomason** [comment]
Yeah, me neither - in particular if people have maps on `<` alone, or `<{SOME CHARACTER}`, etc...
