### ISSUE TITLE
"Too many files" when updating

### ISSUE THREAD

**Issue by mhartington** [wbthomason/packer.nvim#149]
Applogies if this has been asked already, but when trying to update my installed plugins with the `PackerUpdate` command, I get  the following error 

```
Error executing vim.schedule lua callback: Vim:E903: Process failed to start: too many open files: "/bin/zsh"
remote/host: python3 host registered plugins []
```

And only get a few plugins to update. Seems like it's failing to check all my plugins? I have about 80 of them, so not sure if that's too many.

**Comment by wbthomason** [comment]
Fascinating! I have never seen that one before, even with a larger number of plugins. There should theoretically not be an upper bound.

Could you please share (1) your system info (OS, etc.) and (2) your config? Thanks!

**Comment by mhartington** [comment]
Sure, im on macOS big sur and my plugins/config are here 

https://github.com/mhartington/dotfiles/blob/master/config/nvim/lua/mh/plugins/init.lua

**Comment by wbthomason** [comment]
Hmm, ok. Does this happen every time you run `PackerUpdate`? Unless you have the max number of files per process set weirdly low, `packer` should not be opening nearly enough files to run into that limit. If you still run into this when you run `PackerUpdate` right after opening Neovim in a fresh shell, then we know something else is going on.

**Comment by mhartington** [comment]
So I moved packer from being in opt to being in start and surprisingly haven't run into this issue since. 

Not sure on the "max number of files per process". Is that a packer setting or shell/os setting?

**Comment by wbthomason** [comment]
....absolutely bizarre. The "max files per process" is an OS-level setting, but should be way higher than we'd run into here, unless your shell/Neovim has a lot of other files open (for example, on my Arch Linux system, this value is 1024)

**Comment by mhartington** [comment]
Oh wow, looking into this...

```
$ launchctl limit maxfiles
        maxfiles    256            unlimited
```

That's super low! I think I can close this and mark it as being caused by that setting, and nothing to do with packer. Sorry for the noise!

**Comment by wbthomason** [comment]
No worries; glad it's working again!

**Comment by kornicameister** [comment]
@mhartington did you try changing that setting?

**Comment by bekicot** [comment]
@kornicameister I Updated mac today and got this issue. Are you doing the same? Did you also try updating the setting?

**Comment by kornicameister** [comment]
The one posted above crashed my Mac. Using ulimit instead fixed the issue

**Comment by phantomwhale** [comment]
Cross-linked - hit this issue today on MacOS, and didn't quite see the fix spelled out here (nor was this quite the problem I saw; but it's the one Google pushed as the first hit, so I guess others might arrive via the same path).

A little more research on `launchctl` and `ulimit` showed me how to modify one or the other and try again, but in the end I opted to cap the number of jobs Packer uses (as that's a fix that's more likely to persist over time in my current dotfiles setup)

That solution was detailed in this separate issue - https://github.com/wbthomason/packer.nvim/issues/1199
