### ISSUE TITLE
"run" and support for vim commands

### ISSUE THREAD

**Issue by bobicino** [wbthomason/packer.nvim#150]
Hi!
I just started using packer.nvim and it is fantastic.
However, there is something I cannot find in the documentation, and I'm not sure packer has support for it.
In vim-plug, there is the `Do` action, to execute commands after a plugin is updated.
Here we have `run`.
The vim-plug counterpart has built-in support for vim commands. So if a command in `Do` starts with `:`, then it is recognized as a vim command.
I used this with Treesitter: `Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}`.
Does packer support this function?

**Comment by akinsho** [comment]
@bobicino the equivalent is `run = ':TSUpdate'`

**Comment by bobicino** [comment]
Thanks a lot!
I thought it was like that but I wasn't sure.

**Comment by wbthomason** [comment]
This seems resolved (thanks, @akinsho!), so I'll go ahead and close the issue. Feel free to open it again or use the Discussion tab if you have other questions, etc.!
