### ISSUE TITLE
Packer compile does not pick up require-d config changes

### ISSUE THREAD

**Issue by akinsho** [wbthomason/packer.nvim#152]
When using packer with dependency configs specified via `require`
e.g. `use {"myplugin", config = require("path.settings")}`, updating the file being required isn't picked up till packer compile is re-run multiple times.

Understandably the changes won't be seen till `packer_compiled.vim` is sourced but the actual file doesn't reflect the newly added change till it is rerun. So the ideal flow would be
1. make change in "path.settings"
2. Run `PackerCompile`
3. Restart neovim (ideally not even this since it's disruptive but 1 problem at a time 😄 )

I've narrowed down the issue to require's behaviour i.e. it caching the result of the first require so subsequent calls to compile don't see that the file is different. So the way to get this to work is currently.
1. Make a settings change
2. Restart neovim or if you know to do this set the settings package to be unloaded and re require it
3. Start neovim run packer compile
4. (if you want the setting to actually be active) restart neovim (or potentially re-source the compiled vim file)

Ideally I wonder if configs supplied like this (a pattern I've seen in quite a few dotfiles) can either work this way i.e. I make a change run a command and packer picks up that it needs to recompile with these changes, seems like in this case packer will have to unload a bunch of config modules for the user 🤔 😓 . Not sure how easy that would be. Or a built in mechanism specifically for specifying config options for plugins that require reams of it (that might be tidier kept elsewhere) that would take a path and manage requiring it and reloading it every time compile is run so every run picks up the changes.

e.g.
```lua
use {'myplugin', config_path = "myplugin.settings"}
-- In packer somewhere
require(plugin.config_path)

-- During compile
if config_path then
  packages[plugins.config_path].loaded = nil
  config = require(plugins.config_path)
  config_to_dump_as_str = config
end
```

This is all only thought halfway through, just a sketch of a possible solution, alternatively maybe the solution would be as simple as something like `dofile` but trying that causes packer to error. I'm not super familiar with how that function differs from `require` except that I'd assumed it wouldn't cache values but would run the code and return the value

**Comment by akinsho** [comment]
As a side note I know you can specify the option as `[[require("value")]]` which just runs require at some later date rather than in the startup function. I'm not actually sure if it's better or worse to have config loaded in the use function or presumable later via evaluating the string, in which case maybe the solution is just formalizing `[[require("thing")]]` as the solution but the syntax _to me_ (super subjective) is kind of weird and it could be offered more like `config_path = "path"` and when packer dumps out the string it wraps anything in that key with a require call?

**Comment by akinsho** [comment]
Actually found a good explanation of [`dofile`](https://stackoverflow.com/a/34235619), so if you pass in the full path to your settings file and loadfile `plugins.lua` then run packer compile that will update the compiled file. So I guess I'm wondering if this process can be abstracted away from the user and they just specify a module (hopefully, rather than an absolute path)

**Comment by wbthomason** [comment]
Thanks for the report and diagnosis! The idea of adding something like `config_path` is reasonable, but I'm leery of adding a separate mechanism for specifying configurations.

The trick here would be to (1) add logic to `PackerCompile` to reload `plugins.lua` and (2) recursively reload the modules it `require`s. This second part is the real tricky part - I'm not sure how or if this is possible in Lua.

Just thinking out loud here, but maybe we could do something like iterating through `config` and `setup` values and checking ourselves if they're already in the `packages.loaded` table, then forcing a reload if they are? That seems like it should work...

**Comment by akinsho** [comment]
@wbthomason I think without a separate mechanism i.e. if the user specifies the `config` or `setup` inline using `use {"mplugin", config = require("path")}` packer wouldn't be able to tell that the config came from a require since it would already be evaluated at that point right? so the `require("path")` at that point would be equivalent to `config = <function returned from require>`.

I do think the general idea of iterating through `config` and `setup` and reloading those is a good solution I'm just not sure you could do it without having access to the path inside of packer. Could it be that `config` or setup takes a `config = { path = "my/module" }` and if config is a table the path is required inside of packer and then on compile we check all the configs and setups specified as tables with paths and force reload all of them?

Not sure if I'm missing something though and you can somehow see what was required inside of packer if the config is specified as `require(config)`

**Comment by wbthomason** [comment]
The idea (which might be wrong) was that we could make an inverted table from `package.loaded`, then for each `config` or `setup` value, search through this inverted table for a matching value. If we find one, then that means it was `require`'d, and we can look at the corresponding key to know what to reload.

**Comment by akinsho** [comment]
@wbthomason to make sure I'm on the same page as you you mean
```lua
-- we can potentially disregard any packages than don't return a function
local tbl = {
	<func_ref> = "package-name"
}

-- in or before compile
for _, v in pairs(tbl) do
  local package = tbl[v.config]
  if package then
   packages.loaded[package] = nil
   require(package)
  end
end
```

**Comment by wbthomason** [comment]
That's the basic idea, yes! I'm not 100% sure it'll work - in particular, if the `require`'d module itself requires modules, we can't detect and recursively reload those - but it is a lot more convenient than a separate, custom require function (to my mind).

**Comment by akinsho** [comment]
Tbh I'm not sure if it matters in this case since any require statement in the function is not going to be resolved inside the `packer_compiled.vim` anyway it will still just be a call to a require. The thing that matters is that the string in the compiled output is updated which this should allow for.

I'm happy to look into implementing this (or something close to it), it feels like it might be a bit "magic" to the user since there'll be this automatic inexplicable reloading of modules but probably it won't matter since I'd guess most users would ideally like it to just work and not wonder about why 🤷🏿

**Comment by wbthomason** [comment]
If you'd like to take a stab at it, that would be great! Feel free to make a draft PR; I can offer comments and guidance.

I think this will (hopefully) be positive "magic" - it should only trigger upon a compile/sync, and ideally will just seamlessly make life easier.

Thanks for the great suggestion!
