### ISSUE TITLE
can install some plugins from GitHub but not others

### ISSUE THREAD

**Issue by sturban** [wbthomason/packer.nvim#154]
Playing around with init.lua and latest nightly build of nvim. 
The below plugins from GitHub clones and installs fine
```
return require('packer').startup(function()
    -- Packer can manage itself as an optional plugin
    use {'wbthomason/packer.nvim', opt = true}

    use {'junegunn/fzf'}
    use {'junegunn/fzf.vim'}
    use {'yggdroot/indentline'}
    use {'tpope/vim-fugitive'}
    use {'tpope/vim-commentary'}
    use {'ojroques/nvim-hardline'}
    use {'ojroques/vim-oscyank'}
    use {'preservim/nerdtree'}
...
```

But when I add these plugins to the bottom of the list, PackerInstall gives errors for all three
```
    use {'nvim-lua/popup.vim'}
    use {'nvim-lua/plenary.vim'}
    use {'nvim-telescope/telescope.vim'}`
```

Here's one of the identical errors for these plugins. 
```
 Failed to install nvim-lua/popup.vim
  -------------------- HELPERS -------------------------------                                                        
│  Errors:
│    Cloning into '/home/neovim/.local/share/nvim/site/pack/packer/start/popup.vim'...
│    fatal: could not read Username for 'https://github.com': terminal prompts disabled
```
-Funny thing is that I had exactly same problem when trying out paq, the other plugins cloned fine, the above three did not. 

Same problem comes up both on a Docker-image with Ubuntu Hirsute and on Windows 10 Pro.  

When doing `git clone` from command-prompt for these three plugins, it works fine.

**Comment by nanotee** [comment]
There's a typo in the repository names: they should end in `.nvim`, not `.vim`. Since the repositories don't exist, Git tries to prompt for a password

**Comment by sturban** [comment]
-Doh!  That was it, thank you!
