### ISSUE TITLE
:PackerClean wants to delete plugin it shouldn't

### ISSUE THREAD

**Issue by sandersantema** [wbthomason/packer.nvim#156]
I've got the following packer startup function:

```lua
  use {'lervag/vimtex', ft = 'tex'}
```

Still on `:PackerClean` packer tries to remove vimtex. Removing vimtex and reinstalling it doesn't work. I've got the latest version of neovim and packer installed. This is my config related to packer, if any other info is needed to debug this issue please let me know:

```lua
vim.cmd [[packadd packer.nvim]]
return require('packer').startup(function(use)
  use {'wbthomason/packer.nvim', opt = true}
  use {'tpope/vim-unimpaired'}
  use {'tpope/vim-surround'}
  use {'tpope/vim-commentary'}

  -- FZF
  use {'junegunn/fzf'}
  use {'junegunn/fzf.vim'}
  use {'vijaymarupudi/nvim-fzf'}

  -- General utilities
  use {'kassio/neoterm'}
  use {'easymotion/vim-easymotion'}
  use {'justinmk/vim-gtfo'}
  use {'christoomey/vim-tmux-navigator'}
  use {'MattesGroeger/vim-bookmarks'}
  use {'https://gitlab.com/HiPhish/info.vim'}
  use {'triglav/vim-visual-increment'}
  use {'romainl/vim-cool'}
  use {'dstein64/vim-startuptime', opt = true, cmd = {'StartupTime'}}
  use {'reedes/vim-pencil', opt = true, cmd = {'Pencil'}}

  -- Vimwiki
  use {'vimwiki/vimwiki'}
  use {'michal-h21/vim-zettel'}

  -- Colorscheme
  use {'arcticicestudio/nord-vim'}

  -- Neovim lua
  use {'svermeulen/vimpeccable'}
  -- https://github.com/bfredl/nvim-luadev

  -- Filetypes and programming languages

  -- Tests
  use {'junegunn/vader.vim'}

  -- Completion
  use {
    'Shougo/deoplete.nvim',
    run = ':UpdateRemotePlugins',
    -- config = 'vim.call[[deoplete#enable]]'
  }
  use {'Shougo/deoplete-lsp'}

  -- nvim-lsp
  use {'neovim/nvim-lspconfig'}
  use {'nvim-lua/diagnostic-nvim'}
  use {'p00f/nvim-ts-rainbow'}
  use {'nvim-treesitter/nvim-treesitter-refactor'}
  use {
    'nvim-treesitter/nvim-treesitter',
    run = ':TSUpdate',
    config = require'nvim-treesitter.configs'.setup {
      ensure_installed = 'maintained',
      highlight = {enable = true, disable = {}},
      indent = {enable = true},
      use_languagetree = false,
      incremental_selection = {
        enable = true,
        keymaps = {
          init_selection = 'gnn',
          node_incremental = 'grn',
          scope_incremental = 'grc',
          node_decremental = 'grm',
        },
      },
      rainbow = {enable = true, disable = {'bash'}},
      refactor = {highlight_definitions = {enable = true}},
    },
  }

  -- Linting
  use {'w0rp/ale'}

  -- General
  use {'sheerun/vim-polyglot'}
  use {'sirver/ultisnips', ft = 'tex'}

  -- LaTeX
  use {'lervag/vimtex'}

  -- csv
  use {'chrisbra/csv.vim', ft = 'csv'}

  -- Fish
  use {'kmarius/vim-fish', ft = 'fish'}

  -- Haskell
  use {'monkoose/fzf-hoogle.vim'}
  use {'neovimhaskell/haskell-vim'}
end)
```

**Comment by wbthomason** [comment]
This might be a regression after #143. Did this just start happening recently? Also, is `vimtex` the only plugin for which this happens?

**Comment by sandersantema** [comment]
I've just switched to packer and this happened right after install, so unfortunately I've got no clue whether this happened because of some specific update. It only happens for `vimtex` indeed.

**Comment by wbthomason** [comment]
And, just to confirm - is the `vimtex` specification you use the one at the top of your post, or the one in your config snippet? One lazy-loads `vimtex` (using `ft`); the other has it as a `start` plugin.

Also, just as a style note: if you want, you can omit the brackets for plugins which have no additional configuration (e.g. `use {'monkoose/fzf-hoogle.vim'}` could be just `use 'monkoose/fzf-hoogle.vim'`). It makes things a bit more concise.

**Comment by sandersantema** [comment]
It's the one without lazy loading (i.e. without `ft`), I've probably removed it in order to debug after copying the first line and forgot I changed it. 

Thanks for the style tip, still getting to grips with lua :)

**Comment by wbthomason** [comment]
Hmm. I'm having trouble reproducing this issue - using the config you posted, `vimtex` gets installed and doesn't get cleaned, for me. Could you walk me through the steps you take that trigger the error?

**Comment by sandersantema** [comment]
Sorry for the late response. Unfortunately there's not much I can tell you about it given that I've simply installed the plugin and encountered the bug after running `:PackerClean` afterwards. This is with or without any additional configuration of the plugin packer wise.

**Comment by disrupted** [comment]
I am having a similar issue. My config is the following: [init.lua](https://github.com/disrupted/dotfiles/blob/master/.config/nvim/init.lua)

Every time I run `:PackerClean` it wants to remove `completion-nvim`, `nvim-lspconfig` and `nvim-treesitter` even though those are clearly in use.

**Comment by wbthomason** [comment]
For both of you: is there any chance you have the plugins `packer` erroneously tries to remove installed at two locations? For instance, a copy in both `opt` and `start`?

**Comment by disrupted** [comment]
> For both of you: is there any chance you have the plugins `packer` erroneously tries to remove installed at two locations? For instance, a copy in both `opt` and `start`?

You're right, I just checked and for me this is actually the case. Wonder how that happened.

**Comment by sandersantema** [comment]
This could've indeed been the case. It seems the issue has resolved itself in any case, but I haven't paid much attention to it since I haven't been using the plugins with which I was having problems much lately.

I just did notice packer leaves behind the old plugin directory in opt if you change a plugin from being lazy loaded/ optional to required on startup i.e. `use {'lervag/vimtex', ft = 'tex', opt = true}` vs `use {'lervag/vimtex'}`. It might be nice to move the plugin directory when executing `:PackerCompile` instead of having to delete the old plugin and downloading it again.

**Comment by wbthomason** [comment]
Ah, so this might be the source of confusion. When you run `:PackerCompile`, it only regenerates the lazy loaders. You need `:PackerSync` (which runs update and compile) or `:PackerUpdate` to actually move the plugin - `packer` will not redundantly download, but does just move the directory. I suspect what happened is that `:PackerInstall` probably got run after you changed the plugin type, but before a update or clean was run. Sorry for the confusion!

**Comment by danielo515** [comment]
I also ended with plugins being on two folders, the ones described on this issue. How that can be? Maybe if I mistakenly lazy load a plugin it gets copied to both locations or what?
