### ISSUE TITLE
attempt to index a boolean value

### ISSUE THREAD

**Issue by F4IL3D** [wbthomason/packer.nvim#161]
Hi Wil,

for 2-3 days i have been unable to load the packer module.
In order to rule out an error in my config, I carried out the following steps:

nvim -u NORC --noplugin
:packadd packer.nvim
:lua require('packer').startup(function() use {'wbthomason/packer.nvim'} end)

This then leads to the following error:

E5108: Error executing lua [string ":lua"]:1: attempt to index a boolean value

![image](https://user-images.githubusercontent.com/48415231/104608115-e6ed1880-5681-11eb-8229-e4ac75f2a8a8.png)

Even stranger, `:lua print(vim.inspect(require('packer')))` returns _true_ 

NVIM Version: v0.5.0-dev+1023-gea8756f85
Packer Version: latest (today)
OS: Arch Linux (WSL2)

**Comment by akinsho** [comment]
@F4IL3D I've become pretty familiar with this error you probably have something invalid in your `packer_compiled`. For me when I was first setting up it was that I had an `upvalue`(using a local variable inside a packer config function) in my `packer_compiled.vim` as a quick test if you delete this file and re-open nvim does that work?
1. If it does then try removing all `setup`,`config` etc. from your plugin declarations and re-run packer compile and see if the error happens again.
2. If it doesn't it means one of `functions` in one fo the plugin configs is using a local variable, which isn't allowed.

I'd been wondering if it's possible to capture this error and embellish it with some sort of hint but it's quite generic, I wonder if all of the `packer_compiled.vim` script can be placed in a `try/catch/finally` block and all exceptions are caught and somehow massaged into something more coherent e.g. `[packer] Your packer compiled file is likely invalid please inspect you plugins`. Thoughts @wbthomason (also sorry for sticking my nose in 😆 )

**Comment by wbthomason** [comment]
@akinsho: That's a reasonable theory, but I would think that @F4IL3D's use of `--noplugin` and `-u NORC` would prevent `packer_compiled.vim` from being sourced, right? I separately like the idea of providing better error messages from `packer_compiled`; I should be able to throw something together for that now. (and no worries for "sticking your nose in"; I'm always happy to have debugging help :smile:)

@F4IL3D: In case I'm wrong about `packer_compiled.vim` not getting sourced because of your flags, could you please try deleting or moving that file and see if the error persists? Alternatively, there's no chance you have a `packer.lua` anywhere that could be getting found first, right?

**Comment by F4IL3D** [comment]
@akinsho and @wbthomason thanks for the replies

That it might have something to do with packer_compiled.vim was also my first thought. 
That's why I deleted them first to rule this out.  ;-)

![image](https://user-images.githubusercontent.com/48415231/104632495-0eea7500-569e-11eb-8cea-e0450dc3c355.png)

But step by step.
I've already tried these:

1. delete the packer_compiled.vim file -> error persists
2. delete all config files under .config/nvim and restore from them from my git repo -> error persists
3. delete packer.nvim and redownload the latest version -> error persists
4. installation of the latest nvim nightly -> error persists
5. start nvim with `-u NORC --noplugin` (default config, no plugins), then load packer (`:packadd packer.nvim`) and execute minimal packer.startup  (`:lua require('packer').startup(function() use {'wbthomason/packer.nvim'} end)`) -> error persists

@wbthomason I don't know whether ` --noplugin` and `-u NORC ` would prevent packer_compiled.vim from being sourced because I don't have one any more.  ^^

I also can't create a new one because all the commands like PackerCompile are not there, even though packer was loaded with  packadd.

![image](https://user-images.githubusercontent.com/48415231/104647335-fbe1a000-56b1-11eb-8752-7656e49b7586.png)

It seems like packer is not loading properly. I just don't know why. I checked all the commits of the last few days at neovim and packer but found nothing to explain this behavior.

The first time the error occurred after this commit:

https://github.com/wbthomason/packer.nvim/commit/6d1e029d07efc03070debb8aa8f6126935498908

But it doesn't look to me as if it could be related to that.

There were no other system updates that could be related to neovim. As a package I use neovim-nightly-bin, so a compilation error is also excluded.

So I don't know where to look anymore.  :-(

**Comment by wbthomason** [comment]
I see the problem, I think. 
> Alternatively, there's no chance you have a packer.lua anywhere that could be getting found first, right?

Looks like (from your `tree` output) you have a `~/.config/nvim/lua/packer.lua`. I believe what's happening is that, when you run `require('packer')`, **that** file is found before the `packer.lua` in the plugin (given that package directories come after `~/.config/nvim/lua` in Neovim's `package.path`).

Try renaming that file to `plugins.lua` or `packer_config.lua` or something, and see if the error persists.

**Comment by F4IL3D** [comment]
Now that you mention it. It was in front of my eyes the whole time and I didn't see.
After deleting packer.lua everything works again.

I also very much apologize for wasting your time.  :-(

SOOOOOORRRRRRYYYYYYY!!!

**Comment by wbthomason** [comment]
Not a problem at all; happy to help!
