### ISSUE TITLE
Check if plugin is loaded

### ISSUE THREAD

**Issue by YodaEmbedding** [wbthomason/packer.nvim#167]
Is there a way to check if an arbitrary plugin is loaded?

```lua
if packer.is_loaded("neoclide/coc.nvim") then
  print("coc.nvim is available!")
end
```

---

`vim-plug` provides a global `g:plugs` which can be used to determine if a plugin is loaded. For instance:

```vim
function! PlugLoaded(name)
    return (
        \ has_key(g:plugs, a:name) &&
        \ isdirectory(g:plugs[a:name].dir) &&
        \ stridx(&runtimepath, trim(g:plugs[a:name].dir, "/")) >= 0)
endfunction

if PlugLoaded("coc.nvim")
    echo "coc.nvim is available!"
endif
```

**Comment by akinsho** [comment]
I don't think this exists already but I've been wanting something like this, since I moved over. I hacked something into place using `globpath` to check the `runtimepath`. But that's not reliable and an official method would be good IMO

**Comment by wbthomason** [comment]
It doesn't exist yet, but would be trivial to add - basically, we'd need to make the `plugins` table in the generated code in `packer_compiled.vim` a global rather than a local, and add entries for non-lazy-loaded plugins to it. It already contains a field `loaded` which is changed to `true` when a plugin gets lazy-loaded.

**Comment by akinsho** [comment]
@wbthomason you mean global in lua e.g. `_G.packer_plugins`, think this would be better than trying to use a `vim.g` variable given the issues that has with changing table values, and for adding the entries for non-lazy loaded values I'm guessing the values in the existing plugins table exclude any plugins loaded at the start?

I could look into it later on this week if no one else does. A lot of my config has historically depended on checks like the example from @YodaEmbedding would be nice to have an official mechanism.

**Comment by wbthomason** [comment]
Yes, a Lua global. I wasn't aware that people used the `g:plugs` variable like this, but it's easy and low cost to enable for `packer`, so I'm ok doing so. I may have time to get to it this coming week; @akinsho, feel free to tackle it sooner if you'd like. Thanks for the suggestions n

**Comment by luiz00martins** [comment]
@wbthomason Is there a way to check for a plugin in your `init.lua`? It seems like #171's variables are `nil` when `init.lua` is running, and are only set later on.

I wanted to run `require('...')` for a certain plugin only if that plugin is actually `use`d by packer. Is there a way to do that?

**Comment by Susensio** [comment]
> @wbthomason Is there a way to check for a plugin in your `init.lua`? It seems like #171's variables are `nil` when `init.lua` is running, and are only set later on.
> 
> I wanted to run `require('...')` for a certain plugin only if that plugin is actually `use`d by packer. Is there a way to do that?

This would be awesome!
