### ISSUE TITLE
What does the return statement do in the example plugins.lua file?

### ISSUE THREAD

**Issue by pianocomposer321** [wbthomason/packer.nvim#168]
Snippet from plugins.lua example file:
```lua
return require('packer').startup(function()
```

Removing the return statement and just calling `require('packer').startup()` seems to do the same thing.

I am kinda a noob when it comes to lua, and my questions are these:
What does return do in lua in general (when on the file/global scope, not in a function)?
What does it do in this particular case?
Is it necessary?
If not, why is it there?

**Comment by wbthomason** [comment]
`return` in the global scope returns a value from a module. i.e. if I have a Lua file `foobar.lua` containing:
```lua
local mod = {}
mod.somefn = function(x, y) return x + y end
mod.someconst = 'hello'
return mod
```
then the result of e.g. `require('foobar')` will be a table with keys `somefn` and `someconst` as defined above.

In this particular case, I believe the `return` is redundant. I didn't write that particular example myself (I think; I don't personally use the `startup` function), so I can only guess as to why it's included, but I believe it's a typo. I'll remove it now.

Thanks for the question, and please feel free to reopen the issue if you have more questions, etc.!

**Comment by pianocomposer321** [comment]
Nope, that's all I wanted to know! Thanks for the answer!

**Comment by MuhammedZakir** [comment]
Also PIL recommends `return` statement approach.

https://www.lua.org/pil/15.1.html:
> Maybe you noticed that the last statement in the package was
> ```
>     return complex
> ```
> This return is not necessary, because the package is already assigned to a global variable (complex). Nevertheless, we consider a good practice that a package returns itself when it opens. The extra return costs nothing, and allows alternative ways to handle the package.
