### ISSUE TITLE
Early plugin loading

### ISSUE THREAD

**Issue by kraftwerk28** [wbthomason/packer.nvim#169]
Thanks for nice plugin manager! Is there some way to load plugin at time when I call `use` function? Some plugins (e.g. [bufferline](https://github.com/akinsho/nvim-bufferline.lua)) require that they are loaded before `init.vim` is processed, otherwise they won't work.

**Comment by akinsho** [comment]
@kraftwerk28 👋🏾 I actually wrote that plugin, that shouldn't be the case anymore for `bufferline`. I think there was an old issue in nvim that meant that wasn't working correctly before but it should work fine now with a normal `use` declaration in packer.

**Comment by kraftwerk28** [comment]
Here is how I load bufferline: https://github.com/kraftwerk28/dotfiles/blob/master/.config/nvim/lua/plugins.lua#L21-L28
My neovim version is `v0.5.0-dev+1027-g0f2d37f11`, but the problem still remains for me. I have tabline like this right now
![image](https://user-images.githubusercontent.com/31807671/104850060-7fd79a00-58f5-11eb-81d0-6a2d9c53d7c3.png)

**Comment by akinsho** [comment]
@kraftwerk28 have you run `PackerCompile` and restarted neovim? That's the usual flow for installing packer plugins?

Your setup doesn't look too dissimilar from mine i.e. I call setup in the config field inside a function

**Comment by kraftwerk28** [comment]
Yes, I ran `:PackerCompile`, the problem remains, also put some logs (`echom` & `print`) to determine order of evaluation and plugins seem to load at last

**Comment by kraftwerk28** [comment]
Is it required to use init.lua instead of init.vim?

**Comment by akinsho** [comment]
@kraftwerk28 nope using either should work fine. One thing of not in your config is that you are using both `packer.init` and `packer.startup`, I'm not a packer expert but I believe using just `startup` is enough. Although I'm not sure what's going on specifically. If you try manually running `packadd nvim-bufferline.lua` then running `lua require('bufferline').setup{}` that that do anything? also are your other plugins loading correctly?

**Comment by kraftwerk28** [comment]
Just temporarily tried installing bufferline with vim-plug and encountered same problem, so it's definitely not a packer issue

**Comment by akinsho** [comment]
@kraftwerk28 you can raise an issue over on my repo and we can discuss it there, on an unrelated note I just loaded bufferline in a minimal vimrc and it works fine. I wonder if you could try the same i.e. just loading your plugin manager no other config and just bufferline to see if it works. I haven't really had anyone report that it wasn't loading before (since the `opt` vs `start` dir thing was resolved months ago)

**Comment by kraftwerk28** [comment]
You're right, setting up config from scratch solves the issue. I'm going to investigate what's wrong with my setup. Thank you

**Comment by akinsho** [comment]
Ah yep, didn't notice you were using lightline. Yeah it takes over the tabline, I'll add a warning to the README so it's clearer 👍🏿

**Comment by wbthomason** [comment]
It seems like this is (1) resolved and (2) not a `packer` issue, so I'm going to mark as closed. Feel free to reopen if those conditions aren't true!
