### ISSUE TITLE
PackerCompile fails on luarocks.generate_path_setup()

### ISSUE THREAD

**Issue by ianzhuo** [wbthomason/packer.nvim#172]
I run nvim on windows 10, 
after the latest update, PackerCompile will fail as below, seems have some path handling problem.

![image](https://user-images.githubusercontent.com/1394735/105479539-8a23da80-5cdf-11eb-8e8b-fe6681a02c63.png)

after comment `compile.lua` :473, it work without error.
![image](https://user-images.githubusercontent.com/1394735/105479640-a889d600-5cdf-11eb-9833-5185a20b3efd.png)

**Comment by wbthomason** [comment]
Thanks for the report! I am guessing that this is a Windows-specific bug.

Could you please run `:lua print(require('packer.luarocks').generate_path_setup())` and post the results?

**Comment by ianzhuo** [comment]
Hi, here's the result.
![image](https://user-images.githubusercontent.com/1394735/105509743-ccaddd00-5d08-11eb-820d-b0b828eb8141.png)

**Comment by wbthomason** [comment]
Thanks. Cou

**Comment by ianzhuo** [comment]
Thanks, it is fixed.
