### ISSUE TITLE
If `open_fn` fails, there is no error warning displayed

### ISSUE THREAD

**Issue by tjdevries** [wbthomason/packer.nvim#18]
Had a bug in my `open_fn` and Packer just silently failed. Should probably use pcall or something and then grab the values out from there. 

If it doesn't work, fall back to default maybe?

**Comment by wbthomason** [comment]
Nice catch - there are probably a bunch of places I should be using `pcall`. I'll put together a patch.

**Comment by wbthomason** [comment]
Also, for posterity: this happens because errors in coroutines (apparently) get swallowed. I noticed this while debugging during initial development.

**Comment by tjdevries** [comment]
Yeah, it is difficult to debug errors in some of the async stuff too... but that could be just be cause I don't understand it fully yet :laughing:

**Comment by wbthomason** [comment]
I added changes in d06c193 that properly handles errors in async code (rather than silently swallowing them). Hopefully that makes debugging easier!
