### ISSUE TITLE
Undefined log functions

### ISSUE THREAD

**Issue by akinsho** [wbthomason/packer.nvim#181]
I've just noticed trying something out locally that references to log functions such as `log.warning` still exist despite the recent refactor of logging in #46. From that diff it appears that all the `log.*` functions were removed but there are still quite a few references to these in `display.lua` etc. When called these through nil reference errors.

**Comment by wbthomason** [comment]
Whoops, I thought I pushed a commit patching that already. My bad; thanks for catching this (interestingly, I hadn't seen any error messages...)
