### ISSUE TITLE
Extmark id for failed luarocks is nil

### ISSUE THREAD

**Issue by akinsho** [wbthomason/packer.nvim#184]
In `display.lua` on [this line](https://github.com/wbthomason/packer.nvim/blob/b88a45a51387f263394c933cfd5011fe0689a0b5/lua/packer/display.lua#L22) when a task fails, an error is thrown from the `nvim_buf_get_extmark_by_id` function
```
Error executing vim.schedule lua callback: ...site/pack/packer/opt/local-packer/lua/packer/display.lua:159: Expected 4 arguments
```
This appears to be the result of the first call to the api function which is wrapped in a `pcall` failing, doing some debugging the return `reason` is that the argument passed in for the extmark id for that particular task/plugin is `nil`.

This is specifically being triggered by attempts by packer rocks to install a rock it is unable to find i.e. `luaformatter`. I'm not sure when/where or how the extmark id's are being assigned but since this rock fails to be installed it seems it might be missing an id

**Comment by wbthomason** [comment]
Hmm. Marks should be created on https://github.com/wbthomason/packer.nvim/blob/b88a45a51387f263394c933cfd5011fe0689a0b5/lua/packer/display.lua#L127 - this is probably happening either because I forgot a `task_start` somewhere or `task_succeeded` or `task_failed` (which delete a task's mark) are getting called twice.

**Comment by akinsho** [comment]
It seems to be happening on `task_failed` when trying and failing to install `luaformatter` using `use_rocks "luaformatter"`

**Comment by wbthomason** [comment]
This also raises a separate question for the Luarocks functionality: `luaformatter` is only installable with an additional server argument to `luarocks`. Perhaps `packer` needs to accept this as part of a rock specification?

Separately, I cannot reproduce this. I have `use_rocks 'luaformatter'`, which fails, but I see no errors in `:messages`.

**Comment by akinsho** [comment]
Yeah I was thinking about the server argument/other like it. It would be nice to be able to pass that through. I'd love to be able to setup luaformatter on all my machines without having to manually setup luarocks.

Also here's a quick screen grab from my machine of the error reproducing. Strangely enough it also reproduced on my mac by just adding the `luaformatter` line. Are you on the latest nightly?
![image](https://user-images.githubusercontent.com/22454918/106297884-205d8080-624b-11eb-9566-0785d7549f61.png)


```
NVIM v0.5.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-25tvGF/neovim-0.5.0+ubuntu2+git202101281833-8950f4e94-d569569c9=. -fstack-protector-strong -Wformat -Werror=f
ormat-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissin
g-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOA
T32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-25tvGF/neovim-0.5.0+ubuntu2+git202101281833-8950f4e94-d569569c9/build/config -I/build/neovim-25tvGF/neovim-0.5
.0+ubuntu2+git202101281833-8950f4e94-d569569c9/src -I/build/neovim-25tvGF/neovim-0.5.0+ubuntu2+git202101281833-8950f4e94-d569569c9/.deps/usr/include -I/usr/include -I/build/n
eovim-25tvGF/neovim-0.5.0+ubuntu2+git202101281833-8950f4e94-d569569c9/build/src/nvim/auto -I/build/neovim-25tvGF/neovim-0.5.0+ubuntu2+git202101281833-8950f4e94-d569569c9/buil
d/include
Compiled by buildd@lgw01-amd64-058

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by wbthomason** [comment]
Yup, I'm on https://github.com/neovim/neovim/commit/8950f4e94af1534852cab5f41066d7c21330bd64

```
NVIM v0.5.0-dev+1055-g8950f4e94
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=native -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/yaytmp-1000/neovim-git/src/build/config -I/tmp/yaytmp-1000/neovim-git/src/neovim-git/src -I/usr/include -I/tmp/yaytmp-1000/neovim-git/src/build/src/nvim/auto -I/tmp/yaytmp-1000/neovim-git/src/build/include
Compiled by wil@tesla

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by wbthomason** [comment]
Turns out I was using `luarocks` as the lookup name in `display` for both the install jobs and the uninstall jobs. So, if both types of job are running (e.g. in a `sync`) and both types happen to start before either has finished, then we get a double-close of the job. Now all luarocks jobs use unique names.

Please let me know if you keep encountering the issue! Thanks again for the report!

**Comment by akinsho** [comment]
That seems to have resolved it 👍🏿 thanks @wbthomason
