### ISSUE TITLE
Packer updates are shown out of order (if there is a removal present)

### ISSUE THREAD

**Issue by akinsho** [wbthomason/packer.nvim#185]
When running `:PackerSync` if I have a plugin to be removed (I think this is the trigger) the updates are reported out of order i.e. the commits shown under one plugin or message meant for another are shown under the wrong plugin information. I hope/don't think this was related to #183 since I didn't really touch the actual display within that panel.

Other things of note are that I have luarocks enabled, not sure this is relevant but I hadn't noted this issue before but could just be chance and unrelated

**Comment by wbthomason** [comment]
This is probably a luarocks regression or a regression due to the changes to `clean` a few weeks back. Probably a mismatch between `results_order` and the output table...

Is it consistently off, e.g. always off by one?

**Comment by akinsho** [comment]
The few examples I've seen have seems a bit random (I'm sure not actually completely random) but not obviously just off by one, it seemed like the metadata that was for each plugin had just shifted by some amount in the list I'll try and grab some screen shots when next I update

**Comment by wbthomason** [comment]
Thanks! I should have some time for `packer` work this weekend/Monday; I'll take a look then.

**Comment by wbthomason** [comment]
I'm actually thinking this might be a regression from https://github.com/wbthomason/packer.nvim/commit/b88a45a51387f263394c933cfd5011fe0689a0b5. I'll push a change that might fix it in a sec.

**Comment by wbthomason** [comment]
0df654d maybe fixes this; I need to test more to confirm.

**Comment by wbthomason** [comment]
Ok, in my testing, I cannot reproduce this issue (with 0df654d), so I'm hoping it's fixed.

**Comment by akinsho** [comment]
Will try it out as well, I don't have any changes pending but sure something will come up. Also just a heads up it looks like that commit added in a print statement thats maybe still in there

**Comment by wbthomason** [comment]
Whoops, that's what I get for coding during a meeting...

Nice catch, thanks!

**Comment by akinsho** [comment]
I haven't encountered this in quite a few days so will close this off to keep things tidy and re-open it if it recurs
