### ISSUE TITLE
Add ability to specify args to luarocks

### ISSUE THREAD

**Issue by wbthomason** [wbthomason/packer.nvim#187]
As mentioned in #184, some rocks require further args for luarocks, e.g. `server`. We should add the ability to specify these args (or some subset of the possible args) to a rock's specification, and have `packer` forward these to `luarocks`.

**Comment by wbthomason** [comment]
Closed by #210.

**Comment by wbthomason** [comment]
Note from Gitter discussion with @clason: we may need to expand the set of allowed arguments, given that some packages (e.g. openssl) need certain environment variables to be set, etc.

**Comment by akinsho** [comment]
@wbthomason I *briefly* looked at this and the key @clason mentioned isn't actually a `luarocks` key so I'm not sure how we would represent these? the actual keys are formatted as `--key=value` in this case we'd need to add `OPENSSL_DIR=<value>` but to not append the key syntax to it we'd need to be able to flag these kind of keys differently. Any ideas? some sort of prefix? or a heuristic based on the casing?

**Comment by clason** [comment]
@akinsho Maybe treat this as a separate thing (`env`?) to pass to `luarocks`?

**Comment by akinsho** [comment]
Something like?
```lua
use_rocks {"openssl", env = {OPENSSL_DIR = "path/to/dir"}}
```

**Comment by clason** [comment]
Yes, perfect!
