### ISSUE TITLE
`require` format uses slashes

### ISSUE THREAD

**Issue by tjdevries** [wbthomason/packer.nvim#19]
I think it's better if we use `.` notation instead of `/` for requires. We should probably standardize on that.

I think `require('x.y')` makes a different module than `require('x/y')` btw

**Comment by wbthomason** [comment]
Sure, I don't have strong feelings on the style. Is there a semantic difference between the two, or just syntactic preference?

**Comment by tjdevries** [comment]
I don't think there's a big difference, but neovim style is to use `.` notation.

**Comment by tjdevries** [comment]
The main problem is having different styles in the same repo. I don't think it makes a difference on windows, but I haven't checked that though.
