### ISSUE TITLE
Loading plugin on keymap fails

### ISSUE THREAD

**Issue by YaBoiBurner** [wbthomason/packer.nvim#195]
None of my plugins are loading on keymaps.

When I use the keymap, I get the message `E5107: Error loading lua [string ":lua"]:1: '}' expected near ':'`

Loading plugins via commands, filetypes, and events still works fine though. I didn't test functions.

**Comment by akinsho** [comment]
There is a fix pending for this over in #194

**Comment by wbthomason** [comment]
Sorry about this; I thought I'd caught all the old Vim syntax. Thanks @akinsho for the excellent, quick fix!

**Comment by akinsho** [comment]
Credit to @nanotee actually 😄

**Comment by wbthomason** [comment]
Wow, another great example of how I cannot read right now...

Thanks, @nanotee!
