### ISSUE TITLE
Can't Use in RaspberryPi (aarch64 Architecture)

### ISSUE THREAD

**Issue by mirachan010** [wbthomason/packer.nvim#203]
In aarch64 neovim is use Lua5.1 NOT LuaJIT
So it has error in it.

**Comment by wbthomason** [comment]
Thanks for the report. Can you provide specifics on the errors you're encountering? Post #146, `packer` should hypothetically work without LuaJIT.

**Comment by mirachan010** [comment]
when use `require('packer')`
E5108: Error executing lua .../pack/packer/opt/packer.nvim/lua/packer/luarocks.lua:24: attempt to index local 'lua_version' (a nil value)
