### ISSUE TITLE
Not load plugin if commented out

### ISSUE THREAD

**Issue by seblj** [wbthomason/packer.nvim#212]
I want to make a plugin not load if it is commented out without deleting the entire plugin with PackerClean or PackerSync. How can I do this?

**Comment by akinsho** [comment]
@seblj you can use the `cond` key to ensure that a plugin remains installed but not loaded e.g.
```lua
use { "plugin/to-disable.vim", cond = function() return false end }
```
This  *should* keep the plugin installed but won't load it, so you don't need to comment it out. I only just got round to using this key myself and seems to work quite well for this use case

**Comment by wbthomason** [comment]
I'm closing this as solved by @akinsho for now; please feel free to reopen if you disagree.

**Comment by mortezadadgar** [comment]
> I'm closing this as solved by @akinsho for now; please feel free to reopen if you disagree.

It's  so complicated to makes this temporary changes on every plugin in the list, it would be ideal to commented out plugins being unloaded on new nvim instance

**Comment by akinsho** [comment]
@mortezadadgar this is actually just a part of how vim's native packages functionality works see `:h packages` for more info.

I'm not sure packer can do much to make it work differently since it will otherwise just try and delete commented out packages.

**Comment by wbthomason** [comment]
@mortezadadgar: You can also take a look at `conf = 'false'` as a more concise way to do this. As @akinsho says, preventing the loading of commented-out plugins would require a significant restructuring to no longer use native packages (which has been talked about/might happen eventually, but isn't currently the top priority).
