### ISSUE TITLE
Odd plugin performance issues since switching to packer 

### ISSUE THREAD

**Issue by cwebster2** [wbthomason/packer.nvim#213]
I have switched my plugin management from vim-plug to packer about a week ago, and along with it came some plugin performance issues.

I am using neovim nightlies  from github.

These manifest in two ways

 1. unresponsive startup time and delays on quitting. 
 2. unresponsive plugins at runtime

For the first, i can reliably reproduce this in my config by installing or uninstalling kyazdani42/nvim-tree.lua.  If i do not have it installed, neovim starts as expected. If I install it, then after nvim starts i get around 5 seconds of unrestonsiveness and then normal operation.  The startup time reported by dstein64/vim-startuptime is nearly identical in both cases.  I did not have this issue with vim-plug.

The second issue seems most noticeable with tpope/vim-fugitive.  When i :Gstatus it takes a few seconds for it to display and each operation with its split is similarly delayed.  I did not have this issue when I was using vim-plug.  

Its possible ive hit some edge case or regression with nvim nightly or added some problematic plugin i havent identified yet that coincided with my switch to packer, but throwing this out there to see if anyone has ideas or sees an obvious problem with my config that i'm missing.

My packer config is here ; https://github.com/cwebster2/vim/blob/nvim-lua/lua/plugins.lua

Tomorrow I'm going to reimplement my current plugin setup with vim-plug to objectively compare them side by side and see what that shows me.  If any data from my setup would be helpful to diagnose this behavior, just let me know what / how to collect it and i'll provide it here.

**Comment by cloggier** [comment]
1. seems like a known issue https://github.com/kyazdani42/nvim-tree.lua/issues/172

**Comment by wbthomason** [comment]
If you could please post your `vim-plug` config that does not have the slowdown, that would be useful to see.

**Comment by cwebster2** [comment]
I'm going to close this for now.  I just recreated my vim-plug conf with my current plugins and it behaves the same, so i'm guessing i have some bad interactions between plugins or a regression in nvim itself.  As ursual, changed too many things at once in the beginning and now backtracking to see what is causing my problem.  Likely not you :) Sorry to bother.

**Comment by wbthomason** [comment]
No worries; feel free to reopen if it seems like `packer` is involved. Good luck!

**Comment by cwebster2** [comment]
I found my problem and 100% not packer, but 100% me.  Revisiting my issues across all plugins and slowness led me to one culprit... things that spawn shells.  When I overhauled my setup to packer, i coincidentally also started using neoterm and naively `set shell /bin/zsh` and there is a fair bit of overhead in starting zsh in my env...  reverted that to bash and everything is fast again.

**Comment by wbthomason** [comment]
Glad you got things working! Thanks for reporting back!
