### ISSUE TITLE
Packer doesn't detect when switching to a different plugin with the same repo name

### ISSUE THREAD

**Issue by akinsho** [wbthomason/packer.nvim#231]
Whilst trialing PR fixes for various plugins, I've noticed that moving from
```lua
-- from
use {"person-1/cool-plugin"}
-- to
use {"person-2/cool-plugin"}
```

Doesn't trigger a packer clean and then subsequent installation of the fork of the package, I think this is because packer primarily distinguishes based on plugin type i.e. local or remote but not the author i.e. the `person-x` prefix

**Comment by wbthomason** [comment]
Thanks! The challenge with this is that, once a plugin is installed, `packer` "forgets" whether it came from `person-1` or `person-2`. I suppose a reasonable fix for this would be looking at `.git/config` for a plugin's directory, but I wonder if there's an easier/less hacky fix...

**Comment by akinsho** [comment]
@wbthomason wouldn't it be easier to just keep track of the author when the package is installed e.g. the spec specifies `user1/plugin` but packer only saves `plugin` which I guess is one way to get around duplication, but could also be valuable to save the `user1` bit under a field like author and if that changes then re-install the plugin.

**Comment by wbthomason** [comment]
@akinsho are you suggesting we store the author information in `_G.packer_plugins` and, when running `use`, check plugin specs against `packer_plugins` to detect if the URL has changed? That could work, though there might be interactions I'm missing between stale `packer_compiled` files and using the information like this (probably not, if we assume that the spec passed to `use` always overrules what's in `packer_plugins`).

**Comment by akinsho** [comment]
Yep was thinking it would be stored in the packer plugins table, regarding interactions my understanding is that generally the hierarchy of data should be whatever is in the user's specs > compiled output so if you run `PackerSync` it would check vs what is written in the actual spec and trigger a change based on that.

Not sure what other interactions there could I guess if somehow the compiled file wasn't updated it might try and re-install an already installed plugin, but tbh that problem is true for a multitude of cases in packer/not sure how that would happen.

**Comment by Kirill-Bugaev** [comment]
To avoid conflicts may be it has sense to place plugins to more verbose directory paths like `github.com/aws/aws-sdk-go@v1.29.8` in golang.
For example: `~/.local/share/nvim/site/pack/packer/start/github.com/9mm/vim-closer`.

**Comment by akinsho** [comment]
I think changing the names under which the plugins are stored @Kirill-Bugaev would be a breaking change since it would mean existing `packer_compiled.vim` files wouldn't work.

Coming back to this again though I think rather than just an author field packer should just keep track of the full url/path a user initially specified so it can reference it against the short name later. So similar to your suggest @Kirill-Bugaev but just with the plugin's metadata rather than renaming the key in the global plugins table.

**Comment by bew** [comment]
Maybe this is not possible, I don't know the details of how packer works, but as you mention the file `.git/config` I'm guessing you have the git repository of the plugin. Couldn't you check the `git remote get-url origin` and use that?

**Comment by akinsho** [comment]
Doing async calls and checking git config files or the output of the remote command seems unnecessarily complicated to me given that the specific information to solve this issue is readily available in the user's plugin config and just isn't stored. I think just storing this information and verifying it at the point where packer is deciding if it should clean a plugin is much simpler.

**Comment by Kirill-Bugaev** [comment]
@akinsho, sounds like needs persistent storage. If neovim already has API for it I am not well-informed. `ejdb-lua` is option, but maybe overhead.

**Comment by akinsho** [comment]
In packer's case it sort of already has this in the form of the compiled file it creates, although I just started looking at this locally and that won't work unfortunately since I forgot that a user can run `PackerCompile` at any point before `PackerClean` or `PackerSync` which will more or less blow away any record we had that the plugin had a different url. Seems like doing an `async` check via the git remote command might be the only way.

Unfortunately that makes the change a bit more complex since I have to change quite a few places in packer to allow for the function that gets this information to be async instead of sync 😓
