### ISSUE TITLE
When installing plugins using packer.nvim, it asks to remove itself then quits

### ISSUE THREAD

**Issue by wantyapps** [wbthomason/packer.nvim#233]
When I tried the command ":PackerInstall" (Neovim 0.5.0) it asks to remove the packer.nvim file from ~/.local/share/nvim/...etc and when I pressed y and then enter, it installed. After that, when I quit and reopened nvim, 
<img width="1440" alt="Screen Shot 2021-02-25 at 8 35 44" src="https://user-images.githubusercontent.com/56798701/109113162-763b2080-7744-11eb-9264-3765e07d230e.png">

**Comment by wantyapps** [comment]
And BTW: How do I uninstall packer.nvim?

**Comment by wantyapps** [comment]
Can someone help me?

**Comment by akinsho** [comment]
@wantyapps think @.wbthomason is quite busy atm so you might have to wait a little while. How have you setup `packer` what does your `plugins.lua` look like. Are you called `packadd packer` have you made sure to clone packer into the opt directory? either using the bootstrap function in the README or manually?

**Comment by wantyapps** [comment]
- [x] I did set it up in opt/ (used command in README.md)
- [x] I did `packadd packer.nvim`. Is this correct?
My plugins.lua file is below:

vim.cmd("packadd packer.nvim")                                                                                                                                  
                                                                                                                                                                
return require("packer").startup(function()                                                                                                                     
        use "tpope/vim-commentary"                                                                                                                              
        use "tpope/vim-dispatch"                                                                                                                                
        use "tpope/vim-fugitive"                                                                                                                                
        use "ap/vim-css-color"                                                                                                                                  
        use "voldikss/vim-floaterm"                                                                                                                             
        use "airblade/vim-gitgutter"                                                                                                                            
        use "arcticicestudio/nord-vim"                                                                                                                          
        use "kyazdani42/nvim-web-devicons"                                                                                                                      
        use "gkeep/iceberg-dark"                                                                                                                                
        use "cocopon/iceberg.vim"                                                                                                                               
        use "morhetz/gruvbox"                                                                                                                                   
        -- Lightline (statusline)                                                                                                                               
        use "itchyny/lightline.vim"                                                                                                                             
        use "sainnhe/artify.vim"                                                                                                                                
        use "itchyny/vim-gitbranch"                                                                                                                             
        use "macthecadillac/lightline-gitdiff"                                                                                                                  
        use "albertomontesg/lightline-asyncrun"                                                                                                                 
        use "rmolin88/pomodoro.vim"                                                                                                                             
        -- Tmuxline                                                                                                                                             
        use "edkolev/tmuxline.vim"                                                                                                                              
        -- LSP                                                                                                                                                  
        use "neovim/nvim-lspconfig"                                                                                                                             
        use "nvim-lua/lsp_extensions.nvim"                                                                                                                      
        use "nvim-lua/completion-nvim"                                                                                                                          
        -- Telescope.nvim                                                                                                                                       
        use "nvim-lua/popup.nvim"                                                                                                                               
        use "nvim-lua/plenary.nvim"                                                                                                                             
        use "nvim-telescope/telescope.nvim"                                                                                                                     
        -- My plugins                                                                                                                                           
        use "wantyapps/vim-fountainpen"                                                                                                                         
        -- Secret writing                                                                                                                                       
        use "ernstwi/vim-secret"                                                                                                                                
end)

**Comment by akinsho** [comment]
@wantyapps looking at your config it doesn't look like you `use {"wbthomason/packer.nvim", opt = true}` which is why it keeps trying to uninstall it. The plugin manages itself so it has to be specified also

**Comment by wantyapps** [comment]
thx!

**Comment by wantyapps** [comment]
Worked like a charm.

**Comment by wbthomason** [comment]
Glad things are working, and thanks @akinsho!
