### ISSUE TITLE
Doc: Don't recommend packer as optional

### ISSUE THREAD

**Issue by clason** [wbthomason/packer.nvim#239]
The [quickstart example](https://github.com/wbthomason/packer.nvim#quickstart) in the README has `packer` as an optional plugin (`opt=true`) and adds a `vim.cmd [[ packadd packer.nvim ]] to manually load it. These days, this should have the same effect as `opt=false` and be less confusing for newcomers, so the example probably should omit both `opt=true` and the `vim.cmd`. (The fact that `packer` can be made optional is interesting but probably better postponed to a later remark.)

Also, it might be useful to mention early on and prominently that packer uses native packages, e.g., by adding after "use-package inspired plugin/package management for Neovim." something like

> **Packer is built on native vim packages. Before continuing, read `:h packages`.**

On a related note, can we add a FAQ somewhere? For example "how to temporarily disable a plugin (corresponding to commenting out its `Plug` line with `vim-plug`)?"

**Comment by richban** [comment]
Thanks for this!

**Comment by wbthomason** [comment]
Added! An FAQ would be great - the Wiki for this repo is enabled, so maybe we could start something there?
