### ISSUE TITLE
Packer doesn't compile

### ISSUE THREAD

**Issue by NTBBloodbath** [wbthomason/packer.nvim#240]
Everytime I use `:PackerCompile` it fails. No matter what I do, it always fails.

```
E5108: Error executing lua ...are/nvim/site/pack/packer/opt/packer.nvim/lua/packer.lua:419: invalid value (boolean) at index 18 in table for 'concat'
```

**Comment by akinsho** [comment]
@NTBBloodbath can you provide some more context on what is happening e.g. what does your `packer_compiled.vim` look like and your `plugins.lua` etc.

* Have you tried manually removing the `packer_compiled.vim` and recompiling?
* Is this a new problem after you added some change to your config or is this on first install of packer?
* What OS are you on?
* What version of neovim are you using?

**Comment by NTBBloodbath** [comment]
> @NTBBloodbath can you provide some more context on what is happening e.g. what does your `packer_compiled.vim` look like and your `plugins.lua` etc.
The problem started since I changed my init.vim to a lua version, there's my [`plugins.lua`](https://github.com/NTBBloodbath/dotfiles/blob/main/nvim/lua/plugins/init.lua)

> * Have you tried manually removing the `packer_compiled.vim` and recompiling?
> * Is this a new problem after you added some change to your config or is this on first install of packer?
> * What OS are you on?
> * What version of neovim are you using?

**Comment by NTBBloodbath** [comment]
> @NTBBloodbath can you provide some more context on what is happening e.g. what does your `packer_compiled.vim` look like and your `plugins.lua` etc.
> 
> * Have you tried manually removing the `packer_compiled.vim` and recompiling?
> * Is this a new problem after you added some change to your config or is this on first install of packer?
> * What OS are you on?
> * What version of neovim are you using?

**Comment by NTBBloodbath** [comment]
> @NTBBloodbath can you provide some more context on what is happening e.g. what does your `packer_compiled.vim` look like and your `plugins.lua` etc.

There's my [`plugins.lua`](https://github.com/NTBBloodbath/dotfiles/blob/main/nvim/lua/plugins/init.lua)
 
> * Have you tried manually removing the `packer_compiled.vim` and recompiling?

Yes but can't recompile it

> * Is this a new problem after you added some change to your config or is this on first install of packer?

The problem came out when I started using Lua instead of Vimscript for my init and other lot of changes to my plugins configs

> * What OS are you on?

Fedora 33

> * What version of neovim are you using?

`v0.5.0-dev+1112-ge55ded00c`

**Comment by NTBBloodbath** [comment]
Nvm, I forgot to turn some plugin settings into function. It's working now

I'm really sorry for wasting your time :sweat_smile:

**Comment by wbthomason** [comment]
Glad things are working! Thanks, @akinsho!
