### ISSUE TITLE
undefined global 'use'

### ISSUE THREAD

**Issue by boydkelly** [wbthomason/packer.nvim#243]
Hi,
This is really low priority... as nothing is broken, and I am a total amateur here.   I just found that with the default config, and using the sumneko_lua/lua-language-server, I get get these complaints:

`use { 'wbthomason/packer.nvim', opt=true }     ■ Undefined global `use`.`

I tried defining local and/or global use.packer etc, but just got myself into more error messages...   Is this an issue with sumneko_lua/lua-language-server?  

Thanks!

**Comment by akinsho** [comment]
@boydkelly the error is spurious as packer adds the `use` function to the scope of the function passed to `packer.startup` the issue though is that `sumneko_lsp` can't see that so the easiest solution is to either add `use` to the globals for that lsp or my personal favourite use the `use` function passed in to startup e.g.

```lua
packer.startup(function(use)
 use {'plugin'}
end)
```
@wbthomason (for when you're back) this comes up quite a bit it seems and probably warrants going in the README I think

**Comment by wbthomason** [comment]
Thanks, @akinsho. I agree - I'll make a quick edit to the README now.
