### ISSUE TITLE
README directions for setup result in error about _update_package_paths

### ISSUE THREAD

**Issue by brandonpittman** [wbthomason/packer.nvim#249]
Howdy!

Tried setting up packer as per the README (w/neovim nightly 0.5+) but I keep keeping this error about `_update_package_paths` when my `init.nvim` gets to `lua require('plugins')`. Any idea what I might be doing wrong?

![CleanShot 2021-03-06 at 16 20 05](https://user-images.githubusercontent.com/967145/110198875-da728880-7e98-11eb-9465-85da16776c18.png)

**Comment by wbthomason** [comment]
Thanks for the report! Just to check, does your Neovim version **not** have https://github.com/neovim/neovim/pull/12632 merged? Earlier versions of Neovim need the `_update_package_paths` call; later versions do not need it, and most recent versions do not have the function available at all.

**Comment by brandonpittman** [comment]
@wbthomason It’s the most recent nightly, so I’m guessing it’s not available at all then.

**Comment by brandonpittman** [comment]
@wbthomason Doh. I just copied the README example. That *only necessary if your Neovim is old* line kinda screwed me up there.

**Comment by wbthomason** [comment]
Ah, yep - that'd do it. Perhaps I should make that line an actual conditional, to make it a NOP if it doesn't apply. Sorry for the confusion!
