### ISSUE TITLE
Question about the disable property

### ISSUE THREAD

**Issue by mnarrell** [wbthomason/packer.nvim#251]
What is the intended use for this property?  If I mark a plugin as disabled, it's now a candidate for cleanup, as if I had removed (or commented) the declaration of a plugin.  Is there a way to simply disable a plugin (i.e. remove its capabilities), without cleanup or otherwise removing the declaration?

I find myself wanting to disable a given plugin often to try new Lua implementations of similar functionality, and perhaps wanting to revert quickly.  Happy to retrain myself if there's a new approach.

**Comment by wbthomason** [comment]
`disable` is really meant for plugins you only want conditionally **installed** - for instance, you could have a plugin where the value of the `disable` key is the result of a function testing whether the current system was Linux or Windows, etc.

To keep a plugin installed but not activated, try setting `opt = true`.

This is somewhat confusingly named; sorry about that.

**Comment by mnarrell** [comment]
Thanks for the explanation!
