### ISSUE TITLE
How to use rocks installed through packer?

### ISSUE THREAD

**Issue by VVKot** [wbthomason/packer.nvim#252]
I added `use_rocks "lua-cjson"` to my packer config and successfully installed them. My impression was that now I can do something like `local json = require("cjson")` in my Lua files and it will succeeded, however, it fails with `module 'cjson' not found`.

Admittedly I don't know much about Lua - maybe I am missing something obvious here? Is there some path setup that I should add?

**Comment by wbthomason** [comment]
`packer` should be doing the path setup you need. If you open your `packer_compiled`, do you see some lines setting `package.path` and `package.cpath`?

**Comment by VVKot** [comment]
Eh, I tried to bust everything completely again, and reinstalled it - works now. 🤷 Maybe because at first I tried to install, and only then found https://github.com/wbthomason/packer.nvim/issues/180#issuecomment-768140924? In any case, sorry for the noise.

**Comment by wbthomason** [comment]
Ah, that's possible. I'm glad things are working now - feel free to reopen if they break again.
