### ISSUE TITLE
How would you update this package?

### ISSUE THREAD

**Issue by cjnucette** [wbthomason/packer.nvim#254]
I can't find a `packer.upgrade` or something like that. Should I run every now and then a `git clone`? This doesn't seem a very intuitive.

**Comment by wbthomason** [comment]
Sorry, I'm confused - are you asking how to update plugins with `packer` (see: `packer.update`, the `PackerUpdate` command, as well as `sync`) or how to update `packer` itself? The usual way to do the latter is to just have `packer` manage itself.

**Comment by cjnucette** [comment]
Yes I was asking about `packer`. Thanks.
