### ISSUE TITLE
PackerInstall fails with older git

### ISSUE THREAD

**Issue by ranebrown** [wbthomason/packer.nvim#255]
On CentOS 7 the default git is 1.8.3.1. I didn't look into the reason but PackerInstall fails to clone anything with this version of git. Updating git per [these instructions](https://computingforgeeks.com/how-to-install-latest-version-of-git-git-2-x-on-centos-7/) fixes the problem. It might be worth mentioning a minimum version in the Notices? Related to #52

**Comment by wbthomason** [comment]
Thanks for the report, and sorry for not getting to this sooner! I don't suppose you have anything in `~/.cache/nvim/packer.nvim.log`? If so, could you please post it - I'd like to figure out what specific `git` operation is failing so that I can narrow down the correct minimum version.

**Comment by ranebrown** [comment]
Looks like it is the `-C` option which was added in [1.8.5](https://github.com/git/git/blob/master/Documentation/RelNotes/1.8.5.txt).

**Comment by TeoDev1611** [comment]
@wbthomason this will be closed ? 🤔

**Comment by wbthomason** [comment]
@TeoDev1611 If we can have someone confirm that the referenced PR did in fact remove this `git` version restriction. My version of `git` is too new to verify this.
