### ISSUE TITLE
Plugin loaded as a dependency before 'use' gives warning about Plugin being used twice

### ISSUE THREAD

**Issue by muchosteechos** [wbthomason/packer.nvim#258]
I get the warning `[packer.nvim] [WARN 11:53:25] pack... "nvim-web-devicons" is used twice!` with my configuration on startup. 

I'm kind of aware of this due to the fact that I have this plugin as a dependency and use it after that anyways:
```
return require('packer').startup(function()
  use {'wbthomason/packer.nvim', opt = true}

  use {
    'kyazdani42/nvim-tree.lua',
    requires = {'kyazdani42/nvim-web-devicons'},
  }

  use {'kyazdani42/nvim-web-devicons'}
end)
```

This is intended. I want to specify `nvim-web-devicons` as a dependency of `nvim-tree`, but load it regardless of wether I use `nvim-tree` or not. 

Is there a way to not get this warning at startup? I can only think of inelegant solutions, that either require too much manual work or don't specify the intended behavior I want
- put `nvim-tree` down in the configuration (too much manual work if I manage more plugins in this way),
- something like `cond=--[[ check if nvim-web-devicons loaded --]]` in `nvim-web-devicons` use
- use of `opt`
- suppress warnings in general

I'm also unaware of the implications of this warning. Does `packer` actually load the plugin twice? Can this setup lead to significantly worse startup time?

**Comment by akinsho** [comment]
@muchosteechos I think this might be some confusion in how the dependency specification in packer works. Specifying a plugin as `requires` means that when nvim-tree is installed it will also nvim web devicons, and that if nvim tree is removed it should remove web devicons. If you then go on to specify the plugin in its own use block there is no point having it inside the requires of nvim tree.

**Comment by akinsho** [comment]
`requires` should only really be used if the only reason a plugin is specified is because it is needed by another and should only be there if the other one is there. If you want a plugin to be around regardless of the other ones status then it is not really a dependency anymore

**Comment by wbthomason** [comment]
@akinsho is correct. That said, if you want to specify a plugin as a dependency for multiple plugins (or have it in its own block and also as a dependency), just give its name (not the full path) as the dependency. In your case, this would be `nvim-web-devicons` instead of `kyazdani42/nvim-web-devicons`.

**Comment by muchosteechos** [comment]
Thank you both! This explains things. 

I'm happy with my configuration now and packer helps me a lot with this. It's just a minor inconvenience (if at all in the context of vim plugins) that I can't specify dependencies as I originally had in mind. That being said, I don't think your suggestion @wbthomason achieves that either.  To explain:

When packer specifies dependencies as @akinsho described,
> `requires` should only really be used if the only reason a plugin is specified is because it is needed by another and should only be there if the other one is there. 

then this is contrary to what I wanted. 

In my scenario "a plugin is specified (in `requires`) because it is needed by another".  Thus my notion of a dependency was merely, that it is required by another plugin. 

As I said, the strong coupling of packer dependencies only leads to minor inconvenience in my setup. In this specific example I have to remember to specify `nvim-web-devicons` as a dependency of `nvim-tree` once I don't use it anymore in other contexts. 

I wouldn't be so happy about this in other contexts than vim plugins, like say pacman (package manager for Arch Linux), if I had to manage and remember this. 

## Suggestion

To led you know I went ahead and tried @wbthomason suggestion anyways and get the following results. I'm assuming by "have it in its own block" means `use` block. With this however, it results in the same warning. 
```
  use {
    'kyazdani42/nvim-tree.lua',
    requires = {'nvim-web-devicons'},
  }

 use { 'kyazdani42/nvim-web-devicons' }
```
warns (`'nvim-web-devicons' used twice`). Same thing when I change the order of `nvim-web-devicons` and `kyazdani42/nvim-web-devicons`.

Whereas I get no warning, when
```
use {
  'kyazdani42/nvim-tree',
  requires = {'kyazdani42/nvim-web-devicons'}
}

--[[ use {'kyazdani42/nvim-web-devicons'} --]]

use {
  'glepnir/galaxyline.nvim',
  config = function() require'c-galaxyline' end,
  requires = {'kyazdani42/nvim-web-devicons'}
}
```

**Comment by akinsho** [comment]
@muchosteechos I actually didn't know about @wbthomason's suggestion or I would have made it as well although I think for simplicity it's worth thinking about it (at least to me) the way I described but looking at your example I don't think you've adjusted it correctly.

I actually decided to experiment with it in my own config for another plugin just to see about the semantics and why you might do that I actually think it's a sensible use case but maybe not super common.

I used it like this and it worked fine for me
```lua
     use {"mfussenegger/nvim-dap", config = require("as.plugins.dap")}

    use {
      "neovim/nvim-lspconfig",
      config = require("as.plugins.lspconfig"),
      event = "VimEnter",
      disable = is_work,
    }

    use {
      "personal/flutter-tools.nvim",
      config = require("as.plugins.flutter"),
      after = "nvim-lspconfig",
      requires = {"nvim-dap", "nvim-lspconfig"} <-- Specified without the user name from git, this is Key!
    }
```

**Comment by akinsho** [comment]
OOI @wbthomason how does this work? and secondly is the intended use case so that removing one plugin doesn't end up removing the dependencies of another. Apologies this issue maybe isn't the best place to go over packer internals and I could have asked on Gitter 😆

**Comment by muchosteechos** [comment]
> I actually think it's a sensible use case but maybe not super common.

I agree. As I said I think this is a minor inconvenience in managing vim plugins. I don't expect complicated dependency structures when managing vim plugins, after all they are pretty simple and don't rely on other dependencies that much. Thus it doesn't put up much of a burden to manage, in contrast to a system managed e.g. by pacman.

> I used it like this and it worked fine for me
> 
> ```lua
>      use {"mfussenegger/nvim-dap", config = require("as.plugins.dap")}
> 
>     use {
>       "neovim/nvim-lspconfig",
>       config = require("as.plugins.lspconfig"),
>       event = "VimEnter",
>       disable = is_work,
>     }
> 
>     use {
>       "personal/flutter-tools.nvim",
>       config = require("as.plugins.flutter"),
>       after = "nvim-lspconfig",
>       requires = {"nvim-dap", "nvim-lspconfig"} <-- Specified without the user name from git, this is Key!
>     }
> ```
> 
> EDIT: you need to remove `kyazdani42` from the `requires`

This works, when I adjust my code from the first example accordingly. 
```
  use { 'kyazdani42/nvim-web-devicons' }

  use {
    'kyazdani42/nvim-tree.lua',
    requires = {'nvim-web-devicons'},
  }
```
It's just the order that is different, which is something I want to avoid having to rely on.

**Comment by akinsho** [comment]
@muchosteechos seems like this is resolved so going to close this now

**Comment by knpwrs** [comment]
This appears to be an issue for me again. With the following:

```lua
  use { 'tommcdo/vim-fugitive-blame-ext', requires = {{'vim-fugitive'}} }
  use 'tpope/vim-fugitive'
```

I get the warning that `vim-fugitive` is used twice. If I comment out the second line there is no more warning.

**Comment by akinsho** [comment]
@knpwrs can you change the order of the statements and see if you still the error?
e.g.
```lua
  use 'tpope/vim-fugitive'
  use { 'tommcdo/vim-fugitive-blame-ext', requires = {{'vim-fugitive'}} }
```

**Comment by wbthomason** [comment]
@akinsho is right that changing the ordering should fix this (you also don't need the nested table for `requires`, but that's not the problem). However, this surfaces a consideration about how we detect duplicate plugins. Right now, if you `require` a plugin, we assume that either:
1. You have previously fully specified the plugin and are referring to it by its short name.
2. You have not previously specified the plugin and are referring to it by its full name (i.e. `tpope/vim-fugitive` here).

One alternative approach could be to just merge multiple specifications (we set some properties for `requires` plugins, e.g. to handle transitive optness and disabling). I could see this causing some undesired behavior with people accidentally overriding parts of their config, though. Maybe we could instead tag plugin specifications as `from_requires`, and allow any top-level specifications for the same to override `from_requires` specifications, but still display the warning for multiple top-level specifications?

**Comment by knpwrs** [comment]
@akinsho that works but then my plugins aren't in alphabetical order (true tragedy, I know).

**Comment by akinsho** [comment]
I've definitely hit this issue a few times in my own config, @wbthomason the `from_requires` solution sounds like a good fix 🤔 so any plugins that are part of the `requires` key are marked as such and before flagging any duplicates check if the duplicate is `from_requires` or not before showing the warning?

Do I have that right? in which case I can look into putting together a PR for that. Would be nice to just have it automagically work, I guess this will be less potentially problematic than merging properties. I guess #246 will eventually handle the multiple requires and configs etc right?

**Comment by wbthomason** [comment]
I'm not sure of the status of #246 right now; it might need a new champion. It should in theory handle merging multiple configs. Your #471 allows for the most common use case that causes this spurious error, so I think that's already an improvement. Thanks!

**Comment by wbthomason** [comment]
We could also in the meanwhile add logic to always return early (whether or not `from_requires` is set) if a plugin has a full config - effectively just choosing the first config we get for a plugin.

**Comment by akinsho** [comment]
@wbthomason do you mean around where I added the change just returning if there is a already a config for that plugin, tbh it sounds like that could have unintended consequences in terms of determining what a "full" config is?
