### ISSUE TITLE
Install freezes if not a valid git repository

### ISSUE THREAD

**Issue by tjdevries** [wbthomason/packer.nvim#26]
If you try and install an invalid repo using packer, the entire Neovim freezes and you can't do anything about it.

I was able to reproduce with `use 'asdfasdfasdf/asdfasdfasdf'`

(This is on WSL, I can check somewhere else later as well)

**Comment by clason** [comment]
I just tested on macOS (using the table version of `startup`), and got a proper error message (no freeze)

**Comment by wbthomason** [comment]
Hmm, yeah, I cannot reproduce this on Arch Linux. Maybe related to #25/WSL-specific?

**Comment by Shougo** [comment]
It maybe git command freezes

**Comment by tjdevries** [comment]
(I ended up just instaling ubuntu on my laptop because I was having some troubles with WSL... so it may be awhile before I get around to testing this :laughing: ) Not a high priority for me and user error in some ways anyway ;)

**Comment by wbthomason** [comment]
Presumed fixed by #91
