### ISSUE TITLE
Hererocks can't install when `$LUAROCKS_CONFIG_5_1` is set to something that changes the Lua interperter

### ISSUE THREAD

**Issue by YaBoiBurner** [wbthomason/packer.nvim#265]
Note - this could also be an issue with hererocks itself and not packer.

I have my luarocks config set up to avoid the existence of a `~/.luarocks` folder, which is done via environment variables for `LUAROCKS_CONFIG_<lua version>`. And to enforce using LuaJIT for Lua 5.1, i have `lua_interpreter = 'luajit'` in my luarocks 5.1 config.

When this is the case, packer's hererocks break.

I can run nvim in an environment without `LUAROCKS_CONFIG_5_1` set, or comment out the `lua_interperter` line in my luarocks config, but neither of these are really ideal solutions.

Rocks packages still load without issue.

**Comment by YaBoiBurner** [comment]
I finally had some time to experiment, and this seems to be a hererocks issue.

Also, it can be fixed by just clearing variables in the virtualenv activation script.

**Comment by wbthomason** [comment]
Thank you for following up on this!
