### ISSUE TITLE
ERROR: when neovim compiled against `Lua 5.1`  and not `Luajit 5.1`

### ISSUE THREAD

**Issue by MrAdityaAlok** [wbthomason/packer.nvim#268]
# Problem
When neovim compiled against `Lua 5.1`  and not `Luajit 5.1`,  calling  `lua/luarocks.lua` results into error
```
E5113: Error while calling lua chunk: ...ack/packer/start/packer.nvim/lua/packer/luarocks.lua:24: attempt to index local 'lua_version' (a nil value)
```
# Solution

Though your code checks for it 
```
15 local lua_version = nil
 16 if jit then
 17   local jit_version = string.gsub(jit.version, 'LuaJIT ', '')
 18   lua_version = {lua = string.gsub(_VERSION, 'Lua ', ''), jit = jit_version, dir = jit_version}
 19 end

```
still `lua_version` is used in line 24 , i.e with `nil`  value
```
24 local hererocks_install_dir = util.join_paths(rocks_path, lua_version.dir)
```

**Comment by wbthomason** [comment]
I think this is the same as #146 and maybe #205? If so, I'll prioritize finishing/fixing #205 to resolve these problems.

I will note that I cannot guarantee that `packer` will work without LuaJIT in the future - there's a fairly decent chance that I'm going to end up using some LuaJIT-only features (e.g. `ffi`-related things) that may not be able to be easily gated off like the `luarocks` functionality.

**Comment by MrAdityaAlok** [comment]
Okay, then I'm waiting for #205 to finish
