### ISSUE TITLE
Entries in `event` key aren't escaped in `packer_compiled.vim`

### ISSUE THREAD

**Issue by YaBoiBurner** [wbthomason/packer.nvim#273]
Example

A plugin is configured to load on `CmdlineEnter \?`, which in the plugin spec means that it has
```lua
use {
	...
	event = 'CmdlineEnter \\?',
	...
}
```

But in the compiled spec, we end up with a line containing the following:
```lua
vim.cmd [[au CmdlineEnter \? ++once lua require("packer.load")({...}, { event = "CmdlineEnter \?" }, _G.packer_plugins)]]
--																							  ^
--																							  this is the problem
```

As a result, the plugin will fail to load when it should, and throw an E5107:
```
E5500: autocmd has thrown an exception: Vim(lua):E5107: Error loading lua [string ":lua"]:1: invalid escape sequence near '"CmdlineEnter '
```

---

This is admittedly a bit of an edge case, and it can be mitigated by just not lazy loading the plugin, but I figured it'd be worth mentioning.

**Comment by wbthomason** [comment]
Thanks for the report! Could you please give #278 a spin and see if it fixes this for you?

**Comment by YaBoiBurner** [comment]
Fix works perfectly on my end. Thanks.
