### ISSUE TITLE
Custom name

### ISSUE THREAD

**Issue by p00f** [wbthomason/packer.nvim#28]
How do I do the vim-plug equivalent of `Plug 'dracula/vim', { 'as': 'dracula' }` (ie install it in a folder named `dracula` or else it would be installed in a folder named `vim` because the repository is [https://github.com/dracula/***vim***](https://github.com/dracula/vim))

**Comment by wbthomason** [comment]
Right now, you can't easily do so (to be honest, I'd never understood the need for that feature in `vim-plug`, so I didn't implement it for `packer`...). That should be easy enough to add, though. I'll give it a look.

**Comment by p00f** [comment]
>  I'd never understood the need for that feature in vim-plug

Because `vim` would be a confusing name for a plugin haha

**Comment by wbthomason** [comment]
Yeah, I'd just never used a plugin with a name like that...

**Comment by wbthomason** [comment]
@p00f I've added this in https://github.com/wbthomason/packer.nvim/pull/31; could you check it out and confirm that the feature works as expected when you have a chance? Thanks!
