### ISSUE TITLE
Using function as value optional config seem not work

### ISSUE THREAD

**Issue by Julpikar** [wbthomason/packer.nvim#280]
I have tried using the functions in the config as described in the documentation, it seem not worked. My test code look like this:
```lua
-- this code won't print "hello world" in vim
use {"glepnir/dashboard-nvim",config=function() print("hello world") end}
```
but config worked if my code look like this:
```lua
-- this code will print "hello world"
use {"glepnir/dashboard-nvim",config=print("hello world")}
```

**Comment by wbthomason** [comment]
Have you run `PackerCompile` or `PackerSync`? Your first example should work, whereas the second should not.

**Comment by wbthomason** [comment]
Please also note that `config` functions run only when plugins are loaded, i.e. at Neovim startup (for an eagerly loaded plugin).

**Comment by ikalnytskyi** [comment]
I have the same issue. I have something like this in my `init.lua`

```lua
  use({"norcalli/nvim-colorizer.lua", config = function()
    require("colorizer").setup({
      css = { css = true };
      stylus = { css = true };
      javascript;
      html;
    })
  end})
```

and it seems it's not invoked.

**Comment by wbthomason** [comment]
Have you regenerated your `packer_compiled` file since adding that `config` function?

**Comment by wbthomason** [comment]
Compilation is mandatory, but runs for you on `PackerSync` (which you use to update plugins), so you usually don't need to worry about it. If the compilation step fails, you'll see (and have logged) an error message. You can also add an autocommand to run `PackerCompile` every time your `plugins.lua` is saved (you only need to recompile on a change to your plugin specification). Making compilation more automatic is on the queue of improvements, but requires a bit of re-engineering first.

**Comment by ikalnytskyi** [comment]
Oh, alright. I think I've got what the problem. So I have two terminal tabs. In first one I have permanently opened NeoVim with `init.lua`. The second one I use to open various files and battle test changed settings. Apparently, running `:PackerCompile` from the NeoVim where I edit my `init.lua` is not enough. It seems like `:PackerCompile` does not re-evaluate `init.lua`, and thus settings are not applied.

**Comment by wbthomason** [comment]
Ah - this is a common issue for people new to Lua. Lua caches modules, so the **first** time you `require` your `plugins.lua` or `init.lua`, etc., it'll be evaluated, but changes won't be picked up on successive `require`s unless you unload the module or restart Neovim.

**Comment by Julpikar** [comment]
Oh, thank you for the advice that has been given. I have tried to run `PackerCompile` after I restarted Neovim without opening any config files. It worked!!.
