### ISSUE TITLE
Configs get sourced before the plugin is installed

### ISSUE THREAD

**Issue by gseidler** [wbthomason/packer.nvim#281]
I am migrating my Mac configuration to my Ubuntu computer. Most of my plugins use the following configuration to source the config file from a module using the `config` option:

```lua
use {'nvim-telescope/telescope.nvim',
	config = require'plug.telescope'.config(),
	requires = {{'nvim-lua/popup.nvim'}, {'nvim-lua/plenary.nvim'}}}
```

The code in the telescope.lua module configuration requires the plugin to be installed so it throws an error when launching neovim.  Packer then can't see the plugins to install when neovim launches with an error. PackerInstall shows no plugins. By commenting the `config` option I was able to launch neovim without errors and install the plugins. After that I re-enabled the configs. Should I implement the logic to check if the plugin is installed before running the config or should Packer detect it out of the box?

**Comment by akinsho** [comment]
@gseidler it's not immediately clear what's happening in your case because the config is hidden in the function. Would be good to see the contents of the `plug.telescope` although my guess is that you aren't returning a function in the config key. I'll explain.
The two valid formats for the `config` key are
```lua
use {'plugin', config = [[require('config.plugin')]]}
-- Or
use {'plugin', config = function() require('plugin').setup()}

--- When you move the above function to a separate file that file should look like
-- inside `config.plugin`
return function()
  require('plugin').setup()
end
-- in packer setup
use {'plugin', config = require('config.plugin')}
```
The important thing to note here is that the require of `config.plugin` returns a function. That function has *not* been called yet and will not be called till later by packer. In your case I'm guessing that because you are invoking the function immediately you are getting the error because the plugin has not been loaded at that point. That's just where you declare it to be loaded later.

Does that make sense?

**Comment by gseidler** [comment]
Interesting, makes sense. The first syntax worked well for me, thanks!

**Comment by gseidler** [comment]
The contents of my telescope. lua module:
```lua
local M = {}

function M.config()

	local map = vim.api.nvim_set_keymap
	local nrs = { noremap = true, silent = true }

	require('telescope').setup{
		defaults = {
			prompt_prefix = ' ❯ ',
			file_ignore_patterns = {
				"%.jpg", "%.jpeg", "%.png", "%.otf", "%.ttf", "%.zip", "%.rar", "%.dmg", "%.sqlite"
			}
		},
		extensions = {
			fzy_native = {
				override_generic_sorter = false,
				override_file_sorter = true,
			}
		}
	}

	require('telescope').load_extension('fzy_native')
	require('telescope').load_extension('ultisnips')

	map('n', '<Leader>ff', "<Cmd>lua require('telescope.builtin').find_files()<CR>", nrs)
	map('n', '<Leader>fc', "<Cmd>lua require('telescope.builtin').find_files({ follow = true, cwd = '$XDG_CONFIG_HOME' })<CR>", nrs)
	map('n', '<Leader>fv', "<Cmd>lua require('telescope.builtin').find_files({ cwd = '$XDG_CONFIG_HOME/nvim' })<CR>", nrs)
	map('n', '<Leader>fg', "<Cmd>lua require('telescope.builtin').live_grep()<CR>", nrs)
	map('n', '<Leader>fb', "<Cmd>lua require('telescope.builtin').buffers()<CR>", nrs)
	map('n', '<Leader>fh', "<Cmd>lua require('telescope.builtin').help_tags()<CR>", nrs)
	map('n', '<Leader>fu', "<Cmd>lua require'telescope'.extensions.ultisnips.ultisnips{}<CR>", nrs)

end

return M
```

**Comment by akinsho** [comment]
@gseidler in your case you should *not* be calling `config` in the declaration just passing the function
```lua
--- This won't work
use {'nvim-telescope/telescope.nvim',
	config = require'plug.telescope'.config(),
	requires = {{'nvim-lua/popup.nvim'}, {'nvim-lua/plenary.nvim'}}}

--- Use This instead
use {'nvim-telescope/telescope.nvim',
	config = require'plug.telescope'.config, -- Do not call the function, packer will do that later
	requires = {{'nvim-lua/popup.nvim'}, {'nvim-lua/plenary.nvim'}}}

**Comment by gseidler** [comment]
The plugin works now but the mappings didn't get configured. Any ideas?

**Comment by wbthomason** [comment]
Have you called `:PackerSync` or `:PackerCompile`? If not, the file where your config actually gets invoked doesn't exist yet.

**Comment by gseidler** [comment]
Awesome! It works! Thanks, guys!
