### ISSUE TITLE
PackerUpdate removes the packer.nvim itself

### ISSUE THREAD

**Issue by lalitmee** [wbthomason/packer.nvim#284]
Why is it happening that when I do `:PackerUpdate` everytime it asks me to remove `packer.nvim` and if I do `y` it removes and then I have to install it again.

My `plugins.lua`
```lua
local execute = vim.api.nvim_command
local fn = vim.fn

local install_path = fn.stdpath('data') .. '/site/pack/packer/start/packer.nvim'

if fn.empty(fn.glob(install_path)) > 0 then
  execute('!git clone https://github.com/wbthomason/packer.nvim ' ..
              install_path)
  execute 'packadd packer.nvim'
end

vim.cmd 'autocmd BufWritePost plugins.lua PackerCompile'

require('packer').init({ display = { auto_clean = false } })

return require('packer').startup {
  function(use)
    -- Packer can manage itself as an optional plugin
    use 'wbthomason/packer.nvim'

    -- my plugins
  end,
  config = { display = { open_cmd = 'topleft 65vnew [packer]' } }
}
```

Is there something which I am not doing right?

**Comment by wbthomason** [comment]
You have a couple of small issues, but I'm not immediately sure what's causing this.

1. You don't need to `packadd packer.nvim`; you're installing it as a `start` plugin
2. You do not need to call both `packer.init` and `packer.startup` - `packer.startup` takes care of `init` for you

**Comment by lalitmee** [comment]
@wbthomason , after commenting out these issues. Still I am facing the same thing. I don't understand, it was working fine till yesterday. Why is it doing so from yesterday?

**Comment by wbthomason** [comment]
Do you have a log of what you changed yesterday? Did you update `packer`? There haven't been any changes to `packer` that should have affected this...

Could you please post your complete `plugins.lua` (or ideally a link to your entire config)? Is it possible that you have multiple plugin specification files, so that your plugin set is getting overwritten somewhere?

**Comment by lalitmee** [comment]
@wbthomason , this is my complete `plugins.lua` https://github.com/lalitmee/dotfiles/blob/master/editors/nvim/lua/plugins.lua

**Comment by lalitmee** [comment]
@wbthomason , I don't have a log of what I changed yesterday. I really don't know.

**Comment by wbthomason** [comment]
You could try posting the contents of `~/.cache/nvim/packer.nvim.log`, but I'm not sure there will be anything useful in there.

Does anything other than `packer` get removed? Is the path that you're prompted to remove the *current* path where `packer` is installed, or an old path (e.g. `~/.local/share/nvim/site/pack/paacker/opt/packer.nvim` instead of `~/.local/share/nvim/site/pack/packer/start/packer.nvim`)?

**Comment by lalitmee** [comment]
So when I do `:PackerUpdate`, it simply asks me in my command mode bar `Ok to remove [y/N]` I have to press `y` and then everything gets removed along with packer. How I got to know that everything is removed is this when I start nvim again there is not plugin installed and I get so many errors. 
I never installed `packer` to `opt` path. It has always been in my `start` path.

**Comment by lalitmee** [comment]
I think there is something wrong with my config. When I have all of the plugins installed but don't source all the configurations and do `:PackerUpdate` it is working fine but when I source all the configurations for plugins it asks to remove `Packer` and other `plugins` too.

**Comment by lalitmee** [comment]
Sometimes I am getting this error 
```
[packer.nvim] [WARN  22:19:21] jobs.lua:77: Killing git due to timeout!
```

**Comment by wbthomason** [comment]
I'm not sure I know what you mean by "source all the configurations"? I briefly looked through your config repo and didn't see anywhere that you e.g. reset `packer` state when you shouldn't, but doing that would explain this behavior.

**Comment by lalitmee** [comment]
By "source all the configurations` meaning is that when I apply configs of the plugins which I am using.

**Comment by lalitmee** [comment]
When I try to run any command for `packer` like `:PackerUpdate` or `:PackerSync` and then it gives me the options to `Ok to remove [y/N]` and if I select `N` it gives me this error. 

```
[packer.nvim] [WARN  00:23:44] clean.lua:75: Cleaning cancelled!
[packer.nvim] [ERROR 00:23:44] async.lua:20: Error in coroutine: ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:380: attempt to index local 'display_win' (a nil value)

```

**Comment by alok** [comment]
I've had this issue too. No idea what fixed it though.

**Comment by wbthomason** [comment]
Is there any chance that you have multiple calls to `packer.init` or `packer.startup` or `packer.reset` - basically, anything that could clear the set of managed plugins in an unexpected way?

Could you also try running `:PackerStatus` to see your set of managed plugins? That might help pin down if this is due to a bug in `packer` or an issue with your config.

**Comment by Apppppppple** [comment]
It looks like I'm having the same issue. `:PackerStatus` doesn't show anything out of the ordinary - packer doesn't sneak in there or anything. Running sync/update always asks to clean packer - I thought it was intentional until I found this issue.

**Comment by Apppppppple** [comment]
Adding packer to my plugins list by doing
```lua
use { 'wbthomason/packer.nvim', config = function() require 'plugins' end, cmd = { 'PackerClean', 'PackerCompile', 'PackerInstall', 'PackerProfile', 'PackerStatus', 'PackerSync', 'PackerUpdate' } }
```
works but idk if that's what I'm supposed to do or if it's a hackfix - I can't anything like this in the readme

**Comment by akinsho** [comment]
@Apppppppple that isn't a hack that's the correct way to specify packer. It should be part of your plugin spec

**Comment by akinsho** [comment]
You don't need to add those `config` and `cmd` keys to make it work though 🤷🏿 but you also can if that's how you like it.

**Comment by akinsho** [comment]
@wbthomason maybe packer should error if it isn't included in the list of plugins since it has to be?

**Comment by wbthomason** [comment]
Technically it doesn't need to be - if you put `packer` somewhere outside of your plugin install path but still somewhere Neovim can find it, it's fine - it just won't update itself. The issue arises when you have `packer` in your install directory but not your managed set, which we could easily add a warning for.

**Comment by Apppppppple** [comment]
> @Apppppppple that isn't a hack that's the correct way to specify packer. It should be part of your plugin spec

Yeah I just saw that sorry

**Comment by garymh** [comment]
I think I'm also getting something similar... there must be an issue in my config somewhere but I can't figure it out.

If I type `:PackerCompile` while nvim is running, it will make a `packer_compiled.vim` with all the plugins missing (i.e. `_G.packer_plugins = {}`). Then typing `:PackerSync` will try to remove every single plugin. 

If I close nvim and reopen it, then try `:PackerCompile` again, it will put all the plugins back but `:PackerSync` will still try to delete them all. 

I have a pretty simple `init.lua`:

```lua
require 'plugins'

vim.cmd([[source ~/code/dotfiles/home/vim/vimscript/packer_compiled.vim]])

-- (irrelevant stuff below)
```

Here are my [plugins.lua](https://pastebin.com/kPyCecJR) and [packer_compiled.vim](https://pastebin.com/KJxyeYAU) (when it has plugins)

**Comment by garymh** [comment]
I figured out my issue at least! It was an issue with https://github.com/nvim-telescope/telescope-packer.nvim - removing that seems to have fixed everything.

**Comment by lalitmee** [comment]
@garymh , yup it seems my issue was also the same. Removing `telescope-packer.nvim` solves this issue.

**Comment by wbthomason** [comment]
Fascinating, I'm glad you were able to figure out this issue. Can I ask what the specific problem was, if you know?

**Comment by theol0403** [comment]
I also came across this issue, but it was because I didn't have packer in my plugin list. I think it would be beneficial if this could be made more clear in the readme, and/or if it was enforced/warning by packer (or even automatically add it).
