### ISSUE TITLE
How to load local plugins?

### ISSUE THREAD

**Issue by jojoyuji** [wbthomason/packer.nvim#286]
I'm having trouble loading custom local plugins: 

```lua 
  use '~/.config/nvim/myPlugins/myplugin.nvim'
```
as it is in the description, 
but when I try to install it tries to load from github as it was a remote plugin:

```
 ✗ Failed to install /Users/jojo/.config/nvim/myPlugins/myplugin.nvim
  Errors:
    Cloning into '/Users/jojo/.local/share/nvim/site/pack/packer/start/myplugin.nvim'...
    remote: Not Found
    fatal: repository 'https://github.com//Users/jojo/.config/nvim/myPlugins/myplugin.nvim/' not found

```

am I doing something wrong here?

**Comment by wbthomason** [comment]
Thanks for the report! Your spec looks correct, so I think this is probably a bug.

Was `myplugin` originally installed as a `git` plugin that you're now moving to local, or is this a completely new addition?

**Comment by wbthomason** [comment]
Ah - one thing that could cause this: does the directory `~/.config/nvim/myPlugins/myplugin.nvim` already exist? If not, we will guess that the plugin is a `git` plugin.

**Comment by jojoyuji** [comment]
`myPlugin` was not a was not a git plugin at all, and it does exists: 
<img width="719" alt="Captura de Tela 2021-04-09 às 11 25 05" src="https://user-images.githubusercontent.com/675317/114203568-488ded80-9926-11eb-89fe-01f37df16755.png">

**Comment by wbthomason** [comment]
Hmm. I'm having trouble reproducing this issue - I created the directory `~/.config/nvim/myPlugins/foobar.nvim` and added it to my config using `use '~/.config/nvim/myPlugins/foobar.nvim'`; it gets installed as a local plugin, as expected.

Could you please run `:echo isdirectory('/Users/jojo/.config/nvim/myPlugins/myPlugin.nvim')` and confirm that it prints '1'?

**Comment by jojoyuji** [comment]
whoops, my bad!

`myPlugin.nvim` is not a dir, that's why it's not working -_- 

I did not realize it should be a dir, sorry for taking your time! 

It worked as a dir thou, tysm!

**Comment by wbthomason** [comment]
Ah, got it. No worries, glad you got things working!

**Comment by wbthomason** [comment]
Sorry for my delay in getting to this! When you say "added as symbolic links", do you mean that the path that you provide to `packer` for the plugin is a path to a symbolic link?

**Comment by tigion** [comment]
I think that's what he means.

---

As information, if it's still relevant:

I made the same mistake today. My plugin has a long path, so I created a shorter one via symbolic link. (My workflow for current projects.)

- normal path: `~/my/long/path/to/my/projects/neovim/plugin/`
- symbolic link: `~/code/plugin` which points to `~/my/long/path/to/my/projects/neovim/plugin/`

In my `plugin.lua` I have tested:
- `use '~/code/plugin'` -> it does not work
- `use '~/my/long/path/to/my/projects/neovim/plugin'` -> it works
