### ISSUE TITLE
config in requires ignored?

### ISSUE THREAD

**Issue by AckslD** [wbthomason/packer.nvim#290]
I have a config inside a requires-block which seems to be ignored, i.e.:
```lua
    use {
        'AckslD/nvim-whichkey-setup.lua',
        requires = {
            'liuchengxu/vim-which-key',
            config = 'require("plugin_settings.whichkey")',
        },
    }
```
but there is no entry `require("plugin_settings.whichkey")` in `packer_compiled.vim`.

**Comment by akinsho** [comment]
@AckslD I think this is an issue of formatting, `requires` can be `string` or a `list` but not just a `table` i.e. I think what you have there should be

```lua
   use {
        'AckslD/nvim-whichkey-setup.lua',
        requires = {
           { 'liuchengxu/vim-which-key', config = 'require("plugin_settings.whichkey")'}
      },
    }
```

**Comment by AckslD** [comment]
Oh, I see, thanks @akinsho! :)
