### ISSUE TITLE
Use packer alongside vim-plug or vundle

### ISSUE THREAD

**Issue by adgai19** [wbthomason/packer.nvim#294]
Hi, I came across a plugin which requires 2 luarocks to be installed with the plugin to make it work.([telescope-arecibo ](https://github.com/nvim-telescope/telescope-arecibo.nvim)). Although I want to use it, they only have packer installations as for now. I am currently using vim-plug to manage my plugins and I do not want to migrate my init.vim to lua. Is there any way to make them work together?

I am sorry if this is a repeat question.

**Comment by akinsho** [comment]
@adgai19 trying to have two package managers installed I think is a bad idea and will cause a bunch of issues down the line. It is possible to use packer with an `init.vim` not only with an `init.lua` you just need to put all of the lua in a `heredoc`. There is documentation about this in neovim's help. I can't remember the exact subheading but it is there. Alternatively I think *maybe* you can just manually install the dependencies using https://github.com/luarocks/luarocks.

I also believe packer can install lua rocks without having to be the package manager i.e. it can be used just for that and I think the usage of that is in the README.md

**Comment by wbthomason** [comment]
Actually, using `packer` just for luarocks support _is_ something we want to support: https://github.com/wbthomason/packer.nvim#luarocks-support

You should be OK using the `use_rocks` function or the `PackerRocks` command - the linked section has more details.

I would strongly recommend against managing some plugins with `packer` and some with another plugin manager, though.

**Comment by wbthomason** [comment]
Oh, and as @akinsho mentioned, you do *not* need to switch to `init.lua` to use `packer`.
