### ISSUE TITLE
Feature request: Add a command to load plugins

### ISSUE THREAD

**Issue by shadmansaleh** [wbthomason/packer.nvim#301]
### Idea

It'll be nice to have a command that loads a specific plugin . For example :
```
:PackerLoad telescope.nvim
```
loads telescope plugin (when opt=true) with it's setup and config if the plugin isn't already loaded.

### Motivation
I have most of the plugin configuration done in packer config . If I wanted to load a plugin I can do packadd but that means the configs won't be loaded . It would have been great if packer handled that . Also I think I can skip requires and after with this 😄

**Comment by shadmansaleh** [comment]
@wbthomason if I were to implement it where should I look at ?

**Comment by wbthomason** [comment]
This would probably go in `lua/packer/load.lua` - basically, this would work by calling the `load` function (which already handles things like sequencing, configs, lazy-load teardown, etc.) for the specified plugin name. It should be pretty simple to implement; `load` already does most of the work for you.

**Comment by akinsho** [comment]
@shadmansaleh maybe I can help a bit, was thinking it would be nice to add something to the `PackerStatus` window I added at some point.

The commands are registered [here](https://github.com/wbthomason/packer.nvim/blob/34368c842ab7aefbbdd3cf26f1d8fe48a4e8dcb6/lua/packer.lua#L103). I believe the module you are looking for is `load.lua`.

An example of the usage can be found in your `packer_compiled.vim`
e.g.
```vim
vim.cmd [[au BufEnter *_spec.lua ++once lua require("packer.load")({'nvim-terminal.lua'}, { event = "BufEnter *_spec.lua" }, _G.packer_plugins)]]

```

I think you can pass in an empty table as the second argument but you might want to check the logic to make sure that doesn't do anything weird

**Comment by shadmansaleh** [comment]
Thanks . I'll checkout the code when I'm free.
