### ISSUE TITLE
PackerCompile not using updated config until after nvim has restarted

### ISSUE THREAD

**Issue by HumblePresent** [wbthomason/packer.nvim#304]
If I edit the file with my packer.nvim config, write the buffer, and then run `PackerCompile`, the new `packer_compiled.vim` file does not include the changes I just made to my config file. I have to restart neovim before running `PackerCompile` for the updates to be included. Maybe I'm just confused, but is this how `PackerCompile` is supposed to work? I am asking because I also have an autocommand to run `PackerCompile` whenever my config file is edited, as described in the README, but it's useless when `PackerCompile` does not include the changes I just made without restarting neovim. This doesn't seem right to me.

**Comment by shadmansaleh** [comment]
You need to run the config after saving so PackerCompile can work with latest version .
I usually do 
```lua
:w
:luafile %
:PackerCompile
```

It's the same for other plugin managers . In VimPlug you need to source the config first before PlugInstall or any other command can use the latest config.

**Comment by wbthomason** [comment]
@shadmansaleh Does running `luafile` like that work for you every time, or just the first time?

**Comment by wbthomason** [comment]
Right, but if that file requires modules, do those not get cached? I assume that the Neovim commands for using Lua all manipulate the same Lua state, but perhaps that's wrong?

**Comment by HumblePresent** [comment]
Thank you for your responses! Now that you explain that it actually makes a lot of sense. I think I was thrown off by the autocommand example from the README
```
autocmd BufWritePost plugins.lua PackerCompile
```
I assumed that was all I needed for the auto-recompile to work. I think there should be an addition to the README to include
```
autocmd BufWritePost plugins.lua luafile plugins.lua
```
because the first autocommand is kind of useless without rerunning your packer config first.
