### ISSUE TITLE
All plugins update except packer.nvim

### ISSUE THREAD

**Issue by mache73k** [wbthomason/packer.nvim#311]
When running :PackerUpdate or PackerSync, everything updates normally except Packer, it always shows this error: wbthomason/packer.nvim: failed to update 

Any idea why or how to diagnose this?

**Comment by akinsho** [comment]
@mache73k you can press `<CR>` over a failed update to get information on what happened. In all likelihood it was an issue with git updating the repo but you'll get a better idea once you expand the output. Please paste the result here if it isn't immediately clear

**Comment by mache73k** [comment]
@akinsho thank you for your reply. the issue was that I changed the timeout value in packer.lua and the update process wouldn't continue because it will overwrite those changes. the issue is fixed now.
