### ISSUE TITLE
'lua_version is nil' in luarocks.lua on Gentoo

### ISSUE THREAD

**Issue by dsunnerer** [wbthomason/packer.nvim#318]
In luarocks.lua the variable `lua_version` stays at a nil value causing errors in startup.

`lua_version` is unset after
```lua
local lua_version = nil
if jit then
  local jit_version = string.gsub(jit.version, 'LuaJIT ', '')
  lua_version = {lua = string.gsub(_VERSION, 'Lua ', ''), jit = jit_version, dir = jit_version}
end
```

After hardcoding all instances of `lua_version` in this file, which don't access the `jit` attibute to my selected version (5.1) the plugin seems to behave correctly.

For example:
```lua
local package_paths = (function()
  local install_path = util.join_paths(hererocks_install_dir, 'lib', 'luarocks',
                                       fmt('rocks-%s', '5.1'))
  local share_path = util.join_paths(hererocks_install_dir, 'share', 'lua', '5.1')
  return package_patterns(share_path) .. ';' .. package_patterns(install_path)
end)()
```

Seems to be fixed by the the following:
```lua
local lua_version = nil
if jit then
  local jit_version = string.gsub(jit.version, 'LuaJIT ', '')
  lua_version = {lua = string.gsub(_VERSION, 'Lua ', ''), jit = jit_version, dir = jit_version}
else
  lua_version = {lua = string.gsub(_VERSION, 'Lua ', ''), jit = nil, dir = string.gsub(_VERSION, 'Lua ', '')}
end
```
But I'm sure there is a much more elegant solution.

**Comment by wbthomason** [comment]
Probably related to #205?

**Comment by dsunnerer** [comment]
Yes, looks like exactly the same thing.
A mention that plain LUA is not supported in the readme could help others to avoid this path.

**Comment by akinsho** [comment]
@dsunnerer it's not a requirement specific to packer but to neovim which I think needs to be made more prominent there since all plugins should be developing against the version of lua neovim supports

**Comment by wbthomason** [comment]
Plain Lua is technically supported by Neovim (depending on the build) and `packer` (though we reserve the right to break this compatibility in the future, and the `luarocks` functionality right now does require LuaJIT). I need to fix the check so that the `luarocks` functionality doesn't break the rest of `packer` if you don't have LuaJIT.

**Comment by akinsho** [comment]
@wbthomason the `lua-intro` under `:h lua` refers specifically to `lua 5.1`  (presumably with luajit) as built in. This isn't really one for packer but I think that despite supporting multiple versions of lua people should be strongly urged to use that specific version of `lua` to ensure compatibility, I think since it hasn't been as clearly enforced it's giving rise to a lot of confusion especially given that the versions are incompatible. I think the more people are flexible with the version number they use the more issues we'll see across the whole plugin ecosystem.

**Comment by wbthomason** [comment]
@akinsho Is the problem with the Lua version, or the Lua implementation? To clarify, by "plain Lua" I do mean Lua 5.1, as implemented by the default Lua interpreter. I think the problem in this issue is the implementation (though certainly versions have caused confusion in other cases).

**Comment by akinsho** [comment]
Sorry @wbthomason I've gone completely off track from the main issue here 😆 I've encountered the version confusion a bit in my own plugins so got a bit of tunnel visions, I'm not sure what the distinction here is though that means a user can have the correct version of lua but be unable to use `luaJIT` though (but that's probably on me to read up on)

**Comment by wbthomason** [comment]
@dsunnerer I've updated #205 to return early with a NOP-version of the luarocks API if `jit` is not present. Could you please test this and see if it fixes the issue for you?

**Comment by wbthomason** [comment]
> Sorry @wbthomason I've gone completely off track from the main issue here laughing I've encountered the version confusion a bit in my own plugins so got a bit of tunnel visions, I'm not sure what the distinction here is though that means a user can have the correct version of lua but be unable to use `luaJIT` though (but that's probably on me to read up on)

Ah, no worries. Basically: LuaJIT is a specific implementation of the Lua 5.1 spec (plus some extensions). Neovim _mostly_ compiles against LuaJIT, but some platforms compile against the "vanilla" implementation of the 5.1 spec (without those extensions), so we cannot always rely on having LuaJIT present.

**Comment by dsunnerer** [comment]
@wbthomason
Your patch seems to run fine with Lua 5.1.
No Errors/Warnings on startup and all the Packer* commands are working as expected.
