### ISSUE TITLE
Packer not update plugin when repo changed to repo with same name

### ISSUE THREAD

**Issue by Kirill-Bugaev** [wbthomason/packer.nvim#339]
- `nvim --version`: NVIM v0.5.0-dev+1293-ga0da4c3a4
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -@
- `git --version`: git version 2.31.1
- Operating system/version: 5.11.16-arch1-1 #1 SMP PREEMPT Wed, 21 Apr 2021 17:22:13 +0000 x86_64 GNU/Linux
- Terminal name/version: st 0.8.2

### Steps to reproduce
1. I started with such `plugins.lua`
```lua
return require('packer').startup(function(use)
	use 'wbthomason/packer.nvim'
	use '9mm/vim-closer'
end)
```
2. Launch `PackerSync`
3. Then change `9mm/vim-closer` to `rstacruz/vim-closer`
```lua
return require('packer').startup(function(use)
	use 'wbthomason/packer.nvim'
	use 'rstacruz/vim-closer'
end)
```
 4. Launch `PackerSync` again and get "Everything already up to date!". `vim-closer` still bound to `9mm/vim-closer` repo.
 ```shell
~/.local/share/nvim/site/pack/packer/start/vim-closer on  master
$ git remote -v                                                                                                                                  [0]
origin  https://github.com/9mm/vim-closer (fetch)
origin  https://github.com/9mm/vim-closer (push)
```

### Actual behaviour
Packer not update plugin when repo changed to repo with same name.

### Expected behaviour
Packer should update plugin and bound to new repo when repo changed to repo with same name.
May be it has sense to place plugins to more verbose directory paths like `github.com/aws/aws-sdk-go@v1.29.8` in golang.
### packer files

<details>
<summary>packer log file</summary>
[INFO  Tue 04 May 2021 10:54:08 PM +07] .../site/pack/packer/start/packer.nvim/lua/packer/clean.lua:78: Already clean!
[DEBUG Tue 04 May 2021 10:54:10 PM +07] ...ite/pack/packer/start/packer.nvim/lua/packer/install.lua:23: Installed tpope/vim-endwise
[DEBUG Tue 04 May 2021 10:54:10 PM +07] ...ite/pack/packer/start/packer.nvim/lua/packer/install.lua:23: Installed 9mm/vim-closer
[INFO  Tue 04 May 2021 10:54:10 PM +07] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:486: Finished compiling lazy-loaders!
[INFO  Tue 04 May 2021 10:54:10 PM +07] ...ack/packer/start/packer.nvim/lua/packer/plugin_utils.lua:84: Updating helptags for /home/user1/.local/share/nvim/site/pack/packer/start/vim-closer/doc
[INFO  Tue 04 May 2021 10:54:10 PM +07] ...ack/packer/start/packer.nvim/lua/packer/plugin_utils.lua:84: Updating helptags for /home/user1/.local/share/nvim/site/pack/packer/start/packer.nvim/doc
[INFO  Tue 04 May 2021 11:12:50 PM +07] .../site/pack/packer/start/packer.nvim/lua/packer/clean.lua:78: Already clean!
[INFO  Tue 04 May 2021 11:12:51 PM +07] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:486: Finished compiling lazy-loaders!
[INFO  Tue 04 May 2021 11:16:39 PM +07] .../site/pack/packer/start/packer.nvim/lua/packer/clean.lua:78: Already clean!
[INFO  Tue 04 May 2021 11:16:40 PM +07] ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:486: Finished compiling lazy-loaders!
[WARN  Tue 04 May 2021 11:16:52 PM +07] ...ite/pack/packer/start/packer.nvim/lua/packer/display.lua:518: No plugin selected!
[WARN  Tue 04 May 2021 11:17:05 PM +07] ...ite/pack/packer/start/packer.nvim/lua/packer/display.lua:493: No plugin selected!
[WARN  Tue 04 May 2021 11:17:07 PM +07] ...ite/pack/packer/start/packer.nvim/lua/packer/display.lua:493: No plugin selected!
[WARN  Tue 04 May 2021 11:17:52 PM +07] ...ite/pack/packer/start/packer.nvim/lua/packer/display.lua:493: No plugin selected!
[WARN  Tue 04 May 2021 11:17:54 PM +07] ...ite/pack/packer/start/packer.nvim/lua/packer/display.lua:493: No plugin selected!
[WARN  Tue 04 May 2021 11:17:58 PM +07] ...ite/pack/packer/start/packer.nvim/lua/packer/display.lua:493: No plugin selected!
[WARN  Tue 04 May 2021 11:18:10 PM +07] ...ite/pack/packer/start/packer.nvim/lua/packer/display.lua:493: No plugin selected!
[WARN  Tue 04 May 2021 11:18:12 PM +07] ...ite/pack/packer/start/packer.nvim/lua/packer/display.lua:493: No plugin selected!
</details>

<details>
<summary>packer compiled file</summary>

Post the contents of `packer_compiled.vim` here

</details>

**Comment by akinsho** [comment]
@Kirill-Bugaev thanks for logging this issue 👍🏾.
I think it's essentially a duplicate of https://github.com/wbthomason/packer.nvim/issues/231 though.

**Comment by Kirill-Bugaev** [comment]
@akinsho yes, thanks
