### ISSUE TITLE
Packer commands generate errors

### ISSUE THREAD

**Issue by Tinku10** [wbthomason/packer.nvim#346]
![bug](https://user-images.githubusercontent.com/29244595/117188377-a107bc00-adfa-11eb-91ad-c5fde681dbf7.png)

An error gets generated whenever I use ```:PackerInstall```, ```:PackerUpdate```, or ```PackerSync```. Is this something to do with the number of plugins as the error says ```too many file names```.

For reference, I have around 22 plugins installed.

```
NVIM v0.5.0-dev+1231-g48e805728
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

```
OS: Ubuntu 20.04
Terminal emulator: Kitty
Shell: zsh
git version 2.25.1
```

**Comment by nanotee** [comment]
Oh, I think I know what this is: `[]` brackets count as a wildcard (`:h wildcard`)

Here's a minimal reproducer:

```sh
mkdir test_dir
cd test_dir
touch p a c
nvim -u NONE
```
```vim
:vnew [packer]
```

So this can occur in rare circumstances if you have more than one file that matches one of the letters in the wildcard.

The default `open_cmd` should probably escape `[]` brackets
