### ISSUE TITLE
Packer Compile: attempt to index upvalue nil

### ISSUE THREAD

**Issue by ahmedkhalf** [wbthomason/packer.nvim#351]
- `nvim --version`: NVIM v0.5.0-dev
- `git --version`: git version 2.27.0
- Operating system/version: Ubuntu
- Terminal name/version: kitty

### Steps to reproduce

Use the following config: 
```lua
return require('packer').startup(function(use)
  -- Packer can manage itself
  use 'wbthomason/packer.nvim'

  local load = function(use_table)
    local index = use_table[1]:match'^.*()/'
    local plugin_name = string.sub(use_table[1], index + 1)

    use_table.config = function()
      local plugin_file = fn.stdpath('config')..'/lua/plugins/'..plugin_name..".lua"
      if fn.filereadable(plugin_file) then
        require("plugins." .. plugin_name)
      end
    end

    use(use_table)
  end

  load {'glepnir/dashboard-nvim'}

end)
```

As you can see, I am creating a function called load which given a table will create its config key by getting the name of the plugin, in this case "dashboard-nvim" and sourcing the plugin config if it exists.

### Actual behaviour

Unfortunately when I compile, I get the following error:
```
Error in packer_compiled: Vim(lua):E5108: Error executing lua [string ":lua"]:52: [string "
..."]:0: attempt to index upvalue '' (a nil value)                                         
Please check your config for correctness  
```

### Expected behaviour

I just want it to compile correctly and source the proper config file with require if they exist.

### packer files

<details>
<summary>Plugin specification file(s)</summary>

Post or link your plugin specification files here, if you aren't able to provide a minimal
reproducer

</details>

<details>
<summary>packer log file</summary>

Post the contents of ~/.cache/nvim/packer.nvim.log here

</details>

<details>
<summary>packer compiled file</summary>

Post the contents of `packer_compiled.vim` here

</details>

**Comment by akinsho** [comment]
Ahhh I just noticed another probable cause that happens to me very often. It looks like you have aliased `vim.fn` to `fn` and you are using `fn` inside the config function so that will also be an upvalue.

As a side note I think when @wbthomason is free he's planning on a refactor that might remove this problem. If not I was going to look into seeing if there's a way to improve the situation but these are all future improvements can't promise any ETAs

**Comment by akinsho** [comment]
Hmm that's a bit strange, I have a function in my dotfiles that is vaguely similar that works fine i.e. a new function in my case called `local_use` the function is defined outside of the startup function and that works without this error. I guess something to check is that you are definitely re-compiling your `packer_compiled.vim` *after* reloading/re-requiring the file that you startup function is in right?

**Comment by ahmedkhalf** [comment]
Update I don't know why I'm so dumb, but there is a much better way, instead of trying to fit as many things as possible inside of the config function, why not just try to fit as many things outside of the config function!!

Here is the resulting code:
```lua
  local load = function(use_table)
    local index = use_table[1]:match'^.*()/'
    local plugin_name = string.sub(use_table[1], index + 1)
    local plugin_file = vim.fn.stdpath('config')..'/lua/plugins/'..plugin_name..'.lua'

    if vim.fn.filereadable(plugin_file) then
        use_table.config = "require('plugins.' .. '"..plugin_name.."')"
    end

    use(use_table)
    -- print(vim.inspect(strfunc))
  end
```
Much better and much more elegant, although I am still getting the huge error pointed above the code here is definitely cleaner.

**Comment by akinsho** [comment]
@ahmedkhalf actually that makes sense 🤦🏾‍♂️ `use_table` is an `upvalue` even inside `use_table.config` 🤔 I can't currently think of anyway to pass that information to your config func without it being an upvalue. Tbh what you're trying to do could be done more simply although it depends on if you are very keen on the `load` wrapper syntax.

You could just make the function that checks for the existence of of the plugin a wrapper e.g.
```lua
local function protected_require(path_segment)
-- logic to check for existence
-- if nil
return nil
-- derive path
local derived_path = '<blah>/'..path_segment
return require(derived_path)
end

packer.startup(function(use)
  use {'plug_name', config = protected_require('path_segment')}
```
😆 Just saw the post and was about to recommend something similar

**Comment by ahmedkhalf** [comment]
Look like the error come from loading the plugin `kyazdani42/nvim-tree.lua`, why would anyone name his plugin with .lua :cry:, it's causing some unexpected behavior.

**Comment by ahmedkhalf** [comment]
Problem fixed changed the if statement from 'if vim.fn.filereadable(plugin_file) then` to 'if vim.fn.filereadable(plugin_file) == 1 then'
Should I closed this issue now that my problem is fixed, or leave it open to eventually allow upvalues.

**Comment by Doraj1908** [comment]
o stoped
all

**Comment by Doraj1908** [comment]
no more mouve at console
befor the same have jump ping "ms" but dont se 10 k 33 k donty know whats hapen  i used ineternet witch me phone
