### ISSUE TITLE
MIxed post-install/update hooks

### ISSUE THREAD

**Issue by anuvyklack** [wbthomason/packer.nvim#355]
I have a question:

CHADTree plugin needs to execute `python3 -m chadtree deps` as shell command in plugins directory which I can do by: 
```run = 'python3 -m chadtree deps'```
 and after this need to call vim command `CHADdeps`, which I can do as: 
```run =  ':CHADdeps'```
But how to call both commands in turn?

**Comment by akinsho** [comment]
Ah that's a tough one I don't think we actually support that as far as I'm aware. In the future I guess we could make the run command take a list of commands, in the short term can you try using something like `'python3 -m chadtree deps && nvim --headless +"CHADdeps | exit"' or something like this

**Comment by anuvyklack** [comment]
Yes, this works. Thank you!

**Comment by wbthomason** [comment]
Yeah, thanks for the report - we should absolutely allow lists of `run` values. The current best way to do what you want is either @akinsho's suggestion or passing a function to `run` which manually handles starting the shell process and then runs the command.

**Comment by akinsho** [comment]
Completely forgot that you could just use a function as well 🤦🏾 😆 ah well.

**Comment by surmish** [comment]
@akinsho can you post how you would set up the installation of Chadtree using packer?

**Comment by akinsho** [comment]
@surmish I don't use CHADTree but based on the commands you pointed out earlier something like
```lua
use {'chadtree', run = function()
  vim.fn.system("python3 -m chadtree deps")
  vim.cmd("CHADdeps")
end}
```
One downside of doing it this way is that the `system` command is blocking but since this is a user initiated action that's probably fine but not ideal.

**Comment by wbthomason** [comment]
I've made (but not yet tested) #364, which adds the ability for a plugin's `run` key to be a table mixing functions, commands, system commands, etc.

@anuvyklack, if you have a chance to test that PR, that would be helpful. Otherwise, I'll give it a spin when I get back to the PR to update the docs.
