### ISSUE TITLE
How to load plugin settings when it lazy loads ?

### ISSUE THREAD

**Issue by medwatt** [wbthomason/packer.nvim#356]
I have a couple of plugins setup with `opt = true`. Because the plugin is not loaded on startup, when the settings for the plugin load (eg. require("plugin_name")), I get errors saying the plugin is not found. How can I load the settings only when the plugin is loaded ?

**Comment by akinsho** [comment]
@medwatt when you say when it loads do you mean that you are manually calling `packadd` somewhere and want the `config` for that plugin to run?

Can you share some snippet that isn't working, based on what you have reported it's not entirely clear what is actually happening. Can you fill out the content that should be in the issue template please 🙏🏾 it will be easier to help you with more information

**Comment by medwatt** [comment]
> @medwatt when you say when it loads do you mean that you are manually calling `packadd` somewhere and want the `config` for that plugin to run?
> 
> Can you share some snippet that isn't working, based on what you have reported it's not entirely clear what is actually happening. Can you fill out the content that should be in the issue template please 🙏🏾 it will be easier to help you with more information

Thanks for the reply. Let me explain what I'm trying to achieve. I use the firenvim module. Previously, when I had everything in vimscript and was using the VimPlug, I had the main `init.vim` source one of two other `init.vim` files depending on whether firenvim was active or not. I did this because I had no use for most of the plugins I use outside of firenvim. For example, I use `Startify`. There's no need for that to load in firenvim. The way I did it with VimPlug is have a separate list of plugins in each of the `init.vim` files. I was trying to achieve this with packer but it seems that as long as the plugin is installed in the `start` folder, there's no way to selectively disable it as easily as I was doing with VimPlug by simply not including the name of the plugin in the `init.lua` file I have for firenvim.

I have experimented with different things but nothing seems to work. For example, I have no need for Telescope and it's dependent plugins to be enabled when using firenvim. This is an example of what I have tried.

```lua
local nofirenvim = function()
    return not vim.g.started_by_firenvim
end

local plugins = function()
    -- Packer
    use 'wbthomason/packer.nvim'

    -- Firenvim
    use {'glacambre/firenvim',
         run = function() vim.fn['firenvim#install'](0) end}

    -- Telescope
    use {'nvim-lua/popup.nvim', cond = { nofirenvim} }
    use {'nvim-lua/plenary.nvim', cond = { nofirenvim} }
    use {'nvim-telescope/telescope.nvim',
         config = [[require('main.plugin_config.telescope_config')]],
         cond = { nofirenvim}
        }
end

require('packer').startup(plugins)

if vim.g.started_by_firenvim then
    vim.cmd('luafile ~/.config/nvim/lua/firenvim/firenvim.lua')
else
    vim.cmd('luafile ~/.config/nvim/lua/main/main.lua')
end
```

I hope you can help me achieve what I explained above.

**Comment by akinsho** [comment]
@medwatt thanks for the info 👍🏾 , so packer uses native vim functionality called packages `:h packages` to manage plugins. As you noted if a plugin is `start` then it will always be loaded. You should be able to achieve what you want in packer though using either the `cond` key or the `disable` key.

`cond` will allow plugins to stay installed but not load them unless a condition is met. For example firenvim sets `g:started_by_firenvim` so you can check for that inside of the `cond` key. For example
```lua
use {'plug1', cond = function() return vim.g.started_by_firenvim == 0 end} -- this will only be active if firenvim is also active or
use {'plug1', cond = function() return vim.g.started_by_firenvim == 1 end} -- this will only be active if firenvim is NOT active
```
This way you can specify which plugins should be loaded based on some condition

**Comment by medwatt** [comment]
@akinsho what you suggested in your post is already what I'm doing. Look at the snippet I posted again. The only difference between yours and mine is that I made a helper function to avoid duplicating code. Telescope continues to load.

**Comment by akinsho** [comment]
@medwatt apologies trying to do this in my lunch break 😆 , one difference between the thing we have I guess it that you are using `not g:var` rather than explicitly checking the value of `g:var` a lot of `g:vars` then to be `1` or `0` based on vimscripts behaviour re. numbers so if `g:started_by_firenvim` is `0` in lua `0` is truthy because it is a number. I'd check explicitly that that value is returning what you expect i.e. your helper function is working correctly.

If if it is definitely working correctly can you try just passing the function directly rather than the table of functions that should be fine anyway but just checking that there is no bug there

**Comment by medwatt** [comment]
@akinsho Thanks for continuing to put up with me. I have managed to get it to work. I had to use `vim.g.started_by_firenvim == nil` to get `true` or `false`.

One last question if you don't mind. I would like to make Telescope dependency plugins also disabled when not needed. For some reason, when I set things up as shown below, I get an error on startup saying it couldn't find `plenary`. If I make `plenary` a startup plugin, Telescope loads without any issues.

```lua
    -- Telescope
    use {'nvim-lua/popup.nvim', cond = {nofirenvim}}
    use {'nvim-lua/plenary.nvim', cond = {nofirenvim}}
    use {'nvim-telescope/telescope.nvim',
         cond = {nofirenvim},
         config = [[require('main.plugin_config.telescope_config')]],
        }
```

**Comment by akinsho** [comment]
@medwatt I'm occupied atm but you can have a look at the `after` key for dependencies of `telescope`

**Comment by medwatt** [comment]
@akinsho, sorry for taking much of your time.

I think I've narrowed down the problem to the `config` option in the code below. If I remove that field, I get no error. The config file that is loaded contains just `require("telescope").setup{}`. I guess this brings us back to my original question, which is how do I apply the configuration file for a plugin that is optional.

```lua
-- Telescope
use {'nvim-lua/popup.nvim', cond = {nofirenvim}}
use {'nvim-lua/plenary.nvim', cond = {nofirenvim}}
use {'nvim-telescope/telescope.nvim', after = 'plenary.nvim',
    cond = {nofirenvim},
    config = [[require('main.plugin_config.telescope_config')]]}
```

**Comment by akinsho** [comment]
@medwatt what sort of error are you seeing I have loads of optional plugins in my config using a config key but this doesn't result in any errors. Can you post the error messages you are seeing?

**Comment by medwatt** [comment]
@akinsho, with the setup below

```lua
use {'nvim-lua/popup.nvim', cond = {nofirenvim}}
use {'nvim-lua/plenary.nvim', cond = {nofirenvim}}
use {'nvim-telescope/telescope.nvim',
    after = 'plenary.nvim', cond = {nofirenvim},
    config = [[require('main.plugin_config.telescope_config')]]}

```

where the `telescope_config.lua` file contains only `require('telescope').setup {}`. Initially, this file contained my own specific config, but even with just this line, I still get the error.

When I run `PackerCompile`, I get this error: [image](https://i.imgur.com/kttOsbs.png)

When I open neovim, I get this error: [image](https://i.imgur.com/MBpRtWr.png)

**Comment by akinsho** [comment]
@medwatt it seems something in your config is incorrect so packer cant run compile so you are still likely using an outdated compiled file. Can you try converting your config to a function and doing the require in there. I don't use the string syntax personally so I'm not sure about it's behaviour e.g.
```lua
use {'nvim-telescope/telescope.nvim',
    after = 'plenary.nvim', cond = {nofirenvim},
    config = function()
      require("telescope").setup()
    end
}
```
This isn't really likely to help so as a short term solution as I don't have anymore time this evening
you can also add `vim.cmd('packadd plenary.nvim')` before you require telescope e.g.

```lua
    config = function()
      vim.cmd('packadd plenary.nvim') -- <--- this line
      require("telescope").setup()
    end
```

None of this should be necessary but somewhere in your config you must be still loading something somewhere that is stopping it from compiling

**Comment by wbthomason** [comment]
This looks like another instance of confusion around the semantics of `after`, which is probably the longest-running issue for `packer`.  @medwatt the issues with compilation aside, using `after = 'plenary.nvim'` means that `telescope` will be loaded after `plenary` is loaded for some other reason. You probably want `wants = 'plenary.nvim'`
...which I now realize was never documented.

Sorry for the confusion, and please let me know if you continue to have trouble!
