### ISSUE TITLE
Add results window keybinding to toggle all details

### ISSUE THREAD

**Issue by wbthomason** [wbthomason/packer.nvim#36]
Per https://github.com/wbthomason/packer.nvim/issues/33#issuecomment-675004825

**Comment by wbthomason** [comment]
@clason: Does b4a01a7 do what you wanted in the linked comment? It's not *exactly* the same (i.e. it just automatically displays the info if you have the relevant config option set, and there's currently no "toggle all" keybinding), but it does provide an easy way to just see all update info without manually toggling each plugin.

**Comment by clason** [comment]
@wbthomason I think that'll do fine :) Thanks! (Of course, I'll have to wait for the _next_ update to really test it...)

**Comment by wbthomason** [comment]
Great, thanks! And yeah, I had to do a bunch of manual "downgrades" to test during development...
