### ISSUE TITLE
Package installation fails on slower connections

### ISSUE THREAD

**Issue by pard68** [wbthomason/packer.nvim#365]
- `nvim --version`: NVIM v0.5.0-dev+1339-g5d9c56012
- `git --version`: 2.31.1
- Operating system/version: Arch Linux
- Terminal name/version: st 0.8.2

### Steps to reproduce
Step 1. Have slow internet (I have 15Mbps down max, generally in the 7ish range
Step 2. Attempt to install more than one or two larger packages at a time

### Actual behaviour
Packages fail to finish installing. There is no timeout on the network, packer just gives up and calls it a failed installation

### Expected behaviour
Packages would download _slowly_ and be installed as they become available

**Comment by pard68** [comment]
Update, I was able to install one or two troublesome packages by commenting out all but one package at a time and installing it that way. Didn't work for all of them though.

Knowing this could be a failure on git's side I've gone ahead and cloned into the failing packages with git. ie 
`cd ~/.local/share/nvim/sites/pack/packer/opt && git clone https://github.com/foo/bar.nvim`

While indeed _slow_, this has worked for every package Packer has had an issue with. This leads me to believe it isn't a failing on git's part, for some reason Packer is closing the connection before git does.

**Comment by wbthomason** [comment]
Yep - please see the `config.git.clone_timeout` setting (https://github.com/wbthomason/packer.nvim#custom-initialization)

On slow connections, you probably want a higher value for this.
