### ISSUE TITLE
[Question] Should packer use a specify dir for packer_compiled.vim instead of plugin?

### ISSUE THREAD

**Issue by kevinhwang91** [wbthomason/packer.nvim#366]
Most users migrate from `vim-plug` which creates a plugged dir and source the script within user `init.vim`. This make `nvim -u mini.vim` skip to load the plugins managed by `vim-plug`. But `packer_compiled.vim` produced by packer can't skip. User must use `nvim -u mini.vim --noplugin` to reproduce the issue for the plugin maintainer in Github. 

We know the compiled file can be specified by users, but most of the users don't want to RTFM. This will make the plugin authors so tired to explain to their users.

**Comment by akinsho** [comment]
@kevinhwang91 I think this is similar to but not quite a duplicate of #201 and I think the general plan is to move away from this pattern when there is time/ a plan to migrate user's already compiled files so it doesn't suddenly break.

Also regarding loading during the init.vim/lua there are so many issues on this topic or that touch on this topic I think but TLDR is @wbthomason is planning a refactor that will also include doing this when he has time.

FWIW I completely agree with the idea I've hit the debugging issue in particular a zillion times.

**Comment by kevinhwang91** [comment]
Thanks for explaination.

**Comment by wbthomason** [comment]
@akinsho is (as usual) fully right, and the debugging issue you mention @kevinhwang91 is a big one.

The plan (for which I absolutely welcome PRs to accelerate) is:
1. Merge #331 to make `require`ing `packer` not so expensive
2. Add logic to detect if the compiled file is out of date (this will ideally be an efficient hash on the full set of specified plugins, but I need to figure out how that can be implemented)
3. Add `packer.load`, which recompiles if necessary and sources the compiled file, which will now live in `~/.cache/nvim/packer` by default
4. Make `packer.startup` call `packer.load`
5. Add temporary migration logic to (except under some conditions, like a customized `packer_compiled` path) move people's existing `packer_compiled` files. This will fix things up for people using the `startup` method, but we'll need a notice or something to get people using alternative methods to manually migrate.

**Comment by wbthomason** [comment]
To add: this will enable things like using Lua modules, packages, etc. in `init.lua/vim`, and hopefully also remove the closures restriction on `setup/config` etc. (I want to move away from `loadstring`).
