### ISSUE TITLE
Packer stops to load plugins on vim.api.nvim_err_write

### ISSUE THREAD

**Issue by kuznetsss** [wbthomason/packer.nvim#372]
Hello! Thank you for the plugin it's really usefull!

Calling `vim.api.nvim_err_write()` in precompiled plugin loader causes stop loading all my plugins. Is this behavior desired?
In case it is desired, could it be configurable?

**Comment by wbthomason** [comment]
Thanks for your report! Do you mind resubmitting this issue as a bug report, with the associated information requested in the issue template? This sounds more like a problem than something you'd like added to `packer`, and that information will be necessary to debug.

**Comment by kuznetsss** [comment]
Wow, thank you for such quick reply, I'll open issue.

**Comment by wbthomason** [comment]
Thanks!

**Comment by kuznetsss** [comment]
I haven't opened the issue yet because I can't reproduce it with some simple config. It happens only with my full config and only with nvim-treesitter. So I need some time to find a good example reproducing the issue.

**Comment by wbthomason** [comment]
I appreciate it, but also feel free to open an issue with your full config if you cannot find a minimal reproducer.

**Comment by kuznetsss** [comment]
Finaly, I've opened related issue #387. Sorry for delay.
