### ISSUE TITLE
Bootstrap example load packer as a `start` plugin but README still says it's `opt`

### ISSUE THREAD

**Issue by Akeboshiwind** [wbthomason/packer.nvim#394]
- `nvim --version`: N/A
- `git --version`: N/A
- Operating system/version: N/A
- Terminal name/version: N/A

### Steps to reproduce

Here in the [bootstrapping](https://github.com/wbthomason/packer.nvim/blob/master/README.md#bootstrapping) section:
The example uses `/site/pack/packer/start/packer.nvim`, but the text says `Note that this will install packer as an opt plugin`

This was introduced in 5da511660732e8fb8c98715ff5ea6dcbf53de102

### Actual behaviour

The text is contradictory

### Expected behaviour

It's at least not contradictory.

Imo it should should stay as `opt` seeing as there's the `execute 'packadd packer.nvim'` line in the if clause.

Possibly a better change might be to put a section like this below?
```diff
diff --git a/README.md b/README.md
index 3970b9c..706e89f 100644
--- a/README.md
+++ b/README.md
@@ -197,7 +197,7 @@ configuration to, add the following snippet (which is due to @Iron-E) somewhere
 local execute = vim.api.nvim_command
 local fn = vim.fn
 
-local install_path = fn.stdpath('data')..'/site/pack/packer/start/packer.nvim'
+local install_path = fn.stdpath('data')..'/site/pack/packer/opt/packer.nvim'
 
 if fn.empty(fn.glob(install_path)) > 0 then
   fn.system({'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path})
@@ -205,8 +205,18 @@ if fn.empty(fn.glob(install_path)) > 0 then
 end
 `` `
 
-Note that this will install `packer` as an `opt` plugin; if you want `packer` to be a `start`
-plugin, you must modify the value of `install_path` in the above snippet.
+Note that this will install `packer` as an `opt` plugin, to configure it correctly use the following
+in your `startup` function:
+```lua
+  use {
+    'wbthomason/packer.nvim',
+    cmd = { 'PackerCompile', 'PackerInstall', 'PackerUpdate', 'PackerClean', 'PackerSync', 'PackerLoad' }
+  }
+```
+
+Or you can install `packer` as a `start` plugin. To do so you must modify the value of `install_path`
+in the above snippet like so:
+```lua
+local install_path = fn.stdpath('data')..'/site/pack/packer/start/packer.nvim'
+```

Note: I haven't tested the above 

 ## Usage
 

```

### packer files

<details>
<summary>Plugin specification file(s)</summary>

N/A

</details>

<details>
<summary>packer log file</summary>

N/A

</details>

<details>
<summary>packer compiled file</summary>

N/A

</details>

**Comment by mxdevmanuel** [comment]
got the same error a momento ago, I updated neovim to latest commit and it was fixed,  I got no more insight tho.

**Comment by wbthomason** [comment]
Whoops, thanks for catching this! I think I prefer standardizing on `start`. I believe (though I haven't tested this) that the `packadd` in the conditional is required regardless, as otherwise the newly-cloned `packer` plugin won't be in Neovim's Lua module search path, and so the `require` will fail? I'm not sure, though, and will remove the `packadd` if I turn out to be wrong about this.

**Comment by wbthomason** [comment]
9db3e41 partially addresses this - it leaves the `packadd` until I or someone else has been able to test whether it has any effect.

**Comment by Akeboshiwind** [comment]
Fair enough on the preference.

Looking closer you're right, the `packadd` would be necessary good catch 😁 (although I also haven't tested this yet :P)

I'm going to close this seeing as the original issue is solved 👍

**Comment by wbthomason** [comment]
Sounds good, thanks! Part of the preference is due to some planned changes to enable auto-recompilation, which need `packer` to be available in `init.lua`.
