### ISSUE TITLE
setup option is not loaded before  plugin ?

### ISSUE THREAD

**Issue by JoseConseco** [wbthomason/packer.nvim#395]
If I understand correctly setup option is for initializing settings before plugin is loaded.
In my case I  cant override theme colors using:

```lua
	use {'folke/tokyonight.nvim',
		setup=function() vim.g.tokyonight_colors = { hint = "orange", }  end}
```
The  `vim.g.tokyonight_colors` should be loaded before theme, but theme does not 'see' the color override.

#Actual Behavior 
Theme config  option `vim.g.tokyonight_colors`  is being ignored. Only reloading nvim  config makes the changes visible to theme.

#Expected Behavior
 Config option `vim.g.tokyonight_colors' should be loaded before theme, so that theme can 'see' it.

I use latest Packer, and neovim,  on manjaro.

**Comment by wbthomason** [comment]
Thanks for your report! Can you please post your `packer_compiled`?

**Comment by JoseConseco** [comment]
Ok my bad. I used 
`vim.cmd('colorscheme tokyonight')`
In  the  main vim config,  and it was causing theme to be loaded before the `setup` - thus theme did not 'see' the  setup options. Closing.
