### ISSUE TITLE
wrong github package name leads to UI freeze

### ISSUE THREAD

**Issue by bfredl** [wbthomason/packer.nvim#40]
I misspelled an `use 'githubuser/pakcage'` and the UI locks up with `Username for 'https://github.com':  1 / 5 plugins` message.
It should give an error message instead.

**Comment by wbthomason** [comment]
Thanks for the report! I'm having trouble reproducing this - would you mind telling me the specific typo you made? For instance, testing with
```lua
use 'junegunn/vim-peekabool'
```
fails to install as expected, without freezing the UI.

I'm wondering if your typo accidentally stumbled upon a private repo name, which could make Git prompt for authentication?

Regardless, I should add some timeout/job stopping logic for installs (though probably not build stages; plugins requiring compilation sometimes take a while to finish).

**Comment by wbthomason** [comment]
I'm wondering if this is related to #26 - I'm still not able to reproduce either issue, but I've pushed a timeout feature in fd3a94f which should hopefully help. Could you please give it a try and let me know if it resolves the issue?

I still need to add documentation for the associated new config option (`config.git.clone_timeout`), but the default timeout is 60s (taken from `plug.vim`'s default timeout value); you might want to set that to be shorter for testing.

**Comment by nanotee** [comment]
Leaving this here just in case it turns out to be useful: Git has a `GIT_TERMINAL_PROMPT` environment variable that deactivates the password prompt (which you probably don't want when using Git non-interactively)

https://serverfault.com/a/665959
