### ISSUE TITLE
Regex cmd for lazy loading

### ISSUE THREAD

**Issue by serhez** [wbthomason/packer.nvim#408]
Hello,

Could it be possible to have the _cmd_ argument to _use_ be a regex instead of a specific command? This would make a config much cleaner. Examples of plugins that would benefit from this are Telescope and DAP (DebugToggleBreakpoint, DebugContinue, DebugStepInto, DebugStepOver, DebugToggleRepl, DebugStart, etc.).

Thanks!

**Comment by wbthomason** [comment]
This would probably be possible using the `CmdUndefined` event. We'd need to store a list of patterns to match against and add a single autocmd on that event.

I'm not adding new features until after #402 is done, but I'd be happy to help guide a PR adding this; it shouldn't be too involved.

**Comment by tmccombs** [comment]
Even just having wildcards would be good enough for me. I'd be willing to make a PR if you point me in the right direction.

**Comment by wbthomason** [comment]
Sure. This would be a change primarily in `lua/packer/compile.lua` and `lua/packer/load.lua`. The gist of it is that you'd need to change the command lazy-loading - which currently generates "fake" commands in `compile.lua` and deletes these fake commands before sourcing the plugin being loaded and running the resulting "real" command in `load.lua` - to instead generate `CmdUndefined` autocommands with the patterns given in the `cmd` key, and invoke the `load` function in the same way as we currently do when those autocommands trigger.

The one downside to this approach is that we will lose command autocompletion (i.e. when you start typing the command and press `<tab>`) by switching to this approach (see `:h CmdUndefined`).

**Comment by wbthomason** [comment]
One benefit, however, is that we could work around issues like #442 and the issue @gegoune (if I recall correctly) encountered, where using a lazy-loaded command after recompiling breaks unexpectedly because running `packadd` again doesn't re-source runtime files. This isn't the only way to fix those issues, but it would be a pleasant side-effect.
