### ISSUE TITLE
Ability to lock plugins

### ISSUE THREAD

**Issue by clason** [wbthomason/packer.nvim#41]
It may be desirable to prevent a plugin from updating; for example, if it follows APIs from neovim HEAD too closely and one doesn't want or is not able to update neovim itself (immediately). This could be done via a new `lock` option that keeps a plugin installed and managed (in contrast to `disable`), but skips it when `sync()` is called.

**Comment by wbthomason** [comment]
I added this feature (though I still need to document it). @clason please let me know if this isn't what you wanted/if you run into issues!

You should see that plugins using the `lock` keyword in their specification are silently skipped during updates (but not installs!)

**Comment by clason** [comment]
Yes, that looks good, thanks!
