### ISSUE TITLE
Windows 10: Errors when running PackerSync

### ISSUE THREAD

**Issue by Nazeehe** [wbthomason/packer.nvim#412]
- `nvim --version`: NVIM v0.5.0-dev+1417-g6a77def1e
- `git --version`: git version 2.30.0.windows.1
- Operating system/version: Windows 10 21H1
- Terminal name/version: Windows Terminal Preview

Running PackerSync or Install and I sometimes will see:

[ERROR 6/17/2021 11:11:26 AM] ...\site\pack\packer\start\packer.nvim\lua\packer\async.lua:20: Error in coroutine: ...ack\packer\start\packer.nvim\lua\packer\plugin_utils.lua:169: Vim(source):E484: Can't open file C:Users

I added a log.info in the code to see what the "file" name actually is to see if it's coming in wrong, it's not:

[INFO  6/17/2021 11:11:26 AM] ...ack\packer\start\packer.nvim\lua\packer\plugin_utils.lua:168: file: C:\Users\nazee\AppData\Local\nvim-data\site\pack\packer\start\nvim-tree.lua\plugin\tree.vim

Any idea why the file name that's going in is being interpreted wrong by the vim.cmd statement:

            vim.cmd('silent exe "source ' .. file .. '"')

Thoughts?

**Comment by yhnu** [comment]
#418 https://github.com/wbthomason/packer.nvim/pull/419 can slove it

**Comment by wbthomason** [comment]
Presumed closed by #419.
