### ISSUE TITLE
[packer.nvim] [ERROR 08:52:09] async.lua:20: Error i...484: Can't open file C:UsersAdministratorAppDataLocal

### ISSUE THREAD

**Issue by yhnu** [wbthomason/packer.nvim#418]
- `nvim --version`:

NVIM v0.5.0-dev+1429-gb585f723b

- `git --version`:

git version 2.30.0.windows.2

- Operating system/version:

windows10

- Terminal name/version:

windows terminal

### Steps to reproduce
:PackerInstall

### Actual behaviour
[packer.nvim] [ERROR 08:52:09] async.lua:20: Error i...484: Can't open file C:UsersAdministratorAppDataLocal

### packer files

<details>
<summary>Plugin specification file(s)</summary>

Post or link your plugin specification files here, if you aren't able to provide a minimal
reproducer

</details>

<details>
<summary>packer log file</summary>

Post the contents of ~/.cache/nvim/packer.nvim.log here

</details>

<details>
<summary>packer compiled file</summary>

Post the contents of `packer_compiled.vim` here

</details>

**Comment by wbthomason** [comment]
Presumed closed by #419.
