### ISSUE TITLE
it hangs when misspel github package name

### ISSUE THREAD

**Issue by bfredl** [wbthomason/packer.nvim#42]
I did `use 'vim-cnof-live/pres.vim'` and it freezed up. I would expect no freeze and an async error message a few secs later when `git` gives up.

**Comment by wbthomason** [comment]
How long did you wait? Clones should time out after the value of `config.git.clone_timeout` (...which I now realize I never added to the docs, whoops), which defaults to 60s (based on the timeout value used in `plug.vim`). The freeze is bizarre, though - the entire editor froze up?

**Comment by wbthomason** [comment]
I also cannot reproduce this on my machines....exactly what you describe happens for me....

**Comment by bfredl** [comment]
ok, I will try again today..

**Comment by bfredl** [comment]
yes it hangs on `username for https://github.com/xx/yy` message (the entire neovim UI)

**Comment by bfredl** [comment]
it unhangs after 60s yes, but neovim should not freeze during this minute.

**Comment by wbthomason** [comment]
Agreed; I'll look into why it's freezing. Could you post your .gitconfig, since I can't seem to replicate the behavior on my system?

**Comment by wbthomason** [comment]
Hmm. I'm shooting in the dark with this theory as I still cannot reproduce the bug, but I wonder if this would be caused by not passing a `stdin` fd to the `luv.spawn` call used to start `git`? Since you mention that it hangs on a prompt for username...

**Comment by bfredl** [comment]
@wbthomason I would guess you have to override the stdin explicitly. We should make our `vim.loop` documentation clearer about this.

**Comment by wbthomason** [comment]
I pushed a commit just now adding this. It doesn't break anything on my end, but I have still never been able to repro the issue here (or in #40 or #26, which I think are duplicates of this), so I'm not sure if it fixes the issue.

**Comment by wbthomason** [comment]
Fixed by #91
