### ISSUE TITLE
config is never called

### ISSUE THREAD

**Issue by winston0410** [wbthomason/packer.nvim#424]
- `nvim --version`: 0.5.0
- `git --version`: 2.31.1
- Operating system/version: MacOS, BigSur11.2.3
- Terminal name/version: alacrity 0.8.0

### Steps to reproduce

An minimal example

```
vim.cmd [[ packadd packer.nvim ]]

return require'packer'.startup(function()
   use { 'wbthomason/packer.nvim', opt = true }
   use({"kyazdani42/nvim-web-devicons", config = function () 
        print('run')
    end})
end)
```
### Actual behaviour

I expected the 'run' to be printed, as based on the doc, `config` of a plugin declaration should be called after it is declared.

### Expected behaviour

Nothing get printed.

**Comment by ReneganRonin** [comment]
why is the next `use` enclosed with ()?

**Comment by akinsho** [comment]
Hi @winston0410, did you run packer compile and reload the module this is in or restart nvim? I just tried your example locally and that works for me.

**Comment by winston0410** [comment]
I thought `PackerCompile` is only for optimising performance, and yet after running it the config is running perfectly fine, thanks.

Btw, how can I make packer compile automatically after I have updated the config? Using auto command?

**Comment by akinsho** [comment]
@winston0410 there's currently a WIP change to have this work automatically over in #402, but in the short term I've been using 
```vim
au! BufWritePost */<plugins-dir>/*.lua lua require('packer').compile()
```
This will call compile whenever you save inside the directory containing your plugin configs. If you don't split them out, then change the command target as needed.

The compile command is currently mandatory btw not just an optimisation but has been a sticking point for *a lot* of people, so we're going to be working on making it automatic, so people don't have to think about it

**Comment by winston0410** [comment]
That autocommand is awesome, and thank you so much for your response and effort.

**Comment by wbthomason** [comment]
This seems fixed, so I'm going to close it. Feel free to re-open if I'm wrong.

If you'd like to track the discussion/progress on making recompilation automatic, take a look at #402.
