### ISSUE TITLE
Can't install plugins

### ISSUE THREAD

**Issue by TimUntersberger** [wbthomason/packer.nvim#43]
**init.vim**
```vimscript
packadd packer.nvim 

execute 'luafile ' . stdpath('config') . '/lua/plugins.lua'

command! PackerInstall lua require('plugins').install()
command! PackerUpdate lua require('plugins').update()
command! PackerSync lua require('plugins').sync()
command! PackerClean lua require('plugins').clean()
command! PackerCompile lua require('plugins').compile(
```

**lua/plugins.lua**
```lua
return require('packer').startup(function()
    use {'wbthomason/packer.nvim', opt = true}
    use 'morhetz/gruvbox'
end)
```

When I run `:PackerCompile` followed by `:PackerInstall` it fails to install both plugins.

I am using `NVIM v0.5.0-659-g7b1b271f4` on `Windows 10`.

Can I somehow provide you with some logs?

**Comment by wbthomason** [comment]
Fascinating. Do you have `packer` cloned to somewhere on your `packpath`? What does happen when you run those commands?

**Comment by TimUntersberger** [comment]
I tried to see what happens exactly when i run `:PackerInstall`, but going from running the command to failed installation is so fast that I can't really see what is happening. I do notice that it is cloning the repo. 

I cloned `packer` into `%LOCALAPPDATA%\nvim-data\site\pack\packer\opt\packer.nvim`.

After looking through the folders I found that `packer` is now downloaded twice (even though one created by `packer` is empty).

![image](https://user-images.githubusercontent.com/32014449/92320112-475ab200-f01f-11ea-8550-44f7cbd66227.png)

Nothing besides my manually created folders exist in `%LOCALAPPDATA%\nvim-data\site\pack`.

In `C:\Users\timun\AppData\Local\nvim-data\site\pack\packer\start` a folder called `morhetz` (for gruvbox) does exist, but it is also empty.

My assumption is that something goes wrong when `packer` tries to clone the repos. This is 90% a configuration error on my part, but because I don't know how I can see logs or errors I can't really debug this on my own.

**Comment by TimUntersberger** [comment]
Another thing I don't really understand is, why do you need to do

```lua
execute 'luafile ' . stdpath('config') . '/lua/plugins.lua'
```

and not just

```lua
require('plugins')
```

**Comment by TimUntersberger** [comment]
I think I found the problem.

![image](https://user-images.githubusercontent.com/32014449/92321340-6fe7a980-f029-11ea-8a64-30791979ee9c.png)

As you can see `packer` assumes the url is `https://github.com/morhetz\\gruvbox`.

**Comment by TimUntersberger** [comment]
I fixed it by changing `plugin_utils.lua`. I can open a PR later today.

Also can you update the README?

Running 

```bash
git clone https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/opt/packer.nvim
```

when you also let packer manage itself results in packer being cloned twice. Once manually and once automatically.

If you change the recommended way to 

```bash
git clone https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/opt/wbthomason/packer.nvim
```

`packer` wouldn't have to reclone itself right?

**Comment by TimUntersberger** [comment]
After trying to rewrite my config using `packer` I noticed that nothing really works for me on Windows.

**Comment by wbthomason** [comment]
> After trying to rewrite my config using `packer` I noticed that nothing really works for me on Windows.

Sorry about that; I don't have a Windows machine, so I haven't been able to test much of anything on Windows. If you're willing to make issues for the problems you've observed, that would be great, but no worries if it's too much of a hassle.

Thanks for your PR with the URL fix; I'll merge that as soon as I'm back at my computer later today.

Your README comment is indicative of a different bug that I haven't experienced on Linux - the username for a GitHub plugin is typically not part of its install path. I suspect this is probably again to do with the difference in path separators, or perhaps with a difference in git behavior on Windows (when you manually clone a repo, does it get put in a directory of the form "username\reponame", or just "reponame"?)

And yes, logs would make this easier to debug. I'll add some basic logging functionality later today or tomorrow.

Thanks for the reports, and sorry for the hassle! You are getting the dubious honor of being the first Windows tester for this...

**Comment by TimUntersberger** [comment]
> If you're willing to make issues for the problems you've observed, that would be great, but no worries if it's too much of a hassle.

I was thinking about just fixing all of the issues I am encountering in my PR. 

> Sorry about that; I don't have a Windows machine, so I haven't been able to test much of anything on Windows.

No worries.

> perhaps with a difference in git behavior on Windows (when you manually clone a repo, does it get put in a directory of the form "username\reponame", or just "reponame"?)

It is the same as on linux.

**Comment by TimUntersberger** [comment]
I am going to list the problems I found while fixing the problems here.

**Note**: I will be updating this comment as I fix more things.

### `vim.fn.expand` is not pure

In the manage function of `packer.lua` you assumed that the `<username>/<repo>` doesn't get modified, so you only split with `/`. This won't work because `vim.fn.expand` modifies the given string.

**Comment by wbthomason** [comment]
Thank you! Taking a look now.
