### ISSUE TITLE
"Removing the following directories" when using PackerInstall or PackerSync (gruvbox)

### ISSUE THREAD

**Issue by bamboozila** [wbthomason/packer.nvim#431]
- `nvim --version`:
- `git --version`: v0.5.0-dev+1430-g9a39a1180
- Operating system/version: Mac OS Big Sur
- Terminal name/version: Kitty 0.21.1

### Steps to reproduce
Install `/jared-mackey/gruvbox.nvim`

Please note that I use other plugins, I stripped my configuration to the minimum for the repro.

### Actual behaviour
Calling `:PackerInstall` or `:PackerSync` asks to remove gruvbox prior to installing it (even if it's already installed)

### Expected behaviour
It should not install gruvbox it it's already there and not uninstall it before doing so.

### packer files

<details>
<summary>Plugin specification file(s)</summary>

return require('packer').startup(function()
  use 'wbthomason/packer.nvim'
  use {"/jared-mackey/gruvbox.nvim", requires = {"rktjmp/lush.nvim"}}
end)

</details>

<details>
<summary>packer log file</summary>

Post the contents of ~/.cache/nvim/packer.nvim.log here

</details>

<details>
<summary>packer compiled file</summary>
" Automatically generated packer.nvim plugin loader code

if !has('nvim-0.5')
  echohl WarningMsg
  echom "Invalid Neovim version for packer.nvim!"
  echohl None
  finish
endif

packadd packer.nvim

try

lua << END
  local time
  local profile_info
  local should_profile = false
  if should_profile then
    local hrtime = vim.loop.hrtime
    profile_info = {}
    time = function(chunk, start)
      if start then
        profile_info[chunk] = hrtime()
      else
        profile_info[chunk] = (hrtime() - profile_info[chunk]) / 1e6
      end
    end
  else
    time = function(chunk, start) end
  end
  
local function save_profiles(threshold)
  local sorted_times = {}
  for chunk_name, time_taken in pairs(profile_info) do
    sorted_times[#sorted_times + 1] = {chunk_name, time_taken}
  end
  table.sort(sorted_times, function(a, b) return a[2] > b[2] end)
  local results = {}
  for i, elem in ipairs(sorted_times) do
    if not threshold or threshold and elem[2] > threshold then
      results[i] = elem[1] .. ' took ' .. elem[2] .. 'ms'
    end
  end

  _G._packer = _G._packer or {}
  _G._packer.profile_output = results
end

time([[Luarocks path setup]], true)
local package_path_str = "/Users/chell/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/?.lua;/Users/chell/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/?/init.lua;/Users/chell/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/?.lua;/Users/chell/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/?/init.lua"
local install_cpath_pattern = "/Users/chell/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/?.so"
if not string.find(package.path, package_path_str, 1, true) then
  package.path = package.path .. ';' .. package_path_str
end

if not string.find(package.cpath, install_cpath_pattern, 1, true) then
  package.cpath = package.cpath .. ';' .. install_cpath_pattern
end

time([[Luarocks path setup]], false)
time([[try_loadstring definition]], true)
local function try_loadstring(s, component, name)
  local success, result = pcall(loadstring(s))
  if not success then
    vim.schedule(function()
      vim.api.nvim_notify('packer.nvim: Error running ' .. component .. ' for ' .. name .. ': ' .. result, vim.log.levels.ERROR, {})
    end)
  end
  return result
end

time([[try_loadstring definition]], false)
time([[Defining packer_plugins]], true)
_G.packer_plugins = {
  ["gruvbox.nvim"] = {
    loaded = true,
    path = "/Users/chell/.local/share/nvim/site/pack/packer/start/gruvbox.nvim"
  },
  ["lush.nvim"] = {
    loaded = true,
    path = "/Users/chell/.local/share/nvim/site/pack/packer/start/lush.nvim"
  },
  ["packer.nvim"] = {
    loaded = true,
    path = "/Users/chell/.local/share/nvim/site/pack/packer/start/packer.nvim"
  }
}

time([[Defining packer_plugins]], false)
if should_profile then save_profiles() end

END

catch
  echohl ErrorMsg
  echom "Error in packer_compiled: " .. v:exception
  echom "Please check your config for correctness"
  echohl None
endtry

</details>

**Comment by akinsho** [comment]
Hi @bamboozila I'm not 100% of what's going on since this issue is a little light on details but one thing that I think could *maybe* be the cause is that you have a `/` at the beginning of you plugin name `/jared-mackey/gruvbox.nvim` when it should be `jared-mackey/gruvbox.nvim` similar to vim plug and other plugin managers. Not sure if that's definitely the issue but worth trying.

**Comment by bamboozila** [comment]
> Hi @bamboozila I'm not 100% of what's going on since this issue is a little light on details but one thing that I think could _maybe_ be the cause is that you have a `/` at the beginning of you plugin name `/jared-mackey/gruvbox.nvim` when it should be `jared-mackey/gruvbox.nvim` similar to vim plug and other plugin managers. Not sure if that's definitely the issue but worth trying.

This did the trick, thx!

Is it a wanted behavior though?

**Comment by akinsho** [comment]
@bamboozila the pattern for using `username/project` is *very common* I believe all (n)vim package managers do this, so I think it's fine to expect/require this behaviour especially since it doesn't make sense (IMO) for packer to try and guess if it should remove strings from the beginning or end of a plugin's name.
