### ISSUE TITLE
Question: How disable a plugin without removing it?

### ISSUE THREAD

**Issue by cjnucette** [wbthomason/packer.nvim#432]
You can do this in `vim-plug` by commenting the corresponding line, but with `packer` the plugin is always loaded because is in the `rtp`, which is not the case with vim-plug. I want to be able to disable some plugins to create a minimal `init.vim` without the need to run `:PackerClean`.

**Comment by akinsho** [comment]
@cjnucette you can prevent plugins from loading by making them `opt=true` this will move them out of the `start` directory where all plugins are loaded automatically. The difference between packer and vim-plug here is that packer uses vim's native `packages` feature which you can read more about under `:help packages` whilst plug doesn't. Packages do come with a few gotchas such as this for example though.


Alternatively, if this is something you might want to do a lot you can create a pattern for it, e.g.
```lua
-- outside of packer startup probably
local function minimal()
  return vim.env.MINIMAL == nil
end

packer.startup(function(use)
  use {"a/plugin", cond = minimal}
end)

```

When you start vim and want a minimal init you can run

```sh
MINIMAL=true nvim
```

**Comment by akinsho** [comment]
FWIW there's some discussion around making all plugin opt by default and packer loading them itself, which will make things like creating a minimal init.vim easier to do (see #50)

**Comment by cjnucette** [comment]
Thanks, I'll try this.

**Comment by akinsho** [comment]
I should also mention that after adding `opt=true` you need to run `PackerSync`

**Comment by wbthomason** [comment]
See #307 and #402 (discussion) as well.
