### ISSUE TITLE
config to specify the default URL format.

### ISSUE THREAD

**Issue by jdhao** [wbthomason/packer.nvim#433]
### Describe the feature

In vim-plug, there is this nice little config [`g:plug_url_format`](https://github.com/junegunn/vim-plug/blob/master/plug.vim#L776) so that users can specify the URL template used for cloning the repository. Due to certain reasons, I have to set `g:plug_url_format` to `'https://hub.fastgit.org/%s.git'`, which is faster than github.

It would be nice to have such a feature in packer so that when user use `aaa/bbb`, we would clone from `https://hub.fastgit.org/aaa/bbb.git`.

**Comment by wbthomason** [comment]
That's an interesting idea, thanks. I wasn't aware of that `vim-plug` feature. This should be quite easy to add.
