### ISSUE TITLE
loadstring in packer_compiled.lua throw error when using different lua version

### ISSUE THREAD

**Issue by kevinhwang91** [wbthomason/packer.nvim#436]
- `nvim --version`: 0.5 and v0.6.0-dev+1476-g62d67de59
- `git --version`: 2.32.0
- Operating system/version: ArchLinux
- Terminal name/version: alacritty

### Steps to reproduce
1. config `setup` with function like `use {'wbthomason/packer.nvim', setup = function() end}`
2. use 0.6 version to generate compiled.lua
3. open nvim with 0.5 version

### Actual behaviour
`packer.nvim: Error running setup for packer.nvim: attempt to call a nil value`

### Expected behaviour
keep silent event use luarocks.

### context

Here're snippets generated by compiled.lua
By LuaJIT 2.0.5 -- NVIM v0.5.0:
`try_loadstring("\27LJ\1\2\v\0\0\1\0\0\0\1G\0\1\0\0", "setup", "packer.nvim")`

By LuaJIT 2.1.0-beta3 --- NVIM v0.6.0-dev+1476-g62d67de59:
`try_loadstring("\27LJ\2\n\v\0\0\1\0\0\0\1K\0\1\0\0", "setup", "packer.nvim")`

**Comment by clason** [comment]
Yes, there is no stability between LuaJIT versions (or even commits). Do not use LuaJIT 2.0.5, neovim expects 2.1.0-beta3 (in fact, a specific commit), or the May release from openresty/luajit2 (which is functionally mostly identical).

**Comment by clason** [comment]
To be clear, the "error" here is that your 0.5 release was built against LuaJIT 2.0.5 for some reason -- this is wrong.

**Comment by kevinhwang91** [comment]
0.5 built by `Arch Build System`. I can confirm lua version of 0.5 downloaded by `https://github.com/neovim/neovim/releases/tag/v0.5.0`  and build 0.5 by myself are both ` LuaJIT 2.1.0-beta3`
