### ISSUE TITLE
`compile_path` only load compiled file from nvim/plugin/packer_compiled

### ISSUE THREAD

**Issue by babygau** [wbthomason/packer.nvim#437]
- `nvim --version`: 0.5 nightly
- `git --version`: 2.32.0
- Operating system/version: macOS Big Sur
- Terminal name/version: iTerm 3.4.9

### Steps to reproduce
```lua
return packer.startup {
  function(use)
  -- plugins...
  end,
  config = {
    compile_path = data_dir .. '/lua/packer_compiled.lua'
  }
}
```
### Actual behaviour

`packer` doesn't load compiled file from custom path, only load from `vim.fn.stdpath 'config' .. '/plugin/packer_compiled.lua'`

### Expected behaviour

`packer` should load `packer_compiled.lua` from custom path

### packer files

<details>
<summary>Plugin specification file(s)</summary>

Post or link your plugin specification files here, if you aren't able to provide a minimal
reproducer

</details>

<details>
<summary>packer log file</summary>

[INFO  Sat  3 Jul 20:35:07 2021] ...im/site/pack/packer/opt/packer.nvim/lua/packer/clean.lua:79: Already clean!
[DEBUG Sat  3 Jul 20:35:08 2021] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:23: Installed rhysd/accelerated-jk
[DEBUG Sat  3 Jul 20:35:08 2021] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:23: Installed folke/which-key.nvim
[DEBUG Sat  3 Jul 20:35:08 2021] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:23: Installed nvim-lua/popup.nvim
[DEBUG Sat  3 Jul 20:35:08 2021] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:23: Installed jose-elias-alvarez/nvim-lsp-ts-utils
[DEBUG Sat  3 Jul 20:35:09 2021] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:23: Installed tpope/vim-eunuch
[DEBUG Sat  3 Jul 20:35:09 2021] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:23: Installed nvim-treesitter/nvim-treesitter-textobjects
[DEBUG Sat  3 Jul 20:35:09 2021] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:23: Installed lukas-reineke/indent-blankline.nvim/lua
[DEBUG Sat  3 Jul 20:35:09 2021] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:23: Installed neovim/nvim-lspconfig
[DEBUG Sat  3 Jul 20:35:09 2021] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:23: Installed marklcrns/vim-smartq
[DEBUG Sat  3 Jul 20:35:09 2021] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:23: Installed nvim-telescope/telescope.nvim
[DEBUG Sat  3 Jul 20:35:09 2021] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:23: Installed windwp/nvim-ts-autotag
[DEBUG Sat  3 Jul 20:35:09 2021] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:23: Installed hrsh7th/vim-vsnip
[DEBUG Sat  3 Jul 20:35:09 2021] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:23: Installed norcalli/nvim-colorizer.lua
[DEBUG Sat  3 Jul 20:35:09 2021] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:23: Installed windwp/nvim-autopairs
[DEBUG Sat  3 Jul 20:35:09 2021] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:23: Installed jose-elias-alvarez/null-ls.nvim
[DEBUG Sat  3 Jul 20:35:09 2021] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:23: Installed lewis6991/gitsigns.nvim
[DEBUG Sat  3 Jul 20:35:09 2021] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:23: Installed kyazdani42/nvim-web-devicons
[DEBUG Sat  3 Jul 20:35:09 2021] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:23: Installed tpope/vim-repeat
[DEBUG Sat  3 Jul 20:35:09 2021] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:23: Installed hoob3rt/lualine.nvim
[DEBUG Sat  3 Jul 20:35:09 2021] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:23: Installed karb94/neoscroll.nvim
[DEBUG Sat  3 Jul 20:35:09 2021] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:23: Installed sainnhe/gruvbox-material
[DEBUG Sat  3 Jul 20:35:09 2021] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:23: Installed b3nj5m1n/kommentary
[DEBUG Sat  3 Jul 20:35:09 2021] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:23: Installed hrsh7th/nvim-compe
[DEBUG Sat  3 Jul 20:35:09 2021] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:23: Installed folke/tokyonight.nvim
[DEBUG Sat  3 Jul 20:35:10 2021] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:23: Installed junegunn/vim-easy-align
[DEBUG Sat  3 Jul 20:35:10 2021] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:23: Installed folke/lua-dev.nvim
[DEBUG Sat  3 Jul 20:35:10 2021] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:23: Installed folke/trouble.nvim
[DEBUG Sat  3 Jul 20:35:10 2021] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:23: Installed nvim-telescope/telescope-fzf-native.nvim
[DEBUG Sat  3 Jul 20:35:10 2021] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:23: Installed nvim-treesitter/nvim-treesitter
[DEBUG Sat  3 Jul 20:35:10 2021] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:23: Installed akinsho/nvim-toggleterm.lua
[DEBUG Sat  3 Jul 20:35:11 2021] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:23: Installed mattn/emmet-vim
[DEBUG Sat  3 Jul 20:35:12 2021] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:23: Installed editorconfig/editorconfig-vim
[DEBUG Sat  3 Jul 20:35:12 2021] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:23: Installed romainl/vim-qf
[DEBUG Sat  3 Jul 20:35:12 2021] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:23: Installed akinsho/nvim-bufferline.lua
[DEBUG Sat  3 Jul 20:35:12 2021] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:23: Installed iamcco/markdown-preview.nvim
[DEBUG Sat  3 Jul 20:35:13 2021] .../site/pack/packer/opt/packer.nvim/lua/packer/install.lua:23: Installed nvim-lua/plenary.nvim
[INFO  Sat  3 Jul 20:35:13 2021] .../pack/packer/opt/packer.nvim/lua/packer/plugin_utils.lua:84: Updating helptags for /Users/babygau/.local/share/nvim/site/pack/packer/opt/nvim-lspconfig/doc
[INFO  Sat  3 Jul 20:35:13 2021] .../pack/packer/opt/packer.nvim/lua/packer/plugin_utils.lua:84: Updating helptags for /Users/babygau/.local/share/nvim/site/pack/packer/opt/vim-eunuch/doc
[INFO  Sat  3 Jul 20:35:13 2021] .../pack/packer/opt/packer.nvim/lua/packer/plugin_utils.lua:84: Updating helptags for /Users/babygau/.local/share/nvim/site/pack/packer/start/vim-easy-align/doc
[INFO  Sat  3 Jul 20:35:13 2021] .../pack/packer/opt/packer.nvim/lua/packer/plugin_utils.lua:84: Updating helptags for /Users/babygau/.local/share/nvim/site/pack/packer/start/nvim-compe/doc
[INFO  Sat  3 Jul 20:35:13 2021] .../pack/packer/opt/packer.nvim/lua/packer/plugin_utils.lua:84: Updating helptags for /Users/babygau/.local/share/nvim/site/pack/packer/start/vim-vsnip/doc
[INFO  Sat  3 Jul 20:35:13 2021] .../pack/packer/opt/packer.nvim/lua/packer/plugin_utils.lua:84: Updating helptags for /Users/babygau/.local/share/nvim/site/pack/packer/start/gruvbox-material/doc
[INFO  Sat  3 Jul 20:35:13 2021] .../pack/packer/opt/packer.nvim/lua/packer/plugin_utils.lua:84: Updating helptags for /Users/babygau/.local/share/nvim/site/pack/packer/opt/telescope.nvim/doc
[INFO  Sat  3 Jul 20:35:13 2021] .../pack/packer/opt/packer.nvim/lua/packer/plugin_utils.lua:84: Updating helptags for /Users/babygau/.local/share/nvim/site/pack/packer/opt/emmet-vim/doc
[INFO  Sat  3 Jul 20:35:13 2021] .../pack/packer/opt/packer.nvim/lua/packer/plugin_utils.lua:84: Updating helptags for /Users/babygau/.local/share/nvim/site/pack/packer/start/nvim-bufferline.lua/doc
[INFO  Sat  3 Jul 20:35:13 2021] .../pack/packer/opt/packer.nvim/lua/packer/plugin_utils.lua:84: Updating helptags for /Users/babygau/.local/share/nvim/site/pack/packer/opt/nvim-treesitter/doc
[INFO  Sat  3 Jul 20:35:13 2021] .../pack/packer/opt/packer.nvim/lua/packer/plugin_utils.lua:84: Updating helptags for /Users/babygau/.local/share/nvim/site/pack/packer/opt/nvim-treesitter-textobjects/doc
[INFO  Sat  3 Jul 20:35:13 2021] .../pack/packer/opt/packer.nvim/lua/packer/plugin_utils.lua:84: Updating helptags for /Users/babygau/.local/share/nvim/site/pack/packer/opt/editorconfig-vim/doc
[INFO  Sat  3 Jul 20:35:13 2021] .../pack/packer/opt/packer.nvim/lua/packer/plugin_utils.lua:84: Updating helptags for /Users/babygau/.local/share/nvim/site/pack/packer/opt/indent-blankline.nvim/doc
[INFO  Sat  3 Jul 20:35:13 2021] .../pack/packer/opt/packer.nvim/lua/packer/plugin_utils.lua:84: Updating helptags for /Users/babygau/.local/share/nvim/site/pack/packer/opt/gitsigns.nvim/doc
[INFO  Sat  3 Jul 20:35:13 2021] .../pack/packer/opt/packer.nvim/lua/packer/plugin_utils.lua:84: Updating helptags for /Users/babygau/.local/share/nvim/site/pack/packer/start/neoscroll.nvim/doc
[INFO  Sat  3 Jul 20:35:13 2021] .../pack/packer/opt/packer.nvim/lua/packer/plugin_utils.lua:84: Updating helptags for /Users/babygau/.local/share/nvim/site/pack/packer/opt/accelerated-jk/doc
[INFO  Sat  3 Jul 20:35:13 2021] .../pack/packer/opt/packer.nvim/lua/packer/plugin_utils.lua:84: Updating helptags for /Users/babygau/.local/share/nvim/site/pack/packer/opt/nvim-colorizer.lua/doc
[INFO  Sat  3 Jul 20:35:13 2021] .../pack/packer/opt/packer.nvim/lua/packer/plugin_utils.lua:84: Updating helptags for /Users/babygau/.local/share/nvim/site/pack/packer/start/lualine.nvim/doc

</details>

<details>
<summary>packer compiled file</summary>

-- Automatically generated packer.nvim plugin loader code

if vim.api.nvim_call_function('has', {'nvim-0.5'}) ~= 1 then
  vim.api.nvim_command('echohl WarningMsg | echom "Invalid Neovim version for packer.nvim! | echohl None"')
  return
end

vim.api.nvim_command('packadd packer.nvim')

local no_errors = pcall(function()

  local time
  local profile_info
  local should_profile = true
  if should_profile then
    local hrtime = vim.loop.hrtime
    profile_info = {}
    time = function(chunk, start)
      if start then
        profile_info[chunk] = hrtime()
      else
        profile_info[chunk] = (hrtime() - profile_info[chunk]) / 1e6
      end
    end
  else
    time = function(chunk, start) end
  end
  
local function save_profiles(threshold)
  local sorted_times = {}
  for chunk_name, time_taken in pairs(profile_info) do
    sorted_times[#sorted_times + 1] = {chunk_name, time_taken}
  end
  table.sort(sorted_times, function(a, b) return a[2] > b[2] end)
  local results = {}
  for i, elem in ipairs(sorted_times) do
    if not threshold or threshold and elem[2] > threshold then
      results[i] = elem[1] .. ' took ' .. elem[2] .. 'ms'
    end
  end

  _G._packer = _G._packer or {}
  _G._packer.profile_output = results
end

time([[Luarocks path setup]], true)
local package_path_str = "/Users/babygau/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/?.lua;/Users/babygau/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/?/init.lua;/Users/babygau/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/?.lua;/Users/babygau/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/?/init.lua"
local install_cpath_pattern = "/Users/babygau/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/?.so"
if not string.find(package.path, package_path_str, 1, true) then
  package.path = package.path .. ';' .. package_path_str
end

if not string.find(package.cpath, install_cpath_pattern, 1, true) then
  package.cpath = package.cpath .. ';' .. install_cpath_pattern
end

time([[Luarocks path setup]], false)
time([[try_loadstring definition]], true)
local function try_loadstring(s, component, name)
  local success, result = pcall(loadstring(s))
  if not success then
    vim.schedule(function()
      vim.api.nvim_notify('packer.nvim: Error running ' .. component .. ' for ' .. name .. ': ' .. result, vim.log.levels.ERROR, {})
    end)
  end
  return result
end

time([[try_loadstring definition]], false)
time([[Defining packer_plugins]], true)
_G.packer_plugins = {
  ["accelerated-jk"] = {
    config = { "\27LJ\2\nÂ\1\0\0\a\0\n\0\0176\0\0\0'\2\1\0B\0\2\0029\0\2\0\18\1\0\0'\3\3\0'\4\4\0'\5\5\0005\6\6\0B\1\5\1\18\1\0\0'\3\3\0'\4\a\0'\5\b\0005\6\t\0B\1\5\1K\0\1\0\1\0\2\texpr\2\fnoremap\1\31v:lua.enhance_jk_move(\"k\")\6k\1\0\2\texpr\2\fnoremap\1\31v:lua.enhance_jk_move(\"j\")\6j\6n\bmap\15core.utils\frequire\0" },
    loaded = false,
    needs_bufread = false,
    path = "/Users/babygau/.local/share/nvim/site/pack/packer/opt/accelerated-jk"
  },
  ["editorconfig-vim"] = {
    loaded = false,
    needs_bufread = false,
    path = "/Users/babygau/.local/share/nvim/site/pack/packer/opt/editorconfig-vim"
  },
  ["emmet-vim"] = {
    loaded = false,
    needs_bufread = false,
    path = "/Users/babygau/.local/share/nvim/site/pack/packer/opt/emmet-vim"
  },
  ["gitsigns.nvim"] = {
    loaded = false,
    needs_bufread = false,
    path = "/Users/babygau/.local/share/nvim/site/pack/packer/opt/gitsigns.nvim"
  },
  ["gruvbox-material"] = {
    config = { "\27LJ\2\nØ\1\0\0\2\0\t\0\0176\0\0\0009\0\1\0'\1\3\0=\1\2\0006\0\0\0009\0\4\0)\1\1\0=\1\5\0006\0\0\0009\0\4\0'\1\a\0=\1\6\0006\0\0\0009\0\4\0)\1\1\0=\1\b\0K\0\1\0(gruvbox_material_better_performance\fcolored-gruvbox_material_diagnostic_virtual_text#gruvbox_material_enable_italic\6g\nlight\15background\6o\bvim\0" },
    loaded = true,
    path = "/Users/babygau/.local/share/nvim/site/pack/packer/start/gruvbox-material"
  },
  ["indent-blankline.nvim"] = {
    loaded = false,
    needs_bufread = false,
    path = "/Users/babygau/.local/share/nvim/site/pack/packer/opt/indent-blankline.nvim"
  },
  kommentary = {
    loaded = true,
    path = "/Users/babygau/.local/share/nvim/site/pack/packer/start/kommentary"
  },
  ["lua-dev.nvim"] = {
    loaded = true,
    path = "/Users/babygau/.local/share/nvim/site/pack/packer/start/lua-dev.nvim"
  },
  ["lualine.nvim"] = {
    loaded = true,
    path = "/Users/babygau/.local/share/nvim/site/pack/packer/start/lualine.nvim"
  },
  ["markdown-preview.nvim"] = {
    config = { "\27LJ\2\n1\0\0\2\0\3\0\0056\0\0\0009\0\1\0)\1\0\0=\1\2\0K\0\1\0\20mkdp_auto_start\6g\bvim\0" },
    loaded = false,
    needs_bufread = false,
    path = "/Users/babygau/.local/share/nvim/site/pack/packer/opt/markdown-preview.nvim"
  },
  ["neoscroll.nvim"] = {
    config = { "\27LJ\2\nÈ\1\0\0\4\0\6\0\t6\0\0\0'\2\1\0B\0\2\0029\0\2\0005\2\4\0005\3\3\0=\3\5\2B\0\2\1K\0\1\0\rmappings\1\0\4\22respect_scrolloff\1\24use_local_scrolloff\1\rstop_eof\2\25cursor_scrolls_alone\2\1\n\0\0\n<C-u>\n<C-d>\n<C-b>\n<C-f>\n<C-y>\n<C-e>\azt\azz\azb\nsetup\14neoscroll\frequire\0" },
    loaded = true,
    path = "/Users/babygau/.local/share/nvim/site/pack/packer/start/neoscroll.nvim"
  },
  ["null-ls.nvim"] = {
    loaded = true,
    path = "/Users/babygau/.local/share/nvim/site/pack/packer/start/null-ls.nvim"
  },
  ["nvim-autopairs"] = {
    load_after = {
      ["nvim-treesitter"] = true
    },
    loaded = false,
    needs_bufread = false,
    path = "/Users/babygau/.local/share/nvim/site/pack/packer/opt/nvim-autopairs"
  },
  ["nvim-bufferline.lua"] = {
    loaded = true,
    path = "/Users/babygau/.local/share/nvim/site/pack/packer/start/nvim-bufferline.lua"
  },
  ["nvim-colorizer.lua"] = {
    loaded = false,
    needs_bufread = false,
    path = "/Users/babygau/.local/share/nvim/site/pack/packer/opt/nvim-colorizer.lua"
  },
  ["nvim-compe"] = {
    loaded = true,
    path = "/Users/babygau/.local/share/nvim/site/pack/packer/start/nvim-compe"
  },
  ["nvim-lsp-ts-utils"] = {
    loaded = true,
    path = "/Users/babygau/.local/share/nvim/site/pack/packer/start/nvim-lsp-ts-utils"
  },
  ["nvim-lspconfig"] = {
    loaded = false,
    needs_bufread = false,
    path = "/Users/babygau/.local/share/nvim/site/pack/packer/opt/nvim-lspconfig"
  },
  ["nvim-toggleterm.lua"] = {
    loaded = false,
    needs_bufread = false,
    path = "/Users/babygau/.local/share/nvim/site/pack/packer/opt/nvim-toggleterm.lua"
  },
  ["nvim-treesitter"] = {
    after = { "nvim-autopairs", "nvim-ts-autotag", "nvim-treesitter-textobjects" },
    loaded = false,
    needs_bufread = true,
    path = "/Users/babygau/.local/share/nvim/site/pack/packer/opt/nvim-treesitter"
  },
  ["nvim-treesitter-textobjects"] = {
    load_after = {
      ["nvim-treesitter"] = true
    },
    loaded = false,
    needs_bufread = false,
    path = "/Users/babygau/.local/share/nvim/site/pack/packer/opt/nvim-treesitter-textobjects"
  },
  ["nvim-ts-autotag"] = {
    load_after = {
      ["nvim-treesitter"] = true
    },
    loaded = false,
    needs_bufread = false,
    path = "/Users/babygau/.local/share/nvim/site/pack/packer/opt/nvim-ts-autotag"
  },
  ["nvim-web-devicons"] = {
    loaded = true,
    path = "/Users/babygau/.local/share/nvim/site/pack/packer/start/nvim-web-devicons"
  },
  ["packer.nvim"] = {
    loaded = false,
    needs_bufread = false,
    path = "/Users/babygau/.local/share/nvim/site/pack/packer/opt/packer.nvim"
  },
  ["plenary.nvim"] = {
    loaded = true,
    path = "/Users/babygau/.local/share/nvim/site/pack/packer/start/plenary.nvim"
  },
  ["popup.nvim"] = {
    loaded = true,
    path = "/Users/babygau/.local/share/nvim/site/pack/packer/start/popup.nvim"
  },
  ["telescope-fzf-native.nvim"] = {
    loaded = true,
    path = "/Users/babygau/.local/share/nvim/site/pack/packer/start/telescope-fzf-native.nvim"
  },
  ["telescope.nvim"] = {
    loaded = false,
    needs_bufread = false,
    path = "/Users/babygau/.local/share/nvim/site/pack/packer/opt/telescope.nvim"
  },
  ["tokyonight.nvim"] = {
    config = { "\27LJ\2\na\0\0\3\0\6\0\t6\0\0\0009\0\1\0'\1\3\0=\1\2\0006\0\0\0009\0\4\0'\2\5\0B\0\2\1K\0\1\0\27colorscheme tokyonight\bcmd\bday\21tokyonight_style\6g\bvim\0" },
    loaded = true,
    path = "/Users/babygau/.local/share/nvim/site/pack/packer/start/tokyonight.nvim"
  },
  ["trouble.nvim"] = {
    config = { "\27LJ\2\n9\0\0\3\0\3\0\a6\0\0\0'\2\1\0B\0\2\0029\0\2\0004\2\0\0B\0\2\1K\0\1\0\nsetup\ftrouble\frequire\0" },
    loaded = true,
    path = "/Users/babygau/.local/share/nvim/site/pack/packer/start/trouble.nvim"
  },
  ["vim-easy-align"] = {
    config = { "\27LJ\2\n\1\0\0\a\0\t\0\0176\0\0\0'\2\1\0B\0\2\0029\0\2\0\18\1\0\0'\3\3\0'\4\4\0'\5\5\0005\6\6\0B\1\5\1\18\1\0\0'\3\a\0'\4\4\0'\5\5\0005\6\b\0B\1\5\1K\0\1\0\1\0\1\fnoremap\1\6x\1\0\1\fnoremap\1\22<Plug>(EasyAlign)\15<Leader>xa\6n\bmap\15core.utils\frequire\0" },
    loaded = true,
    path = "/Users/babygau/.local/share/nvim/site/pack/packer/start/vim-easy-align"
  },
  ["vim-eunuch"] = {
    loaded = false,
    needs_bufread = false,
    path = "/Users/babygau/.local/share/nvim/site/pack/packer/opt/vim-eunuch"
  },
  ["vim-qf"] = {
    loaded = false,
    needs_bufread = true,
    path = "/Users/babygau/.local/share/nvim/site/pack/packer/opt/vim-qf"
  },
  ["vim-repeat"] = {
    loaded = true,
    path = "/Users/babygau/.local/share/nvim/site/pack/packer/start/vim-repeat"
  },
  ["vim-smartq"] = {
    loaded = false,
    needs_bufread = false,
    path = "/Users/babygau/.local/share/nvim/site/pack/packer/opt/vim-smartq"
  },
  ["vim-vsnip"] = {
    loaded = true,
    path = "/Users/babygau/.local/share/nvim/site/pack/packer/start/vim-vsnip"
  },
  ["which-key.nvim"] = {
    loaded = false,
    needs_bufread = false,
    path = "/Users/babygau/.local/share/nvim/site/pack/packer/opt/which-key.nvim"
  }
}

time([[Defining packer_plugins]], false)
-- Config for: gruvbox-material
time([[Config for gruvbox-material]], true)
try_loadstring("\27LJ\2\nØ\1\0\0\2\0\t\0\0176\0\0\0009\0\1\0'\1\3\0=\1\2\0006\0\0\0009\0\4\0)\1\1\0=\1\5\0006\0\0\0009\0\4\0'\1\a\0=\1\6\0006\0\0\0009\0\4\0)\1\1\0=\1\b\0K\0\1\0(gruvbox_material_better_performance\fcolored-gruvbox_material_diagnostic_virtual_text#gruvbox_material_enable_italic\6g\nlight\15background\6o\bvim\0", "config", "gruvbox-material")
time([[Config for gruvbox-material]], false)
-- Config for: tokyonight.nvim
time([[Config for tokyonight.nvim]], true)
try_loadstring("\27LJ\2\na\0\0\3\0\6\0\t6\0\0\0009\0\1\0'\1\3\0=\1\2\0006\0\0\0009\0\4\0'\2\5\0B\0\2\1K\0\1\0\27colorscheme tokyonight\bcmd\bday\21tokyonight_style\6g\bvim\0", "config", "tokyonight.nvim")
time([[Config for tokyonight.nvim]], false)
-- Config for: neoscroll.nvim
time([[Config for neoscroll.nvim]], true)
try_loadstring("\27LJ\2\nÈ\1\0\0\4\0\6\0\t6\0\0\0'\2\1\0B\0\2\0029\0\2\0005\2\4\0005\3\3\0=\3\5\2B\0\2\1K\0\1\0\rmappings\1\0\4\22respect_scrolloff\1\24use_local_scrolloff\1\rstop_eof\2\25cursor_scrolls_alone\2\1\n\0\0\n<C-u>\n<C-d>\n<C-b>\n<C-f>\n<C-y>\n<C-e>\azt\azz\azb\nsetup\14neoscroll\frequire\0", "config", "neoscroll.nvim")
time([[Config for neoscroll.nvim]], false)
-- Config for: vim-easy-align
time([[Config for vim-easy-align]], true)
try_loadstring("\27LJ\2\n\1\0\0\a\0\t\0\0176\0\0\0'\2\1\0B\0\2\0029\0\2\0\18\1\0\0'\3\3\0'\4\4\0'\5\5\0005\6\6\0B\1\5\1\18\1\0\0'\3\a\0'\4\4\0'\5\5\0005\6\b\0B\1\5\1K\0\1\0\1\0\1\fnoremap\1\6x\1\0\1\fnoremap\1\22<Plug>(EasyAlign)\15<Leader>xa\6n\bmap\15core.utils\frequire\0", "config", "vim-easy-align")
time([[Config for vim-easy-align]], false)
-- Config for: trouble.nvim
time([[Config for trouble.nvim]], true)
try_loadstring("\27LJ\2\n9\0\0\3\0\3\0\a6\0\0\0'\2\1\0B\0\2\0029\0\2\0004\2\0\0B\0\2\1K\0\1\0\nsetup\ftrouble\frequire\0", "config", "trouble.nvim")
time([[Config for trouble.nvim]], false)
vim.cmd [[augroup packer_load_aucmds]]
vim.cmd [[au!]]
  -- Filetype lazy-loads
time([[Defining lazy-load filetype autocommands]], true)
vim.cmd [[au FileType go ++once lua require("packer.load")({'editorconfig-vim'}, { ft = "go" }, _G.packer_plugins)]]
vim.cmd [[au FileType vue ++once lua require("packer.load")({'emmet-vim'}, { ft = "vue" }, _G.packer_plugins)]]
vim.cmd [[au FileType c ++once lua require("packer.load")({'editorconfig-vim'}, { ft = "c" }, _G.packer_plugins)]]
vim.cmd [[au FileType javascript ++once lua require("packer.load")({'emmet-vim', 'editorconfig-vim'}, { ft = "javascript" }, _G.packer_plugins)]]
vim.cmd [[au FileType javascriptreact ++once lua require("packer.load")({'emmet-vim'}, { ft = "javascriptreact" }, _G.packer_plugins)]]
vim.cmd [[au FileType html ++once lua require("packer.load")({'nvim-colorizer.lua', 'emmet-vim'}, { ft = "html" }, _G.packer_plugins)]]
vim.cmd [[au FileType css ++once lua require("packer.load")({'nvim-colorizer.lua', 'emmet-vim'}, { ft = "css" }, _G.packer_plugins)]]
vim.cmd [[au FileType sass ++once lua require("packer.load")({'nvim-colorizer.lua'}, { ft = "sass" }, _G.packer_plugins)]]
vim.cmd [[au FileType markdown ++once lua require("packer.load")({'markdown-preview.nvim'}, { ft = "markdown" }, _G.packer_plugins)]]
vim.cmd [[au FileType zig ++once lua require("packer.load")({'editorconfig-vim'}, { ft = "zig" }, _G.packer_plugins)]]
vim.cmd [[au FileType rust ++once lua require("packer.load")({'editorconfig-vim'}, { ft = "rust" }, _G.packer_plugins)]]
vim.cmd [[au FileType cpp ++once lua require("packer.load")({'editorconfig-vim'}, { ft = "cpp" }, _G.packer_plugins)]]
vim.cmd [[au FileType typescript ++once lua require("packer.load")({'nvim-colorizer.lua', 'emmet-vim', 'editorconfig-vim'}, { ft = "typescript" }, _G.packer_plugins)]]
vim.cmd [[au FileType typescriptreact ++once lua require("packer.load")({'nvim-colorizer.lua', 'emmet-vim'}, { ft = "typescriptreact" }, _G.packer_plugins)]]
vim.cmd [[au FileType qf ++once lua require("packer.load")({'vim-qf'}, { ft = "qf" }, _G.packer_plugins)]]
vim.cmd [[au FileType vim ++once lua require("packer.load")({'nvim-colorizer.lua', 'editorconfig-vim'}, { ft = "vim" }, _G.packer_plugins)]]
time([[Defining lazy-load filetype autocommands]], false)
  -- Event lazy-loads
time([[Defining lazy-load event autocommands]], true)
vim.cmd [[au BufReadPre * ++once lua require("packer.load")({'nvim-lspconfig'}, { event = "BufReadPre *" }, _G.packer_plugins)]]
vim.cmd [[au BufRead * ++once lua require("packer.load")({'gitsigns.nvim', 'nvim-toggleterm.lua', 'nvim-treesitter', 'telescope.nvim', 'vim-smartq', 'vim-eunuch', 'indent-blankline.nvim', 'accelerated-jk'}, { event = "BufRead *" }, _G.packer_plugins)]]
vim.cmd [[au VimEnter * ++once lua require("packer.load")({'which-key.nvim'}, { event = "VimEnter *" }, _G.packer_plugins)]]
vim.cmd [[au InsertEnter * ++once lua require("packer.load")({'emmet-vim'}, { event = "InsertEnter *" }, _G.packer_plugins)]]
vim.cmd [[au BufNewFile * ++once lua require("packer.load")({'gitsigns.nvim'}, { event = "BufNewFile *" }, _G.packer_plugins)]]
time([[Defining lazy-load event autocommands]], false)
vim.cmd("augroup END")
if should_profile then save_profiles(0) end

end)

if not no_errors then
  vim.api.nvim_command('echohl ErrorMsg | echom "Error in packer_compiled: ".v:exception | echom "Please check your config for correctness" | echohl None')
end

</details>

**Comment by gegoune** [comment]
I don't think it is Packer that loads it actually. Reason why it is saved to plugin/ by default is because nvim loads all files in there at startup.

**Comment by wbthomason** [comment]
@gegoune is correct. `packer` does no explicit loading of the compiled file; it's loaded (by default) by Neovim because it's placed in a runtime directory (again, by default). You can certainly customize `compile_path` to be somewhere else, but then you are responsible for loading the file yourself. Putting `vim.cmd [[luafile path/to/your/compiled/file]]` (or similar, you can use `source` too, I think) in your `init.lua` or another file sourced at startup should usually do it in this case.

**Comment by babygau** [comment]
Thank you all for your insight. I got it fixed according to your suggesstion

**Comment by wbthomason** [comment]
Great, I'm glad things are working now!

**Comment by babygau** [comment]
> Great, I'm glad things are working now!

Yay, I put `packer_compiled.lua` in `stdpath 'data'/lua` dir, then `require 'packer_compiled`. However this seems not to load all plugins as expected as default path `stdpath 'config'/plugin`. I'll see where it went wrong
