### ISSUE TITLE
Error on :PackerUpdate

### ISSUE THREAD

**Issue by p00f** [wbthomason/packer.nvim#44]
After b11f288cf3d632099cd41414783e3639571a14b6 I get
```
Error executing vim.schedule lua callback: .../site/pack/packer/opt/packer.nvim/lua/packer/display.lua:90: Expected lua number                                                                                                              
Error executing vim.schedule lua callback: .../site/pack/packer/opt/packer.nvim/lua/packer/display.lua:129: Expected lua number
Error executing vim.schedule lua callback: .../site/pack/packer/opt/packer.nvim/lua/packer/display.lua:107: Expected lua number
```
on `:PackerUpdate`.

Checking out to the previous commit fixes it, so I don't think I messed something up

**Comment by wbthomason** [comment]
Ok, this is probably a bug with the shim introduced to deal with the extmarks API change. Could you send me your Neovim version?

**Comment by p00f** [comment]
`NVIM v0.5.0-654-g3acfefb63`

**Comment by p00f** [comment]
ie this https://github.com/neovim/neovim/commit/3acfefb63ee70c8eac13bf6b308a0e73e6fb8007

**Comment by wbthomason** [comment]
@p00f: Thanks for the report; it should be fixed now! (at least, I can no longer reproduce the bug on that commit)

**Comment by p00f** [comment]
Fixed, thanks
