### ISSUE TITLE
Suggested autocommand in README doesn't work

### ISSUE THREAD

**Issue by knpwrs** [wbthomason/packer.nvim#455]
- `nvim --version`: v0.5.0
- `git --version`: 2.30.2
- Operating system/version: macOS 11.0.1
- Terminal name/version: Alacritty / zsh

### Steps to reproduce

The README suggests using the following snippet to automatically recompile the packer configuration when `plugins.lua` is written:

```
autocmd BufWritePost plugins.lua PackerCompile
```

However, running `PackerCompile` doesn't appear to work for me until I run `source %` or `source plugins.lua`. Am I missing something? Is there some setting to automatically re-source `plugins.lua` so `PackerCompile` can work as expected?

**Comment by akinsho** [comment]
@knpwrs lua actually caches required modules, so actually just calling compile would not be enough, since packer isn't actually "seeing" the update module, and it's changes. I think a better autocommand would be
```vim
autocmd BufWritePost plugins.lua source <afile> | PackerCompile " untested btw
```
I use something similar.

**Comment by knpwrs** [comment]
@akinsho that works for me! I'll submit a PR.

**Comment by knpwrs** [comment]
Opened #460 to address this issue

**Comment by tom-anders** [comment]
Not sure if worth opening a new issue for this: IMO the Readme should suggest wrapping the autocmd in an augroup. Otherwise, a new autocmd will be set everytime you save `plugins.lua` which can quickly lead to slowdowns

**Comment by knpwrs** [comment]
@tom-anders I think I've noticed that in my setup. Would you mind submitting a PR?

**Comment by wbthomason** [comment]
See #581
