### ISSUE TITLE
vim.fn.executable is not reliable

### ISSUE THREAD

**Issue by TimUntersberger** [wbthomason/packer.nvim#49]
I don't really know why this it the case, but if you don't have `set shell=powershell` on windows, then vim thinks that `mklink` is not executable, even though it is.

I guess `mklink` is not an executable in `cmd`, but in `powershell` it is? I am really confused.

I'll try to find an alternative.

To be honest, I think you can assume that `mklink` exists on Windows right?

Update:

I now tested again with `set shell=powershell` and it still doesn't work. I can execute `mklink` using `:!mklink`, so I think something else is the problem.

**Comment by wbthomason** [comment]
If you run `:lua vim.fn.executable('mklink')` as a manual command, does it output correctly?

**Comment by TimUntersberger** [comment]
I tested using `:echo executable('mklink')`

**Comment by wbthomason** [comment]
And this does not return the expected result?

**Comment by TimUntersberger** [comment]
It returns `0`

**Comment by wbthomason** [comment]
Hmm, ok. Might be an upstream bug?

I'd be pretty comfortable assuming `mklink` exists and then erroring out if that turns out to be incorrect. What do you think?

**Comment by TimUntersberger** [comment]
I think that this would be ok to do 👍
