### ISSUE TITLE
Packer commands do not exist

### ISSUE THREAD

**Issue by katawful** [wbthomason/packer.nvim#495]
- `nvim --version`: NVIM v0.5.0 Build type: Release LuaJIT 2.0.5
- `git --version`: 2.32.0
- Operating system/version: Arch Linux
- Terminal name/version: kitty 0.21.2

### Steps to reproduce
Install packer.nvim. I'm using the following init.lua
```lua
local execute = vim.api.nvim_command
local fn = vim.fn
local fmt = string.format
local packer_path = fn.stdpath("data") .. "/site/pack"
function ensure (user, repo)
        local install_path = fmt("%s/packer/start/%s", packer_path, repo, repo)
        if fn.empty(fn.glob(install_path)) > 0 then
                execute(fmt("!git clone https://github.com/%s/%s %s", user, repo, install_path))
                execute(fmt("packadd %s", repo))
        end
end
ensure("wbthomason", "packer.nvim")
ensure("Olical", "aniseed")
-- load aniseed environment
vim.g["aniseed#env"] = {module = "init"}
```

### Actual behaviour
No packer commands appear

### Expected behaviour
Packer commands should appear

### packer files
I can't get any files since I can't use packer commands

**Comment by akinsho** [comment]
@katawful in the example snippet you posted the GitHub URL looks incorrect. Could be because I'm on mobile but looks like there are special characters in it and the format string is one space away from there rest of the URL

**Comment by katawful** [comment]
It's using the Lua string library to format the url string. The %s are placeholders that are filled by the variables after. I have successfully used it before to install packer but not anymore

**Comment by akinsho** [comment]
@katawful sorry should have been clearer I'm familiar with the format string on mobile they looked like random Unicode characters so thought maybe that was they issue just checked on web and they look normal

**Comment by akinsho** [comment]
@katawful I should have realised this sooner this isn't a bug but rather a change that has happened since the refactor. In order to have access to packers commands a user must have run the `startup` function. In your case what are you trying to achieve? it's probably best to call startup with your plugins after the bootstrap call.

**Comment by katawful** [comment]
I did some looking around at my startup function, which gets loaded right after aniseed starts and I simply missed a set of parentheses to enclose. I didn't know that the startup function was required for the packer commands

The proper fennel syntax for a packer startup function is this:
```clojure
((. (require :packer) :startup) (fn []
   ... your plugins
))
```

**Comment by wbthomason** [comment]
I'll note that you can manually run `packer.make_commands()` if you don't want to use `startup`.
