### ISSUE TITLE
Documentation for log level is only in the readme

### ISSUE THREAD

**Issue by lucc** [wbthomason/packer.nvim#498]
### Steps to reproduce
```
:help packer.nvim
/level
:e %:h:h/README.md
n
```

### Actual behaviour
Docs for log level are not in the help file but only in the README which is inconvenient to use from within nvim. The readme is also not indexed with tags like the help file is.

### Expected behaviour
Everything that is documented in the readme should also be documented in the help file. For me as a nvim user the main documentation for a plugin should be the help file. 

I would go one step further and shorten the readme significantly to the point to only advertise the plugin and give some info useful for newcomers. The full docs should be available from the help file.

**Comment by wbthomason** [comment]
Thanks for the catch! I've fixed this in 92dcbe5. The docs (README and `vimdoc` both) could definitely benefit from some polish and improvement - if you're at all interested in even partially helping with this, I'd be happy to help by answering questions, reviewing, etc.!

**Comment by lucc** [comment]
Would you only be interested in expanding the help file or also in shortening/streamlining the readme?

**Comment by wbthomason** [comment]
Either/both would be great. I've tried to keep both in sync and current with `packer`, but they could both use improvement. Having a simpler README would be great; filling gaps in the vimdoc help would also be a useful improvement.
