### ISSUE TITLE
Packer tries to remove packer folder when updating Plugins

### ISSUE THREAD

**Issue by carlesba** [wbthomason/packer.nvim#499]
- `nvim --version`:
v0.6.0-dev+nightly-247-g682247b52

- `git --version`:
2.32.0

- Operating system/version:
macOS 11.4
- Terminal name/version:

### Steps to reproduce
1. Install packer using
```
git clone https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim
```
2. Create config in `~/.config/nvim/lua/plugins.lua` with the dependencies
3. Run `:PackerUpdate`

### Actual behaviour
Nvim asks to remove `~/.local/share/nvim/site/pack/packer/start/packer.nvim` directory. When confirm with yes, Packer stops working on next updates.
Update works correctly

### Expected behaviour
User shouldn't be asked to remove the packer folder. 

### packer files

<details>
<summary>Plugin specification file(s)</summary>

```lua

require('packer').startup(function()

use 'tpope/vim-commentary'
use 'jiangmiao/auto-pairs'
use 'ciaranm/detectindent'
use 'dag/vim-fish'
use 'maxmellon/vim-jsx-pretty'
-- use 'evanleck/vim-svelte', {'branch': 'main'}
use 'sbdchd/neoformat'


use 'arcticicestudio/nord-vim'
use 'gruvbox-community/gruvbox'
use 'airblade/vim-gitgutter'
use 'ayu-theme/ayu-vim'
use 'sainnhe/everforest'


use 'nvim-lua/popup.nvim'
use 'nvim-lua/plenary.nvim'
use 'nvim-telescope/telescope.nvim'
use 'nvim-telescope/telescope-fzy-native.nvim'
use 'phaazon/hop.nvim'

use 'tpope/vim-fugitive'

use 'hrsh7th/nvim-compe'
use 'neovim/nvim-lspconfig'
use 'glepnir/lspsaga.nvim'

use 'hoob3rt/lualine.nvim'
use 'kyazdani42/nvim-web-devicons'

use 'itchyny/vim-gitbranch'

end)
```

</details>

<details>
<summary>packer log file</summary>

Post the contents of ~/.cache/nvim/packer.nvim.log here
```
[WARN  Sat Jul 24 15:22:19 2021 3.3462232147382e+15] .../site/pack/packer/start/packer.nvim/lua/packer/clean.lua:79: Cleaning cancelled!
```

</details>

<details>
<summary>packer compiled file</summary>

Post the contents of `packer_compiled.vim` here

</details>

**Comment by nanotee** [comment]
The usual setup is to put `use 'wbthomason/packer.nvim'` in your plugin specification and let `packer` manage itself

**Comment by carlesba** [comment]
That worked. Thanks!

Should this be added to the readme?

**Comment by nanotee** [comment]
It's easy to miss but it is actually mentioned in the README! It should probably be featured more prominently, though

**Comment by wbthomason** [comment]
Yeah - it's in the example, but we could add an explicit statement that your options are to either (1) let `packer` manage itself or (2) clone `packer` to somewhere on your `packpath` but outside of `packer`'s package root.
