### ISSUE TITLE
Allow setting opt by default

### ISSUE THREAD

**Issue by comfortablynick** [wbthomason/packer.nvim#50]
I've been using vim packages for some time and have almost all plugins installed as `opt = true`. I do `packadd!` in init.vim or `packadd` elsewhere as needed. It makes it easy to disable plugins in my experience.

Is there a way to do this with packer? There may be some fancy lua trick that can be used that I'm not aware of. If not, can this be added as a configuration option? ([vim-packager](https://github.com/kristijanhusak/vim-packager#packagerinitoptions) has this)

**Comment by wbthomason** [comment]
There currently isn't a great way to do this (you could use some Lua metatable trickery, but it's more effort than it's worth). I'd be happy to add an option for this, though.

**Comment by wbthomason** [comment]
I added the `opt_default` option to implement this feature; it seems to work in my testing - @comfortablynick please let me know if you experience bugs or if this isn't what you had in mind.
