### ISSUE TITLE
Default to non_interactive mode when neovim is headless

### ISSUE THREAD

**Issue by mjlbach** [wbthomason/packer.nvim#503]
I'm trying to use packer headless. One problem is that with the current autocommand workaround for non-blocking insatlls, packer prompts if it detects any non-tracked packages in package path. Since we can't feedkeys to silence this with headless, the installation hangs.

I would suggest defaulting to non_interactive mode is neovim has no ui attached which can be detected with #vim.api.nvim_list_uis() == 0

![image](https://user-images.githubusercontent.com/13316262/126910876-03775d2e-8b86-4bd3-9548-7363a93d6aed.png)

**Comment by nanotee** [comment]
Currently `packer.install()` is a variadic function that optionally takes a list of plugins as arguments so allowing options would be a breaking change

Perhaps `packer` should detect whether nvim is running in headless mode and automatically set `display.non_interactive = true`?

**Comment by mjlbach** [comment]
That would be a good solution, for reference you can test this by checking `#vim.api.nvim_list_uis() == 0`

**Comment by wbthomason** [comment]
Yeah, adding this check in `init` or similar seems like a good idea.
