### ISSUE TITLE
PackerSync, PackerUpdate not fully completed

### ISSUE THREAD

**Issue by saifulapm** [wbthomason/packer.nvim#518]
Suddenly, PackerSync and PackerUpdate not fully complete the list. Check screenshot. Any idea ?
<img width="704" alt="Screenshot 2021-07-29 at 5 10 31 AM" src="https://user-images.githubusercontent.com/3833316/127407882-4ae8cc60-46f6-4a7d-9203-55599a877a0a.png">

**Comment by wbthomason** [comment]
Thanks for the report! Can you please provide the information from the issue template, i.e. your `packer` and Neovim versions, your OS information, and your plugin spec file? (I don't think the compiled file is likely to be implicated here)

Do you know roughly when this started? Is there a known good commit of `packer` that does not exhibit this issue? Have you made any recent changes to your setup?

**Comment by saifulapm** [comment]
@wbthomason Thanks for response. I found why this happening. 
https://github.com/wbthomason/packer.nvim/issues/120


Thanks
