### ISSUE TITLE
Error executing Lua : ...packer/plugin_types/git.lua:134: attempt to concatenate field 'get_msg' (a nil value)

### ISSUE THREAD

**Issue by rktjmp** [wbthomason/packer.nvim#522]
Just did a `:PackerSync` and hit this bug in a previously working setup.

After the update, *no* packer commands work (compile, sync, clean).

It logs the error (in nvim):

```
Error executing Lua : ...packer/plugin_types/git.lua:134: attempt to concatenate field 'get_msg' (a nil value)
```

`git co 637520c` (prev HEAD) and everything works, seems bug was added in `710b9bf`?

- `nvim --version`: NVIM v0.6.0-dev+59-g2475161de
- `git --version`: git version 2.32.0
- Operating system/version: Linux 5.13.4-arch2-1

<summary>packer log file</summary>
No logs written

<summary>packer compiled file</summary>
NA?

**Comment by wbthomason** [comment]
Agh, sorry. I didn't think this would break anyone, as it worked for several people in testing (https://github.com/wbthomason/packer.nvim/pull/511).

The `git.config.get_msg` was renamed - have you, by chance, customized that config value? It still should not be causing a `nil` concatenation; it's gone from `git.lua`...

**Comment by wbthomason** [comment]
Could you please share your `git.lua` file, or at least line 134? I'm not sure what's going on here, but that line has had nothing to do with `get_msg` for a while.

Is it possible that you have `packer` installed in more than one place, one copy of which is severely out of date?

**Comment by rktjmp** [comment]
**Sorry!!**

Seems I had `paq` sitting around with a copy of `packer.nvim` in it's package tree (unsure how that happened??). So yes, I had an older copy sitting around that was getting loaded.

Sorry for the noise!

**Comment by wbthomason** [comment]
Ah, no worries! I'm glad it was just that and not something with the new feature.

**Comment by nawordar** [comment]
I had an exact same error, but in my case I had two packers. One installed from AUR and one by packer itself. So don't be sorry, because this helped me find the root of my problem. Thank you!
