### ISSUE TITLE
Plugin config not compiled?

### ISSUE THREAD

**Issue by huyvohcmc** [wbthomason/packer.nvim#538]
- `nvim --version`: NVIM v0.6.0-dev+111-gf22326ef0914
- `git --version`: 2.32.0
- Operating system/version: macOS 11.4
- Terminal name/version: alacritty 0.8

### Actual behaviour

plugins.lua:
```lua
  use {
    'f-person/git-blame.nvim',
    config = function() require('plugins/git_blame') end
  }

  use {
    'kyazdani42/nvim-tree.lua',
    config = function() require('plugins/nvim_tree') end
  }
```

plugins/git_blame.lua:
```lua
local g = vim.g
local api = vim.api

g.gitblame_enabled = 0
g.gitblame_date_format = '%d/%m/%Y'
g.gitblame_message_template = '<sha> • <summary> • <author> • <date>'

api.nvim_set_keymap('n', 'gb', ':GitBlameToggle<CR>', { noremap = true, silent = false })
```

plugins/nvim_tree.lua:
```lua
local g = vim.g
local api = vim.api

g.nvim_tree_ignore = { '.git', 'node_modules', 'dist' }
g.nvim_tree_auto_open = 1
g.nvim_tree_auto_close = 1
g.nvim_tree_auto_ignore_ft = { 'dashboard' }
g.nvim_tree_tab_open = 1
g.nvim_tree_quit_on_open = 1
g.nvim_tree_disable_netrw = 0
g.nvim_tree_hijack_netrw = 1
g.nvim_tree_follow = 1
g.nvim_tree_gitignore = 1
g.nvim_tree_update_cwd = 1
g.nvim_tree_show_icons = {
  git = 0,
  folders = 0,
  files = 0,
  folder_arrows = 1
}
g.nvim_tree_group_empty = 1
g.nvim_tree_lsp_diagnostics = 1
g.nvim_tree_hijack_cursor = 1
g.nvim_tree_window_picker_exclude = {
  filetype = {
    "packer",
    "qf",
    "Trouble"
  }
}

api.nvim_set_keymap('n', '-', ':NvimTreeFindFile<CR>', {noremap = true, silent = true})
api.nvim_set_keymap('n', '<leader>n', ':NvimTreeToggle<CR>', {noremap = true, silent = true})
api.nvim_set_keymap('n', '<leader>r', ':NvimTreeRefresh<CR>', {noremap = true, silent = true})
```

### Expected behaviour

Plugin configs are loaded normally

### Actual

Only the config of git-blame is loaded, nvim-tree's config are not loaded.

<details>
<summary>packer compiled file</summary>
-- Pre-load configuration
-- Post-load configuration
-- Config for: nvim-treesitter
loadstring("\27LJ\2\n2\0\0\3\0\2\0\0046\0\0\0'\2\1\0B\0\2\1K\0\1\0\23plugins/treesitter\frequire\0")()
-- Config for: nvim-compe
loadstring("\27LJ\2\n-\0\0\3\0\2\0\0046\0\0\0'\2\1\0B\0\2\1K\0\1\0\18plugins/compe\frequire\0")()
-- Config for: hop
loadstring("\27LJ\2\n­\1\0\0\6\0\n\0\0176\0\0\0009\0\1\0009\0\2\0'\2\3\0'\3\4\0'\4\5\0005\5\6\0B\0\5\0016\0\0\0009\0\1\0009\0\2\0'\2\3\0'\3\a\0'\4\b\0005\5\t\0B\0\5\1K\0\1\0\1\0\2\vsilent\2\fnoremap\1\18:HopChar2<CR>\6S\1\0\2\vsilent\2\fnoremap\1\18:HopChar1<CR>\6s\6n\20nvim_set_keymap\bapi\bvim\0")()
-- Config for: nvim-colorizer.lua
loadstring("\27LJ\2\n7\0\0\3\0\3\0\0066\0\0\0'\2\1\0B\0\2\0029\0\2\0B\0\1\1K\0\1\0\nsetup\14colorizer\frequire\0")()
-- Config for: gitsigns.nvim
loadstring("\27LJ\2\n0\0\0\3\0\2\0\0046\0\0\0'\2\1\0B\0\2\1K\0\1\0\21plugins/gitsigns\frequire\0")()
-- Config for: indent-blankline.nvim
loadstring("\27LJ\2\n8\0\0\3\0\2\0\0046\0\0\0'\2\1\0B\0\2\1K\0\1\0\29plugins/indent_blankline\frequire\0")()
-- Config for: tmux.nvim
loadstring("\27LJ\2\nk\0\0\4\0\6\0\t6\0\0\0'\2\1\0B\0\2\0029\0\2\0005\2\4\0005\3\3\0=\3\5\2B\0\2\1K\0\1\0\15navigation\1\0\0\1\0\1\31enable_default_keybindings\2\nsetup\ttmux\frequire\0")()
-- Config for: git-blame.nvim
loadstring("\27LJ\2\n1\0\0\3\0\2\0\0046\0\0\0'\2\1\0B\0\2\1K\0\1\0\22plugins/git_blame\frequire\0")()
-- Conditional loads
-- Load plugins in order defined by `after`
END
</details>

**Comment by wbthomason** [comment]
Hi! I replied to your post on the Neovim subreddit; I'll copy-paste that here as I think it still might be the cause:
> If you're not seeing the config for nvim-tree in packer_compiled (and you're looking at the right file - packer creates packer_compiled.lua, not packer_compiled.vim, since a couple of months ago), then I suspect you ran PackerCompile with a cached old version of your plugin spec that did not include the config key (this is a common pain point, and is due to how Lua caches modules). Try restarting Neovim and running the compile command again; from what you've posted here, it should work fine.

**Comment by huyvohcmc** [comment]
Thanks, I decided to reinstall packer and now it creates `packer_compiled.lua` file, the configs are generated correctly.
