### ISSUE TITLE
Full names (or urls?) in PackerStatus

### ISSUE THREAD

**Issue by will** [wbthomason/packer.nvim#542]
It would be nice if PackerStatus showed either the full name (eg `wbthomason/packer.nvim` instead of just `packer.nvim`) in PackerStatus, or maybe even the full github url when you hit enter to get more information. PackerSync shows the full names but just for a moment then they're gone unless there were updates.

Sometimes I forget that I'm on a fork of a plugin if I was trying something out.

**Comment by dsully** [comment]
Would an OSC code to do this be acceptable as well @wbthomason ?

https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda

**Comment by will** [comment]
> Would an OSC code to do this be acceptable as well @wbthomason ?
> 
> https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda
> 
> I'm often wanting to go to the repository after looking over the updates after a PackerSync to see the commits.

Even if this feature never comes ever to Packer, thanks for pointing out that gist. I had no idea my terminal could do links like this, and I'm going to take advantage of this for other things for sure.

**Comment by dsully** [comment]
Yes, I mean emitting an OSC code. A full URL would be great as well. I can help with a PR. I also use Kitty.

**Comment by akinsho** [comment]
@dsully I don't believe that's what @wbthomason meant. More that a global variable containing all the installed plugins and their metadata is created when packer compile is run. The `PackerStatus` display essentially visualises the content of that table. If you would like to add the url key to the display then the best place to start would be deriving the url during compilation and adding it as a key in the packer plugins table.

It might be good to run `print(vim.inspect(_G.packer_plugins))` so you can see this table and have a sense of what it is.

**Comment by dsully** [comment]
Got it. Thanks.
