### ISSUE TITLE
Add option for relative plugin paths in compiled plugins

### ISSUE THREAD

**Issue by dartacao** [wbthomason/packer.nvim#545]
I run a init.lua and require other init files from a sync'd dropbox folder, so it stays synchronized across my systems. Plugins, nvim-data, etc are all included in this folder. However, when I switch systems, I must run PackerCompile on startup, otherwise the paths for all opt plugins are not updated properly and lazy-loaded plugins throw an error.

Just like there is a profile=true option in PackerCompile, I suggest the addition of a relativepath=true, loading plugins relative to `nvim-data` folder or a custom one. If a similar feature already exists, I could not find it.

As an example, replace "C:\\Users\\USER\\Dropbox\\Dev\\NVim\\data\\nvim-data\\site\\pack\\packer\\start\\nvim-treesitter" in
![image](https://user-images.githubusercontent.com/2131630/128855116-ace53913-d61e-4b21-8d49-883cecc67812.png)
with "$HOME\\NVim\\data\\nvim-data\\site\\pack\\packer\\start\\nvim-treesitter" etc.. in my case.

**Comment by clason** [comment]
You know about neovim's `stdpath` and packer's `compile_path` option? (I use that to put the `packer_compiled.lua` into `stdpath('data')` (which is `.local/share/nvim` on unixy systems) which I don't sync.

**Comment by dartacao** [comment]
@clason Well i tried to use stdpath('data'), in fact my plugins are in that specific folder. However, I cannot get it to work because it I'm also syncing my plugins through nvim-data :(

**Comment by clason** [comment]
Well, if you have a more complicated setup, you have to adapt the paths, of course.

**Comment by dartacao** [comment]
Ok, so where should I put packer_compiled.lua? I presume it should be somewhere that it gets loaded on startup no? Or should I require it in my init.lua?

**Comment by clason** [comment]
Yes, somewhere in `runtimepath` (which you can extend in your `init.lua`).

**Comment by dartacao** [comment]
I believe I've sorted this out, thanks for your help, clason! Closing this now.
