### ISSUE TITLE
[BUG] update or sync will remove a lot of plugins

### ISSUE THREAD

**Issue by Young1783** [wbthomason/packer.nvim#546]
- `nvim --version`:v0.6.0-dev+nightly-292-g51251e1dc
- `git --version`:2.32.0
- Operating system/version: Big Sur
- Terminal name/version:kitty

### Steps to reproduce
1. `:PackerUpdate` 
2. Packer will give a hit to remove a lot of plugins 

### Actual behaviour
Packer will remove other plugin and only 9 plugins remains

### Expected behaviour
update or install plugins which are not installed.

### packer files

<details>
<summary>Plugin specification file(s)</summary>

Post or link your plugin specification files here, if you aren't able to provide a minimal
reproducer
[plugins.lua.txt](https://github.com/wbthomason/packer.nvim/files/6965406/plugins.lua.txt)

</details>

<details>
<summary>packer log file</summary>

Post the contents of ~/.cache/nvim/packer.nvim.log here

</details>

<details>
<summary>packer compiled file</summary>

Post the contents of `packer_compiled.vim` here

-- Automatically generated packer.nvim plugin loader code

if vim.api.nvim_call_function('has', {'nvim-0.5'}) ~= 1 then
  vim.api.nvim_command('echohl WarningMsg | echom "Invalid Neovim version for packer.nvim! | echohl None"')
  return
end

vim.api.nvim_command('packadd packer.nvim')

local no_errors, error_msg = pcall(function()

  local time
  local profile_info
  local should_profile = false
  if should_profile then
    local hrtime = vim.loop.hrtime
    profile_info = {}
    time = function(chunk, start)
      if start then
        profile_info[chunk] = hrtime()
      else
        profile_info[chunk] = (hrtime() - profile_info[chunk]) / 1e6
      end
    end
  else
    time = function(chunk, start) end
  end
  
local function save_profiles(threshold)
  local sorted_times = {}
  for chunk_name, time_taken in pairs(profile_info) do
    sorted_times[#sorted_times + 1] = {chunk_name, time_taken}
  end
  table.sort(sorted_times, function(a, b) return a[2] > b[2] end)
  local results = {}
  for i, elem in ipairs(sorted_times) do
    if not threshold or threshold and elem[2] > threshold then
      results[i] = elem[1] .. ' took ' .. elem[2] .. 'ms'
    end
  end

  _G._packer = _G._packer or {}
  _G._packer.profile_output = results
end

time([[Luarocks path setup]], true)
local package_path_str = "/Users/evan/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/?.lua;/Users/evan/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/?/init.lua;/Users/evan/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/?.lua;/Users/evan/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/?/init.lua"
local install_cpath_pattern = "/Users/evan/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/?.so"
if not string.find(package.path, package_path_str, 1, true) then
  package.path = package.path .. ';' .. package_path_str
end

if not string.find(package.cpath, install_cpath_pattern, 1, true) then
  package.cpath = package.cpath .. ';' .. install_cpath_pattern
end

time([[Luarocks path setup]], false)
time([[try_loadstring definition]], true)
local function try_loadstring(s, component, name)
  local success, result = pcall(loadstring(s))
  if not success then
    vim.schedule(function()
      vim.api.nvim_notify('packer.nvim: Error running ' .. component .. ' for ' .. name .. ': ' .. result, vim.log.levels.ERROR, {})
    end)
  end
  return result
end

time([[try_loadstring definition]], false)
time([[Defining packer_plugins]], true)
_G.packer_plugins = {
  ["TrueZen.nvim"] = {
    loaded = true,
    path = "/Users/evan/.local/share/nvim/site/pack/packer/start/TrueZen.nvim"
  },
  ["galaxyline.nvim"] = {
    config = { "\27LJ\2\n-\0\0\3\0\2\0\0046\0\0\0'\2\1\0B\0\2\1K\0\1\0\18my_statusline\frequire\0" },
    loaded = true,
    path = "/Users/evan/.local/share/nvim/site/pack/packer/start/galaxyline.nvim"
  },
  ["nvim-bufferline.lua"] = {
    loaded = true,
    path = "/Users/evan/.local/share/nvim/site/pack/packer/start/nvim-bufferline.lua"
  },
  ["nvim-cursorline"] = {
    loaded = true,
    path = "/Users/evan/.local/share/nvim/site/pack/packer/start/nvim-cursorline"
  },
  ["nvim-web-devicons"] = {
    loaded = true,
    path = "/Users/evan/.local/share/nvim/site/pack/packer/start/nvim-web-devicons"
  },
  ["packer.nvim"] = {
    loaded = true,
    path = "/Users/evan/.local/share/nvim/site/pack/packer/start/packer.nvim"
  },
  ["plenary.nvim"] = {
    loaded = true,
    path = "/Users/evan/.local/share/nvim/site/pack/packer/start/plenary.nvim"
  },
  ["popup.nvim"] = {
    loaded = true,
    path = "/Users/evan/.local/share/nvim/site/pack/packer/start/popup.nvim"
  },
  ["telescope.nvim"] = {
    loaded = true,
    path = "/Users/evan/.local/share/nvim/site/pack/packer/start/telescope.nvim"
  }
}

time([[Defining packer_plugins]], false)
-- Config for: galaxyline.nvim
time([[Config for galaxyline.nvim]], true)
try_loadstring("\27LJ\2\n-\0\0\3\0\2\0\0046\0\0\0'\2\1\0B\0\2\1K\0\1\0\18my_statusline\frequire\0", "config", "galaxyline.nvim")
time([[Config for galaxyline.nvim]], false)
if should_profile then save_profiles() end

end)

if not no_errors then
  vim.api.nvim_command('echohl ErrorMsg | echom "Error in packer_compiled: '..error_msg..'" | echom "Please check your config for correctness" | echohl None')
end

</details>

**Comment by wbthomason** [comment]
Thanks for your report! `packer` will ask to remove all plugins which are not in your currently loaded plugin spec. Do you still see this behavior after you restart Neovim (forcing a reload of your plugin spec module)? If so, please share your plugin specification file and the list of plugins which `packer` asks to remove.

**Comment by Young1783** [comment]
> Thanks for your report! `packer` will ask to remove all plugins which are not in your currently loaded plugin spec. Do you still see this behavior after you restart Neovim (forcing a reload of your plugin spec module)? If so, please share your plugin specification file and the list of plugins which `packer` asks to remove.

I have upload plugin specification file.

FYI, After exec `:PackerStatus`, I can see the plugins which are recognized by Packer.

 • galaxyline.nvim
 • nvim-bufferline.lua
 • nvim-cursorline
 • plenary.nvim
 • packer.nvim
 • popup.nvim
 • nvim-web-devicons
 • telescope.nvim
 • TrueZen.nvim

**Comment by Young1783** [comment]
I use `startup` again in my init.lua. The remained plugins are listed in the second `startup`. After remove these codes, the behavior is expected. So I fix the bug in my config. This is not bug from packer repo.

Thanks a lot for you help anyway.

**Comment by wbthomason** [comment]
I'm glad things are working now!

**Comment by 1478zhcy** [comment]
I have encountered the same problem before, are you using telescope-packer.nvim? It seems that telescope-packer.nvim causes this problem.
