### ISSUE TITLE
The "run" command doesn't work on Windows.

### ISSUE THREAD

**Issue by baysmith** [wbthomason/packer.nvim#551]
- `nvim --version`: 0.5.0
- `git --version`: NA
- Operating system/version: Windows 10
- Terminal name/version: NA

### Steps to reproduce

Add a plugin with a run command. For example

    use {
        "baysmith/nvim-rs-hello",
        run = "cargo build --release",
    }

### Actual behaviour

`cmd.exe -c "cargo build --release"` is executed, but cargo doesn't run.

### Expected behaviour

`cmd.exe /c "cargo build --release"` should be executed and cargo should run. Note the difference of `-c` versus `/c`. I think that may be the problem.

**Comment by spindensity** [comment]
The same problem here.

**Comment by wbthomason** [comment]
Sorry for my delayed response on this (#562), and thanks @spindensity for the fix!
