### ISSUE TITLE
Depth is not respected

### ISSUE THREAD

**Issue by clason** [wbthomason/packer.nvim#552]
By default, packer should `git clone` with `--depth=1` (unless the `depth` option is set differently). However, that is not respected; packer always makes a full clone. 

The reason is that this is wrong: https://github.com/wbthomason/packer.nvim/blob/710b9bfc5d557556816329cb2f1317430000fb25/lua/packer/plugin_types/git.lua#L135

`999999 or 1` evaluates to `999999` in Lua :D 

An easy fix is to reverse the order (since `or` returns the first truthy operand if both are truthy). A better fix may be to rewrite this to add the `depth` key if and only if `depth` is not set to `-1` (or negative).

**Comment by clason** [comment]
Sorry, didn't test with the additional `and`, which changes the order -- so the current boolean is correct. I still see a massive difference from `git clone --depth=1`, though...

**Comment by wbthomason** [comment]
Sorry, finally making my way this deep in the issues. When you say a "massive difference", you mean in cloned size?

**Comment by clason** [comment]
Oh, sorry, I forgot I never put my findings here (I just mentioned them in chat). Yes, the issue was that the size of the repo (plenary.nvim) was much larger when checked out via `packer` than manually; the reason was the default `--no-single-branch` argument, which pulls in _all_ branches -- including one that happened to still contain an accidentally committed binary...

**Comment by wbthomason** [comment]
Ah, ok. To be honest, I'm not sure if that argument is still necessary, since we `fetch` when switching to a new branch anyway.
