### ISSUE TITLE
How to specify `<Plug>...` as cmd for lazy loading?

### ISSUE THREAD

**Issue by subsetpark** [wbthomason/packer.nvim#556]
Forgive me if this has been answered, but GH doesn't let me search for the literal string `<Plug>`.

---

Many plugins - we can use https://github.com/b3nj5m1n/kommentary/ as an example - expose `<Plug>` commands rather than normal command-line commands, which must be mapped to a keystroke. Is there any way to specify those commands as the `cmd` to lazy-load the kommentary plugin? I tried simply putting the full name of thne command, prefixed with "`<Plug>`", but it had no effect.

**Comment by ram02z** [comment]
See https://github.com/wbthomason/packer.nvim/discussions/226#discussioncomment-386687

**Comment by subsetpark** [comment]
Thank you! Apologies for the duplicate.
