### ISSUE TITLE
Running PackerCompile while PackerSyncing would cause it to end early

### ISSUE THREAD

**Issue by glyh** [wbthomason/packer.nvim#560]
Every config detail is the same as #559. 

To reproduce, just type PackerCompile some times when Syncing, it would cause it to end early.

**Comment by wbthomason** [comment]
I'm having a bit of trouble reproducing this - how do you know that the sync is being prematurely terminated?

**Comment by wbthomason** [comment]
#602 is a potential fix to this issue, but, again, I'm having trouble verifying that it happens (and thus verifying that the fix is correct).

**Comment by glyh** [comment]
Sorry for late response. Well, I think this might be actually not early end, but, rather, early redraw the UI. 

I've tested the following config, and ":PackerCompile" will not cause the update to end early, so I assume this is fixed.
```lua
    require("packer").startup({
        {
            "wbthomason/packer.nvim",
            "chromium/chromium",
            {"sarcasticadmin/empty-repo",
              run = "tail -f /dev/null" -- Do nothing forever
            }
        },
        config = {
            package_root = package_root,
            compile_path = compile_path,
        },
    })

```
