### ISSUE TITLE
`:PackerCompile` try to source lua file `packer_compiled.lua`

### ISSUE THREAD

**Issue by PascalZh** [wbthomason/packer.nvim#574]
- `nvim --version`:NVIM v0.5.0-dev+1384-gf2906a466
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az32-610

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info

- `git --version`:git version 2.25.1
- Operating system/version:wsl2 ubuntu
- Terminal name/version:windows terminal

### Steps to reproduce
Add `print(output_path)` before line 698 in `lua/packer.lua`:
```lua
    print(output_path)
    vim.cmd('source ' .. output_path) -- line 698
```
### Actual behaviour
output_path = 'path/to/plugin/packer_compiled.lua'

### Expected behaviour
should not source packer_compiled.lua

### packer files

<details>
<summary>Plugin specification file(s)</summary>

Post or link your plugin specification files here, if you aren't able to provide a minimal
reproducer

</details>

<details>
<summary>packer log file</summary>

Post the contents of ~/.cache/nvim/packer.nvim.log here

</details>

<details>
<summary>packer compiled file</summary>

Post the contents of `packer_compiled.vim` here

</details>

**Comment by wbthomason** [comment]
@PascalZh sorry for my delayed response; I was away (#562). Can I ask what the solution was here? You can disable this behavior with the config variable `auto_reload_compiled`, if you haven't found that yet.

**Comment by PascalZh** [comment]
> @PascalZh sorry for my delayed response; I was away (#562). Can I ask what the solution was here? You can disable this behavior with the config variable `auto_reload_compiled`, if you haven't found that yet.

I update the neovim to the newest nightly version, and find that everything is ok.

**Comment by wbthomason** [comment]
Ah, you were missing the runtime Lua files PR. I'm glad that you got things working!
