### ISSUE TITLE
Install plugins in custom directory other than $HONE/.local/share/nvim/site

### ISSUE THREAD

**Issue by d0u9** [wbthomason/packer.nvim#575]
### Describe the feature

Hi, all. I want to install plugins in a custom directory other than the `packpath`. Is that possible?

**Comment by wbthomason** [comment]
The way to do this properly is to
1. Set `package_path` and `compile_path`, as you've discovered, and
2. In your `init.lua`, set `packpath` (the Neovim setting) to the appropriate value to include your custom location.

I suppose `packer` _could_ check if your `package_root` is on the `packpath` and, if not, update the `packpath` value for you, but it does not yet do so.

**Comment by samodostal** [comment]
> I set `package_root` and `compile_path` variables to a custom location, and the plugins are installed there properly:
> 
> ```
> packer.init({
>     package_root = util.join_paths('~/.config/nvim/plugins', 'pack'),
>     compile_path = util.join_paths('~/.config/nvim/plugins', 'packer_compiled.lua'),
> })
> ```
> 
> However, when use `require'lspconfig'.gopls.setup{}` to load a **lsp** plugin, error occurs:
> 
> ```
> E5113: Error while calling lua chunk: /home/xxx/.config/nvim/lua/plugin_settings.lua:3: module 'lspconfig' not found
> ```
> 
> I have to manually tweak the `runtimepath` variable to add the path to lsp plugin to make it work.

I had the exact same issue and I also made it (kind of) work by tweaking the `runtimepath`. My issue now is that packer won't run any configs for plugins (`:PackerStatus` doesn't show any plugins), only when I call `:PackerCompile` the configs are loaded. So every time I close and reopen neovim I have to run `:PackerCompile` for the configs to load.

Adding `package_root` to `packpath` didn't work either but maybe I am doing something wrong there. Should I use a combination of `packpath` and `runtimepath` for it to work?

@wbthomason do you know what I might be doing wrong?
