### ISSUE TITLE
Dependencies should be specified by the plugin itself instead of the plugin provider

### ISSUE THREAD

**Issue by RobinVdBroeck** [wbthomason/packer.nvim#584]
### Describe the feature
Right now, if you use packer, you are required to manually specify which dependencies a plugin has in `packer.startup()`. Other package managers like cargo, npm, ... can do this automatically. It would be a nice to have to let the plugins itself manage that. For example, we could have a packer.json file that specifies the requirements. An example implementation could be something like this:

```json
{
 "dependencies": [
   "foo/bar.nvim",
   {"name": "nvim-telescope/telescope.nvim", "opt": true}
 ]
}
 ```

When plugin x has a packer.json, we can fill in the requirements in use automatically.

In the future we could extend this to have stuff like version management.

**Comment by akinsho** [comment]
@RobinVdBroeck there's actually quite a long discussion thread on this issue https://github.com/wbthomason/packer.nvim/discussions/176.

Think this is more suitable for that format since as you'll see on reading through the discussion there's *a lot of considerations*

**Comment by wbthomason** [comment]
That said: definitely something I'm interested in, though I am far from the first person to try and get a unified dependency specification format standardized among the Vim/Neovim community, and it's a hard problem (as that discussion shows).
