### ISSUE TITLE
Packer wants to clean itself

### ISSUE THREAD

**Issue by alexDarcy** [wbthomason/packer.nvim#587]
- `nvim --version`: v.0.5.0
- `git --version`: 2.32.0
- Operating system/version: FreeBSD 13.0
- Terminal name/version: kitty 0.23.1

### Steps to reproduce
Install packer.vim with 

```git clone --depth 1 https://github.com/wbthomason/packer.nvim\
   ~/.local/share/nvim/site/pack/packer/start/packer.nvim
```

Activate packer.vim as in the README.
Run :PackerClean

### Actual behaviour

``` Removing the following directories. OK? (y/N)                   
 - /usr/home/alex/.local/share/nvim/site/pack/packer/start/packer.nvim 
```

### Expected behaviour
Just an update

### packer files

<details>
~/.config/nvim/lua/plugins.lua

```
return require('packer').startup(function()
	use 'tpope/vim-commentary'
	use 'tpope/vim-unimpaired'
	use 'tpope/vim-sensible'
	use 'tpope/vim-surround'
	use { 'nvim-telescope/telescope.nvim',
	requires = { {'nvim-lua/plenary.nvim'} }
}
end)
```

 ~/.cache/nvim/packer.nvim.log :

`[WARN  Sat Sep  4 11:17:04 2021 2970046545917] .../site/pack/packer/start/packer.nvim/lua/packer/clean.lua:79: Cleaning cancelled!
`
</details>

**Comment by nanotee** [comment]
You have to put `use 'wbthomason/packer.nvim'` in your plugin specification, that's usually the simplest way to let `packer` manage itself

**Comment by alexDarcy** [comment]
Right, I've missed the part from the documentation.
Thanks for the quick answer !
