### ISSUE TITLE
Error when setting `working_sym = "~"`

### ISSUE THREAD

**Issue by riazufila** [wbthomason/packer.nvim#588]
- `nvim --version`: `NVIM v0.6.0-dev+214-gdce50312e`
- `git --version`: `git version 2.33.0`
- Operating system/version: `Arch Linux 5.13.13-zen1-1-zen Kernel`
- Terminal name/version: `rxvt-unicode 9.26-2`

### Steps to reproduce
Change configuration of packer's `display` to use `~` as the symbol.

```
local packer = require("packer")

packer.startup(
  {
    function(use)
      -- Package manager
      use "wbthomason/packer.nvim"
    end,
    config = {
      display = {
        working_sym = "~",
      }
    }
  }
)
```

Then, `:PackerSync`.

### Actual behaviour
Error message: `[packer.nvim] [ERROR 19:08:53] async.lua:20: Error in coroutine: ...ite/pack/packer/start/packer.nvim/lua/packer/display.lua:793: Vim(syntax)
:E874: (NFA) Could not pop the stack!`

The window that is supposed to popup is blank.

### Expected behaviour
Window appears with content respective to it.

**Comment by riazufila** [comment]
Turns out when I comment out the packer.init lines the error went away. But how can I implement this without an error? I never got error before while using this as it is.

**Comment by riazufila** [comment]
So I found out using `~` as the symbol in `display` causes the error to popup.

**Comment by riazufila** [comment]
Somehow, after several updated of nvim nightly, this problem has gone away. Closing.

**Comment by wbthomason** [comment]
Fascinating! I'm not sure what was going on here, but it seems there may have been an upstream bug? Regardless, I'm glad things are working now, and sorry for being slow to reply.

**Comment by emileferreira** [comment]
I've just encountered this bug in Neovim v0.8.0 @wbthomason.

`[packer.nvim] [ERROR 18:58:54] async.lua:20: Error in coroutine: ...ite/pack/packer/start/packer.nvim/lua/packer/display.lua:946: Vim(syntax):E874: (NFA) Could not pop the stack!`

Perhaps the tilde is not being interpreted as a string literal when executed as Vimscript in `vim.cmd(c)`?
