### ISSUE TITLE
How to lazy load treesitter?

### ISSUE THREAD

**Issue by siduck76** [wbthomason/packer.nvim#591]
Hi , I want to load treesitter only after a file is added to the buffer , BufAdd event works but opening any file with nvim (nvim myfile) doesnt load treesitter since treesitter loads at BufAdd event , shouldnt opening a file directly with nvim trigger BufAdd event too?

**Comment by babygau** [comment]
Could you try `BufReadPre`?

**Comment by siduck76** [comment]
> BufReadPre

doesnt work 


https://user-images.githubusercontent.com/59060246/132646592-0410ac46-40d8-4beb-8f1c-aee1e316684c.mp4

**Comment by babygau** [comment]
Sorry, it should be `BufRead`. That's how I lazy load tree-sitter.

**Comment by siduck76** [comment]
> Sorry, it should be `BufRead`. That's how I lazy load tree-sitter.

I have used that before. Im looking for an event that gets triggers if a file is opened as in a buffer.


( there's no file opened here , why is bufread triggered and treesitter on bufread gets loaded too)
![image](https://user-images.githubusercontent.com/59060246/132661436-807e1367-e354-4c8f-a6d1-aba07d397c10.png)

**Comment by ignamartinoli** [comment]
Should I also load `nvim-treesitter` after my theme? Doing it makes `neorg` highlighting not appear

**Comment by siduck** [comment]
> Should I also load `nvim-treesitter` after my theme? Doing it makes `neorg` highlighting not appear

just load it at bufread.

**Comment by ignamartinoli** [comment]
Thanks :D
