### ISSUE TITLE
Setup packer in containerized nvim fails to run packer bootstrap

### ISSUE THREAD

**Issue by qwelyt** [wbthomason/packer.nvim#599]
- `nvim --version`: 0.5.0
- `git --version`: 2.33.0
- Operating system/version: alpine:edge
- Terminal name/version: rxvt-unicode (urxvt) v9.26 - released: 2021-05-14

### Steps to reproduce
A basic example can be found here: https://github.com/qwelyt/docker-stuff/tree/4a8ac109753dacb7dde8f762927ef15b5ce1bf68/devenv/nvim (linked specific commit to pin state)
Clone that and run `docker build`. It fails to do the setup, complains about `PackerSync` not being an editor command.

What is odd is that if you comment out the `RUN nvim --headless ....` lines and just build the container - you can run those exact commands inside the container and they work. So for some reason or the other, they don't work when in this kind of headless mode.

### Actual behaviour
```
 % docker build -t devenv-minimal .
Sending build context to Docker daemon  11.26kB
Step 1/8 : FROM alpine:edge
 ---> 4e873038b87b
Step 2/8 : RUN apk --no-cache add git neovim bash nodejs npm ripgrep alpine-sdk
 ---> Using cache
 ---> af674d182628
Step 3/8 : WORKDIR /root/.config/nvim
 ---> Using cache
 ---> 57ca1e52ba72
Step 4/8 : COPY . .
 ---> d09fa152e4e2
Step 5/8 : RUN nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
 ---> Running in ddffc613ecd8
Error detected while processing command line:
E492: Not an editor command: PackerSync
Press ENTER or type command to continue
^C
```

### Expected behaviour
That the packer commands should work

### packer files

<details>
<summary>Plugin specification file(s)</summary>

Just packer itself. See linked repo. 
```
return packer.startup(function()
    use {
        "wbthomason/packer.nvim",
    }
end)
```

</details>

**Comment by wbthomason** [comment]
Thanks for your report! Looking at your linked repo, I'm not sure I see where you actually load your `plugin` or `packerInit` modules - it seems that `init.lua` only loads `core`, which in turn only loads `core.options`. I could be missing something, but this would imply that `packer` never actually gets installed and thus the commands are not created.

**Comment by qwelyt** [comment]
It would look like that, yes. But even if you include the `plugins` module it fails with the same error.

**Comment by wbthomason** [comment]
Fascinating, huh. I have no idea why that might happen (I don't know a lot about Docker). If you just run `lua require('packer').sync()` instead of `PackerSync`, do you get anything different?

**Comment by qwelyt** [comment]
Well, a different error happened.

```
Step 5/7 : RUN nvim --headless -c 'autocmd User PackerComplete quitall' -c "lua require('packer').sync()"
 ---> Running in 60eb25f3c739
Unable to find packerError detected while processing command line:
E5108: Error executing lua [string ":lua"]:1: module 'packer' not found:
	no field package.preload['packer']
	no file './packer.lua'
	no file '/usr/share/luajit-2.1.0-beta3/packer.lua'
	no file '/usr/local/share/lua/5.1/packer.lua'
	no file '/usr/local/share/lua/5.1/packer/init.lua'
	no file '/usr/share/lua/5.1/packer.lua'
	no file '/usr/share/lua/5.1/packer/init.lua'
	no file '/usr/share/lua/common/packer.lua'
	no file '/usr/share/lua/common/packer/init.lua'
	no file './packer.so'
	no file '/usr/local/lib/lua/5.1/packer.so'
	no file '/usr/lib/lua/5.1/packer.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
Press ENTER or type command to continue
^C
```
And I get the same error when trying to run it inside the container.

```
bash-5.1# nvim --headless -c 'autocmd User PackerComplete quitall' -c "lua require('packer').sync()"
Unable to find packerError detected while processing command line:
E5108: Error executing lua [string ":lua"]:1: module 'packer' not found:
	no field package.preload['packer']
	no file './packer.lua'
	no file '/usr/share/luajit-2.1.0-beta3/packer.lua'
	no file '/usr/local/share/lua/5.1/packer.lua'
	no file '/usr/local/share/lua/5.1/packer/init.lua'
	no file '/usr/share/lua/5.1/packer.lua'
	no file '/usr/share/lua/5.1/packer/init.lua'
	no file '/usr/share/lua/common/packer.lua'
	no file '/usr/share/lua/common/packer/init.lua'
	no file './packer.so'
	no file '/usr/local/lib/lua/5.1/packer.so'
	no file '/usr/lib/lua/5.1/packer.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
Press ENTER or type command to continue
```

**Comment by qwelyt** [comment]
Huh. I think you lead me down a path that solved it. https://github.com/qwelyt/docker-stuff/commit/a41c2275e2311d3f6a5d53f7c4001999cd5005dd

Instead of lazily assume that my `packerInit.lua` would install packer I create a function that I explicitly call if I can't find `packer`. This seems to great. Not sure why it wouldn't install packer without the explicit function call though.

**Comment by wbthomason** [comment]
Hmm, I agree - I read your initial `packerInit` and also thought it would install `packer` if it was missing. I'm also not sure why that didn't work, though I'm glad things are working now. Feel free to reopen if you continue to hit trouble!

**Comment by DreamingRaven** [comment]
Just to help anyone else who happens to stumble upon this, as it was quite a headache at first. I had what looks to be a similar initial problem in my own docker containers, however I solved the [--headless and neovim prompt issue by simply prepending PackerSync with silent](https://stackoverflow.com/questions/890802/how-do-i-disable-the-press-enter-or-type-command-to-continue-prompt-in-vim):

```docker
RUN nvim --headless -c 'autocmd User PackerComplete quitall' -c 'silent PackerSync'
```

So in my case I have taken [NvChad](https://github.com/NvChad/NvChad) and tried to package it inside a docker container. [The specific commit](https://gitlab.com/deepcypher/dockeride/-/commit/41ebe9cf80fd20aa0d53b2b558f64511b804ed5e) 

P.S I realize the problem in the end of this specific issue was actually the installation of Packer, but searching the error message and docker took me here. So I am trying to save anyone else who ends up in the same place.
