### ISSUE TITLE
Lazy loading based on filename?

### ISSUE THREAD

**Issue by IndianBoy42** [wbthomason/packer.nvim#601]
I want to set up lazy loading for [crates.nvim](https://github.com/saecki/crates.nvim). The ideal is that it only gets loaded when a file called `cargo.toml` is loaded in a rust project. I'm not sure if packer has this capability (or something similar).
I can do `ft = 'toml'` but that would trigger on something other than `cargo.toml`.
I was also thinking about whether we could use the LSP to be more precise about lazy loading.

**Comment by akinsho** [comment]
@IndianBoy42 you can already achieve this using the `event` key which creates an autocommand so you can pass in valid autocommand patterns already e.g. 
```lua
use {'crates.nvim', event = "BufEnter Cargo.toml" }
```
This will restrict this plugin to only loading in that specific file

**Comment by wbthomason** [comment]
Closing because @akinsho is correct, but please feel free to reopen if this does not address your use case.
