### ISSUE TITLE
Pass a logging callback to Lua hook

### ISSUE THREAD

**Issue by zeertzjq** [wbthomason/packer.nvim#608]
Passing a logging callback to Lua hook will enable a Lua hook to send output like an external command.

**Comment by wbthomason** [comment]
I'm sorry, but I think I need some more information. What Lua hooks are you referring to? Can you give an example of the use case you'd like to see?

**Comment by zeertzjq** [comment]
I'm referring to post-install/update hooks. I want write a Lua hook that wraps `:TSUpdate` and shows its output in packer buffer instead of in the messages area.

**Comment by wbthomason** [comment]
Ah, so you want the post-install/update hooks to be able to submit display messages? We already display the output for post-update hooks specified as jobs to run (i.e. external commands); it's a little harder to wrap the output of a command to be displayed in this manner. That said, I can definitely add the display object as a parameter to the Lua function form of post-update hook (https://github.com/wbthomason/packer.nvim#updateinstall-hooks)

**Comment by wbthomason** [comment]
Added this in 553907
