### ISSUE TITLE
Question: how can i use nvim -u mini.lua ?

### ISSUE THREAD

**Issue by ayoubelmhamdi** [wbthomason/packer.nvim#612]
when openning : 
```bash
$ nvim -u mini.lua
```
 neovim load/check all plugins in  the default directory in:
```bash
~/.local/share/nvim/site/pack/packer/start
~/.config/nvim/pack/packer/start
```
 but , I want only the plugins in my config in `mini.lua`, like:
```lua
require('packer').startup(function()
  use 'wbthomason/packer.nvim'
  use 'hrsh7th/nvim-compe'
  use 'L3MON4D3/LuaSnip'
  use 'nvim-treesitter/nvim-treesitter'
  use 'David-Kunz/treesitter-unit'

end)
```
because some plugins doesn't needed `require 'module'` to run!

**Comment by clason** [comment]
That's not an issue with packer but with how native vim packages work. You need to explicitly `set packpath=` in your `mini.lua` to skip all packages.

**Comment by ayoubelmhamdi** [comment]
thank's
