### ISSUE TITLE
compile plugins to lua bytecode

### ISSUE THREAD

**Issue by goolord** [wbthomason/packer.nvim#614]
luajit is capable of serializing/deserializing lua programs to/from bytecode
```
       -b ... Save  or list bytecode. Run without arguments to get help
              on options.
```
compiling lua programs to bytecode can save luajit from doing a significant amount of work for larger modules

what i'm imagining is something like
`PackerCompile -b/--bytecode`
(or maybe this is the default behavior and `PackerCompile --plaintext`)

ref https://blog.openresty.com/en/luajit-bytecode/

**Comment by akinsho** [comment]
Is this bytecode functionality available in the version of luajit that nvim ships with, or the openresty fork? I'm definitely not an expert on luajit versions, but am aware of https://github.com/neovim/neovim/issues/15737 and an older issue trialling the version of luajit. Neither of which are available yet/still needs to be discussed by the nvim team and eventually maybe merged at some point in the future

**Comment by goolord** [comment]
yes, these flags are available in the version of luajit that neovim ships with. i'm having mild trouble learning if it's in the spec, but i can see its been an option since at most luajt 2.0. luac also seems to have this option.

i experimented with compiling to bytecode to reduce load time in my plugin here https://github.com/goolord/alpha-nvim/tree/alpha-ui and saw some pretty wins, and it worked without any additional configuration

**Comment by Joakker** [comment]
Doesn't `luac` compile a script into bytecode? It should be available in all luajit distributions, since it comes from upstream lua. What is a concern though, is that the bytecodes may be incompatible between releases/distributions.

**Comment by goolord** [comment]
why is this a concern? presumably the lua compiler that is interpreting the bytecote is also the same compiler that compiles the bytecode.

all lua compilers that implement lua > 5 compile to bytecode as per the spec, i don't really know of any lua compilers that can't also serialize/deserialize the bytecode if that's what you're asking. if such a compiler were to exist that's what i foresaw when suggesting that this be a configurable option, not mandatory

**Comment by Joakker** [comment]
Yeah, you're right. I seem to have overlooked that

**Comment by shadmansaleh** [comment]
[impatient.nvim](https://github.com/lewis6991/impatient.nvim) already compiles lua modules and https://github.com/neovim/neovim/pull/15436 might put module compilation in core.

**Comment by goolord** [comment]
oh, you're right, impatient.nvim should be compiling the lua modules. the behavior i am encountering must be a bug or configuration issue. upstream neovim is definitely a more appropriate place for this, but i assumed it might be faster to get it in here. closing
