### ISSUE TITLE
Error detected while processing function <SNR>27_load

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [wbthomason/packer.nvim#64]
I get this error when opening a group of files
```
Error detected while processing function <SNR>27_load
line      1:
E5108: Error executing lua [string "..."]:0 attempt to index upvalue ' ' (a nil value)
Press ENTER or type command to continue
```

**NOTE: the ... upvalue ' ' is actually two single quotes without a space. I added the space for legibility**

I have troubleshooted this to this portion of my packer compiled plugin

```vim
augroup packer_load_aucmds
  au!
  " Filetype lazy-loads
  au FileType sh ++once call s:load(['nvim-treesitter', 'vim-sh', 'completion-tags', 'completion-treesitter'], { "ft": "sh" })
augroup END
```

**NOTE: This happens on other files with similiar autocmds**

I'm not sure where it's getting tripped up.

**Comment by wbthomason** [comment]
Thanks for the report! Could you send me your config for the plugins in that call to `load`? I'm guessing from the error message that there's an issue with something there, or with the part of the `packer` compiler that handles `config` functions, since filetype loading in general works for me.

**Comment by Th3Whit3Wolf** [comment]
Absolutely, here is [my config](https://github.com/Th3Whit3Wolf/Almost-Finished-Neovim-Config/blob/dev/lua/plug.lua)

**Comment by Th3Whit3Wolf** [comment]
I've narrowed it down to it being an issue with using config (maybe incorrectly).

**Comment by Th3Whit3Wolf** [comment]
Heres one example

```lua
-- Simpler Rainbow Parentheses
    use {
        'junegunn/rainbow_parentheses.vim',
        event = 'InsertEnter *',
        config = 'vim.cmd[[RainbowParentheses]]'
    }
```

On insert I get the following error

```
Error detected processing function <SNR>25_load:
line    1:
E5108: Error executing lua [string: "vim.cmd[[RainbowParentheses]]"]:1 Vim(for) :E714 List required
```
but this is fairly similliar to the example

```lua
use {
    'w0rp/ale',
    ft = {'sh', 'zsh', 'bash', 'c', 'cpp', 'cmake', 'html', 'markdown', 'racket', 'vim', 'tex'},
    cmd = 'ALEEnable',
    config = 'vim.cmd[[ALEEnable]]'
  }
```

**Comment by wbthomason** [comment]
Hmm, this is interesting - I still cannot reproduce the error, even with your example. I get no error message and do see rainbow parentheses, as expected.

**Comment by wbthomason** [comment]
Could you post your Neovim version? I'm wondering if this is something with a change in the Lua interface, maybe?

**Comment by Th3Whit3Wolf** [comment]
```sh
NVIM v0.5.0-736-g07fde6c39
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/var/tmp/pamac-build-doc/neovim-nightly-git/src/build/config -I/var/tmp/pamac-build-doc/neovim-nightly-git/src/neovim-nightly-git/src -I/usr/include -I/var/tmp/pamac-build-doc/neovim-nightly-git/src/build/src/nvim/auto -I/var/tmp/pamac-build-doc/neovim-nightly-git/src/build/include
Compiled by doc@Nebula

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by wbthomason** [comment]
Hmm. That *is* an earlier version than I'm using, but not so old that it should cause trouble, I would think....

Oh, though it wouldn't cause this problem, I did want to note that you don't need to manually mark plugins as `opt` if you're lazy-loading them - `packer` takes care of that for you.

**Comment by wbthomason** [comment]
For you, does a minimal `plugins.lua` containing *just* the example you sent trigger the issue you report? Or does that example in isolation work as expected?

**Comment by wbthomason** [comment]
Could you please post the contents of your compiled file? I assume it matches mine with your example config, but maybe inspecting it will show me something useful.

**Comment by Th3Whit3Wolf** [comment]
[heres the gist](https://gist.github.com/Th3Whit3Wolf/20aa1d96ff55e416d6b268d761496a5d)

**Comment by wbthomason** [comment]
Thanks - unfortunately, it looks like that's incomplete (the command definitions at the bottom are cut off, for example).

**Comment by Th3Whit3Wolf** [comment]
Terribly sorry about that, it's fixed now

**Comment by wbthomason** [comment]
Thanks! Unfortunately, at a glance, I'm really not seeing anything unusual. I'll look more in depth later, but as of now I still have not been able to reproduce the issue, sorry.

**Comment by Th3Whit3Wolf** [comment]
> I'm sorry, but even when I replace my plugin specification with exactly what you posted (modulo the references to `global`; I assume that `global.local_nvim = '/home/me/.local/share/nvim'` and `global.path_sep = '/'`), I cannot reproduce the error :/

`global.local_nvim = '/home/me/.local/share/nvim'` if that makes a difference

> About everything _else_ in my config throws errors (because I'm referencing plugins that aren't included in the example config), but I get no errors on `InsertEnter` and `rainbow_parentheses` works as expected.

> Thanks! Unfortunately, at a glance, I'm really not seeing anything unusual. I'll look more in depth later, but as of now I still have not been able to reproduce the issue, sorry.

That's okay I appreciate your help!

**Comment by nanotee** [comment]
I *think* I've managed to reproduce this issue with the gist you provided, although the error message I get is slightly different. I have narrowed it down to [line 1399](https://gist.github.com/Th3Whit3Wolf/20aa1d96ff55e416d6b268d761496a5d#file-packages-vim-L1399).

If I replace

```vim
call luaeval('_packer_load(_A[1], _A[2])', [a:names, a:cause])
```

with

```vim
call luaeval('_packer_load')(a:names, a:cause)
```

the error goes away.

@Th3Whit3Wolf could you try and see if this fixes it for you as well?

**Comment by Th3Whit3Wolf** [comment]
> I _think_ I've managed to reproduce this issue with the gist you provided, although the error message I get is slightly different. I have narrowed it down to [line 1399](https://gist.github.com/Th3Whit3Wolf/20aa1d96ff55e416d6b268d761496a5d#file-packages-vim-L1399).
> 
> If I replace
> 
> ```viml
> call luaeval('_packer_load(_A[1], _A[2])', [a:names, a:cause])
> ```
> 
> with
> 
> ```viml
> call luaeval('_packer_load')(a:names, a:cause)
> ```
> 
> the error goes away.
> 
> @Th3Whit3Wolf could you try and see if this fixes it for you as well?

Using it with my current setup gives me

```
[strubg "..."]:0 attempt to index upvalue '' (a nil value)

**Comment by wbthomason** [comment]
@nanotee: I'm surprised that the modified use of `luaeval` in your suggested patch is valid. `_packer_load` is the name of a globally defined function (so I don't think it's an expression), and (per the docs, at least) the only way to pass arguments to a function call in `luaeval` is by using the "magic global _A".

Also, that line is hardcoded in `packer`'s output, so it's common to *everyone*'s compiled output file. I'd expect to see way more breakage if this was the culprit.

How did you narrow it down to that line, out of curiosity?

**Comment by nanotee** [comment]
Nevermind, I initially narrowed it down by commenting the line out but this seems to have been an unrelated error, apologies for the noise.

I have since managed to reproduce the actual bug reliably by inspecting @Th3Whit3Wolf 's config more closely. It stems from `string.dump()` generating invalid code for the `config` key. Here's a minimal repro:

```lua
local packer = require('packer')

local vim = vim

packer.startup(function(use)
    use {
        'tpope/vim-abolish',
        event = 'VimEnter *',
        config = function()
            vim.cmd [[ if !stridx(&rtp, resolve(expand('~/.config/nvim/lazy/abolish.vim'))) == 0 | execute 'source' fnameescape(resolve(expand('~/.config/nvim/lazy/abolish.vim'))) | endif ]]
        end
    }
end)
```

The error comes from `local vim = vim`. If you comment that line out, `packer` generates valid code again. Probably has to do with upvalues not being saved by `string.dump()`

(FWIW, `luaeval('global_lua_function')` seems to be legal, it evaluates to a `funcref`)

```vim
echo luaeval('print')
call luaeval('print')('hello')
```

**Comment by Th3Whit3Wolf** [comment]
removing `local vim = vim` doesn't fix it for me.

**Comment by wbthomason** [comment]
@Th3Whit3Wolf: Just to confirm, after commenting `local vim = vim` and recompiling, you still have invalid code generated?

**Comment by Th3Whit3Wolf** [comment]
> @Th3Whit3Wolf: Just to confirm, after commenting `local vim = vim` and recompiling, you still have invalid code generated?

That's correct, I am using a different system now and have upgraded to neovim version `v0.5.0-851-g97ffa158a` and am using the latest version of packer.

Here is my plug.lua

```lua
local packer = nil

local function init()
  if packer == nil then
    packer = require("packer")
    packer.init({})
  end

  local use = packer.use
  packer.reset()

  use {"wbthomason/packer.nvim", opt = true}

  -- Collection of common configurations for the Nvim LSP client.
  use {
    "neovim/nvim-lspconfig"
  }

  -- bunch of info & extension callbacks for built-in LSP (provides inlay hints)
  use {
    "tjdevries/lsp_extensions.nvim"
  }

  -- auto completion framework that aims to provide a better completion experience with neovim's built-in LSP
  use {
    "nvim-lua/completion-nvim",
    config = function()
      require "plugins.lsp"
    end
  }

  use {
    "Th3Whit3Wolf/space-nvim-theme",
    branch = "main",
    config = function()
      vim.cmd("colorscheme space-nvim-theme")
    end
  }

  -- Simpler Rainbow Parentheses
  use {
    "junegunn/rainbow_parentheses.vim",
    event = "InsertEnter *",
    config = function()
      vim.cmd("RainbowParentheses")
    end
  }
end

local plugins =
  setmetatable(
  {},
  {
    __index = function(_, key)
      init()
      return packer[key]
    end
  }
)
return plugins
```

I get the following error

```vim
E5108: Error executing lua [string "..."]:0: Vim(for):E714: List required
```

Here's my packer_compiled.vim

```vim
" Automatically generated packer.nvim plugin loader code

if !has('nvim')
  finish
endif

lua << END
local plugins = {
  ["packer.nvim"] = {
    loaded = false,
    only_sequence = false,
    only_setup = false,
    path = "/home/doc/.local/share/nvim/site/pack/packer/opt/packer.nvim"
  },
  ["rainbow_parentheses.vim"] = {
    config = { "\27LJ\1\0026\0\0\2\0\3\0\0054\0\0\0007\0\1\0%\1\2\0>\0\2\1G\0\1\0\23RainbowParentheses\bcmd\bvim\0" },
    loaded = false,
    only_sequence = false,
    only_setup = false,
    path = "/home/doc/.local/share/nvim/site/pack/packer/opt/rainbow_parentheses.vim"
  }
}

local function handle_bufread(names)
  for _, name in ipairs(names) do
    local path = plugins[name].path
    for _, dir in ipairs({ 'ftdetect', 'ftplugin', 'after/ftdetect', 'after/ftplugin' }) do
      if #vim.fn.finddir(dir, path) > 0 then
        vim.cmd('doautocmd BufRead')
        return
      end
    end
  end
end

_packer_load = nil

local function handle_after(name, before)
  local plugin = plugins[name]
  plugin.load_after[before] = nil
  if next(plugin.load_after) == nil then
    _packer_load({name}, {})
  end
end

_packer_load = function(names, cause)
  local some_unloaded = false
  for _, name in ipairs(names) do
    if not plugins[name].loaded then
      some_unloaded = true
      break
    end
  end

  if not some_unloaded then return end

  local fmt = string.format
  local del_cmds = {}
  local del_maps = {}
  for _, name in ipairs(names) do
    if plugins[name].commands then
      for _, cmd in ipairs(plugins[name].commands) do
        del_cmds[cmd] = true
      end
    end

    if plugins[name].keys then
      for _, key in ipairs(plugins[name].keys) do
        del_maps[key] = true
      end
    end
  end

  for cmd, _ in pairs(del_cmds) do
    vim.cmd('silent! delcommand ' .. cmd)
  end

  for key, _ in pairs(del_maps) do
    vim.cmd(fmt('silent! %sunmap %s', key[1], key[2]))
  end

  for _, name in ipairs(names) do
    if not plugins[name].loaded then
      vim.cmd('packadd ' .. name)
      if plugins[name].config then
        for _i, config_line in ipairs(plugins[name].config) do
          loadstring(config_line)()
        end
      end

      if plugins[name].after then
        for _, after_name in ipairs(plugins[name].after) do
          handle_after(after_name, name)
          vim.cmd('redraw')
        end
      end

      plugins[name].loaded = true
    end
  end

  handle_bufread(names)

  if cause.cmd then
    local lines = cause.l1 == cause.l2 and '' or (cause.l1 .. ',' .. cause.l2)
    vim.cmd(fmt('%s%s%s %s', lines, cause.cmd, cause.bang, cause.args))
  elseif cause.keys then
    local keys = cause.keys
    local extra = ''
    while true do
      local c = vim.fn.getchar(0)
      if c == 0 then break end
      extra = extra .. vim.fn.nr2char(c)
    end

    if cause.prefix then
      local prefix = vim.v.count and vim.v.count or ''
      prefix = prefix .. '"' .. vim.v.register .. cause.prefix
      if vim.fn.mode('full') == 'no' then
        if vim.v.operator == 'c' then
          prefix = '' .. prefix
        end

        prefix = prefix .. vim.v.operator
      end

      vim.fn.feedkeys(prefix, 'n')
    end

    -- NOTE: I'm not sure if the below substitution is correct; it might correspond to the literal
    -- characters \<Plug> rather than the special <Plug> key.
    vim.fn.feedkeys(string.gsub(string.gsub(cause.keys, '^<Plug>', '\\<Plug>') .. extra, '<[cC][rR]>', '\r'))
  elseif cause.event then
    vim.cmd(fmt('doautocmd <nomodeline> %s', cause.event))
  elseif cause.ft then
    vim.cmd(fmt('doautocmd <nomodeline> %s FileType %s', 'filetypeplugin', cause.ft))
    vim.cmd(fmt('doautocmd <nomodeline> %s FileType %s', 'filetypeindent', cause.ft))
  end
end

-- Runtimepath customization

-- Pre-load configuration
-- Post-load configuration
-- Config for: completion-nvim
loadstring("\27LJ\1\2+\0\0\2\0\2\0\0044\0\0\0%\1\1\0>\0\2\1G\0\1\0\16plugins.lsp\frequire\0")()
-- Config for: space-nvim-theme
loadstring("\27LJ\1\2@\0\0\2\0\3\0\0054\0\0\0007\0\1\0%\1\2\0>\0\2\1G\0\1\0!colorscheme space-nvim-theme\bcmd\bvim\0")()
-- Conditional loads
-- Load plugins in order defined by `after`
END

function! s:load(names, cause) abort
call luaeval('_packer_load(_A[1], _A[2])', [a:names, a:cause])
endfunction


" Command lazy-loads

" Keymap lazy-loads

augroup packer_load_aucmds
  au!
  " Filetype lazy-loads
  " Event lazy-loads
  au InsertEnter * ++once call s:load(['rainbow_parentheses.vim'], { "event": "InsertEnter *" })
augroup END

```

**Comment by Th3Whit3Wolf** [comment]
I don't think I've mentioned this yet but I'm running on linux if that's relevant.

**Comment by nanotee** [comment]
Okay, had another go at this, I really hope I got it this time because it's been bugging me

I ended up installing the config outright to see what was going on and I think I found the culprit: https://github.com/Th3Whit3Wolf/Almost-Finished-Neovim-Config/blob/19d423dab36289ded345803232d119ca2fe7ed5e/lua/variables.lua#L41

RainbowParentheses expects `g:rainbow#pairs` to be a list, but it's a string in your config

(I think I've learned to appreciate backtraces and good error messages a little bit more today :smile:)

**Comment by wbthomason** [comment]
Fingers crossed, since I have not been able to isolate this to anything with `packer` (I admit I hadn't had the time to go through your config yet, @Th3Whit3Wolf).

@Th3Whit3Wolf: Does @nanotee's suggestion fix this issue for you?

**Comment by Th3Whit3Wolf** [comment]
> (I think I've learned to appreciate backtraces and good error messages a little bit more today smile)

@nanotee Same here 100%!! That fixed it thank you so much for your help!

@wbthomason @nanotee suggestions fixed the issue. Sorry for filing out an issue for my own mistake.

**Comment by wbthomason** [comment]
No worries, I'm glad things are working for you! Thanks (yet again) @nanotee for the help!
