### ISSUE TITLE
packer.nvim Failed  to install

### ISSUE THREAD

**Issue by jclivi** [wbthomason/packer.nvim#645]
![2021-10-10_12-30](https://user-images.githubusercontent.com/14210650/136704945-6281e387-a5f9-4c49-9316-dff6faf66ab0.png)

**Comment by gmr458** [comment]
![image](https://user-images.githubusercontent.com/53343401/136715252-13d17702-9de0-4040-bd62-371857d6be8b.png)

**Comment by wbthomason** [comment]
@jicvi: Sorry, I mean the contents of https://github.com/wbthomason/packer.nvim/blob/master/.github/ISSUE_TEMPLATE/bug_report.md - specifically, I need your plugin specification file and log file.

**Comment by jicvi** [comment]
@wbthomason 
Thank you. I found the Lua environment path was wrong.
