### ISSUE TITLE
disable autoload of not 'used' plugins

### ISSUE THREAD

**Issue by fedoranvar** [wbthomason/packer.nvim#646]
Good day to you!

I have constraint in neovim config,that gives me abillity to choose between minimal and full configs.
![image](https://user-images.githubusercontent.com/52028706/136834218-e68f2310-cc9c-4e01-8ece-abb9de83e0ca.png)

I have all plugins installed (cloned) in packer directory.

When i try to load minimal config, even if i do not `use` some plugins - they still autoloaded (VimL).
![image](https://user-images.githubusercontent.com/52028706/136834418-d67230b8-b319-4790-b69d-8aff710bf80c.png)

Question: is it possible to not autoload not `use`'d plugins? (Maybe some argument in `use {}`?

Thank you!

**Comment by wbthomason** [comment]
Sorry, but I'm not sure I understand what you're after here - you want to replace the `...` with some module name, but automatically?
