### ISSUE TITLE
packer_compile.vim does not degrade gracefully when sourced with vim

### ISSUE THREAD

**Issue by EdenEast** [wbthomason/packer.nvim#65]
I use the same configuration for both nvim and vim. I use nvim primarily but sometimes I have to use vim (when making a git commit when I am on mintty/git-bash). In my configuration I feature check and gracefully degrade my configuration. That means that I will not have all my plugins and nice to haves but my core vim settings will be the same. This is fine for the small instances where I have to use vim.

Currently the `packer_compiled.vim` file is added to the plugin folder in your runtimepath. When running vim I get these errors

```
Error detected while processing /c/Users/James/.local/share/nvim/plugin/packer_compiled.vim:
line    3:
E319: Sorry, the command is not available in this version: lua << END
line    4:
E492: Not an editor command: local plugins = {
line    5:
E492: Not an editor command:   ["packer.nvim"] = {
...
```

Having a feature guard for `nvim` before the `lua` section would solve this issue.

**Comment by wbthomason** [comment]
Thank you for the report and PR! I've merged your changes in.
