### ISSUE TITLE
Update only one plugin.

### ISSUE THREAD

**Issue by shift-d** [wbthomason/packer.nvim#654]
### Describe the feature
I'd like update only one plugin instead of syncing/updating everything. Updating all plugins takes a lot of time, even if I'd like to update only one.

**Comment by shadmansaleh** [comment]
You already can . Just enter name of plugins after `:PackerUpdate` .

**Comment by wbthomason** [comment]
Or in a call to `packer.update` (same thing). You can, in fact, pass any subset of your plugins to specifically update.

**Comment by shift-d** [comment]
Woah, did not know that was a thing, thanks for pointing it out.
