### ISSUE TITLE
Variables in closures passed to config field a plugin is not preserved

### ISSUE THREAD

**Issue by doctoromer** [wbthomason/packer.nvim#655]
Hey, I found out that when I try to pass a closure to `config` field of a plugin, the environment of the function is not preserved.
This is caused due to compilation of the function in `packer_compiled.lua` file (The environment is not serialized).
Why I need it? I'm trying to write factory function that bundles additional behavior with each `config` function.

It can be implemented with `getfenv` and adding additional field in the `packer_compiled.lua`.
Alternatively, passing the name of the plugin to the config function will solve the problem. although,  It'll be less elegant.

I'm willing to solve this myself and open a pull request, but I'm not sure what the best way to handle it.

- `nvim --version`: v0.5.0
- `git --version`: 2.33.0
- Operating system/version: Ubuntu 18.04.6
- Terminal name/version: GNOME terminal 3.28.2

### Steps to reproduce

- Use this code:

```lua
function test(param)
  return function()
    print(param)
  end
end

packer.startup(function()
  use {
    "tpope/vim-surround",
    config = test(6)
  }
end)
```
- Enter vim and execute `PackerCompile`

### Actual behaviour
The value `nil` will be printed.

### Expected behaviour
The value `6` should be printed.

**Comment by babygau** [comment]
This is a long-standing issue. Please see https://github.com/wbthomason/packer.nvim/discussions/443

**Comment by doctoromer** [comment]
I guess I missed that when searching for existing issue...
Is there any estimation for solving this problem? It'll help me alot.

Thanks!

**Comment by babygau** [comment]
Sadly no ETA 😭

**Comment by babygau** [comment]
Yes, it's possible. Please see the following snippet from `null-ls` author (and other plugins you might love) for your reference
 https://github.com/jose-elias-alvarez/dotfiles/blob/main/.config/nvim/lua/plugins/init.lua#L5-L11

**Comment by doctoromer** [comment]
This is a very nice to work around the issue! Although, it makes me put one function in a file, so this is not feasible.
I think I'll open a pull request to pass the plugin name to the `config` function and we'll see how it goes.

Thanks for the help and the quick responding time!

**Comment by akinsho** [comment]
@doctoromer it's probably best to wait for @wbthomason's input before spending time on a PR

**Comment by wbthomason** [comment]
@Hrle97 I'm currently prioritizing #402, which should fix this issue by no longer using `string.dump`. If that, for whatever reason, should fall through, then including something like that gist could be a good alternative, thanks!

**Comment by doctoromer** [comment]
Hey, any chance this will be merged?

**Comment by doctoromer** [comment]
If not, I just want to know so I can solve this problem in another way in my config...

**Comment by wbthomason** [comment]
@doctoromer: Sorry, I'd hoped to finish #402 by now, but haven't had the time I expected to. I'll take a look at #667 now - it's still marked as a draft, but I assume it's ready for review?

**Comment by doctoromer** [comment]
Hey, no problem. thanks for merging!
