### ISSUE TITLE
Failed to call loader() because commit 755f7c4a1

### ISSUE THREAD

**Issue by ray-x** [wbthomason/packer.nvim#659]
- `nvim --version`:  nvim 0.6.0
- `git --version`: 2.33
- Operating system/version: Mac
- Terminal name/version: Kitty

### Steps to reproduce
The loader API used to accept string of plugins
e.g.
```lua 
require"packer".loader("nvim-treesitter nvim-treesitter-refactor nvim-ts-autotag nvim-ts-context-commentstring")
```

Currently, it only accept either
```lua
require"packer".loader("nvim-treesitter")
```
-- or  a list
```lua
require"packer".loader({"nvim-treesitter", "nvim-treesitter-refactor"})
```

This was caused by changes of removing following code in 755f7c4a1c4d92da7cda947efa5e5aed1d010a3a:

```
 local plugin_list = vim.tbl_filter(function(name)
    return #name > 0
  end, vim.split(plugins_names, ' '))
```

### Actual behaviour
Error message and plugins failed load:
```
site/pack/packer/start/packer.nvim/lua/packer/load.lua:127: Error: attempted to load gitsigns.nvim neogit vgit.nvim which is not present in plugins table! 
```

### Expected behaviour

No errors and backward compatible.

### packer files

<details>
<summary>Plugin specification file(s)</summary>

Post or link your plugin specification files here, if you aren't able to provide a minimal
reproducer

</details>

<details>
<summary>packer log file</summary>

Post the contents of ~/.cache/nvim/packer.nvim.log here

</details>

<details>
<summary>packer compiled file</summary>

Post the contents of `packer_compiled.vim` here

</details>

**Comment by ray-x** [comment]
Thanks for the quick fix. Your fix branch works fine for me.

**Comment by wbthomason** [comment]
Thanks for trying it out!
