### ISSUE TITLE
[packer.nvim] [ERROR 10:11:18] async.lua:20: Error in coroutine: ...packer/start/packer.nvim/lua/packer/plugin_types/git.lua:332: attempt to  concatenate field 'msg' (a nil value)

### ISSUE THREAD

**Issue by gufeng0** [wbthomason/packer.nvim#668]
Just did a :PackerSync and hit this bug in a previously working setup.

After the update, All plug-in updates failed.

It logs the error (in nvim):

[packer.nvim] [ERROR 10:15:33] async.lua:20: Error in coroutine: ...packer/start/packer.nvim/lua/packer/plugin_types/git.lua:332: attempt to concatenat
[packer.nvim] [ERROR 10:15:34] async.lua:20: Error in coroutine: ...site/pack/packer/start/packer.nvim/lua/packer/update.lua:97: attempt to index local
 'r' (a nil value)

nvim --version: NVIM v0.5.0
git --version: git version 2.31.1
Operating system/version: mac

**Comment by wbthomason** [comment]
Thanks for your report! I'll need a bit more information to help:
- Did you change anything with your setup between this and your previous attempt to sync?
- Does this error persist every time you run sync? (i.e. it may be an intermittent race condition)
- Please share your packer log file and plugin specification file

**Comment by cseickel** [comment]
@shuaixiaomi I'm having the same problem, do you remember what **_did_** cause this error for you?

**Comment by cseickel** [comment]
For others that might find this, I think the issue was a plugin with errors in it's setup function. I removed an obsolete fork of which-key and that fixed it for me.

**Comment by shuaixiaomi** [comment]
> @shuaixiaomi I'm having the same problem, do you remember what **_did_** cause this error for you?

The reason for this error is that cannot connect to gitHub during update.

**Comment by amada95** [comment]
I'm still having this particular issue on macOS:

- `nvim --version`
```
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.0/share/nvim"

Run :checkhealth for more info
```
