### ISSUE TITLE
Error with vim.schedule on PackerInstall

### ISSUE THREAD

**Issue by FabioRamatis** [wbthomason/packer.nvim#67]
This happens every time I run :PackerInstall, the strange behavior is that actually installs correctly.
![Screen Shot 2020-10-14 at 11 44 31](https://user-images.githubusercontent.com/69860869/96005235-a4156d80-0e12-11eb-978f-5e621fb80baf.png)

my init.vim
```vim
" Ask on packer github repo if this is the best approach
packadd packer.nvim
packadd srcery-vim
packadd nvim-lspconfig
packadd completion-nvim
packadd BetterLua.vim
packadd nlua.nvim
packadd plenary.nvim
packadd express_line.nvim
packadd diagnostic-nvim
packadd popup.nvim
packadd telescope.nvim
packadd nvim-colorizer.lua
packadd vim-fugitive
packadd vim-surround
packadd vim-repeat
packadd vim-easymotion
packadd auto-pairs
packadd vim-commentary
packadd vim-eunuch
packadd ferret
packadd quickfix-reflector.vim
packadd terminus
packadd emmet-vim
packadd vim-dirvish
packadd vim-dirvish-dovish
packadd vim-bujo
packadd nvim-web-devicons
packadd popfix
packadd nvim-lsputils
packadd snippets.nvim

" TODO: do this from lua side
let g:ale_fixers = {
\   '*': ['remove_trailing_lines', 'trim_whitespace'],
\   'typescriptreact': ['prettier', 'eslint'],
\}
let g:ale_disable_lsp = 1
let g:ale_fix_on_save = 1
packadd ale

" Need to load before
let g:polyglot_disabled = ['lua']
packadd vim-polyglot

" TODO: do this from lua side
map <space> <Plug>(easymotion-prefix)

lua require('init')
```

my init.lua

```lua
local api = vim.api
local fn = vim.fn
local luv = vim.loop

local packer_path = luv.os_homedir() .. '/.local/share/nvim/site/pack/packer/opt/packer.nvim'

api.nvim_command('packadd packer.nvim')
-- Temporary until https://github.com/neovim/neovim/pull/12632 is merged
vim._update_package_paths()

local packer = require('packer')
local packages = require('packages')

packer.startup(function()
  for key, value in pairs(packages) do
    packer.use(value)
  end

  -- Temporary until https://github.com/neovim/neovim/pull/12632 is merged
  vim._update_package_paths()
end)

require('settings')
require('config.lsp')
require('config.mappings')
require('config.custom_commands')
require('config.statusline')
require('config.telescope')
require('config.colorizer')
require('config.fugitive')
require('config.dirvish')
require('config.bujo')
require('config.devicons')
```

my packages.lua

```lua
local packages = {
	{ 'wbthomason/packer.nvim', opt = true },
	{ 'srcery-colors/srcery-vim', opt = true },
	{ 'neovim/nvim-lspconfig', opt = true },
	{ 'nvim-lua/completion-nvim', opt = true },
	{ 'tjdevries/nlua.nvim', opt = true },
	{ 'euclidianAce/BetterLua.vim', opt = true },
	{ 'nvim-lua/plenary.nvim', opt = true },
	{ 'nvim-lua/popup.nvim', opt = true },
	{ 'tjdevries/express_line.nvim', opt = true },
	{ 'nvim-lua/diagnostic-nvim', opt = true },
	{ 'nvim-lua/telescope.nvim', opt = true },
	{ 'norcalli/nvim-colorizer.lua', opt = true },
	{ 'tpope/vim-fugitive', opt = true },
	{ 'easymotion/vim-easymotion', opt = true },
	{ 'jiangmiao/auto-pairs', opt = true },
	{ 'tpope/vim-commentary', opt = true },
	{ 'sheerun/vim-polyglot', opt = true },
	{ 'tpope/vim-surround', opt = true },
	{ 'tpope/vim-eunuch', opt = true },
	{ 'tpope/vim-repeat', opt = true },
	{ 'wincent/ferret', opt = true },
	{ 'stefandtw/quickfix-reflector.vim', opt = true },
	{ 'wincent/terminus', opt = true },
	{ 'mattn/emmet-vim', opt = true },
	{ 'justinmk/vim-dirvish', opt = true },
	{ 'roginfarrer/vim-dirvish-dovish', opt = true },
	{ 'dense-analysis/ale', opt = true },
	{ 'vuciv/vim-bujo', opt = true },
	{ 'kyazdani42/nvim-web-devicons', opt = true },
	{ 'RishabhRD/popfix', opt = true },
	{ 'RishabhRD/nvim-lsputils', opt = true },
	{ 'norcalli/snippets.nvim', opt = true }
	-- TODO: find a different binding to this
	-- { 'inkarkat/vim-ReplaceWithRegister', opt = true },
}

return packages
```

**Comment by wbthomason** [comment]
Thanks for the report! Given the error message, I suspect that something in your settings or autocommands is interfering (e.g. something like the problem in https://github.com/neovim/neovim/issues/9755). Could you post the contents of those files (I looked at your dotfiles repo, but it doesn't seem to have your Neovim config)?

Also, re: your comment around the use of `packadd`: You totally don't need to do that. I'd suggest you read about the native packages feature (`:help packages`), but the short version is this:
- If you want the plugin loaded in your `init.vim`, you **do** need to `packadd` it
- If you just want to configure the plugin, put a file in `~/.config/nvim/plugin/<SOMETHING>.vim` to configure it and don't mark it as `opt`; the plugin will be loaded by then
- If you want to lazy-load a plugin, use one of the facilities `packer` provides to do this (e.g. on filetype, event, command, etc.)
- You never need to manually mark something as `opt` unless you're going to control its loading manually later (i.e. not using one of `packer`'s lazy-loaders)

**Comment by FabioRamatis** [comment]
About the packadd, I want to configure the plugins from lua files and the only way that worked was with this approach.

My config - https://github.com/cherryramatis/vim-astronaut

**Comment by wbthomason** [comment]
Thanks! One note - you have both `packer_load.vim` and `packer_compiled.vim` in your `plugins` dir (probably left over from when the default name was changed, sorry), which is presumably not what you want. I'd recommend deleting both and recompiling, just in case.

**Comment by wbthomason** [comment]
> I want to configure the plugins from lua files and the only way that worked was with this approach

jsyk, you could use the `config` key feature of `packer` to do this without needing the explicit `packadd` invocations, but that's down to personal preference.

**Comment by FabioRamatis** [comment]
Ok I recompile! Thanks very much

In this config key, I can require a different file and configure from there? It'll be the goal for me

**Comment by wbthomason** [comment]
Yes - the config key can be any valid Lua string or function. Please let me know if the recompile fixes anything, but I don't expect it to. 

I'm not sure what could cause saving undo information to fail, so I'm asking in the Neovim Gitter to see if anyone has any idea what could cause this, since I cannot reproduce it. Thanks for your patience and help!

**Comment by FabioRamatis** [comment]
Recompile don't change anything at all.

I'm looking at my autocmds but no clue right now, I'll let with you guys to help me haha

Thank you for your patience! I love your package, it's helping me keep a neovim config 100% lua

**Comment by wbthomason** [comment]
One other question: do you see this error on `PackerUpdate` too, or just `PackerInstall`?

And thanks! I'm glad you like it!

**Comment by tjdevries** [comment]
Try updating to latest nvim, see if that fixes it.

**Comment by FabioRamatis** [comment]
Yes! I see this error on PackerUpdate and PackerInstall

**Comment by FabioRamatis** [comment]
![Screen Shot 2020-10-14 at 17 52 30](https://user-images.githubusercontent.com/69860869/96043946-09368680-0e46-11eb-96d1-e701bc96b864.png)
@tjdevries I'm using this version actually

**Comment by tjdevries** [comment]
Is that the latest nightly? I don't know off hand if it is or not.

**Comment by FabioRamatis** [comment]
I build from source and worked now! Thank you so much @tjdevries 

Saved me two times hahah

Thank you for the patience @wbthomason

**Comment by wbthomason** [comment]
Great, thanks!

Thanks for the help, @tjdevries!
