### ISSUE TITLE
Installation of local plugins on Windows requires running with Admin privileges

### ISSUE THREAD

**Issue by nonsleepr** [wbthomason/packer.nvim#679]
- `nvim --version`:
```
NVIM v0.5.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 -DNVIM_TS_HAS_SET_MATCH_LIMIT /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compiled by runneradmin@fv-az152-633

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```
- `git --version`:
```
git version 2.33.1.windows.1
```
- Operating system/version: Windows 10
- Terminal name/version: PowerShell

### Steps to reproduce

1. Add local plugin, e.g. by adding `use '~/path/to/local-plugin'`
2. Run `:PackerInstall`

### Actual behaviour

Operation results in the error:

```
✗ Failed to install C:\Users\username\path\to\local-plugin
  Errors:
    EPERM: operation not permitted: C:\Users\username\path\to\local-plugin
```

### Expected behaviour

Plugin installs successfully.

**Comment by nonsleepr** [comment]
## Error Cause

I investigated the reason for the error and found out that Packer attempts to symlink the directory [here](https://github.com/wbthomason/packer.nvim/blob/3fdea07bec6cb733d2f82e50a10829528b0ed4a9/lua/packer/plugin_types/local.lua#L24). Unfortunately, simlinking on Windows requires admin privileges.

## Workaround

[`fs_symlink`](https://github.com/neovim/deps/blob/master/src/luv/docs.md#uvfs_symlinkpath-new_path-flags-callback) can be told to create a junction, which doesn't require admin rights.

To test if that works I added the following code before calling Packer (it doesn't handle the cases where the call is used to simlink the file, not directory):

```lua
--[[ Patch fs_symlink to use junction which doesn't require admin rights on Windows ]]--
local orig_fs_symlink = vim.loop.fs_symlink
vim.loop.fs_symlink = function(path, new_path, flags, callback)
  if type(flags) == 'nil' then
    flags = {}
  end
  flags.junction = true
  return orig_fs_symlink(path, new_path, flags, callback)
end
```
With that `:PackerInstall` succeeds.

There are downsides to using junctions, e.g. junction can't be used to simlink files. See [this StackOverflow post](https://stackoverflow.com/a/48586946) for more details.

**Comment by tahir-hassan** [comment]
They have updated the master branch for the [local.lua](https://github.com/wbthomason/packer.nvim/blob/master/lua/packer/plugin_types/local.lua), therefore I take it that Windows users don't have to worry about this anymore?

Perhaps the README.md should reflect that it has been fixed?
