### ISSUE TITLE
Lockfile for installed packages 

### ISSUE THREAD

**Issue by shaunsingh** [wbthomason/packer.nvim#695]
### Describe the feature
Neovim plugins change every day, and breaking changes seem to happen every week. On my computer, I run `:PackerSync`, sort out the errors one a week. However, the issue is whenever I use a new laptop and `git clone` my config, then run `:PackeSync`, the plugins have breaking changes since they're newer and I need to go through it all over again 

The solution currently is to pin packages, but its a pain to go through my 50 or so packages and manually update each one. I was wondering if a lock file is possible,

 e.g. nix https://github.com/shaunsingh/nix-darwin-dotfiles/blob/36f8180da0dde786611d6ddea6889a4567482ff5/flake.lock. When I install my nix config, all the dependencies use the commits specified in the lock file, ensuring that my config is the *exact* same across different machines. I can run `nix flake update` to update that lock file to the latest version of each input 
 
 In packer's case, `:PackerSync` should install the plugins according to the rev's specified in the lock file, and a command like `:PackerLock` can be used to update the lock file itself.

**Comment by bew** [comment]
Looks like a duplicate of #298

**Comment by shaunsingh** [comment]
Ah I didn't see that, I searched for `lockfile` and didn't find anything so I assumed no-one asked yet. 

Thanks! closing this in favor of that issue

**Comment by YodaEmbedding** [comment]
Related discussion: 
> https://github.com/wbthomason/packer.nvim/discussions/914):
> 
> How do I use packer snapshots in the exact same way as a `.lock` file?
> 
> [This](https://github.com/YodaEmbedding/dotfiles/blob/3599c4df0ba62bc59dd290c1ea029d161f419c4d/nvim/.config/nvim/lua/plugins/_packer.lua#L132-L139) almost works:
> 
> ```lua
> packer.startup {
>   packer_spec,
>   config = {
>     snapshot = util.join_paths(vim.fn.stdpath("config"), "packer-lock.json"),
>     snapshot_path = vim.fn.stdpath("config"),
>   },
> }
> ```
> 
> ...except that it _always_ tries to rollback on every neovim startup, not merely on `:PackerSync`, which is how `.lock` files usually work.
> 
> Output of `:messages`:
> 
> ```
> Rollback to "/home/username/dotfiles/nvim/.config/nvim/packer-lock.json" completed
> ```
> 
> Also, annoyingly, I have to press enter every time to hide this status message.
