### ISSUE TITLE
Icons in packer.nvim

### ISSUE THREAD

**Issue by bryant-the-coder** [wbthomason/packer.nvim#696]
Is it possible to add icons in the packer.nvim? Like when it fails to install something, the icon will be a X. Is it possible?

**Comment by clason** [comment]
Yes, of course: https://github.com/wbthomason/packer.nvim/blob/7f62848f3a92eac61ae61def5f59ddb5e2cc6823/doc/packer.txt#L223-L228

**Comment by bryant-the-coder** [comment]
Which part?? Kinda hard to read :(

**Comment by bryant-the-coder** [comment]
Example config? Newbie still... 😞

**Comment by bryant-the-coder** [comment]
Uhm?

**Comment by bryant-the-coder** [comment]
> Uhm? 

I will figure it myself then after school. Sorry for disturbing
