### ISSUE TITLE
Running PackerSync/PackerUpdate as a command line job?

### ISSUE THREAD

**Issue by ristillu** [wbthomason/packer.nvim#700]
I've recently migrated from vim + vim-plug to neovim + packer. I really like packer and it's working great for me. I wanted to automate my updating in let's say a cron job so in a script I tried the command:
`nv -es -i NONE -u ~/.config/nvim/init.lua -c "PackerSync" -c "qa"`
This command executes immediately and nothing happens. I know this because if a dependency has updated I can go in to a regular nvim session and run `PackerSync` or `PackerUpdate` manually and it will pull and update. I'm wondering if this is because of the `-c "qa"` immediately after the update? Because if I omit that part then it spawns a nvim session and the update occurs correctly. So I'm guessing that in my command nvim starts, packer tries to spawn a sync process but is interrupted by the `qa` and therefore never completes?

This is fairly niche but if you know of a way to achieve my use case I'd appreciate it.

**Comment by ristillu** [comment]
I should have read the manual ... my friend pointed out to me that it's in there:
`nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'`

**Comment by sdondley** [comment]
Google it was easier than finding it in the manual. So thanks for not reading it.

**Comment by Compree** [comment]
This (not Googling and not reading the manual) might be something that ChatGPT is actually good for :-)
