### ISSUE TITLE
 a...local 'display_win' (a nil value)[packer.nvim] [ERROR 02:39:05] a...local 'display_win' (a nil value)

### ISSUE THREAD

**Issue by defp** [wbthomason/packer.nvim#701]
- `nvim --version`: 

```
NVIM v0.5.1
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20211103-7276-u4ywwo/neovim-0.5.1/build/config -I/tmp/neovim-20211103-7276-u4ywwo/neovim-0.5.1/src -I/opt/homebrew/include -I/tmp/neovim-20211103-7276-u4ywwo/neovim-0.5.1/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include -I/opt/homebrew/opt/gettext/include -I/tmp/neovim-20211103-7276-u4ywwo/neovim-0.5.1/build/src/nvim/auto -I/tmp/neovim-20211103-7276-u4ywwo/neovim-0.5.1/build/include
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.5.1_1/share/nvim"

Run :checkhealth for more info
```

- `git --version`:
- Operating system/version: 
![image](https://user-images.githubusercontent.com/612381/142476812-2ba4bcb4-4a68-4b67-b96e-402ebe2ffaa6.png)

- Terminal name/version:

### packer files

<details>
<summary>Plugin specification file(s)</summary>

init.lua 

```
require('plugins')
```

plugins.lua

```
local fn = vim.fn
local install_path = fn.stdpath('data')..'/site/pack/packer/start/packer.nvim'
if fn.empty(fn.glob(install_path)) > 0 then
  packer_bootstrap = fn.system({'git', 'clone', '--depth', '1', 'https://github.com/wbthomason/packer.nvim', install_path})
end

return require('packer').startup(function(use)
  -- My plugins here
  -- use 'foo1/bar1.nvim'
  -- use 'foo2/bar2.nvim'

  -- Automatically set up your configuration after cloning packer.nvim
  -- Put this at the end after all plugins
  if packer_bootstrap then
    require('packer').sync()
  end
end)
```

</details>

<details>
<summary>packer log file</summary>

```
❯ cat ~/.cache/nvim/packer.nvim.log
[WARN  Fri Nov 19 02:44:02 2021 2.8174368419658e+14] .../site/pack/packer/start/packer.nvim/lua/packer/clean.lua:75: Could not remove /Users/lidashuang/.local/share/nvim/site/pack/packer/start/packer.nvim
[ERROR Fri Nov 19 02:44:02 2021 2.8174368444758e+14] .../site/pack/packer/start/packer.nvim/lua/packer/async.lua:20: Error in coroutine: ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:570: attempt to index local 'display_win' (a nil value)
[ERROR Fri Nov 19 02:44:02 2021 2.8174368453246e+14] .../site/pack/packer/start/packer.nvim/lua/packer/async.lua:20: Error in coroutine: ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:570: attempt to index local 'display_win' (a nil value)
[WARN  Fri Nov 19 02:44:45 2021 2.8178698160542e+14] .../site/pack/packer/start/packer.nvim/lua/packer/clean.lua:75: Could not remove /Users/lidashuang/.local/share/nvim/site/pack/packer/start/packer.nvim
[ERROR Fri Nov 19 02:44:45 2021 2.8178698237663e+14] .../site/pack/packer/start/packer.nvim/lua/packer/async.lua:20: Error in coroutine: ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:570: attempt to index local 'display_win' (a nil value)
[ERROR Fri Nov 19 02:44:45 2021 2.8178698245017e+14] .../site/pack/packer/start/packer.nvim/lua/packer/async.lua:20: Error in coroutine: ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:570: attempt to index local 'display_win' (a nil value)
~/.config/nvim
```

</details>

<details>
<summary>packer compiled file</summary>

Post the contents of `packer_compiled.vim` here

</details>

**Comment by jackpeters667** [comment]
I'm also getting this on a clean install. Just neovim 0.5 and so far packer (which is failing to initialise).

Do you have any progress? I'm using the code in `bootstrapping` in the Readme.

**Comment by joshstobbs** [comment]
I am an echoing voice to this choir - I'm using more or less the same setup as defp (Monterey, nvim 5.1, etc...) and am receiving the same error.

In the same vein like jackpeters667, I've just grabbed the `bootstrapping` code assuming that would work.  Any help would be definitely appreciated!

**Comment by thebearjew** [comment]
Also hitting this issue on Neovim nightly version 0.6

```
NVIM v0.6.0-dev+625-gc132144d2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by CASE@ava.lan

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-c132144_1/share/nvim"

Run :checkhealth for more info
```

**Comment by SibLiant** [comment]
I recompiled from latest source and all is well.

**Comment by wbthomason** [comment]
I haven't been able to reproduce this yet. @SibLiant, what commit of upstream fixed this for you?

**Comment by SibLiant** [comment]
@wbthomason 

`04c7b550384b2246d37c1a893c0f858bc332cb8b
`
```
NVIM v0.6.0-dev+650-g04c7b5503
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/sib/source_neovim/build/config -I/home/sib/source_neovim/src -I/home/sib/source_neovim/.deps/usr/include -I/usr/include -I/home/sib/source_neovim/build/src/nvim/auto -I/home/sib/source_neovim/build/include
Compiled by sib@valla

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/sib/dotfiles/bin/share/nvim"

Run :checkhealth for more info
```

**Comment by defp** [comment]
![image](https://user-images.githubusercontent.com/612381/147640850-adf8bce1-5aca-4d6c-93f5-cd9183d50fc3.png)

**Comment by meijieru** [comment]
Hit this issue on latest nightly.
```
NVIM v0.7.0-dev+839-g09d270bce
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

**Comment by wbthomason** [comment]
@pawmot (or others) do you have more details on the error? In particular, a line number in the error message, or steps to reproduce the error?

**Comment by dustinru** [comment]
@wbthomason Not sure if this is exactly the same as everyone else or the right place but I've been getting the same error message when it attempts to remove the start/packer.nvim directory upon first startup.
```
nvim -v
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
NVIM v0.6.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```
The exact error line is as follows:
`[packer.nvim] [ERROR 01:49:47] async.lua:20: Error in coroutine: ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:570: attempt to index local 'display_win' (a nil value)`
That said, I've been having overall permission issues with my neovim/packer.nvim config on a fresh install w/o any plugins so it could be related. I've had to create the opt directory myself to even get to this point because Packer could not do it automatically via the bootstrapping method and outputting permission denied errors.

This is with Ubuntu 20.04 on WSL using the latest prebuilt nvim.appimage on the Neovim Github Repo.

**Comment by pawmot** [comment]
> @pawmot (or others) do you have more details on the error? In particular, a line number in the error message, or steps to reproduce the error?

I don't have precise steps to reproduce right now unfortunately, sorry about that. IIRC the error message was the same as OP has provided:
```
.../site/pack/packer/start/packer.nvim/lua/packer/async.lua:20: Error in coroutine: ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:570: attempt to index local 'display_win' (a nil value))
```

I've been able to make it work. What I did is I've added nvim-lua/popup.nvim plugin as the second plugin after packer.nvim and I've spammed PackerSync until everything stabilized.

**Comment by dustinru** [comment]
For anyone that is experiencing similar issues as I was, I resolved this behavior by changing ownership of the ~/.local directories, as well as ~/.config/nvim/plugin if permission denied errors were mentioned for that folder in the log output, using the following example command(s). I wasn't able to figure out why I needed to do this on my installation when I didn't need to on another machine but this should workaround the error.

```
sudo chown -R "${USER}" ~/.local
sudo chown $USER ~/.config/nvim/plugin
```

**Comment by wbthomason** [comment]
@dustinru Who owned those directories before the `chown`?

The line in `packer.lua` giving an error seems to imply that there are no plugins to install or update that aren't frozen (by tracing the conditions for initializing the `display_win` object). I'm not sure why that would happen for the cases you describe, but it's easy enough to add a check for that edge case.

**Comment by wbthomason** [comment]
If we still see this behavior (or any regressions) after 11df2e3, we'll reopen this.

**Comment by dustinru** [comment]
> @dustinru Who owned those directories before the `chown`?

If my memory serves me right, it was showing as root, but I don't recall this ever causing me errors previously. That said, I try to bootstrap/install my dotfiles/packages via shell script so could be related.

**Comment by 0ql** [comment]
Clearing cache (`~/.cache/nvim`) fixed it for me.

**Comment by a-irizi** [comment]
i had the same problem, i realized that i did not add the following let packer manage itself:

``` lua
local fn = vim.fn
local install_path = fn.stdpath('data')..'/site/pack/packer/start/packer.nvim'
if fn.empty(fn.glob(install_path)) > 0 then
  packer_bootstrap = fn.system({'git', 'clone', '--depth', '1', 'https://github.com/wbthomason/packer.nvim', install_path})
end

return require('packer').startup(function(use)
    -- make sure to add this line
    use 'wbthomason/packer.nvim'

  -- Automatically set up your configuration after cloning packer.nvim
  -- Put this at the end after all plugins
  if packer_bootstrap then
    require('packer').sync()
  end
end)

```

**Comment by simoneruffini** [comment]
> i had the same problem, i realized that i did not let packer manage itself:
> 
> ```lua
> local fn = vim.fn
> local install_path = fn.stdpath('data')..'/site/pack/packer/start/packer.nvim'
> if fn.empty(fn.glob(install_path)) > 0 then
>   packer_bootstrap = fn.system({'git', 'clone', '--depth', '1', 'https://github.com/wbthomason/packer.nvim', install_path})
> end
> 
> return require('packer').startup(function(use)
>     -- make sure to add this line to let packer manage itself
>     use 'wbthomason/packer.nvim'
> 
>   -- Automatically set up your configuration after cloning packer.nvim
>   -- Put this at the end after all plugins
>   if packer_bootstrap then
>     require('packer').sync()
>   end
> end)
> ```

About that, is it possible to don't have packer auto-manage itself? I'm running nix-os and I installed packer through the nix packaging system, but I want to manage all the plugins with packer. Therefore I left out that line from my packer configuration. As you I got a similar error when running `:PackerSync`.  
At the end I wasn't able to make it run with nix so I went back to regular `git clone` but maybe this is a packer bug?
