### ISSUE TITLE
Allow configuring a lazy loaded plugin before loading

### ISSUE THREAD

**Issue by jandamm** [wbthomason/packer.nvim#716]
### Describe the feature

I use telescope and load it lazily.
For the most common use cases I've created mappings.
I would like to define those mappings in packer.
Adding them just to the config does not work.
Adding them to the config and as a lazy loading trigger seems verbose.

I'd love to have a new `always` key which is always executed when vim is started (except when the plugin is disabled).

**Comment by jandamm** [comment]
Just found out that `setup` is called right away instead of right before loading the plugin.
So it's the proposed `always` I just thought it would work differently 👍

**Comment by wbthomason** [comment]
Glad things are working for you!
