### ISSUE TITLE
Failed to bootstrap packer in a clean init.lua config file

### ISSUE THREAD

**Issue by zchrissirhcz** [wbthomason/packer.nvim#717]
- `nvim --version`: NVIM v0.7.0-dev+667-g419e0d117
- `git --version`: git version 2.31.1
- Operating system/version: Ubuntu 20.04, x86_64
- Terminal name/version: Konsole, 19.12.3

### Steps to reproduce
1. Remove file `~/.config/nvim/init.vim` .
2. Ensure there is no `~/.local/share/nvim/site/pack/packer` directory.
3. Create file `~/.config/nvim/init.lua` with contents:
```lua
local fn = vim.fn
local install_path = fn.stdpath('data')..'/site/pack/packer/start/packer.nvim'
if fn.empty(fn.glob(install_path)) > 0 then
  packer_bootstrap = fn.system({'git', 'clone', '--depth', '1', 'https://github.com/wbthomason/packer.nvim', install_path})
end

return require('packer').startup(function(use)
  -- My plugins here
  -- use 'foo1/bar1.nvim'
  -- use 'foo2/bar2.nvim'

  -- Automatically set up your configuration after cloning packer.nvim
  -- Put this at the end after all plugins
  if packer_bootstrap then
    require('packer').sync()
  end
end)



use {
    'kyazdani42/nvim-tree.lua',
    requires = {
      'kyazdani42/nvim-web-devicons', -- optional, for file icon
    },
    config = function() require'nvim-tree'.setup {} end
}
```
Then use nvim to edit a file, say, `nvim helloSLAM.cpp`, the file's content is:
```c++
#include <iostream>
#include <string>
using namespace std;

int main() {
    cout << "hello slam!" << std::endl;
    return 0;
    for (int i = 0; i < 100; i++) {
        printf("hello\n");
    }
    std::string a = "23";
    return 0;
}
```

### Actual behaviour
nvim complains error
```
Error detected while processing /home/zz/.my_config/home/.config/nvim/init.lua:
E5112: Error while creating lua chunk: /home/zz/.config/nvim/init.lua:21: '<eof>' expected n
ear 'use'
Press ENTER or type command to continue
```

![图片](https://user-images.githubusercontent.com/3831847/144734875-fb014e99-c265-4b8a-a796-c10a9c03dd44.png)

### Expected behaviour
nvim should not report error, it should download packer plugin, and correctly, directly show `helloSLAM.cpp`'s content

### packer files
Well, there is still no `~/.local/share/nvim/site/pack/packer` directory.

<details>
<summary>Plugin specification file(s)</summary>

Post or link your plugin specification files here, if you aren't able to provide a minimal
reproducer

</details>

<details>
<summary>packer log file</summary>

Post the contents of ~/.cache/nvim/packer.nvim.log here

</details>

<details>
<summary>packer compiled file</summary>

Post the contents of `packer_compiled.vim` here

</details>

**Comment by busysumm3r** [comment]
Hi. It looks like you are trying to call `use` after `return`. Try to move `use` block inside `setup` call
