### ISSUE TITLE
Configure plugins many times instead of alltogether in the startup

### ISSUE THREAD

**Issue by zchrissirhcz** [wbthomason/packer.nvim#719]
Hi, packer.vim developers

I would like setup my nvim config like this:
```lua
local fn = vim.fn
local install_path = fn.stdpath('data')..'/site/pack/packer/start/packer.nvim'
if fn.empty(fn.glob(install_path)) > 0 then
  packer_bootstrap = fn.system({'git', 'clone', '--depth', '1', 'https://github.com/wbthomason/packer.nvim', install_path})
end


require('status_line')
    -- inside lua/status_line.lua, configure related plugins
require('color_theme')
    -- inside lua/color_theme.lua, configure related plugins
```

It seems currently I have to put all my plugins inside a call to require packer startup, and only in the very begging of the init.lua file, can't be put into several files.

**Comment by VrIgHtEr** [comment]
In my init function i just did this:

```lua
return require('packer').startup({
    function(use)
        use {'wbthomason/packer.nvim', opt = true}
        require'plugins'.config(use)

        if packer_bootstrap then require('packer').sync() end
    end,
    config = require 'packer-config'
})
```

In my config, I split the configuration into separate modules, each containing a function that accepts one parameter. Then from the main packer startup function I just call that and pass the "use" function to it. In this case, this is from my packer bootstrap file, and it just loads packer and then the actual plugin setup is done in `require'plugins'.config(use)`, which in my case is set up like the following:

```lua
local m = {}
function m.config(use)
    require 'plug/general'(use)
    require 'plug/telescope'(use)
    require 'plug/git'(use)
    require 'plug/lualine-nvim'(use)
    require 'plug/lsp'(use)
    require 'plug/dap'(use)
    require 'plug/cmp'(use)
    require 'plug/java'(use)
    require 'plug/lua'(use)
    require'plug/eclipse-jdt-ls'.setup(use)
end
return m
```

Each one of those modules just returns a function that accepts the `use` function as a parameter, and they do their thing. And if you're so inclined, with some lua magic, you can quite easily set it up to find and load all of them automatically by scanning the folder or something. Here's an example of one of them:

```lua
return function(use)
    use 'equalsraf/neovim-gui-shim'
    use {'nvim-treesitter/nvim-treesitter', run = ':TSUpdate'}
    use {'kosayoda/nvim-lightbulb', config = require 'cfg/nvim-lightbulb'}
    use {
        'kyazdani42/nvim-tree.lua',
        requires = {'kyazdani42/nvim-web-devicons', opt = true},
        config = require 'cfg/nvim-tree'
    }
    use {
        'windwp/nvim-autopairs',
        config = function() require'nvim-autopairs'.setup {} end
    }
    use {
        'ray-x/aurora',
        config = function()
            vim.api.nvim_exec("set termguicolors", true)
            vim.api.nvim_exec("colorscheme aurora", true)
        end
    }
    use {"nathom/filetype.nvim"}
    use {'dstein64/vim-startuptime', disable = true}
    use {"ellisonleao/glow.nvim"}
    use {
        'rcarriga/nvim-notify',
        after = {'telescope.nvim'},
        requires = {'nvim-telescope/telescope.nvim'},
        config = require 'cfg/nvim-notify'
    }
end
```

**Comment by zchrissirhcz** [comment]
@VrIgHtEr Wow, this is cool! Yeah actually I'm new to lua and noticed but not understood the `use` "variable", so now I know it is actually a function. I'll try your pasted configuration snippets when I'm free. Thank you so much!
