### ISSUE TITLE
Unable to use setup to configure plugin

### ISSUE THREAD

**Issue by katsika** [wbthomason/packer.nvim#72]
Trying to set couple of variables for `loupe` results in `packer.nvim` not getting loaded.

```lua
use {
  'wincent/loupe',
  setup = function()
    vim.g.LoupeCenterResults = false
    vim.g.LoupeClearHighlightMap = false
  end
}
```

after `:PackerCompile` and opening new nvim instance no `Packer*` commands are available.

**Comment by wbthomason** [comment]
Note to myself for when I have a chance to look into this properly: seems like it might have to do with limitations on `string.dump`, e.g. upvalues (though the `vim` table should be a global, which I wouldn't think would cause trouble?)

**Comment by nanotee** [comment]
I can't reproduce the bug, `packer_compile.vim` is generated correctly and `Packer*` commands are available after loading it.

@katsika are you calling `packer.startup` from your `init.vim`? Could you provide more details about your configuration?

**Comment by wbthomason** [comment]
@katsika I also cannot reproduce this. Could you please post your plugin specification file (or, better still, link to your configuration files) so I can see how you load `packer`?

**Comment by lewis6991** [comment]
I thought I was hitting this issue too but turns out I didn't know that I needed to run `PackerCompile` whenever changes are made. The README explains this quite well but maybe this should be highlighted a little more as this is a big difference for any users migrating from something like `Plug.vim`.

**Comment by katsika** [comment]
Interesting, tried to replicate it now and couldn't. So I was either doing something wrong before that have corrected ever since or there was an upstream change. Will close for now. Thanks for looking into it and apologies for wasting your time!

**Comment by wbthomason** [comment]
@lewis6991: Thanks for the feedback - if you have suggestions for how to highlight the difference better in the README/elsewhere, I'd be happy to merge a PR!

@katsika: No worries, I'm glad things are working now! Sorry for the difficulty.
