### ISSUE TITLE
Packer update display doesn't cater for broken updates well.

### ISSUE THREAD

**Issue by sunjon** [wbthomason/packer.nvim#73]
I have a package with local changes, that I know will fail during updates. I'm happy to have the error message in the window.

If subsequent package updates are successful however, their status messages get intermingled with the output from the failed update. 

![packer_update](https://raw.githubusercontent.com/sunjon/images/master/packer.png)

**Comment by tami5** [comment]
Totally unrelated question @sunjon , but how did you manage to have a packer open in a popup. Thanks

**Comment by wbthomason** [comment]
Nice catch! This is a regression.

I won't be able to look at this before 2020-11-02 at the earliest, but if you happen to feel like taking a stab at a PR, the likely culprit is `final_results` in `packer/display`.

Otherwise, I'll put this on my list of `packer` things to do after this deadline...

**Comment by sunjon** [comment]
> Totally unrelated question @sunjon , but how did you manage to have a packer open in a popup. Thanks

the options have a parameter `open_fn` to specify a function that will create a window for Packers content:

```lua
local opts = {
  display = {
    open_fn = "call vimrc#floating_window()",
  }
}
```

with a function based on https://github.com/neovim/neovim/issues/9718#issuecomment-559573308

**Comment by sunjon** [comment]
> I won't be able to look at this before 2020-11-02 at the earliest, but if you happen to feel like taking a stab at a PR, the likely culprit is final_results in packer/display.

Done, hopefully!

**Comment by wbthomason** [comment]
Thank you very much!
