### ISSUE TITLE
Packer doesn't get installed

### ISSUE THREAD

**Issue by zim0369** [wbthomason/packer.nvim#736]
I have problem installing packer for the root user. I had this problem with
normal user to but removing the packer directory solved it but that trick didn't
work for the root user.

`PackerInstall` command not found.

**Comment by shadmansaleh** [comment]
Did you get this resolved since in #738 you seem to have packer installed . Also you've provided no info about how you were trying to install packer. You need to provide enough info with the issue so it can be reproduced . Without info issues make no sense 😢

**Comment by zim0369** [comment]
> Did you get this resolved since in #738 you seem to have packer installed . Also you've provided no info about how you were trying to install packer. You need to provide enough info with the issue so it can be reproduced . Without info issues make no sense cry

I moved my `nvim` directory to `root` user's `.config` directory and I also installed packer for the root user. But there are no packer commands available. I assume that it probably isn't installed.

**Comment by shadmansaleh** [comment]
You still haven't said how you tried to install packer ? Also probably allowing plugins to runs as root is a bad idea . You should use `sudoedit` insead of `sudo nvim`

**Comment by zim0369** [comment]
> You still haven't said how you tried to install packer ? Also allowing plugins to runs as root is probably a bad idea . You should use `sudoedit` insead of `sudo nvim`

```  ❤ git clone --depth 1 https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim
Cloning into '/home/zim/.local/share/nvim/site/pack/packer/start/packer.nvim'...
```

It wasn't getting installed for the root user but now that I'd accidentally deleted the `.local` directory and then reinstalled packer, it just wouldn't show up any commands inside neovim. The installation command ran absolutely fine but there are no Packer commands in neovim.

**Comment by zim0369** [comment]
The issue was related to another plugin. I do not recall anymore info.

**Comment by Elliot2636** [comment]
> 该问题与另一个插件有关。我不记得更多信息了。

please tell me about how do you solved, I maybe encountered the same problem too
