### ISSUE TITLE
Error running config for plugins: attemp to call a nil value

### ISSUE THREAD

**Issue by SleepyCatOnTheBed** [wbthomason/packer.nvim#737]
After updated to nvim 0.6.0, packer throw these error for my configs. The nvim 0.5.x works fine. May I know the solution for this ?

Thank you.

![image](https://user-images.githubusercontent.com/71932200/146672048-0eb970d9-1437-4f8d-b7bb-e93fbefb8458.png)

**Comment by shadmansaleh** [comment]
I can't see how you expect your issue to be resolved if you're going to ignore the issue template ? You have provided no info at all that can be used to find the source of your issue 🤦‍♂️

**Comment by lisperatu** [comment]
I've seen similar problem on one of my machines.
Try removing `plugin/packer_compiled.lua` in your `~/.config/nvim` before you start neovim, then, when you start it: `:PackerCompile`.
