### ISSUE TITLE
Issue with firenvim

### ISSUE THREAD

**Issue by zim0369** [wbthomason/packer.nvim#738]
I'm facing this issue with firenvim:
https://imgur.com/hvBOryt

I made an issue at their github:
https://github.com/glacambre/firenvim/issues/1271

Owner suggests that some other plugin might be the cause of the issue.
I can see packer appearing multiple times in the output so is it a packer issue?

**Comment by shadmansaleh** [comment]
No it's not a packer's issue . The error seems to be from nvim-cmp . But I agree with glacambre only you can debug your config .

**Comment by zim0369** [comment]
> No it's not a packer's issue . The error seems to be from nvim-cmp . But I agree with glacambre only you can debug your config .

Okay. One thing that I've noticed is that it happens only in tiny text boxes
like the title input boxes on all websites.
