### ISSUE TITLE
Bootstrapping packer (sorta) fails on new setup

### ISSUE THREAD

**Issue by miversen33** [wbthomason/packer.nvim#742]
When setting up a new neovim instance and following the details [here](https://github.com/wbthomason/packer.nvim#bootstrapping), you are presented with 

![This floating window](https://user-images.githubusercontent.com/2640668/147364067-eabcbb30-7106-41e3-8820-8ed8b4a20b0f.png)

Regardless of the choice selected (Y/N), the following error is displayed
```
[packer.nvim] [ERROR 10:14:54] async.lua:20: Error in coroutine: ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:570: attempt to index local 'display_win' (a nil value)
```

- `nvim --version`:
```
NVIM v0.7.0-dev+759-g7b8fbbdeb
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az32-596

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```
- `git --version`:
```
git version 2.25.1
```
- Operating system/version:
```
Ubuntu 20.04 (WSL2 Windows 11)
```

- Terminal name/version:
```
Windows Terminal
Version: 1.11.3471.0
```

### Steps to reproduce

I have verified this issue exists with Neovim 0.6 as well as Neovim 0.7

Reproduction steps
- Create a new neovim environment which can quickly be done by taring the SHADA directory and then deleting it
```shell
$ tar -czf ~/.local/share/nvim.tar.gz ~/.local/share/nvim && rm -rf ~/.local/share/nvim
```

Run Neovim 0.6.0 or 0.7.0
```shell
$ nvim
```
Proceed through either removing Packer (Why does it do this?) or not.
Observe error

### Actual behaviour

Upon initial setup of packer (via the bootstrap method listed above), Packer emits an error indicating something is wrong with [this line](https://github.com/wbthomason/packer.nvim/blob/851c62c5ecd3b5adc91665feda8f977e104162a5/lua/packer.lua#L570). Ignoring this error and restarting neovim appears to make it go away.

### Expected behaviour

Packer should not throw an error during its bootstrapping process

### packer files

<details>
<summary>Plugin specification file(s)</summary>

```lua
-- Packer Bootstrapping
local fn = vim.fn
local install_path = fn.stdpath('data')..'/site/pack/packer/start/packer.nvim'
if fn.empty(fn.glob(install_path)) > 0 then
  packer_bootstrap = fn.system({'git', 'clone', '--depth', '1', 'https://github.com/wbthomason/packer.nvim', install_path})
end

return require('packer').startup(function(use)
  -- My plugins here
  -- use 'foo1/bar1.nvim'
  -- use 'foo2/bar2.nvim'

  -- Automatically set up your configuration after cloning packer.nvim
  -- Put this at the end after all plugins
  if packer_bootstrap then
    require('packer').sync()
  end
end)
```

</details>

<details>
<summary>packer log file</summary>

```
[WARN  Fri 24 Dec 2021 10:17:04 AM CST 2758760637100] .../site/pack/packer/start/packer.nvim/lua/packer/clean.lua:79: Cleaning cancelled!
[ERROR Fri 24 Dec 2021 10:17:04 AM CST 2758761171000] .../site/pack/packer/start/packer.nvim/lua/packer/async.lua:20: Error in coroutine: ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:570: attempt to index local 'display_win' (a nil value)
```

</details>

<details>
<summary>packer compiled file</summary>
-- File not found

</details>

**Comment by miversen33** [comment]
Tested on _actual_ Ubuntu 20.04 (not via WSL) and I am experiencing the same error

**Comment by horseinthesky** [comment]
You must have
```
use { "wbthomason/packer.nvim" }
```
in the `startup` function.

Otherwise, `packer` can't find itself in the list of plugins to install and tries to delete itself.

**Comment by miversen33** [comment]
That fixes the issue! I do not see that listed in the boostrap section which I assumed you would do _instead_ of using the [quickstart](https://github.com/wbthomason/packer.nvim#quickstart). Is this a misunderstanding on my part of how the bootstrapping process works? Looking at it now, it appears that the bootstrapping process is for simply auto installing packer itself and you _still_ have to inform packer to install itself (as laid out in the quickstart).

Is that correct?

**Comment by horseinthesky** [comment]
> Is that correct?

Yes. Bootstraping procedure just helps you to have `packer` ready before you need it.
But when it starts doing plugin management it will take into account ALL plugins in the `start` and `opt` directories including `packer` itself.

**Comment by miversen33** [comment]
Fantastic, thanks!
