### ISSUE TITLE
Add floating packer display

### ISSUE THREAD

**Issue by clason** [wbthomason/packer.nvim#75]
Echoing the following comment on #73, it'd be lovely to have this built-in so I could just set `open_fn = require'packer.util'.float`!

@sunjon

> Totally unrelated question @sunjon , but how did you manage to have a packer open in a popup. Thanks

the options have a parameter `open_fn` to specify a function that will create a window for Packers content:

```lua
local opts = {
  display = {
    open_fn = "call vimrc#floating_window()",
  }
}
```

with a function based on https://github.com/neovim/neovim/issues/9718#issuecomment-559573308

_Originally posted by @sunjon in https://github.com/wbthomason/packer.nvim/issues/73#issuecomment-717569491_

**Comment by wbthomason** [comment]
@sunjon Would you be willing to share the floating window function you appear to use? It looks nice, and (if you're willing) I'd be happy to steal it for the use @clason suggests.

**Comment by clason** [comment]
crs pasted the following Lua snippet in Gitter chat when I asked about this: https://dpaste.org/zghD
```lua
return {
  floatingCentered = function()
    local columns = vim.o.columns
    local rows = vim.o.lines
    local width = math.min(columns - 4, math.max(80, columns - 20))
    local height= math.min(rows - 4, math.max(20, rows - 10))
    local top = ((rows - height) / 2) - 1
    local left = (columns - width) / 2
    local opts = {
      relative = 'editor',
      row = top,
      col = left,
      width = width,
      height = height,
      style = 'minimal'
    }
​
    local buf = vim.api.nvim_create_buf(false, true)
    local win = vim.api.nvim_open_win(buf, true, opts)
    vim.api.nvim_win_set_option(win, 'winhl', 'Normal:NormalFloat')
    opts.row = opts.row + 1
    opts.height = opts.height - 2
    opts.col = opts.col + 2
    opts.width = opts.width - 4
    vim.api.nvim_open_win(vim.api.nvim_create_buf(false, true), true, opts)
    vim.cmd([[autocmd! BufWipeout <buffer> execute 'bw ']] .. buf)
  end
}
```

**Comment by tjdevries** [comment]
This: `vim.cmd([[autocmd! BufWipeout <buffer> execute 'bw ']] .. buf)` can be `vim.api.nvim_buf_delete` now :)

**Comment by wbthomason** [comment]
@clason I've added this. Please let me know if it's not working as expected!

(Thanks @crs for providing your implementation! I've credited you in the code, please let me know if you'd like other attribution)

**Comment by clason** [comment]
Very nice! Two minor things:

* I get a weirdness with the `guibg` highlight for parts of the float: 
<img width="659" alt="Screenshot 2020-11-13 at 18 13 16" src="https://user-images.githubusercontent.com/2361214/99100307-f4334b80-25db-11eb-89ca-87d35d4be0a4.png">
Possibly just my color scheme -- which highlight group is used for the first and last column?

* It'd be extra cool if the height of the popup was set based on the number of plugins ;)

**Comment by wbthomason** [comment]
I used exactly the snippet you posted above, modified to correctly return the status, window ID, and buffer ID. So, I think the highlight should be `NormalFloat`? It might also be an issue with the size, though it seems to look right on my config.

Making the popup height depend on the number of plugins should be feasible, but will require a bit of refactoring (right now, the display does not get the full list of plugins at once; instead, they're added one by one). Could you open a new feature request for that, for tracking?

**Comment by clason** [comment]
I hadn't tested that, I just copied @crs pastebin before it expired ;) (It's not the highlight group; it looks like the calculation for the underlying "border window" is off by one. I'll play around with it after dinner.

The adaptive float is a separate issue, agreed.
