### ISSUE TITLE
config-command is not executed

### ISSUE THREAD

**Issue by RefusesNames** [wbthomason/packer.nvim#76]
Using this setup:
```
vim.cmd [[packadd packer.nvim]]

vim._update_package_paths()

local packer = require('packer')
print('test1')
packer.startup(function()
	print('test2')
	use { 'wbthomason/packer.nvim', opt=true }
	use { 'neovim/nvim-lspconfig', config=function() print('test3') end }

```
I will see "test1" and "test2" printed, but not "test3". This is not only the case for this plugin, but for all I tested.

If you need more context, my complete configuration can be seen [here](https://github.com/RefusesNames/vim_config/blob/fix_lsp/lua/plugins.lua).

**Comment by wbthomason** [comment]
Have you run `PackerCompile` or `PackerSync`?

**Comment by RefusesNames** [comment]
I can confirm that this was the solution. I did call `PackerCompile` (or did not reload my changed config beforehand). My bad and thank you for your time.

**Comment by wbthomason** [comment]
No worries; I'm glad it's working for you!
