### ISSUE TITLE
Option to run function before a plugin is loaded

### ISSUE THREAD

**Issue by nimaipatel** [wbthomason/packer.nvim#766]
### Describe the feature

Many old vimscript plugins rely on reading the values of some global variables before running their code. Configuring them using `config` is not possible and so their settings have to be defined outside the `packer.startup` call. It would be convenient to have a `pre_config` key whose code runs *before* the specific plugin is loaded.

Effectively, something like this:

``` lua
vim.g.plugin_setting_1 = 'blah'
vim.g.plugin_setting_2 = 'blah'
packer.startup(function(use)
    use 'name/plugin'
end)
```

Can be turned into:

``` lua
packer.startup(function(use)
    use { 
        'name/plugin', 
        pre_config = function()
           vim.g.plugin_setting_1 = 'blah'
           vim.g.plugin_setting_2 = 'blah' 
       end}
    
end)
```

**Comment by nanotee** [comment]
That's what the `setup` key does: https://github.com/wbthomason/packer.nvim/blob/d20606aaf0e13702476e295f238e682547ea4a85/doc/packer.txt#L566

**Comment by nimaipatel** [comment]
Thank-you. Somehow managed to miss it 😬.
