### ISSUE TITLE
Execute BufRead later

### ISSUE THREAD

**Issue by AckslD** [wbthomason/packer.nvim#778]
When `packer` sees that a plugin requires `BufRead` (ie by detecting eg a `ftdetect` folder) it does `doautocmd BufRead`.

This happens sometimes too early. For example I had an issue where LSPs didn't start automatically when opening a file using nvim (by doing `nvim some_file`). After a very long time of debugging and trying do understand what was going on, I realised that the following was happening:

In `packer_compiled` when calling all the `setup`/`config` for various plugins the `config` for `nvim-gps` was called before `lspconfig`. `nvim-gps` in turn `require` `nvim-treesitter` by module and I have `nvim-treesitter` lazy loaded by module. So `packer` starts loading `nvim-treesitter` which has a `ftdetect` folder which makes `packer` trigger `BufRead`. However all this happens before `lspconfig` is loaded and the `FileType` autocmds that `lspconfig` adds are therefore never executed.

I think that the better approach would maybe be to:
* keep track of when `packer_compiled` is entered/exited.
* if `needs_bufread` is true while executing `packer_compiled`, don't trigger `BufRead`.
* if by the end of `packer_compiled` at least one of the plugins `needs_bufread` then trigger it.

**Comment by AckslD** [comment]
Opened an MR with one way of doing this as a suggestion in #779

**Comment by wbthomason** [comment]
Thanks! This seems like a tough bug to track down. If I understand correctly, the issue is more to do with being inside a loader at all rather than just in `packer_compiled`, no? I think it might make sense to - instead of tracking whether we're in the compiled file - track if `BufRead` is needed and trigger it at the end of the sequence of loaders (which might require maintaining a stack of "in loader" to prevent triggering it too early...)

**Comment by AckslD** [comment]
Haha yeah took me quite some time but after sufficiently many print statements I finally understood what was going on :P This all depended on the order of the plugins in `packer_compile` so I wasn't also able to find a minimal example that produced the issue.

Hmm you make a good point but I wonder if it would actually solve the issue, but I might be missing something. In my case the issue was that `BufRead` was triggered while loading `nvim-gps` (since it triggered loading `nvim-treesitter` which `needs_bufread`). This happened before starting the load of `lspconfig`. But in my config `lspconfig` is anyway loaded after, and crucially independent of `nvim-gps`. So even if the `BufRead` event would be triggered after `nvim-gps` is finished loading, it would still be before `lspconfig`.

Let me know of that made sense :)

**Comment by RayZ0rr** [comment]
Possibly related to https://github.com/wbthomason/packer.nvim/issues/770

**Comment by AckslD** [comment]
@RayZ0rr does #779 fix also your issue? Note that you need to `PackerCompile` for changes to take affect.

**Comment by RayZ0rr** [comment]
I will test it soon (not at my system). Also, I'm calling `PackerSync` on entering vim, which should do `PackerCompile`.

**Comment by RayZ0rr** [comment]
Just tested in but it didn't fix lsp and treesitter attaching capabilities with early `syntax on` settings

**Comment by AckslD** [comment]
@RayZ0rr ok too bad :) Thanks for trying
