### ISSUE TITLE
The config option doesn't work

### ISSUE THREAD

**Issue by steven-jostar** [wbthomason/packer.nvim#784]
I only installed one plugin, I used the `config` option to setup this plugin:
```lua
use({
  "[plugin name]",
  config = function() require("[plugin name]").setup() end,
})
```
But when I re-open neovim, this plugin doesn't work, although I only wrote config in the `config` function.
In fact, I think packer doesn't invoke `config` option at all.

How to solve this problem? Please help me! Thank you!

**Comment by wbthomason** [comment]
Have you run `:PackerCompile` or `:PackerSync`?

**Comment by steven-jostar** [comment]
Yes, but I just ran :PackerSync once, it just doesn't work

**Comment by Iamafnan** [comment]
Hey I have this problem too

**Comment by steven-jostar** [comment]
> Hey I have this problem too

What branch do you use?

**Comment by steven-jostar** [comment]
I'm already reinstalled this plugin once, but it just doesn't work.

**Comment by Iamafnan** [comment]
> > Hey I have this problem too
> 
> What branch do you use?

I am using the master branch

**Comment by steven-jostar** [comment]
> > > Hey I have this problem too
> > 
> > 
> > What branch do you use?
> 
> I am using the master branch

OHH! I understanded it! When I use `:PackerSync` instead of `:PackerInstall` and `:PackerUpdate`, the plugin does well.

Thank you!
