### ISSUE TITLE
How to remove the some plugins? 

### ISSUE THREAD

**Issue by sober-wang** [wbthomason/packer.nvim#789]
NVIM v0.6.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az152-703

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

I'm run `PackerClean`  clean the plugins in packer plugin mananger, but It's always display some problem when I open my Neovim.

![](https://user-images.githubusercontent.com/35804630/150279491-0aed6e28-7dbe-4c5c-bf2f-f50abe7615b1.png)
![issues_connect](https://github.com/glepnir/galaxyline.nvim/issues/227)

**Comment by max397574** [comment]
run `PackerClean` *and* `PackerCompile` or `PackerSync`
