### ISSUE TITLE
crash on start

### ISSUE THREAD

**Issue by kyazdani42** [wbthomason/packer.nvim#79]
hi, doing some debug, i've noticed packer is crashing at start. It's not noticeable without the debug=throw set.
init.vim:
```vim
set debug=throw
lua require'plugins'
```
lua/plugins.lua
```lua
vim.cmd [[packadd packer.nvim]]

return require('packer').startup(function() end)
```

crashes with
```
E5108: Error executing lua /home/kiyan/.config/nvim/lua/plugins.lua:1: Vim(packadd):E1
21: Undefined variable: g:did_load_filetypes
```

Sorry if this is duplicate or what, it is not really a big issue right now, but i believe this is causing undefined behaviors sometimes (not 100% sure though)

**Comment by wbthomason** [comment]
Hmm, I'm having trouble replicating this. Do you get the same error if you don't have the `return ...startup` in `plugins.lua`?

**Comment by kyazdani42** [comment]
even better debugging:
```
Error detected while processing /home/kiyan/.dotfiles/config/common/nvim/init.vim:
line    3:
Error detected while processing /home/kiyan/.dotfiles/config/common/nvim/plugin/packer
_compiled.vim:
line  195:
&termguicolors must be set
```
with init.vim as
```
set debug=throw
packadd packer.nvim
```
I run archlinux with neovim version 0.5.0-789-gca7449db4

**Comment by kyazdani42** [comment]
it might come from my config though. could you look up [my plugin config ?](https://github.com/kyazdani42/dotfiles/blob/master/config/common/nvim/lua/plugins.lua) ?

**Comment by nanotee** [comment]
I was able to reproduce this with your minimal `init.vim`:

```vim
set debug=throw
packadd packer.nvim
```

However, the crash also happens when I try to load a plugin other than `packer`:

```vim
set debug=throw
packadd snippets.nvim
```

I suspect the bug might be coming from the `:packadd` command

**Comment by wbthomason** [comment]
Thanks for the help, @nanotee! Am I correct in interpreting your results as indicating that the bug is indeed in `packadd`?
If I recall correctly, @bfredl's packages-related PR landed after this report, so if this is an error with packages, it probably doesn't stem from that.

**Comment by kyazdani42** [comment]
i believe this might be upstream related then. Ill open a PR there.
just tagging @bfredl in the meantime.

**Comment by kyazdani42** [comment]
@wbthomason i've found that loading packer with `packadd!` instead of `packadd` resolves the issue.
from the docs:
```
When the optional ! is added no plugin files or ftdetect scripts are loaded,
only the matching directories are added to 'runtimepath'.  This is useful in your .vimrc.  
The plugins will then be loaded during initialization, see |load-plugins|.```

**Comment by wbthomason** [comment]
@kyazdani42: Thanks for following up. That's a strange discovery - `packer` has no plugin files or ftdetect scripts, so maybe this is something to do with how Lua search paths are set on `packadd`? I'm not sure.

**Comment by kyazdani42** [comment]
seems to be a bug in neovim `runtime.c` file. it tries to load the non existent `g:did_load_filetypes`, thus running in debug mode fails. did_load_filetype is a variable used in the vim runtime but never globalized.

**Comment by wbthomason** [comment]
Good to know, thanks!
