### ISSUE TITLE
`PackerClean` does not clean plugins when they are marked optional after install

### ISSUE THREAD

**Issue by stephan-hesselmann-by** [wbthomason/packer.nvim#80]
Steps to reproduce:

- Specify plugin with `use "repo/name"`.
- After `PackerInstall` the repo is cloned to `.../packer/start/name`.
- Change plugin specification to `use {"repo/name", ft = "python"}`.
- After `PackerInstall` the repo is cloned to `.../packer/opt/name`.
- `PackerClean` does not delete the now outdated plugin in `.../packer/start/name`.

The plugin is now duplicated and loaded twice when opening python files. Same is true for the reverse steps.

Expectation:
- `PackerClean` deletes plugins in `.../packer/start` when they are marked with optional loading (and other way around).

**Comment by wbthomason** [comment]
Thanks for the report! The more customary set of steps to change a plugin's type is to use `PackerUpdate` or `PackerSync`, rather than `PackerInstall`, but this is a bug in `PackerClean`.

**Comment by wbthomason** [comment]
@stephan-hesselmann-by: This should be fixed now - could you please confirm that `PackerClean` now works as expected?

**Comment by stephan-hesselmann-by** [comment]
Yes it works as expected now. Thanks for the fix!
