### ISSUE TITLE
win64: full https url in `use` is not properly handled

### ISSUE THREAD

**Issue by FelipeLema** [wbthomason/packer.nvim#802]
- `nvim --version`:
```
NVIM v0.6.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```
- `git --version`: `git version 2.29.2.windows.2`
- Operating system/version: Microsoft Windows 10 Enterprise (10.0.18363 Build 18363)
- Terminal name/version: neovim-qt

### Steps to reproduce
use the following packer config in `plugin.lua`

```lua
return require('packer').startup(function()
  use 'https://codeberg.org/FelipeLema/tiza_salubrista.vim.git'
  use 'wbthomason/packer.nvim' -- Package manager
end)
```
Then run the following commands:
```
PackerCompile
PackerClean
PackerInstall
```

### Actual behaviour

packer errors out saying it couldn't install `tiza_salubrista`:
```
fatal: could not create directories of 'C:\Users\xxx\Appdata\Local\nvim-data\site\pack\packer\start\https://codeberg/FelipeLema/tiza_salubrista.vim.git': Invalid argument
```

### Expected behaviour

packages are installed correctly

### packer files

<details>
<summary>Plugin specification file(s)</summary>
return require('packer').startup(function()
  use 'https://codeberg.org/FelipeLema/tiza_salubrista.vim.git'
  use 'wbthomason/packer.nvim' -- Package manager
end)
</details>

<details>
<summary>packer log file</summary>
Couldn't find such a file in windows 
</details>

<details>
<summary>packer compiled file</summary>
Couldn't find such a file in windows 
</details>

**Comment by FelipeLema** [comment]
Are the compiled files needed? I couldn't find them in windows setup, but if anyone knows their location (and they're needed) I'll be happy to paste their content here

**Comment by wbthomason** [comment]
Thanks for your report! I'm currently unable to reproduce this on Linux, so I may need a bit of help testing things on Windows.

Could you please give #807 a try to see if it fixes your issue?

**Comment by FelipeLema** [comment]
that `/` in the branch name is giving me a hard time to get to test it: I cannot bootstrap packer now.

From what I could see, it seems to fix this issue, so it looks like it's going in the right direction I guess?

**Comment by FelipeLema** [comment]
let me clone #807 's branch with a different name to try it out
