### ISSUE TITLE
Function passed to packer.startup not sourced properly

### ISSUE THREAD

**Issue by axieax** [wbthomason/packer.nvim#824]
- `nvim --version`: 0.6.1
- `git --version`: 2.35.1
- Operating system/version: ArcoLinux
- Terminal name/version: Alacritty

### Steps to reproduce

1. Make change in config (such as adding `disable = true` to a plugin's `use` block)
2. Source file (or use an autocmd to source `$MYVIMRC`)
3. Changes not applied until nvim is re-entered (`PackerClean` does not bring up a cleaning prompt)

### Actual behaviour

Nothing shows up for `PackerClean`

### Expected behaviour

`PackerClean` asks whether you want to remove the specified plugin. Not sure what change caused this, but this used to work as expected. Perhaps it stopped working after I changed to using `packer.reset` and `packer.init`.

### packer files

<details>
<summary>Plugin specification file(s)</summary>

Post or link your plugin specification files here, if you aren't able to provide a minimal
reproducer:

https://github.com/axieax/dotconfig/blob/main/nvim/lua/plugins/init.lua

</details>

<details>
<summary>packer log file</summary>

Post the contents of ~/.cache/nvim/packer.nvim.log here

Relevant logs:

```
[WARN  Thu 17 Feb 2022 02:36:16 92381610267654] .../site/pack/packer/start/packer.nvim/lua/packer/clean.lua:79: Cleaning cancelled!
[WARN  Thu 17 Feb 2022 02:36:26 92391388506208] .../site/pack/packer/start/packer.nvim/lua/packer/clean.lua:79: Cleaning cancelled!
```

</details>

<details>
<summary>packer compiled file</summary>

Post the contents of `packer_compiled.vim` here

[packer_compiled.lua](https://gist.github.com/axieax/df86d03fe0d5c27866664ff2ef11f5a1)

</details>

**Comment by wbthomason** [comment]
Thanks for your report. Can I ask why you're using `init` and `reset` directly? I wouldn't expect that it would cause this (this sounds more like Lua module caching), but it shouldn't be necessary; `startup` handles all that for you.

**Comment by axieax** [comment]
I'm using init and reset to pass in an argument for `max_jobs`. This is to resolve issue #202 on my Mac machines.

**Comment by wbthomason** [comment]
Note that you can pass configuration variables to `startup` too: see bullet 2 of https://github.com/wbthomason/packer.nvim#the-startup-function.

**Comment by axieax** [comment]
Ahh I see thanks for pointing that out. I've removed these function calls now, but the issue still remains:
https://github.com/axieax/dotconfig/blob/main/nvim/lua/plugins/init.lua

**Comment by wbthomason** [comment]
If not for your statement that this used to work, I'd suspect Lua caching - the fix there would be to set `package.loaded['plugins'] = nil` before sourcing. Do you have a commit for your spec file that works, so we could compare?

**Comment by axieax** [comment]
Thanks for the suggestion! Although that command does not fix things, it seems that I have found the commit causing the issue: https://github.com/axieax/dotconfig/commit/1323e6f69a2f27a818e69b0a30df49304f6ea05f

In this commit, I updated my `plugins/init.lua` file to be a function returned (so I can pass in a `dev_mode` parameter), which can be called from the entry `$MYVIMRC`. It seems that sourcing `$MYVIMRC` does not successfully "inform" these changes, although the function does get run (print statements within the function passed to `packer.startup` works).

This may be a similar issue I encountered before when working on my own plugin, where sourcing the Lua module I am working on does not reflect the changes, so I have to restart nvim entirely to load the new changes in. Do you know a way around this?
