### ISSUE TITLE
Setting colorscheme after after packer.startup() executes before plugin's config

### ISSUE THREAD

**Issue by agorgl** [wbthomason/packer.nvim#829]
Given a colorscheme plugin, I would like to execute `colorscheme <somecolorscheme>` after `packer.startup()` call.
Currently, the (colorscheme) plugin's config method is called AFTER the `colorscheme <somecolorscheme>` command that is immediately executed after the `packer.startup()` call.

I suppose this is a general behavior that is linked to the async loading of the plugins?
Is there a way to know that the plugin loading process has finished, and that I can execute some code after that?

My `init.lua` essentially is a for loop requiring/calling my main modules (options, plugins, mappings and colors in that order) and in my colors module that is required/executed after the plugins module I set the colorscheme.

I know that I could modify the `config` function in my colorscheme plugin to execute the `colorscheme <somecolorscheme>` command, but I would like to have multiple colorscheme plugins and have the colorscheme set in my colors module.

What is the appropriate way to achieve this?

**Comment by lewis6991** [comment]
> I know that I could modify the config function in my colorscheme plugin to execute the colorscheme <somecolorscheme> command, 

This is the only reasonable solution. 

> but I would like to have multiple colorscheme plugins and have the colorscheme set in my colors module.
Just group these closer together.

**Comment by EdenEast** [comment]
Using the `after/` folder will make sure that your colorscheme is set after the plugins have installed and configured. Or if you want to [over engineer](https://github.com/EdenEast/nyx/blob/671c4a6eb0ef6ecbda2531756bfc6cacd37f46d1/config/.config/nvim/lua/eden/core/theme.lua) loading a colorscheme [after](https://github.com/EdenEast/nyx/blob/671c4a6eb0ef6ecbda2531756bfc6cacd37f46d1/config/.config/nvim/lua/eden/bootstrap.lua#L156) plugins have been compiled you can use my config as inspiration.
