### ISSUE TITLE
After adding Packer & Lua file in Plugins, I get permission errors. 

### ISSUE THREAD

**Issue by Normanras** [wbthomason/packer.nvim#844]
- `nvim --version`: NVIM v0.6.1
- `git --version`: git version 2.25.1
- Operating system/version:  5.13.0-30-generic 33~20.04.1-Ubuntu
- Terminal name/version: GNU bash, version 5.0.17(1)-release

### Steps to reproduce
Fresh install of nvim. In `.config/nvim` add dir `lua/plugins`, add file `packer.lua`.

In `.config/nvim/init.lua`
```
require("settings")
require("plugins")
```

In `.config/nvim/lua/plugins/init.lua`

```
vim.cmd [[packadd packer.nvim]]

return require("packer").startup {
    function(use)
      use {
	"wbthomason/packer.nvim",
      }
 end
}
```
### Actual behaviour:

This error gets thrown when either a. opening nvim or b. when running `:luafile %` within the main `init.lua` file. 

```
E5113: Error while calling lua chunk: Vim:E739: Cannot create directory /home/norm/.loc
al/share/nvim/site/pack/packer/opt: permission denied
stack traceback:
        [C]: in function 'mkdir'
        ...ack/packer/start/packer.nvim/lua/packer/plugin_utils.lua:93: in function 'en
sure_dirs'
        ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:125: in function 'i
nit'
        ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:978: in function <.
..e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:953>
        [C]: in function 'require'
        init.lua:2: in main chunk
Press ENTER or type command to continue
```

### Expected behaviour
Lua file to reload and load all plugins in the directories as outlined in the files. 

### packer files

<details>
<summary>Plugin specification file(s)</summary>

```
vim.cmd [[packadd packer.nvim]]

return require("packer").startup {
    function(use)
      use {
	"wbthomason/packer.nvim",
      }
 end
}
```

I've also tried syntax exactly like in the Readme of this repo, but that also didn't work. 

Post or link your plugin specification files here, if you aren't able to provide a minimal
reproducer

</details>

<details>
<summary>packer log file</summary>

Post the contents of ~/.cache/nvim/packer.nvim.log here

```
[ERROR Sat 26 Feb 2022 12:32:19 PM EST 3.3217505963856e+14] .../site/pack/packer/start/packer.nvim/lua/packer/async.lua:20: Error in coroutine: ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:716: attempt to index local 'output_file' (a nil value)
[ERROR Sat 26 Feb 2022 12:40:56 PM EST 3.3269208258797e+14] .../site/pack/packer/start/packer.nvim/lua/packer/async.lua:20: Error in coroutine: ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:716: attempt to index local 'output_file' (a nil value)
[ERROR Sat 26 Feb 2022 12:49:36 PM EST 3.3321176524029e+14] .../site/pack/packer/start/packer.nvim/lua/packer/async.lua:20: Error in coroutine: ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:716: attempt to index local 'output_file' (a nil value)
```

</details>

<details>
<summary>packer compiled file</summary>

Post the contents of `packer_compiled.vim` here

The file doesn't exist...? I guess it should?

</details>

**Comment by stephen-everett** [comment]
Hi I'm currently having this problem, can you share with my the permissions that you had to change?

**Comment by Normanras** [comment]
Hi @stephen-everett - Sorry, this was so long ago I don't remember what I did to fix it. 

About 6 months ago I moved managing all my plugins to Lazy, as I don't think packer is as actively maintained. There's even a rumor going around that Packer's author is also using Lazy...

**Comment by stephen-everett** [comment]
Hey @Normanras thanks for the reply. I just came back to add the fix I found in case anyone else lands here like I did:

Somewhere along this path, the folder permissions were set to root instead of user:
~/.local/share/nvim/site/pack/packer/start/packer.nvim

for me it started at /pack/

I had to use chown to change the ownership back to the user. I did "sudo chown -R (my username) pack"
