### ISSUE TITLE
`packer.snapshot` not configured when not using `packer.startup()`

### ISSUE THREAD

**Issue by ViViDboarder** [wbthomason/packer.nvim#845]
- `nvim --version`: NVIM v0.6.0
- `git --version`: git version 2.35.0
- Operating system/version: macOS Monterey
- Terminal name/version: iTerm2

### Steps to reproduce
Config:
```lua
local packer = require("packer")
packer.init({ ... anything here ...})
packer.use("wbthomason/packer.nvim")
-- Other plugins etc...
```

Execute command like `PackerRollback <a snapshot name>`.

### Actual behaviour

Error that `config.git` is null.

### Expected behaviour

Snapshot is rolled back

### Investigation

So, I started poking around. I've noticed that for one, the `packer.snapshot()` function and the `packer.rollback()` functions, the snapshot module is required by using `require 'packer.snapshot'` rather than `require_and_configure 'snapshot'`. This means that they never receive the user or default configuration resulting in the null reference. This would be an easy fix.

However, `PackerDelete` is executed directly from the binding as `lua require('packer.snapshot').delete(<f-args>)`, not providing an opportunity to configure. This could probably be refactored to be similar to snapshot and rollback.

This is not an issue with `packer.startup()` because that function calls `require_and_configure 'snapshot'` already.

So an alternative fix could be to add `require_and_configure 'snapshot'` to `packer.init()` and probably removing it from `packer.startup()` because that calls `packer.init()` already.

I'm happy to make the patch, but I wasn't sure what approach would be preferred as I haven't contributed to this project yet.

**Comment by smhc** [comment]
I just realised this is the same issue that I attempted to address here: https://github.com/wbthomason/packer.nvim/pull/849

I'm not sure the 'rollback' technique is best for a clean install - using the 'plugin_spec.commit' might work better as it only installs the desired commit.
