### ISSUE TITLE
attempt to call field '_update_package_paths' (a nil value)

### ISSUE THREAD

**Issue by F4IL3D** [wbthomason/packer.nvim#85]
First of all, thank you for this plugin.

I'm just a layman, but I think this error is a result of the following merge: [#13119](https://github.com/neovim/neovim/pull/13119/commits/c60c7375f5754eea2a4209cc6441e70b2bb44f14)

Version: NVIM v0.5.0-804-geee066881

![image](https://user-images.githubusercontent.com/48415231/98112120-ebd36600-1ea1-11eb-88f7-7bbadc5f9806.png)

**Comment by wbthomason** [comment]
Yes, that PR removed `_update_package_paths`. Commit b3a1bb on `packer` removed the use of this function - are you on the latest `packer`?

Unfortunately, if you updated your Neovim before your plugins, you might have to manually pull `packer` updates.

**Comment by F4IL3D** [comment]
Hello Wil,

packer himself says I'm up to date. ;-)
But you are right. I ran the Neovim update first and then I updated the plugins. Despite manual PackerCompile, the file packer_compiled.vim was apparently not replaced. I deleted packer_compiled.vim after your advice this morning and had it recreated with PackerCompile.
The "_update_package_path" call in line 137 has thus been removed and everything runs normally. 👍 

I hope I haven't done too much work for you.
I close the issue as it is obviously already fixed. :-)

**Comment by wbthomason** [comment]
I'm glad you got things working. I'm not sure why `PackerCompile` didn't replace your file; it should **always** overwrite an existing file...

**Comment by fffed** [comment]
@wbthomason, Hi, and thanks for great plugin, but I have the same issue: when I mark packer.nvim as optional `use {'wbthomason/packer.nvim', opt = true}` with `vim.cmd [[packadd packer.nvim]]` on top of the file `lua/plugins.lua` a new compiled file then had next calls:
```
    if not plugins[name].loaded then
      vim.cmd('packadd ' .. name)
      vim._update_package_paths()
...

-- Load plugins in order defined by `after`
vim._update_package_paths()
END
```
But when I remove the `opt` - everything is OK.

**Comment by wbthomason** [comment]
@ffed: Is your version of `packer.nvim` the latest? I've removed all uses of `_update_package_paths` in the project.

**Comment by fffed** [comment]
> Is your version of `packer.nvim` the latest? I've removed all uses of `_update_package_paths` in the project.
Yes, it is the latest. I've updated today and tried to move `packer` to `opt` and yet have this error.

**Comment by wbthomason** [comment]
Have you deleted your `packer_compiled.vim` and run `PackerCompile` or `PackerSync`?

**Comment by fffed** [comment]
> Have you deleted your `packer_compiled.vim` and run `PackerCompile` or `PackerSync`?

What i did:
1 - remove `packer_compiled.vim` 
2 - make lua/plugins.lua looks like
```
vim.cmd [[packadd packer.nvim]]

return require('packer').startup(function()
    use {'wbthomason/packer.nvim', opt = true}
...
```
3 - :w, :PackerCompile, :qa 
4 - open nvim and run :PackerSync and :qa 
5 - open nvim and see the error message
![image](https://user-images.githubusercontent.com/47778360/99112359-96642b00-25fe-11eb-81a7-8bc616854d59.png)

**Comment by wbthomason** [comment]
Strange. Very dumb question, but the `packer_compiled.vim` you deleted was at `~/.config/nvim/plugin/packer_compiled.vim`, right?

My confusion is because the `packer` repo literally does not contain the string `_update_package_paths` anywhere except in the docs/README after b3a1bb3...

**Comment by fffed** [comment]
> Very dumb question, but the `packer_compiled.vim` you deleted was at `~/.config/nvim/plugin/packer_compiled.vim`, right?

Right, and I even tried to remove `packer`'s git repo but result the same. @wbthomason , could you reproduce this bug with `opt` property for `packer`?

**Comment by wbthomason** [comment]
That's the confusion - I cannot reproduce this.

Could you please run `grep -RHn _update_package_paths .` in `~/.config/nvim/` and in `~/.local/share/nvim/site/pack/packer`? I suspect that you have an unexpected old copy of `packer` or an unexpected old `packer_compiled.vim` file sitting around somewhere; I'm not sure how you could be getting this error otherwise.

**Comment by fffed** [comment]
> Could you please run `grep -RHn _update_package_paths .` in `~/.config/nvim/`

```
./pack/packer/opt/packer.nvim/doc/packer.txt:63:  vim._update_package_paths()
./pack/packer/opt/packer.nvim/README.md:49:vim._update_package_paths()
./pack/packer/opt/packer.nvim/lua/packer/plugin_utils.lua:113:  vim._update_package_paths()
./pack/packer/opt/packer.nvim/lua/packer/compile.lua:78:      vim._update_package_paths()
./pack/packer/opt/packer.nvim/lua/packer/compile.lua:437:  table.insert(result, 'vim._update_package_paths()')
```


> and in `~/.local/share/nvim/site/pack/packer`

```
./start/packer.nvim/doc/packer.txt:63:  vim._update_package_paths()
./start/packer.nvim/README.md:52:vim._update_package_paths()
```

**Comment by wbthomason** [comment]
You have an old copy of `packer` (and perhaps other packages) in `~/.config/nvim/pack/packer/` - try deleting that directory. I'm guessing that you changed your `packer` install path at some point, and now have some packages in `~/.config/nvim/pack` and some in `~/.local/share/nvim/site/pack`.

**Comment by fffed** [comment]
> You have an old copy of `packer` (and perhaps other packages) in `~/.config/nvim/pack/packer/` - try deleting that directory.

Yes, it helps, thank you very much.

**Comment by wbthomason** [comment]
@fffed: Glad it's working now; sorry for the confusion.
