### ISSUE TITLE
PackerSync fails: 813: expected lua number

### ISSUE THREAD

**Issue by exorcist365** [wbthomason/packer.nvim#883]
- `nvim --version`: 0.7.0
- `git --version`: 2.36.0
- Operating system/version: Arch Linux
- Terminal name/version: st (simple terminal)

### Steps to reproduce

I have no idea how to reproduce, ig just try it with nvim 0.7

### Actual behaviour

[packer.nvim] [ERROR 16:22:29] async.lua:20: Error in coroutine: .../site/pack/packer/opt/packer.nvim/lua/packer/display.lua:813: Expected Lua number

### Expected behaviour

to work

### packer files

<details>
<summary>Plugin specification file(s)</summary>

Post or link your plugin specification files here, if you aren't able to provide a minimal
reproducer

</details>

<details>
<summary>packer log file</summary>

Post the contents of ~/.cache/nvim/packer.nvim.log here

[ERROR Thu 21 Apr 2022 03:54:11 PM EEST 4434579967744] ...im/site/pack/packer/opt/packer.nvim/lua/packer/async.lua:20: Error in coroutine: .../site/pack/packer/opt/packer.nvim/lua/packer/display.lua:813: Expected Lua number
[ERROR Thu 21 Apr 2022 04:21:25 PM EEST 6068637025369] ...im/site/pack/packer/opt/packer.nvim/lua/packer/async.lua:20: Error in coroutine: .../site/pack/packer/opt/packer.nvim/lua/packer/display.lua:813: Expected Lua number
[ERROR Thu 21 Apr 2022 04:22:29 PM EEST 6132156885373] ...im/site/pack/packer/opt/packer.nvim/lua/packer/async.lua:20: Error in coroutine: .../site/pack/packer/opt/packer.nvim/lua/packer/display.lua:813: Expected Lua number

</details>

<details>
<summary>packer compiled file</summary>

Post the contents of `packer_compiled.vim` here

</details>

**Comment by junnunkarim** [comment]
@exorcist365 How did you fix this issue? I'm also having the same problem.

**Comment by exorcist365** [comment]
for me it was that i had
```lua
        open_fn = function()
            return(require("packer.util").float({border = border}))
        end,
```
and i changed it to
```lua
        open_fn = function()
            return require("packer.util").float({border = border})
        end,
```
and it somehow solved itself

**Comment by junnunkarim** [comment]
@exorcist365 Thank you very much.
In my case the problem was I didn't had ```.float({border = border})``` in there. I was trying to move to neovim from vim and I have wasted hours to find out were the problem was. Finally it's fixed.
Thanks again.

**Comment by exorcist365** [comment]
np
