### ISSUE TITLE
[Question] How to disable plugin on large file?

### ISSUE THREAD

**Issue by nyngwang** [wbthomason/packer.nvim#885]
As title.

Context: sometimes the LSP go-to-defintion will jump into the library code, and some neovim packages will cause serious delay in cursor movement. So I would like to know is it possible to temporarily disable these plugins when some condition is met.

**Comment by WieeRd** [comment]
Packer can only decide when to load the plugin.  
If you want to disable plugin under certain condition, you should use autocmd.  

More specifically, an autocmd that is triggered on `BufRead` event,  
checks file size, and disable your LSP plugin for that buffer.

**Comment by nyngwang** [comment]
@WieeRd Thanks for your info!
