### ISSUE TITLE
Many plugins fail to install with error in coroutine

### ISSUE THREAD

**Issue by momofor** [wbthomason/packer.nvim#897]
- `nvim --version`:  v0.7.0
- `git --version`:  2.36.0
- Operating system/version: Gnu/Linux 5.17.5
- Terminal name/version: kitty 0.25.0

### Steps to reproduce
- run PackerInstall
### Actual behaviour
Many plugins fail to install
but when I run PackerInstall again some of them get install and then when I run it again the rest of them will be installed 
### Expected behaviour
all plugins install
### packer files

<details>
<summary>Plugin specification file(s)</summary>

[plugins.lua](https://pastebin.com/SsUbAFdv)

</details>

<details>
<summary>packer log file</summary>

[packer.nvim.log](https://pastebin.com/3mqPhCf7)

</details>

<details>
<summary>packer compiled file</summary>

[packer_compiled.lua](https://pastebin.com/Mj75BtZk)

</details>

**Comment by marcelbeumer** [comment]
Same here with both nvim 0.7.0 and NVIM v0.8.0-dev+1470-g0124a7bfa. Plugins that have dependencies sometimes can't require them when module is (pre)loaded after install(? not sure how it exactly works). Not sure if packer issue, the treesitter `:TSUpdate` also errors it can not find the command, that also happened when using paq instead of packer.

Example error after first `PackerSync`. The next `PackerSync` will then finish without errors.

```
[packer.nvim] [ERROR 15:48:30] async.lua:20: Error in coroutine: ...ack/packer/start/packer.nvim/lua/packer/plugin_utils.lua:206: Vim(lua):E5108: Error executing lua ...s-context-commentstring/lua/ts_context_comments
tring.lua:4: module 'nvim-treesitter' not found:
[packer.nvim] ^Ino field package.preload['nvim-treesitter']
[packer.nvim] ^Ino file './nvim-treesitter.lua'
[packer.nvim] ^Ino file '/opt/homebrew/Cellar/luajit-openresty/2.1-20220411/share/luajit-2.1.0-beta3/nvim-treesitter.lua'
[packer.nvim] ^Ino file '/usr/local/share/lua/5.1/nvim-treesitter.lua'
[packer.nvim] ^Ino file '/usr/local/share/lua/5.1/nvim-treesitter/init.lua'
[packer.nvim] ^Ino file '/opt/homebrew/Cellar/luajit-openresty/2.1-20220411/share/lua/5.1/nvim-treesitter.lua'
[packer.nvim] ^Ino file '/opt/homebrew/Cellar/luajit-openresty/2.1-20220411/share/lua/5.1/nvim-treesitter/init.lua'
[packer.nvim] ^Ino file './nvim-treesitter.so'
[packer.nvim] ^Ino file '/usr/local/lib/lua/5.1/nvim-treesitter.so'
[packer.nvim] ^Ino file '/opt/homebrew/Cellar/luajit-openresty/2.1-20220411/lib/lua/5.1/nvim-treesitter.so'
[packer.nvim] ^Ino file '/usr/local/lib/lua/5.1/loadall.so'
[packer.nvim] stack traceback:
[packer.nvim] ^I[C]: in function 'require'
[packer.nvim] ^I...s-context-commentstring/lua/ts_context_commentstring.lua:4: in function 'init'
[packer.nvim] ^I[string ":lua"]:1: in main chunk
[packer.nvim] ^I[C]: in function 'resume'
[packer.nvim] ^I.../site/pack/packer/start/packer.nvim/lua/packer/async.lua:12: in function <.../site/pack/packer/start/packer.nvim/lua/packer/async.lua:11>
```

**Comment by marcelbeumer** [comment]
Note: i tried different packer setup using `requires`, `after` and just plain list of `use` without extra args. Only `after` prevents the errors but then I run into different issues as the package will not be available until I require the "after".

**Comment by marcelbeumer** [comment]
Minimal init.lua:

```lua
local packer = require("packer")
local use = packer.use
packer.init()
packer.reset()

use("JoosepAlviste/nvim-ts-context-commentstring")
use("NTBBloodbath/color-converter.nvim")
use("RRethy/nvim-treesitter-textsubjects")
use("editorconfig/editorconfig-vim")
use("folke/lua-dev.nvim")
use("folke/persistence.nvim")
use("folke/tokyonight.nvim")
use("folke/which-key.nvim")
use("folke/zen-mode.nvim")
use("hrsh7th/cmp-buffer")
use("hrsh7th/cmp-nvim-lsp")
use("hrsh7th/cmp-nvim-lsp-signature-help")
use("hrsh7th/cmp-vsnip")
use("hrsh7th/nvim-cmp")
use("hrsh7th/vim-vsnip")
use({ "jose-elias-alvarez/null-ls.nvim", commit = "d871b418c67867a11a43eb1412a1a21aee888ae3" })
use("jose-elias-alvarez/nvim-lsp-ts-utils")
use("kazhala/close-buffers.nvim")
use("kdheepak/lazygit.nvim")
use("leoluz/nvim-dap-go")
use("mfussenegger/nvim-dap")
use("neovim/nvim-lspconfig")
use("norcalli/nvim-colorizer.lua")
use("nvim-lua/plenary.nvim")
use("nvim-telescope/telescope-fzy-native.nvim")
use("nvim-telescope/telescope.nvim")
use("nvim-treesitter/nvim-treesitter")
use("preservim/nerdtree")
use("rafcamlet/nvim-luapad")
use("ray-x/go.nvim")
use("rcarriga/nvim-dap-ui")
use("rmagatti/goto-preview")
use("sbdchd/neoformat")
use("terrortylor/nvim-comment")
use("tpope/vim-fugitive")
use("tpope/vim-surround")
use("wbthomason/packer.nvim")
use("windwp/nvim-autopairs")
```

`nvim +PackerSync` will sometimes exit without errors, and sometimes it will error like described above (both nvim 0.7.0 and NVIM v0.8.0-dev+1470-g0124a7bfa)

**Comment by momofor** [comment]
The plugins that don't work are random, cmp-buffer and cmp-path always don't work while others work sometimes and don't work other times.

**Comment by momofor** [comment]
I currently work around the issue by updating the plugins that fail to update separately by using PackerSync <plugin-name>.

**Comment by momofor** [comment]
I didn't change anything in the config but it seems like packer now works just fine don't know why ?

**Comment by QuinnVDB** [comment]
I have the same problem using trying to install treesitter on windows
- nvim --version: v0.8.0-dev+296-g307c5c63e
- git --version: 2.36.1.windows.1
- Operating system/version: Windows 10 Enterprise 21H2
- Terminal name/version: Windows terminal 10.0.19044.1706
![image](https://user-images.githubusercontent.com/106311645/170708583-c2cc8115-3fab-4151-91bb-a26c758acf02.png)

**Comment by momofor** [comment]
I just updated to the latest neovim version and now it seems like packer is working just fine (?).

**Comment by marcelbeumer** [comment]
@momofor, I'm running latest nightly (df4ffce543ba0d4e2464b3978f4e66eaddf6a29a), installing latest packer, still have the issue from time to time (still: not always but from time to time)

**Comment by larsbs** [comment]
In my case, I had to disable git autocrlf using: 

```
$ git config --global core.autocrlf false
```

After doing that, the installation completed successfully. 

However, I feel like this is something I shouldn't have to do in order to be able to correctly install packages. I think it's something that should be managed from packer itself in order to make it feel more robust.

**Comment by flavono123** [comment]
> In my case, I had to disable git autocrlf using:
> 
> ```
> $ git config --global core.autocrlf false
> ```
> 
> After doing that, the installation completed successfully.
> 
> However, I feel like this is something I shouldn't have to do in order to be able to correctly install packages. I think it's something that should be managed from packer itself in order to make it feel more robust.

This is the hero I guess.
Repeatedly `module '...' not found` is cured!
