### ISSUE TITLE
Update/sync known plugins

### ISSUE THREAD

**Issue by ranebrown** [wbthomason/packer.nvim#90]
If you are editing `lua/plugins.lua` and remove a plugin or add a new one `PackerClean` or `PackerInstall` don't detect the change without quitting and restarting. Is there a way to update the changes to avoid the quit/restart?

**Comment by wbthomason** [comment]
Yes - you can run `:luafile %` to source your `plugins.lua` again. Note that unless you force-unload your plugins module (e.g. with `package.loaded['plugins'] = nil`) at the top of your `plugins.lua`, this will only work the first time (until a restart), since Lua only loads modules a single time.

**Comment by ranebrown** [comment]
Thanks for the info, I'm just starting to get familiar with lua stuff.

**Comment by wbthomason** [comment]
Yeah, there's a lot to learn; it takes some time. You may find https://github.com/nanotee/nvim-lua-guide helpful, if you haven't already taken a look.
