### ISSUE TITLE
Better syntax for defining plugins 

### ISSUE THREAD

**Issue by siduck** [wbthomason/packer.nvim#913]
Default : 

```lua
 use  { 
        'andymass/vim-matchup', 
         event = 'CursorMoved'
  }
```

Can be made to : 

```lua
['andymass/vim-matchup'] = { 
       event = 'CursorMoved
}
```

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/168454557-4a1466c0-350f-440b-a4a3-992a7ef88af0.png)

looks much cleaner I guess

**Comment by adrian5** [comment]
Note: as per the packer docs, you can pass a table without `use`:

```lua
require("packer").startup({
  { "wbthomason/packer.nvim" },
  { "andymass/vim-matchup", event = "VimEnter" },
})
```

**Comment by siduck** [comment]
> Note: as per the packer docs, you can pass a table without `use`:
> 
> ```lua
> require("packer").startup({
>   { "wbthomason/packer.nvim" },
>   { "andymass/vim-matchup", event = "VimEnter" },
> })

thx!
