### ISSUE TITLE
startup "expected (to close '(' at line 7) near '='" error with the most basic setup

### ISSUE THREAD

**Issue by alekspickle** [wbthomason/packer.nvim#932]
- `nvim --version`: 0.7.0
- `git --version`: 2.32.0
- Operating system/version: Ubuntu 21.10
- Terminal name/version: konsole/zsh

### Steps to reproduce
I am pretty new to packer because I wanted to try neovim after I was using vim for some time.
I was following [this article](https://mattermost.com/blog/turning-neovim-into-a-full-fledged-code-editor-with-lua/), it was best I found for a newbee in neovim + packer ecosystem and right from the start I did get different results as I started messing with packer. What's wrong with it?

### Actual behaviour
`:PackerStatus` gives `E492: Not an editor command: PackerStatus`
and ther is also this message:
Error detected while processing /home/pickle/.config/nvim/init.lua:
E5113: Error while calling lua chunk: vim/_init_packages.lua:0: /home/pickle/.config/nvim/lua/plug.lua:7: '=' expected near 'install'
stack traceback:
        [C]: in function 'error'
        vim/_init_packages.lua: in function <vim/_init_packages.lua:0>
        [C]: in function 'require'
        /home/pickle/.config/nvim/init.lua:13: in main chunk
### packer files

All files are exactly as article goes

**Comment by TheGhostHuCodes** [comment]
I was just working through the same article and came across a similar issue. The code in #775 worked for me. My `plug.lua` file ended up looking something like this:

```lua
require("packer").startup({
	function(use)
		-- [[ Put Plugins Here ]]
		use({
			"kyazdani42/nvim-tree.lua",
			requires = "kyazdani42/nvim-web-devicons",
		})
	end,
	config = {
		package_root = vim.fn.stdpath("config") .. "/site/pack",
	},
})
```

I did have to append the following to my `vars.lua` file:
```lua
-- Update the packpath
local packer_path = vim.fn.stdpath("config") .. "/site"
vim.o.packpath = vim.o.packpath .. "," .. packer_path
```

**Comment by alekspickle** [comment]
Huh, seems like I did mess up the `/nvim/site` path in vars.lua. Removing `nvim` part fixed it. But hell does this not obvious

**Comment by wbthomason** [comment]
Sorry for the trouble! I believe that article has a bug - `~/.config/nvim/` may be on `packpath` by default, but that means that `~/.config/nvim/pack/...` will be searched, and not `~/.config/nvim/site/pack/...`.
