### ISSUE TITLE
Processing InsertEnter AutoCommands for "*" error

### ISSUE THREAD

**Issue by c4dr01d** [wbthomason/packer.nvim#965]
- `nvim --version`:
```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

- `git --version`:
```
git version 2.37.0
```

- Operating system/version:
Arch Linux

- Terminal name/version:
```
kitty 0.25.2 created by Kovid Goyal
```

### Steps to reproduce
1. Open neovim
2. Open a file

### Actual behaviour
Display error:
```
Error detected while processing InsertEnter Autocommands for "*":
E5108: Error executing lua ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:165: Vim(echomsg):E114: Missing quote: "Error in packer_compiled: ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:142: Vim(source):E5113: Error while calling lua chunk: ...pack/packer/opt/cmp_luasnip/after/plugin/cmp_luasnip.lua:1: module 'cmp' not found:
stack traceback:
        [C]: in function 'cmd'
        ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:165: in function <...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:161>
        [string ":lua"]:1: in main chunk
```

### Expected behaviour
File opened

### packer files

<details>
<summary>Plugin specification file(s)</summary>

Post or link your plugin specification files here, if you aren't able to provide a minimal
reproducer

</details>

<details>
<summary>packer log file</summary>

Post the contents of ~/.cache/nvim/packer.nvim.log here

</details>

<details>
<summary>packer compiled file</summary>

Post the contents of `packer_compiled.vim` here

</details>

**Comment by andrewjwaggoner** [comment]
I'm encountering the same error, but my configuration isn't standard. For me, this is occuring only on empty buffers. Just thought I'd throw my error in here in case it's not my fault, and helpful.

**Comment by oeyoews** [comment]
![image](https://user-images.githubusercontent.com/72405338/178462366-25d4b5ca-3279-4792-906d-62fbee0ca897.png)
@c4dr01d

**Comment by smjonas** [comment]
Please share your packer configuration.

**Comment by c4dr01d** [comment]
I just re-sort my lazy loading sequence, let cmp_luasnip load after cmp and LuaSnip

**Comment by aro1999** [comment]
@c4dr01d Could you clarify the solution please?

**Comment by c4dr01d** [comment]
@aro1999 Loading order:
1. cmp
2. luasnip
3. cmp_luasnip
