### ISSUE TITLE
use {url}=404 will hang nvim and terminal

### ISSUE THREAD

**Issue by salkin-mada** [wbthomason/packer.nvim#97]
using a non existing repo
```
use {neovim/lspconfig}
```
and then `:PackerSync` or `:PackerInstall` freezes/hangs nvim and my terminal.
only solution is to kill my `sway` window.

Arch Linux 5.9.1-rt20-1-rt
NVIM v0.5.0-856-g7dfeadb0f
alacritty 0.5.0 (a6681e3a)

**Comment by wbthomason** [comment]
I believe this is closed by the PR #91 that was just merged - @salkin-mada, can you confirm?

**Comment by salkin-mada** [comment]
yep. confirmed. great work!

**Comment by wbthomason** [comment]
All credit for that one goes to @nanotee, but I'm glad things are working for you!
