### ISSUE TITLE
[Feature] Show a summary page with update availability status for each installed plugin, offering a way to manually update the chosen ones

### ISSUE THREAD

**Issue by pidgeon777** [wbthomason/packer.nvim#978]
It would be great to add a command such as:

```
:PackerSummary
```

That command should open a buffer showing all of the installed plugins and their update availability.

Then, after selecting one (or more) plugins with update available (through a binding such as `T` for `toggle`), make it possible to manually update them (e.g. binding `U`).

**Comment by akinsho** [comment]
This is sort of a duplicate of some functionality being worked on in #975, so I don't think a separate new command on top of that is required

**Comment by pidgeon777** [comment]
Yes @akinsho, the above proposal sounds even better than mine.

Closing my issue for now 👍.
