### ISSUE TITLE
System fzf binary causing problems

### ISSUE THREAD

**Issue by esn89** [wbthomason/packer.nvim#987]
- `nvim --version`: NVIM v0.7.2
- `git --version`: git version 2.32.1 (Apple Git-133)
- Operating system/version: MacOS 12.5
- Terminal name/version:  kitty 0.24.1

### Steps to reproduce
Use homebrew/macports to install fzf to `/opt/local/bin/fzf`

Use my packer config:

```
return require("packer").startup(function(use)
	-- Packer can manage itself
	use("wbthomason/packer.nvim")

	-- fzf
	use("/opt/local/bin/fzf")
	use("junegunn/fzf.vim")
end)

```

### Actual behaviour
What happens when I run `:PackerInstall`:
```
               packer.nvim - finished in 0.254s
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ✗ Failed to install /opt/local/bin/fzf

 Press 'q' to quit
 Press '<CR>' to show more info
 Press 'd' to show the diff
 Press 'r' to revert an update
 Press 'R' to retry failed operations
```

However, fzf does exist on that path:

```
which fzf
/opt/local/bin/fzf
```

### Expected behaviour
I expect it to pick up that path so I can use fzf.vim

### packer files

Post the contents of ~/.cache/nvim/packer.nvim.log here

```
return require("packer").startup(function(use)
	-- Packer can manage itself
	use("wbthomason/packer.nvim")

	-- fzf
	use("/opt/local/bin/fzf")
	use("junegunn/fzf.vim")
end)

```

**Comment by MunifTanjim** [comment]
That's not how you do it.

`/opt/local/bin/fzf` is the binary file, not the plugin directory.

You'll need to use the value of `$(brew --prefix)/opt/fzf` as stated here: https://formulae.brew.sh/formula/fzf

**Comment by MunifTanjim** [comment]
It'll be something like this: https://github.com/MunifTanjim/dotfiles/blob/5287c3ca89b7f773a3d8af6d8d78f3fe1c47062c/private_dot_config/nvim/lua/config/plugins.lua#L298-L301

With the `fzf_root` being:

```lua
vim.trim(vim.fn.system('brew --prefix')) .. '/opt/fzf'
```

**Comment by esn89** [comment]
@MunifTanjim 

I am using macports so I do not have the `brew --prefix` command.  Macports installs everything in `/opt/local/bin`, including fzf.

I did do something similar, but still getting this:
```
    local fzf_root = '/opt/local/bin'
    if vim.fn.isdirectory(fzf_root) == 1 then
        use(fzf_root)
	use('junegunn/fzf.vim')
    end

```
But when I try to do, `:Files`, I see something like:

<img width="721" alt="Screen Shot 2022-08-06 at 10 17 21 AM" src="https://user-images.githubusercontent.com/1475220/183259229-4f18f5a2-66cd-400c-b1e8-b4ffec405cb7.png">

**Comment by MunifTanjim** [comment]
`/opt/local/bin` is where the binary file lives. You need the directory where [the `plugin` folder](https://github.com/junegunn/fzf/tree/6a6130615d600a1dd23bbb6916e386520eaeb6b2/plugin) lives.

**Comment by esn89** [comment]
@MunifTanjim 

Hang on, I am now a bit confused.

So I need both, or only the plugin folder?

**Comment by MunifTanjim** [comment]
Try running `port notes fzf`, it should output something like this: https://github.com/macports/macports-ports/blob/260f33aa2a03fe0adb28933dbd00daf029163d09/sysutils/fzf/Portfile#L156-L168

And the directory should be something like `/opt/local/share/fzf/vim`... that's the directory you need.

```lua
local fzf_root = '/opt/local/share/fzf/vim'
```

**Comment by esn89** [comment]
@MunifTanjim 

Thanks for your reply.

So right now I have:

```
    local fzf_root = '/opt/local/share/fzf/vim'
    if vim.fn.isdirectory(fzf_root) == 1 then
        use(fzf_root)
        use('junegunn/fzf.vim')
    end
```

But now with this config, I get:

<img width="963" alt="Screen Shot 2022-08-06 at 11 06 15 AM" src="https://user-images.githubusercontent.com/1475220/183260768-b82d1a0a-04e3-452e-86c1-5d1d5c44e05d.png">

**Comment by MunifTanjim** [comment]
can you run `fzf --version` from you terminal?

**Comment by MunifTanjim** [comment]
You should open issue on `fzf.vim` repo, this really has nothing to do with `packer.nvim`. Maybe check a few existing issues there: https://github.com/junegunn/fzf.vim/issues?q=failed+to+run ?

**Comment by esn89** [comment]
@MunifTanjim 

Of course, yes right here:

```
fzf --version
0.32.0 (MacPorts)
```

**Comment by esn89** [comment]
@MunifTanjim 
I have fixed it.  Turns out my vim was using the wrong shell.
