### ISSUE TITLE
Incorrect escape sign handling

### ISSUE THREAD

**Issue by konart** [wbthomason/packer.nvim#988]
- `nvim --version`: NVIM v0.7.2
- `git --version`: git version 2.37.1
- Operating system/version: macOS 12.5
- Terminal name/version: Alacritty 0.10.1

### Steps to reproduce
Run `:PackerSync` after install the latest packer (commit 213ed031490ab5318e7996a594b52131e5c1c06f)

### Actual behaviour
Mappings with `\` sign (for example `vim.keymap.set("n", "\\[", ":NvimTreeToggle<CR>", { silent = true })`) cause the following error:

```
[packer.nvim] [ERROR 09:06:46] async.lua:20: Error in coroutine: ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:725: Vim(source):E5112: Error while creating lua chunk: /Users/user/.config/nvim/plugin/packer_compiled.lua:477: invalid escape sequence near '"'
```

### Expected behaviour
No error

Commit 213ed031490ab5318e7996a594b52131e5c1c06f introduced this error I believe (installing previous versions and rerunning `:PackerSync` fixes the error.

The latest version produces
```
vim.api.nvim_set_keymap("", "\[", "<cmd>lua require('packer.load')({'nvim-tree.lua'}, { keys = '\\[', prefix = '' }, _G.packer_plugins)<cr>", { noremap = true, silent = true })
```
note the second argument to `nvim_set_keymap`

**Comment by akinsho** [comment]
Thanks for reporting this. I'll have a look

**Comment by kevinhwang91** [comment]
` keys = {[[<Leader>\]]}` doesn't work also.

**Comment by Bekaboo** [comment]
Also have this bug, if I have `keys = '<C-\\>'`, in packer_compiled.lua it will be compiled to `<C-\>`.

**Comment by akinsho** [comment]
I'm working on a fix over in #989

**Comment by akinsho** [comment]
Can anyone hitting this issue try the PR in #989 I want to confirm that it fixes the issue for other people

**Comment by scwfri** [comment]
The PR in #989 fixes the issue for me
