### ISSUE TITLE
Bootstrap code didn't work(for me).

### ISSUE THREAD

**Issue by BreezyMain** [wbthomason/packer.nvim#997]
The code in [Bootstrap](https://github.com/wbthomason/packer.nvim#bootstrapping) didn't work.

There is a solution:

```lua
local install_path = vim.fn.stdpath('data') .. '/site/pack/packer/start/packer.nvim'
if vim.fn.isdirectory(install_path) == 0 then
    print 'downloading packer.nvim'
    packer_bootstrap = vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
    vim.cmd [[packadd packer.nvim]]
end
```

**Comment by nat-418** [comment]
Can you please describe your machine, operating system, etc?

**Comment by nat-418** [comment]
Could you please close your issue then? Without even knowing what version of neovim you are running it doesn't seem feasible to help solve this issue that may or may not exist.
